### ISSUE TITLE
Limit friend requests (and make them respect blocks)

### ISSUE THREAD

**Issue by Adam314159** [online-go/online-go.com#1000]
Friend requests currently have no limit and can be spammed over and over even when denied.

Not sure what precise limits to apply, maybe 3 tries to the same person, to leave some margin for honest errors? Plus the request should not go through if the user blocked the player.

**Comment by BHydden** [comment]
I whole heartedly agree.

**Comment by flovo** [comment]
Blocking friend requests should probably use the “block chat” property if we don't want to create a separate checkbox.

In this case it's only front end work to hide the friend requests for blocked users.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
