### ISSUE TITLE
Prominently display that your opponent passed 

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#1001]
**Is your feature request related to a problem? Please describe.**
It's not always immediately obvious that your opponent passed, as reported [here](https://www.reddit.com/r/baduk/comments/e47mlx/beginner_on_ogs_problem_with_ui_one_of_opponents/) 

**Describe the solution you'd like**
Display a message on the side (not a popup) saying "$player_colour Passed" 

**Describe alternatives you've considered**
Display a message on the side (not a popup) saying "Opponent Passed"

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
