### ISSUE TITLE
Imposible to copy user name

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#1003]
**Describe the bug**
After selecting the username, right click on it doesn't bring up the context menu, but follows the link to the profile page. This prevents the username from being copied by using the context menu.

**Expected behavior**
Right click should bring up the context menu

**Desktop (please complete the following information):**
The problem happens in Chrome.
Firefox works fine

**Additional context**
https://forums.online-go.com/t/adjust-right-clicking-behavior-for-usernames/23915?u=flovo

**Comment by anoek** [comment]
Yeah that's not good behavior. I'm pretty sure this is the offending code: https://github.com/online-go/online-go.com/blob/devel/src/components/Player/Player.tsx#L284-L334 

I think the fix will be to check if the right mouse button is being pressed, return early and let the default behavior happen. However just note that `event` is not always a mouse click, it can be a touchevent too, maybe a pointerevent in some cases as well, I'm not sure.

**Comment by BHydden** [comment]
FWIW you can copy names just fine from a mobile device, so it's only desktop functionality that needs fixing
