### ISSUE TITLE
 Demo board capturing bug

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#101]
### Summary

In demo board, when you fill all the liberties of a stone, that captured stone doesn't disappear from the board only if you don't use the alternating color tool.

### Environment

 * Operating system: Android 7.0
 * Browser: Firefox
 * Browser Version: 51.0.3

but also:

* Operating sytem: Debian GNU/Linux 8.7
* Browser: Firefox
* Browser Version: 45.7.0

### Steps To Reproduce:

Open a demo board, capture a stone.... and you get a stone surrounded by stones of the opponent but it doesn't disappear from the board. See the screenshot I enclose to the issue.
**Only if you don't use the alternating color tool**.

### Additional Information:

Thread on the forums: https://forums.online-go.com/t/demo-board-capturing-bug/11175

Screenshot:

![demo_board_capture_bug](https://cloud.githubusercontent.com/assets/26174230/23631385/34ad1f30-02b6-11e7-8c8e-9338593ca801.png)

**Comment by anoek** [comment]
This is actually on purpose, if you are editing the board you are simply placing down stones and you exist outside of any rules or system. While teaching beginners this can be useful.
