### ISSUE TITLE
Games vs. stronger and vs. weaker swapped in history

### ISSUE THREAD

**Issue by AresUII** [online-go/online-go.com#1013]
In profile view, weaker and stronger opponents are swapped in win/loss rate and game history.

1. View any player's profile page.
2. Observe the win-loss chart and the game history. You should see that the bug is in effect.

Games vs. stronger opponents are expected to go to vs. stronger opponents (lighter shade in dark mode &vv.). Games vs. weaker opponents are expected to go to vs. weaker opponents (darker shade in dark mode).

![Technical Problem](https://user-images.githubusercontent.com/42591316/70466776-eacb6600-1a91-11ea-8feb-a1807299ff50.png)

Windows 10, Firefox 71. Recent bug.

**Comment by anoek** [comment]
Fixed in PR, will be deployed soon
