### ISSUE TITLE
Moderator names very hard to read in dark mode white player container

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1014]
**Describe the bug**

Purple Moderator names very hard to read in the new dark mode white player container colour scheme

**To Reproduce**

Challenge a moderator to a game where they play white.   When they accept, set dark mode and look at their name on the game page.

Or view here:  https://online-go.com/game/20715145   :)

I forgot this variation when testing that new colour scheme!

I guess pros are another ... what other variations of what can appear in the container are there, I wonder?

**Comment by BHydden** [comment]
It's ok, mods don't play games Kappa

In terms of name colours, there's only blue, yellow, purple and green

**Comment by BHydden** [comment]
I forgot grey for bots
