### ISSUE TITLE
Dark theme white player lost their gradient

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#1015]
**Describe the bug**
After #1006 white player and win percentage bar lost their gradient

**To Reproduce**
1. Go to any game
2. See white has no gradient

**Expected behavior**
White should have a gradient

**Screenshots**
![image](https://user-images.githubusercontent.com/28991649/70476625-d2eff280-1b22-11ea-89fa-7b56627ab50e.png)

Initial report by ronik in help chat

**Comment by GreenAsJade** [comment]
Is there white player name missing there, as well?

**Comment by BHydden** [comment]
> Is there white player name missing there, as well?

Bots have a grey name. Apparently, it's the same colour grey as the monochrome backing.

**Comment by GreenAsJade** [comment]
What broswer, OS is producing this result?

It looks like the screenshots here #1006 to me

**Comment by BHydden** [comment]
I can't speak for Ronik, but for me it's 
Windows 10
Brave browser Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

**Comment by GreenAsJade** [comment]
Hmm - could be screen!   I'll try some different ones!

**Comment by GreenAsJade** [comment]
Do you guys see the gradient in the screenshots in #1006, or do they appear the same as the screenshot here?

**Comment by BHydden** [comment]
> Hmm - could be screen! I'll try some different ones!

My screens are 
Acer P221w
Samsung SyncMaster P2270
Samsung Galaxy S7 (stock)

> Do you guys see the gradient in the screenshots in #1006, or do they appear the same as the screenshot here?

it appears the same for me everywhere

> (Ironically, it is being argued in the forum that we should get rid of the gradient altogether :) )

tell him to submit his own PR :wink:
