### ISSUE TITLE
Ranking table and graph showing non-existent ranked games

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1016]
**Describe the bug**

The rank table and graph of this player shows ranked 19x19 games, on specific dates, where there are no such games in the Game History

**To Reproduce**
1. Go to https://online-go.com/user/view/513966/Shaytan
2. Click on 19x19 correspondence rank value in the rank table
3. See that the value you clicked on exists
4. Look in the graph and see the date for when those games happened (Dec 10)
5. Look in the Game History and see no ranked 19x19 games at all

**Expected behaviour**
Rank table and graph should not have 19x19 values since there are no such games

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
