### ISSUE TITLE
Joseki dictionary unavailable

### ISSUE THREAD

**Issue by AresUII** [online-go/online-go.com#1025]
Joseki dictionary unavailable, showing detailed error message

To reproduce:
1. Go to OGS website
2. Click on "Joseki" tab

Expected:
Blank goban with green and olive squares in the upper right

Actual:
![OGS Josekipedia Problem 20191218](https://user-images.githubusercontent.com/42591316/71118446-307ce280-21a6-11ea-8a3c-f0b9836d1fcd.png)

Windows 10
Firefox 71 and Chromium 74 tested

Addendum:
Clicking there does not file a report.

**Comment by BHydden** [comment]
Confirmed on Samsung Galaxy S7
Brave 1.6.0, Chromium 78
![Screenshot_20191219-060233_Brave](https://user-images.githubusercontent.com/28991649/71119243-a5194680-21d1-11ea-917f-07286ca1caa1.jpg)

**Comment by BHydden** [comment]
@anoek @GreenAsJade 
Could this be related to #1020 ?

**Comment by GreenAsJade** [comment]
Confirmed.   The database back end is not responding.

**Comment by anoek** [comment]
Fixed.

No it wasn't #1020, for some fail of a reason the server auto-updated to 4.0-preview which requires Java 11 which wasn't on the system. I "downgraded" to the latest stable to bring it back online.

**Comment by BHydden** [comment]
> for some fail of a reason the server auto-updated

Was it a Microsoft server? :smirk:
