### ISSUE TITLE
Generalization of server notification statuses (for gtp2ogs)

### ISSUE THREAD

**Issue by wonderingabout** [online-go/online-go.com#1027]
**Is your feature request related to a problem? Please describe.**
Currently, we don't know the notification status in some cases : 
- `notification.handicap`: returns a number of stones (ex: `5`) or `-1` if handicap is automatically chosen
- `notification.komi`: returns a komi number (ex: `7.5`) or `null` if komi is automatically chosen
- `notification.challenger_color`: returns a color string `"automatic"`, `"random"`, if color is automatically or randomly chosen
etc.

The problem in all these cases is that we don't know from server the notification status and/or the value:
- ex: `notification.komi` `null` (automatic) does not tell us if automatic komi was set to `7.5`, `6.5`, `5.5`, `0.5` : 
`null` does not allow us to check challenges to accept based on automatic komi value (for example if automatic komi is set to `6.5` but bot admin wants to specifically allow `7.5` komi too, then bot admin has to do `--komis automatic,7.5`, and `--komis 7.5` will reject komi `automatic` even if the automatic komi value happens to be `7.5`

- ex: `notification.handicap` does not tell us if automatic handicap was set to `0` or `3` or `5` stones : 
`-1` does not allow us to check challenges to accept based on `minhandicap` and `maxhandicap` arguments
- same problem for `challenger_color`, we don't know if `random` or `automatic` color were set to `·black` or `white`, so we cant check challenges based on allowed colors by bot admin
etc.

**Describe the solution you'd like**
We would like to know the notification status separately from the notification value:
example:
`notification: {komi: {status: "custom", value: 7.5}}`
`notification: {komi: {status: "automatic", value: 7.5}}`
`notification: {komi: {status: "automatic", value: 0.5}}`

Server gives or should give an `automatic` (setting value choice by server) or `custom` (setting value choice by user), or some other specific statuses

to make coding more efficient in gtp2ogs, we would like to have a server status for all these arguments : 

### A) for "automatic-independent" status allowed families

here it is always the user who chooses the setting, never the server

- `speed`: `custom` (server never chooses this)
- `timecontrol`: `custom`, `none` (server never chooses this, and `none` is the staus telling us of the absence of time controls, not a specific time control called "none")
for example : 
`notification: {timecontrol: {status: "none", value: false}}`

- `boardsize` : `custom`
also, for boardsizes specfically, we would like a new variable `notification.boardsize` that comes with a status, such as : 
`notification: {boardsize: {status: "custom", value: {width: 19, height: 19}}}`

### B) for status dependent allowed families

Server gives or should give an `automatic` (server's choice) or `custom` (user's choice), or some other specific statuses : 

- `handicap` : `automatic`, `none`, `custom` (again none is a status indicating the absence of handicap stones, it should come with an additional 0 number, for example:
`notification: {handicap: {status: "none", value: 0}}`
- `komis` : `automatic`, `custom`
- `challenger_color` : `automatic`, `random`, `custom`
- `rules` : `automatic`, `custom` (this allows bots configured to use other rules ex: `japanese` not to be forced to use `chinese`)

**Describe alternatives you've considered**
.

**Additional context**

defaults will be provided for bot admins that allow everything if needed, so it will not add extra effort for bot admin
--boardsizes `all` (same for all other families) in gtp2ogs would allow all boardsizes, default is 9,13,19
--speeds `all` would allow all speeds (blitz, live, correspondence), default is `all`

new gtp2ogs code for the allowed families : 
- in config.js: https://github.com/wonderingabout/gtp2ogs/blob/refactor-all-ranked-unranked/config.js#L290-L291
- in connection.js : https://github.com/wonderingabout/gtp2ogs/blob/refactor-all-ranked-unranked/connection.js#L410-L420
- in PR : https://github.com/online-go/gtp2ogs/pull/213

- `notification` so far : 

`
{"id":"592558:fe07d942-1b3b-4540-8065-a73e9d82b924","type":"challenge","player_id":592558,"timestamp":1576818353,"read_timestamp":0,"read":0,"aux_delivered":0,"game_id":20948492,"challenge_id":6077314,"user":{"id":479173,"country":"fr","username":"metaphysician splurgist :)","icon_url":"https://b0c2ddc39d13e1c0ddad-93a52a5bc9e7cc06050c1a999beb3694.ssl.cf1.rackcdn.com/9112aec101fca2f21a0a96b81d57dc10-32.png","ratings":{"overall":{"deviation":113.40208094581482,"rating":1874.2383461965808,"games_played":123,"volatility":0.06310876387739085}},"ui_class":"","professional":false,"rating":"696.388","ranking":24.7100403447036},"rules":"chinese","ranked":false,"aga_rated":false,"disable_analysis":true,"handicap":0,"komi":null,"time_control":{"system":"fischer","time_control":"fischer","speed":"live","pause_on_weekends":false,"time_increment":40,"initial_time":300,"max_time":300},"challenger_color":"automatic","width":19,"height":19}
`

- side note :
 - `notification.private`: does not exist, would like it to be supported as well

**Comment by anoek** [comment]
It would be possible to send an expected value, but it is not possible to make that value reliable. If player A sends B a challenge, but B doesn't accept right away, then if A or B plays any other games and changes their rank, that might very well affect those values. This would most certainly happen if a bot was offline for awhile for instance. I think if a bot is picky about the komi it can support, then it should probably just be specified.

With that in mind perhaps we should instead add a way for the bot to specify what komi/handicaps it accepts, and then they will be a fixed value when they come to you?

Re color, why would a bot be picky about the color it plays?

I'll add private as I visit this topic `private`, no problem

**Comment by wonderingabout** [comment]
thanks, i understand the technical limitations

for the `komis` it may indeed work for now, even though we still can't filter komi based on automatic value

also for `handicap`, something similar to your suggestion that we are already doing in gtp2ogs is `--fakerank` (the fakerank code is here in its latest version : https://github.com/wonderingabout/gtp2ogs/blob/refactor-all-ranked-unranked/connection.js#L352-L382) : 

in fakerank, bot admin sets a fictive bot ranking (ideally as close as possible from the actual bot ranking, for example `--fakerank 8d`, then the fakerank code compares the fake bot ranking with the user ranking.

For example if user ranking is `2k` and `--maxhandicap 3`, fakerank will calculate rank difference (parserank("8d") - parserank("2k") = `10`).
Then if `notification.handicap === -1` (handicap is automatic), we will compare the fake automatic number of handicap stones (here 10 stones based on rank difference), and if it out of `--minhandicap` and `--maxhandicap` (here 10 > max 3 stones, so we'd reject the game)
There is  one limitation to this current implementation : 
- if `minhandicap > 0`, we will reject automatic handicap (because `-1` > `0`)

However setting `minhandicap` to `0` or more disables automatic handicap (so we end up rejecting most challenges), and disabling `minhandicap` makes automatic handicap `-1` always inferior to `maxhandicap`
A workaround would be to use `--noautohandicap` (or --noautohandicapranked), but for now default is false, maybe we should enable it as a default, because some bot admins reported that their bots play handicap ranked games (even though they set `maxhandicap 2` or less) and lose because their bots do not handle many stones of handicap

So, to conclude on the rank needing a refresh if the challenge was sent long ago, maybe it is possible to add an expiration time on the challenges ?
For example, after 15 minutes, challenges requests unanswered are automatically rejected, or maybe it already exists ?
But for a bot playing many games even in that short while bot ranking could be significantly changed too.
So maybe instead it is possible to send bot ranking somehow out of the notification (when we long into gtp2ogs for example ? i dont know the technical details so i am just suggesting general ideas)

finally for `rules` specifically, is it possible not to force `chinese` on the server side, and instead let gtp2ogs use a default for allowed rules set to `chinese`, with the possibility for bot admin to optionally change it ?
I heard that some bots are configured to play under japanese or other rules, maybe they would like to accept japanese rules games.

For `private` thanks too, it was a recurrent request recently

thanks for your feedback and thoughts

maybe @roy7 and @Dorus have thoughts to share about all this

**Comment by anoek** [comment]
Re expiring challenges, that seems like a worthwhile feature, especially for live games, though if it's a more urgent concern that should also be doable on the gtp2ogs side by looking at the timestamp and just rejecting it if it's too old. On the server side, that's going to take a bit more work, though the notification system is due for some revamping so I'll see if I can get it working with that.

For rules, yeah it sounds like I need to start allowing some more rulesets now that bots exist that support them. That was more of a hack put in place a long time ago to stop breaking bots :)

**Comment by wonderingabout** [comment]
just added a commit to support custom `rules` : https://github.com/online-go/gtp2ogs/pull/213/commits/9e6fb90058704940f21a8f053b953464be7e789f 

in PR #213

**Comment by Dorus** [comment]
Re expiring: Just adding the challange date and time and let the bot deal with this would be just fine. However i see little value in rejecting old challenges. If the other player is offline by now, the game will be canceled anyway as games under a few moves are canceled.

Re handicap expectation: Bot ping time is only like a few milliseconds, perhaps worse case seconds. As long as you send the current values when the bot connect, and not the values at the time the challenge is send, i have very little concern with the special case where a user manages to send a challenge and win/lose a game in the exact same second.

What i mean is, sharing the expected values would be a huge improvement over sending nothing as we do right now.

It would be cool to have the ogs interface share bot limitations, so that the user does not have to challenge a bot to find out his rank is  too low, his board size is incompatible, handicap is not accepted etc. etc. But all that should be secondary to the simple solution to just share a little extra data with gtp2ogs to at least have some basic support for private/public games, expected handicap and all that.

**Comment by wonderingabout** [comment]
re on the PR in https://github.com/online-go/gtp2ogs/pull/213/commits/cf9959320375f8365f4c24e37d0db189e7b871fc

added support for : 
- `--privateonly` `--publiconly` (commented out)
- `--rules` `--rulesranked` `--rulesunranked` to support multiple rules (default `chinese`)
