### ISSUE TITLE
Allow plan conditional moves when it is your move

### ISSUE THREAD

**Issue by hzamir** [online-go/online-go.com#1030]
Problem:  When I decide on a move, I often use "Analyze" feature, then when I actually want to submit a move, if I want to plan conditional moves, I have to replicate that work.

Solution: If plan conditional moves would work when it is my turn to move, then the first move would actually be unconditional. Also, I would not have to put in my conditional responses only after having submitted a move, and possibly be forced back into analysis mode after a response.

Alternatives: My original idea was to allow submitting move and conditional moves from analyze mode, but I just realized that adapting "Plan Conditional Moves" to this purpose seems really more straight forward.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
