### ISSUE TITLE
Additional puzzle features

### ISSUE THREAD

**Issue by RobertT53** [online-go/online-go.com#1031]
I would like for the puzzle section to have some additional settings options that would help with study or turn the puzzle section into a game similar to the joseki section.

Puzzle auto advance - Once a puzzle is solved or failed, it auto advances to the next problem.

Randomize puzzle order - Increase puzzle replay-ability by not just memorizing the specific puzzle order.

Running tally of solves vs failures - This would be keeping track of how many success/failures for just this attempt at the collection and could be an overall success/failure rate over all attempts at the puzzle collection.

A timer - either a timer for the overall collection (solved x problems in y time) or a time per problem (solved x number of problems before getting y number of problems incorrect)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
