### ISSUE TITLE
some games does not count in the 'games with your move pending' notification counter

### ISSUE THREAD

**Issue by gubihu** [online-go/online-go.com#1033]
Sometimes some game I'm next to move does not count in the black circle counter.
Actually as I just used to click through that till there is no more game, I can fail on timeout because of this bug.
The game shows on the "home" screen, but not in the counter:
![image](https://user-images.githubusercontent.com/12248483/71910737-c509ad80-3172-11ea-87be-a177db744e48.png)
On this screenshot I have one game I'm next to move (nearly timeout-ed), but show 0 in the black circle.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
