### ISSUE TITLE
Puzzles mobile template

### ISSUE THREAD

**Issue by Nihisil** [online-go/online-go.com#1034]
Is it bug with mobile view of puzzles page or there is just no responsive template on this page? It is kind of hard to figure out what is going on on the board.

**Screenshots**
![image](https://user-images.githubusercontent.com/475367/72032669-15941e80-32cb-11ea-9f08-84202aa6a11d.png)

**Smartphone**
 - OS: Android 9
 - Browser FireFox 68.3.0

**Comment by anoek** [comment]
Bug or missing feature, definitely.
