### ISSUE TITLE
Review Mode: Pen markings not showing up for other users

### ISSUE THREAD

**Issue by bdrose** [online-go/online-go.com#1037]
**Describe the bug**
When in review mode, the pen tool is not visible on other users screens.

**To Reproduce**
1. Create review of a game
2. Have other users in the review
3. Use pen tool to draw on the board, which I can see.
4. Other users cannot see the pen marks when they are synced up to the reviewer

**Expected behavior**
The pen tool used to show up on other users screens, prior to mid-December

**Comment by anoek** [comment]
Fixed
