### ISSUE TITLE
Cancellation message for live tournaments doesn't appear on tournament page.

### ISSUE THREAD

**Issue by koshogs** [online-go/online-go.com#1038]
When waiting for a live tournament to start, the cancellation message doesn't appear in any way on that page. For an experienced user this is only a small trap but for a new user it may significantly impact their early impression of the site as they wait unwittingly. Even after cancellation the message, 'Tournament starts very shortly' continues to be displayed.

**To Reproduce**
1. Enrol in a live tournament that is unlikely to start.
2. Stay on tournament page.
3. Observe no change in available information long after tournament is cancelled (~5min after due start).

**Screenshots**
![Tcancelled](https://user-images.githubusercontent.com/44488770/72660036-358ab700-3a1c-11ea-9ffe-fcbb0db8e647.png)

**Additional Information**
Previously brought up here: https://forums.online-go.com/t/notification-query-participants-left-hanging-in-cancelled-tournaments-bug/22435/6 but one of the issues raised then has already been addressed. Specifically the message that advises me to stay on the page.

**Comment by anoek** [comment]
Yeah good point
