### ISSUE TITLE
a page in a player's Game History won't load (it contains a game where he played himself)

### ISSUE THREAD

**Issue by edhalter** [online-go/online-go.com#1040]
**Describe the bug**
Found a [strange game](https://online-go.com/game/2598338) played on 10 Aug 2015 where the [same player](https://online-go.com/player/163711/001616542.) is both black and white. In the Game History table on his player page, the page containing that game (page 20) can't be viewed -- a js error appears in the console, thrown from PaginatedTable.tsx:179.

**To Reproduce**
1. Go to the player page for user [001616542](https://online-go.com/player/163711/001616542.) (id 163711)
2. In his Game History, go to page 19 -- loads fine
3. Click the right arrow
4. The Game History table stays on page 19; a js error appears in the console

**Expected behavior**
The Game History table displays the selected page (page 20)

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Browser: Firefox
 - Version: 72.0.1

**Additional context**
Black won the game by Cancellation. Found the game while looking at game data I pulled using the api, and had trouble parsing the json. The 'players' key had both 'black' and 'white', both referring to the same user, but the 'historical_ratings' key only had 'black'.

**Comment by anoek** [comment]
Fixed
