### ISSUE TITLE
Ladder timeouts sometimes aren't processed fully.

### ISSUE THREAD

**Issue by koshogs** [online-go/online-go.com#1041]
**Describe the bug**
When a ladder game ends by timeout the loser should be removed from the ladder with the winner rising to their place on the ladder. This sometimes fails to occur.

**To Reproduce**
A method for guaranteed reproduction is not known however there are multiple examples reported 
to the moderator team and I stumbled across this extreme example:

![mmueler](https://user-images.githubusercontent.com/44488770/73058782-738a4e00-3ee8-11ea-8a5f-a16e82dd4cc2.png)

'mmueller' (user212643) has been challenged three times in a row by 'mita va' (user66704) and lost by timeout every time (as Black and White) but the result has never been processed for ladder purposes. Games: https://online-go.com/game/19865937, https://online-go.com/game/20207232 & https://online-go.com/game/21310026

Other examples from forums include: https://forums.online-go.com/t/ladders-timeout-question/24285, https://forums.online-go.com/t/issues-with-ladder-timeouts/15470/5, https://forums.online-go.com/t/ladderbug-not-being-dropped-out-after-a-timeout/22792 and in my short time on the ladder recently, I have already encountered the bug twice.

**Expected behavior**
Loser should be removed. Winner should be elevated if applicable.

**Desktop (please complete the following information):**
 - In my case. Windows 8, Chrome.

[Edit] **Extra Example**

![CSoy](https://user-images.githubusercontent.com/44488770/73141209-a2b1e280-40d5-11ea-82ac-08597cc114db.png)

User 638773 appears to have had a 'hat trick' of timeout ladder losses +1 against me without being removed from the ladder. There are no wins to explain his post-losses position of ~400th.

It may be that the vast majority of instances aren't being reported and this bug is much more prevalent than generally thought.

**Comment by Adam314159** [comment]
@anoek I believe this issue has been solved some months ago by your update. I have not heard a single report for months now.

**Comment by anoek** [comment]
Thanks @Adam314159 , closing unless it resurfaces
