### ISSUE TITLE
Idea: save game configs

### ISSUE THREAD

**Issue by pondturtle** [online-go/online-go.com#1043]
A lot of players have 1-3 time settings, rank limitations and types of games (corr, live, blitz), they tend to play most often. It becomes pain in the butt rather fast when You have to manually change everything over and over again. It would be really cool if I could just save some goto game settings and just pick it from the list and press a button.

**Comment by climu** [comment]
I want to say this would help OSR users very much. Our leagues games have a fixed setting and users have to set it right each time.

One could think about a way to create a new "game setting" from an existing game. It would copy all game setting.

**Comment by LucasBertrand** [comment]
I can think of displaying this option in the profile of the user to challenge and let the challenger to select rules from a running league ?

**Comment by benjaminpjones** [comment]
Closed by #1719
