### ISSUE TITLE
Drawing tool broken

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1045]
Whether or not the marks appear to the reader of the review is messed up.

If you look at this review

https://online-go.com/review/443535

there are marks made by the reviewer about options at Move 38.

The reviewer themselves is confused whether their marks are saved.

In fact they are, but the only way to see them is to click on the chat-move-link for that position.

Once you _do_ click there, the marks never go away - they clutter up the board unless you reload the page.

**Comment by anoek** [comment]
Yikes..

**Comment by BHydden** [comment]
bug. priority. stale.

...I love it :heart:
