### ISSUE TITLE
Double Elimination Fails to Repeat Grand Final 

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#1046]
**Describe the bug**
In the event that the undefeated player loses in the grand final of a double-elimination tournament, the grand final should repeat as both finalists have just one loss.

**To Reproduce**
1. Go to https://online-go.com/tournament/54163 (just one of many examples)
2. See that Darth Noob was deemed the winner, despite tienslebien having only lost one game (the final)

**Expected behavior**
When the undefeated player in a double-elimination grand final loses his first match, the grand final should go into a second round to resolve both finalists having only lost a single game.

**Comment by BHydden** [comment]
This is an old issue with the primary discussion over the years focussed [in this forum thread](https://forums.online-go.com/t/double-elimination-eliminated-on-first-loss/3382)

**Comment by Racines** [comment]
Hi. same bug here and also when I lost the final I get only the copper medal :'(

https://online-go.com/tournament/48688

**Comment by benjaminpjones** [comment]
Timely...

**Comment by dexonsmith** [comment]
Being discussed on the forums at https://forums.online-go.com/t/update-to-double-elimination-tournament/50521
