### ISSUE TITLE
Use CSS prefers-color-scheme to automatically select dark mode

### ISSUE THREAD

**Issue by soerface** [online-go/online-go.com#1047]
OGS already supports a dark theme. It would be nice if it was enabled automatically if the user enable dark mode in his operating system.

This can be achieved with the new `prefers-color-scheme` CSS media query. Example:

```
@media (prefers-color-scheme: dark) {
   /* here are css rules that are only interpreted in dark mode */
}
```

Documentation: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by anoek** [comment]
yes indeed! I've been wanting to do that as well.
