### ISSUE TITLE
Scoring phase timer reunning out not terminating game immediately

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1052]
**Describe the bug**
Scoring phase timer running out not terminating game immediately

**To Reproduce**

* Start a live game
* Have both players pass, after playing a few stones
* Watch the timer run down
* See it sit there on zero

**Expected behavior**

The game should be finished with the currently showing score.

**Screenshots**

<img width="1440" alt="Screen Shot 2020-03-08 at 10 08 40 am (2)" src="https://user-images.githubusercontent.com/61894/76154034-7bfbb880-6125-11ea-8877-84d6f1c72a24.png">

**Desktop (please complete the following information):**
 - OSX, Chrome latest

**Comment by GreenAsJade** [comment]
BHydden and I measured it - it's about a minute that it sits there appearing stuck before it is finally ended.

**Comment by BHydden** [comment]
After just one test, time may vary game by game.

**Comment by benjaminpjones** [comment]
Oh whoops I made a dupe.  I actually did dig into the issue a bit, looks like the timer is still on the game timer not the scoring timer

https://github.com/online-go/online-go.com/issues/1352
