### ISSUE TITLE
Level displayed in the chat when posting a review is incorrect

### ISSUE THREAD

**Issue by SylvainCME** [online-go/online-go.com#1056]
**Describe the bug**
When creating a review, the level displayed is different than the one displayed at the top,

**To Reproduce**
I just created a review. 

**Expected behavior**
The level displayed at the top and in the chat should be similar.

**Screenshots**
![image](https://user-images.githubusercontent.com/61039194/76174927-01a76300-620f-11ea-91fa-64c67e2ebb6a.png)
https://online-go.com/game/21533849

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Similar to this closed issue: https://github.com/online-go/online-go.com/issues/704
It looks like the level may be always 5K when the problem arises, that should be a hint.

**Comment by BHydden** [comment]
This is still a problem, including for our pro players. Wherever the chat pulls the rank from, it's a different location to the review box above or the player card.

**Comment by BHydden** [comment]
Best I can tell this issue has been fixed now.
