### ISSUE TITLE
games with null komi can cause AI review to fail

### ISSUE THREAD

**Issue by edhalter** [online-go/online-go.com#1057]
**Describe the bug**
For some games, at least one of the komi fields is null. When both fields are null, the komi appears as "NaN" in Game information and the AI review fails (it stays stuck in "Processing").

**To Reproduce**
1. Go to e.g. [game 708444](https://online-go.com/game/708444)
2. AI review fails (stuck in "Processing"); in Game information, komi appears as "NaN"

**Expected behavior**
AI review displays as normal; in Game information, komi is displayed (whatever its value).

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 68.5.0

**Additional context**

Appear to be 2 different types of games:

1. Komi appears as "NaN" in Game information (e.g. [708444](https://online-go.com/game/708444), [API](https://online-go.com/api/v1/games/708444))
2. Komi appears as normal in Game information, but one of the API komi fields is null (e.g. [673352](https://online-go.com/game/673352), [API](https://online-go.com/api/v1/games/673352))

Checked a few games of each type, and it looks like only type 1 games break the AI review.

Regarding the multiple fields, let's use user [80572](https://online-go.com/player/80572) as an example of a type 2 game. His most recent game was [708830](https://online-go.com/game/708830). Game information shows komi as 6.5. (The AI review works.) The [/games API](https://online-go.com/api/v1/games/708830) shows 2 komi fields. The 1st, at top-level, is null. The 2nd, under gamedata, is 6.5. (The gamedata field contains duplicates of other top-level fields, like handicap and rules, but their values are the same in both places.) In his [/players/[id]/games API](https://online-go.com/api/v1/players/80572/games/?ordering=-ended), there's no gamedata field, so there's only 1 komi field, the one w/ the null value.

(Incidentally, the komi in type 2 games isn't always 6.5. For example, [game 705574](https://online-go.com/game/705574) ([API](https://online-go.com/api/v1/games/705574)) has komi of 7.5.)

In contrast, reusing [game 708444](https://online-go.com/game/708444) from above, the [API](https://online-go.com/api/v1/games/708444) reports null top-level komi **and** null komi under gamedata. Then, since that game went to scoring, there are 2 **more** komi fields: gamedata[score][white][komi] is null, while gamedata[score][black][komi] is 0.

**Comment by anoek** [comment]
Thanks for digging into that! I'll try and get that fixed up tomorrow.

**Comment by anoek** [comment]
And by tomorrow I meant a couple years.. but it's fixed!
