### ISSUE TITLE
update French profanity filter

### ISSUE THREAD

**Issue by oluc** [online-go/online-go.com#1058]
French profanity filter is filtering out "gueule" (why not), 
but this word is used in "gueule du tigre" which is "tiger's mouth" Go shape.

It should not filter out "gueule" when used in "gueule du tigre".

**Comment by oluc** [comment]
yes, you should update the filter.

**Comment by cassidoo** [comment]
This doesn't appear to be an issue anymore, cc @anoek

**Comment by anoek** [comment]
Thanks!
