### ISSUE TITLE
Chat userlist sort by ranking sometimes doesn't

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#106]
Noone actually put this in the issue tracker yet? I guess I will. :)

Sometimes, seemingly related to people entering or leaving the chat room, the list will fail to re-sort by ranking. Sometimes what happens is the top of the list stays okay but the bottom of the list isn't sorted, such as seen here:

http://puu.sh/uysaZ/7ebf4f4a28.png

Other times the entire list will become seemingly unsorted:

http://puu.sh/uysnO/1b7f56e07c.png

Anoek is always first in the unsorted list, so I thought maybe it was sorted by user ID #?

In time it will re-sort and look correct again. But then later on will de-sort itself.

**Comment by anoek** [comment]
I suspect it might be related to guests joining, I haven't confirmed yet though

**Comment by roy7** [comment]
Now that you mention it, when a guest joins and sorting breaks, if I re-sort manually, it seems like the sorting breaks where the guest appears in the list. All above that are fine, all below it mixed up.

Maybe the case where ranking is null isn't handled in the sort? I assume guests should sort below 30kyu players. Like basically -1 rank.

**Comment by roy7** [comment]
`this.users_by_rank.sort((a, b) => { if (a.ranking - b.ranking === 0)  { return a.username.localeCompare(b.username); } return b.ranking - a.ranking; });`

I assumed the problem was in this code someplace. However the - operator always converts null to 0, so it wouldn't be that. If ranking is undefined and not null for guests, then perhaps that is causing the issue.

I tried testing with local dev server though and couldn't reproduce the problem even with a couple guests popping in and out of chat on the beta server. If it's an undefined vs null issue, then a simple fix like

`if (a.ranking == undefined || b.ranking == undefined) return 0; return b.ranking - a.ranking;`

might solve it? But I'm not sure this is even the problem.
