### ISSUE TITLE
Mark rated games in game list

### ISSUE THREAD

**Issue by w3333** [online-go/online-go.com#1062]
One thing that bugged me several times now is that it's easy to overlook if a game request is rated or not. Especially on mobile, that column of the game list isn't even in the visible area, but also on the desktop it's quite easy to miss. We discussed that on ogs at https://forums.online-go.com/t/filtering-game-list-by-rated/25182/6. If anyone could squeeze that in, it would be really nice. Just making rated games bold, or anything that is easier to spot will do. Thanks.

**Comment by BHydden** [comment]
Already resolved.
