### ISSUE TITLE
Group-specific games

### ISSUE THREAD

**Issue by airjp73** [online-go/online-go.com#1067]
**Is your feature request related to a problem? Please describe.**
My local go club had an online meetup through our OGS group and one thing we ran into was the fact that there's no way to see games that the members are playing. I noticed this has been brought up a couple times on the forums and @anoek mentioned in [this post](https://forums.online-go.com/t/group-specific-games/1684/11) that the support is already there on the backend.

**Describe the solution you'd like**
Some way to see the games that group members are playing. I'm not super picky about the details and would love to hear your thoughts on what you think this should look like.

**Additional context**
I understand that it's a feature that doesn't feel super necessary unless more people are using groups, but it also feels to me like not having this feature makes groups less desirable to use.

I'm interested in implementing this myself if you don't want to prioritize it. Some guidance on how the backend works would be helpful though -- assuming the support for it is still there (that forum post was 6 years ago after all).

**Comment by nemolivier** [comment]
Have-you seen this thread : https://forums.online-go.com/t/kgs-style-rooms-in-groups/25191/8 ?
It seem's that you're aiming the same thing.
With confinement, i guess more and more people would like to be able to have more control over the group usage.

**Comment by airjp73** [comment]
Thanks for bringing that thread to my attention! I'm definitely trying to get at something similar. Our club meetings have moved online due to COVID-19, but the group features on OGS still leave a little to be desired.

**Comment by nemolivier** [comment]
It's exactly the situation where open source can show all his power 😄

**Comment by airjp73** [comment]
I believe this is addressed by #1203
