### ISSUE TITLE
Puzzly typo

### ISSUE THREAD

**Issue by skywinder** [online-go/online-go.com#1071]
I found a small typo in one of the puzzles. would like to make a PR, but can't find, where all the puzzles are stored?

ps if it's in closed db, so here it is:

https://online-go.com/puzzle/2632

> This group has an eye at A. (White can’t play at **B** because the stone would be immediately captured) 
-->
This group has an eye at A. (White can’t play at **A** because the stone would be immediately captured)

**Comment by mmartin** [comment]
That's not a typo.
Playing at *A* is illegal move – suicide.
Playing at *B* is bad, because it would be immediately captured by Black playing *C*.

Also, for puzzle content related problems, You should either ask about it in [the chat](https://online-go.com/chat) contact the author.

**Comment by skywinder** [comment]
Thank you 👍
