### ISSUE TITLE
AI annotation inconsistency

### ISSUE THREAD

**Issue by benjimin** [online-go/online-go.com#1075]
I've noticed that in AI review, the blue circle is not always the greatest value among the numbers displayed.

This is inconsistent with the documentation (that although the green shades mean something else, the numbers are the impact on win probability, and the blue is the most optimal move).

Is this expected behaviour (that might warrant further clarification of the documentation), or is it a bug? Is there something I can inspect to know if the analysis data is strange or just the visualisation layer?

https://online-go.com/game/22649372

![image](https://user-images.githubusercontent.com/12852539/77815791-b7c8e300-7111-11ea-8ffe-290b2326f2f7.png)

![image](https://user-images.githubusercontent.com/12852539/77815969-26f30700-7113-11ea-812c-1d39a8ca7992.png)

tested on: macOS Catalina, Chrome 80.0

**Comment by flovo** [comment]
Hi,

thank you for your report. I had a look at your [game](https://online-go.com/game/22649372). The numbers seem to differ from your screenshots.  I've identified move 15 for your first screenshot, and move 34 for your second screenshot.

The KataGo AI review I've found and used is:
![image](https://user-images.githubusercontent.com/4864182/77820815-6d317180-70e5-11ea-8ea4-0022ac0f60b1.png)
move 15:
![image](https://user-images.githubusercontent.com/4864182/77820956-6f480000-70e6-11ea-845f-22773ee901b3.png)

move 34:
![image](https://user-images.githubusercontent.com/4864182/77820946-54758b80-70e6-11ea-95f8-73a5ed8fa2ce.png)

There was also a LeelaZero run, but it matched even less with your screenshot.

The numbers I've seen are in an expected range for the top move. The move suggested by the AI hasn't to be the move with the highest winrate. The AI calculates a confidence estimation as well. The suggested move is then calculated using winrate and confidence. (The documentation fails to mention this)

Also in your first screenshot, the AI hasn't explored the played move at all (no green background). It could be just a blind spot of the AI. 

Your second screenshot is strange. The suggested move has a much lower winrate than the other well explored move. But it looks much better now.

----

The current reviews are Supporter level 2 reviews. Does that match your Supporter level (when you made the screenshots)?

And can you please verify if you still have the numbers of your screenshot? Can you provide which AI review you are using if this is still the case?

----

If you are interested in the raw data, you can take a look at 

https://online-go.com/api/v1/games/22649372/ai_reviews for the review_ids and https://online-go.com/termination-api/game/22649372/ai_review/3239722 for the raw data. What you're seeing on the goban is just a visualization of those data with only minor adjustments. It should either be in agreement with the raw data in all cases, or should be wrong for all cases.

The `branches` for each move are sorted by preference of the AI. Branch 0 is the move the AI would play, branch 1 is its second choice, and so on. Coordinates for each axis are 0..18 with 0-0 being the top left corner (A19).

**Comment by JDNdeveloper** [comment]
Just wanted to give this a bump. I've noticed this a lot in my games, where the optimal move shown is pretty much always "0", but if it's also the move I played then it has a non-zero win rate.

For example:

When it's NOT the move played:
![image](https://user-images.githubusercontent.com/4645409/103465588-27e44500-4cf2-11eb-99c2-287f4e21c13c.png)

When it's the move played:
![image](https://user-images.githubusercontent.com/4645409/103465585-18fd9280-4cf2-11eb-9b51-23dc8925a3a1.png)

Game for reference: https://online-go.com/game/29740115/7
