### ISSUE TITLE
German voiceover error

### ISSUE THREAD

**Issue by ISibboI** [online-go/online-go.com#1076]
**Describe the bug**
The German voiceover says "vorbeiziehen" instead of "passen" when you pass during a game.

**To Reproduce**
Pass during a game.

**Expected behavior**
The voiceover says "passen", the correct translation of "to pass" in this context.

**Comment by BHydden** [comment]
See also this feedback for German pass voiceover: 
https://forums.online-go.com/t/additional-voice-languages-are-now-available/25894/22?u=bhydden

**Comment by ISibboI** [comment]
The alternative to "passen" in that post is better than mine.

Another addition: When annulling a game, it says "[color] wins" in German, instead of saying "[color] annulled the game" or something.
