### ISSUE TITLE
Unable to change Board Labeling in settings

### ISSUE THREAD

**Issue by phil-flex** [online-go/online-go.com#1077]
**Describe the bug**
The new settings UI, make me unable to change the [Board Labeling] in the setting, so that I have to switch language to change it.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Game Preferences'
3. Scroll down to 'Broad Labeling'
4. No way to change the value.

**Expected behavior**
I should be able to change it.
**Screenshots**
![ogs-board-labeling](https://user-images.githubusercontent.com/34325924/77837988-189ffc00-71a2-11ea-8e08-81821c9af1e5.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10 64bit]
 - Browser [Firefox v75, Chrome v80]
 - Version [UI: 5.1-2188-g6bf39cb]

**Additional context**
Besides the unable to change [Board Labeling] the "1-1" options on previous version also have another issue. If I changed to Chinese for example, it will have one of the axis become Chinese one "一, 二, 三..." , but I am not sure it is by design, but in Chinese "1" and "一" seems looks odd, is it 1,2,3,4..." at both x-y axis should be better? And I think the default value use A1 for Chinese is better, since if we communicate in messaging using A1 format is better than 1-1 format.

**Comment by BHydden** [comment]
I can confirm I experience the same issue.

OS: `[Windows 10 64bit]`
Browser: `[Brave Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)]`
Version: `[UI: 5.1-2188-g6bf39cb]`

**Comment by anoek** [comment]
Whoops! Fixed in 3ef532c4975883d03c69cb21bc4be25581554a1e
