### ISSUE TITLE
Account configuration mix up when sharing computer

### ISSUE THREAD

**Issue by dhrou** [online-go/online-go.com#1080]
**Describe the bug**
My son and I are playing under different account under the same computer. Trouble is that his configuration is leaking into mine.
In particular : 
 - dark mode or not
 - more annoying : when I create a game, the default is the one of his last game (not mine). So I have to spend time to re-specify clock, min/max rank etc...
My guess it has to do with the cookie which is independent of the account

**To Reproduce**
On the same computer. 
Log in as Alice, set mode Dark, create a custom game 3x3, cancel it.
Log in as Bob, notice the mode is Dark, change to Light, create a game, notice the default is 3x3, change it to 9x9, create and cancel
Log again as Alice, notice the Light configuration , and default game 9x9 instead of Dark and 3x3

**Desktop (please complete the following information):**
Mac book pro Catalina, with Safari 13.0.5 (I'm new to OGS so I can't say this is a new problem)

**Comment by dhrou** [comment]
(I am user dhpmrou )

**Comment by GreenAsJade** [comment]
Related thread: https://forums.online-go.com/t/mix-up-when-sharing-computer/26202
