### ISSUE TITLE
Plain links not recognized in markdown formatted fields

### ISSUE THREAD

**Issue by juanchodepisa** [online-go/online-go.com#109]
### Summary

Hyperlinks are not recognized as such when plainly written within text. The only way to get them to behave properly is to specifically tell markdown to do so, by writting `[http://example.org/](http://example.org/)
`
### Environment

 * Operating system: n/a 
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:

1. Go to your profile
2. Click edit
3. type http://example.org/
4. Save
5. Notice this is treated as plain text

**Comment by juanchodepisa** [comment]
Sorry to reopen the discussion, but this seems not to work well with bulleted lists.

For example here https://online-go.com/group/149 there's a news entry by adrianvc that does not render properly.

**Comment by anoek** [comment]
Mm indeed, looks like we should probably switch markdown renderers to do this properly
