### ISSUE TITLE
Suggestion: When ratings are set to hidden, hide the colors in the profile game history

### ISSUE THREAD

**Issue by CoolBoots** [online-go/online-go.com#1092]
**Problem:** At the moment, when ratings are set to hidden, you can still see whether an opponent was stronger or weaker than you by looking at the background color of the game in your game history (lighter colors for stronger, darker for weaker). I think it would better fit the spirit of the 'hide ratings' option to have these colors hidden.

![Annotation 2020-04-07 163620](https://user-images.githubusercontent.com/15002248/78689165-8c01e600-78e5-11ea-874b-6b6477e22e8d.png)

**Solution:** Remove the game history colors when 'hide ratings' is selected.

**Additional context:** I'm trying to do a challenge on OGS where I play 10 games with ratings hidden, and then look back on the results to see if there were any surprises, but the colors make this difficult. It's hard to avoid because I still need access to my game history.

**Comment by GreenAsJade** [comment]
@stefankoegel

**Comment by stefankoegel** [comment]
I will look into this.
