### ISSUE TITLE
Newcomer with rank ? able to play against lowest ranked bot (currently amybot-beginner 24k)

### ISSUE THREAD

**Issue by AlexCoul** [online-go/online-go.com#1102]
Hi, I'm a beginner, without rank, and I've found impossible to play against the lowest ranked bot (currently amybot-beginner, 24k) due to a rule forbidding scored games with rank difference > 9. This rule is good for most of use cases, but for a beginner it could be nice to be able to play at least against the "worst" bot.

**Comment by koshogs** [comment]
Sorry to be so late to the party but this could actually make a lot of sense and be good for OGS...

Ranked games beyond a nine kyu difference can be done as occurs in sitewide tournaments on a regular basis.

Allowing people with [?] rank to play bots below the usual allowed range would make it much easier for new players to establish a full ranking and that in turn makes it easier for everyone to find well matched games.

Hopefully the bots won't complain about the poorly matched games. ;)
