### ISSUE TITLE
A rank of "26k" is displayed

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1110]
**Describe the bug**

A player has reported seeing ranks lower than 25k from time to time.

https://pasteboard.co/J4IfztJ.png

**Comment by BHydden** [comment]
> https://pasteboard.co/J4IfztJ.png

![image](https://user-images.githubusercontent.com/28991649/79806767-8a87f180-83ac-11ea-9d50-a42fbbb20b5b.png)

**Comment by GreenAsJade** [comment]
We've had this before, but it works fine for me!  In different browsers, with different profiles etc!

![75d68b31-3862-44fc-980c-a0add66425b6](https://user-images.githubusercontent.com/61894/79820793-4c022f00-83cc-11ea-9686-22dea2e4c4bf.png)

**Comment by BHydden** [comment]
the lesson is to stop using pasteboard, obviously! 😂

**Comment by GreenAsJade** [comment]
That link was supplied by the original reporter.   You forced me to download and reupload :D 😛

**Comment by BHydden** [comment]
and I appreciate your consideration ❤️
