### ISSUE TITLE
Wiki page update: Understanding AI page missing lock icon explanation 

### ISSUE THREAD

**Issue by jaysephjw** [online-go/online-go.com#1111]
![image](https://user-images.githubusercontent.com/3268245/79889879-3f79d880-83c4-11ea-9afb-873e1e711bf4.png)

After AI analysis of a game I played, I noticed this lock icon. I couldn't find out what it was from https://github.com/online-go/online-go.com/wiki/Understanding-the-AI-review. 

What is it? Happy to submit a PR after!

**Comment by flovo** [comment]
It's 2 overlapping icons. The black territory square, and a 0.

**Comment by jaysephjw** [comment]
Thanks, I'll close this issue- overlap issues could be addressed separately.
