### ISSUE TITLE
Katago Point Estimation instead of Winrate

### ISSUE THREAD

**Issue by Zacharias030** [online-go/online-go.com#1113]
Could you please enable a setting to alternatively display the points-estimation from katago instead of the winrate delta on moves? Seems  like a cool feature for site supporters :)

I'd like it best, if  the  points total could be displayed on moves with negative numbers meaning that white is leading.

**Comment by koshogs** [comment]
Particularly useful suggestion in handicap games as the %win changes can be almost meaningless.

Mentioned here: https://forums.online-go.com/t/ai-review-game-score-graph-feature-request/24422

**Comment by Zacharias030** [comment]
Any news on this one?

**Comment by anoek** [comment]
Thanks @djma for the implementation!
