### ISSUE TITLE
Capture of a stone not allowed (not a ko)

### ISSUE THREAD

**Issue by bdrose** [online-go/online-go.com#1114]
**Describe the bug**
Capturing one stone that has just captured two stones is being recognized as a ko and not letting the one stone be captured in review.

**To Reproduce**
1. Go to game review https://online-go.com/review/468443
2. At move 203 alternate branch (There is only one) have white play at T2 for move 204.
3. Error message comes up 
"Move error in 23347159 on move number 203 at T2: illegal_board_repetition"

**Expected behavior**
This is not an illegal board position and should be an allowed move

**Screenshots**
![error](https://user-images.githubusercontent.com/30013849/80144796-c372c280-8574-11ea-808b-533c8c84822a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version  81.0.416.62 (Official build) (64-bit)

**Additional context**

**Comment by kobakitty** [comment]
Worth noting that game is played under AGA rules, which prohibits board repetition. Its case of "sending two, returning one"

**Comment by bdrose** [comment]
@kobakitty Can you point out where this is specified in official AGA rules documentation? I seem unable to find it when I look.
