### ISSUE TITLE
Profile update: Backend doesn't accept empty about or website field

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#1122]
**Describe the bug**

After a text for the *about* or *website* field on the profile is saved, one cannot delete (clear) the field. 

**To Reproduce**
1. Go to Profile page
2. Write something in the *website* or *about* field and save the change.
3. Clear the field again. (Click on edit and remove the text. The field should now be empty)
4. Click on save
5. See, that the field is still empty.
6. Reload the page.
7. Now the field again contains the text from before.

**Expected behavior**
After clearing the field, it should stay empty until we change it again.

**Additional context**
I tried to debug the problem. 

When clicking on save, a PUT request is sent. The payload contains the empty *about* and *website* fields (`"about":"","website":""`), but the response contains the old values again (`"about":"about","website":"website"`).

As workaround, one can just use a space (" "), which is accepted by the server.

**Forum topic**
https://forums.online-go.com/t/cant-change-profile-describtion-anymore-after-server-problems/26971?u=flovo

**Comment by MartinB74** [comment]
Same issue applies to the "hide real name" check box.
When removed and saved, the checkmark is back again after reloading the page.
