### ISSUE TITLE
Profile page display issues

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#1125]
**Describe the bug**
Current games no longer display correctly in list mode

**To Reproduce**
1. Go to a profile page in list mode
2. Scroll down to Active Games
3. See that Games underlap with Activity box

**Expected behavior**
no hidden elements

**Screenshots**

Desktop:
![image](https://user-images.githubusercontent.com/28991649/80434668-bfacba80-893d-11ea-9e32-8dcf6fa99a3d.png)
![image](https://user-images.githubusercontent.com/28991649/80434679-c804f580-893d-11ea-81c6-8c37ac1e75ae.png)

Landscape Smartphone:
![e10c0c16-7422-4732-86f7-f801f72febf0](https://user-images.githubusercontent.com/28991649/80435057-d4d61900-893e-11ea-8caa-ab121f4b4499.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0.0
 - Browser Brave
 - Version 1.5.131, Chromium: 80.0.3987.162

**Comment by Spoekenkieker** [comment]
Same (or similar) with Google Chrome on macOS 10.14 (see https://forums.online-go.com/t/activity-pane-overlapping-active-games-on-profile/27609)
