### ISSUE TITLE
Make puzzle link an actual `<Link>`

### ISSUE THREAD

**Issue by runarberg** [online-go/online-go.com#1126]
**Describe the bug**
Currently the puzzles in the puzzle-list table are programmatically linked to inside a `click` event listener—as opposed to with an `<a href="/puzzle/id">` tag. This produces a number of annoyances which includes a lack of keyboard navigability, a lack of context-menu for the link (right mouse click), a pop-up blocked center mouse click, etc.

**To Reproduce**
1. Go to '/puzzles'
2. Scroll down to 'puzzle table'
   - Notice you cannot <kbd>Tab</kbd> to a desired puzzle.
3. Hover over any row
   - Notice it is *not* an actual link.

**Expected behavior**
* I should be able to right click the link (say to bookmark, or copy URL).
* I should be able to middle click the link to open in new tab without my pop-up blocker stopping it.
* I should be able to navigate to the puzzle using the <kbd>Tab</kbd> key on my keyboard.

**Screenshots**
![mynd](https://user-images.githubusercontent.com/3984600/80542277-930a9a00-8961-11ea-90e5-dd875806ece2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser Firefox 75.0
 - Version 75.0 (64 bit)

**Additional context**

Note that the tournament table doesn’t have the same row click handler, and favors traditional anchor links. Marking inconsistency between views.

Note that the rating column is not interactive but is visually identical to an interactive rating in an open puzzle. Trying to rate the puzzle collection will simply open the collection—which is a little confusing—because of the row click handler.

Some Users might find it preferable to be able to click anywhere on the row to open the puzzle. So there might be a valid reason not to implement this (or add the link without removing the row click handler).

Also note that it is a bit pedantic to complain about the lack of keyboard navigability—especially since the puzzle it self cannot be solved using the keyboard (as far as I know at least).

**Comment by cassidoo** [comment]
I think this is a great idea and would like to take a crack at it!
