### ISSUE TITLE
Fully implement ranks down to 35k (With no change to Glicko2)

### ISSUE THREAD

**Issue by koshogs** [online-go/online-go.com#1127]
**Is your feature request related to a problem? Please describe.**
OGS functionality is limited for users below 25k.

**Describe the solution you'd like**
Use existing Glicko2 info to implement ranks down to 35k.

**Describe alternatives you've considered**
Maybe just 30k but that might involve coming back to the issue all over again. 35k should cover it based on rank distribution.

**Additional context**
Forums discussion here: https://forums.online-go.com/t/recognising-and-fully-implementing-ranks-beyond-25-kyu/27079.

**Comment by BHydden** [comment]
https://github.com/online-go/online-go.com/blob/ad7b3ac16109c3b0f12e299f99fc55de11ff5029/src/lib/rank_utils.ts#L45

I think you just change this value from 5 to -5 to reduce the min rank from 25k down to 35k (or 0 for 30k) and AFAICS it doesn't break anything mathematically...? I don't currently have an up to date testing environment set up to test this and send in a PR though...

**Comment by BHydden** [comment]
[passing along comments from anoek](https://forums.online-go.com/t/recognising-and-fully-implementing-ranks-beyond-25-kyu/27079/99?u=bhydden) :)
