### ISSUE TITLE
Timeouts against bots don't change ratings

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#1129]
**Describe the bug**
When a player times out against a bot, the game doesn't count for their rating. This enables users to Heliumballon by timing out bot games instead of losing them.

**Expected behavior**
If the bot times out, don't count for rating (otherwise the user can setup games too fast for the bot to balloon).
If the player times out, count the ge for rating, otherwise it's too easy to balloon.

**Additional context**
This user used the fact, that timeouts against bots don't count to increase his rating:
https://online-go.com/player/696679/
https://online-go.com/termination-api/player/696679/rating-history

**Comment by Dorus** [comment]
I found another player with this behavior:

https://online-go.com/player/738203/

Many losses to a 7k bot by a 2k and not losing rank. (see 04-30 games).

**Comment by Dorus** [comment]
https://online-go.com/player/762731/
And another
