### ISSUE TITLE
Fix score display legibility

### ISSUE THREAD

**Issue by popz73** [online-go/online-go.com#1138]
Hi guys,
the score display of OGS is by far the hardest to read on all servers/apps.

This is mainly due to OGS's unique design decision of painting squares over *every single stone on the board*, which gives a messy display/information overload, territories are hard to grasp at a glance. 
Using the same SGF on different apps to illustrate: 

OGS:
![image](https://user-images.githubusercontent.com/12851952/81860380-f7834700-9566-11ea-97ad-c7dd4fc24e01.png)

IGS:
![image](https://user-images.githubusercontent.com/12851952/81860439-08cc5380-9567-11ea-9c53-66d09358c3b7.png)

Fox:
![image](https://user-images.githubusercontent.com/12851952/81860836-990a9880-9567-11ea-9c59-c9d2e0483faa.png)

KGS:
![image](https://user-images.githubusercontent.com/12851952/81860934-c22b2900-9567-11ea-9023-cc496c8d640d.png)

No other server is drawing over non-captured stones, which gives them a cleaner display. I personally find IGS's implementation to be very legible

If for philosophical reasons you prefer to continue drawing over all stones, then the display could be inspired in Sabaki's approach, which is able to do it while giving a much easier at-a-glance perception of territories:
![image](https://user-images.githubusercontent.com/12851952/81861476-965c7300-9568-11ea-9066-81d39f0cf697.png)

**Comment by koshogs** [comment]
Part of what you are seeing in your first pic is due to Chinese counting. Compare with: 

![OGSJap](https://user-images.githubusercontent.com/44488770/81893840-d582d680-95f1-11ea-824f-bbcd989e0cdb.png)

which is one of your own games from OGS using Japanese Rules.

**Comment by popz73** [comment]
good to know the issue is limited to Chinese scoring - no reason the display should be different, though - we don't need the square to remind us they're non-captured stones

**Comment by BHydden** [comment]
> we don't need the square to remind us they're non-captured stones

The square isn't indicating that they aren't captured stones, the square is indicating that in Chinese scoring they count towards your score... it is a visual distinguisher between territory and area scoring.

**Comment by popz73** [comment]
... I know what Chinese scoring is, the stones being alive is the
definition needed for them to being counted as points.
No one else shows them that way for a reason - the examples I gave above
are all with Chinese counting as well! And if you really want to reinforce
them as points, there are better ways to do it, e.g. Sabaki

**Comment by philipkd** [comment]
The Sabaki way looks beautiful, and it would make it easier for newcomers to learn Go.

**Comment by BHydden** [comment]
I must admit, I think Sabaki looks best out of all of them... I wouldn't be at all opposed if someone made a PR to swap our current squares into a Sabaki style shading. I'm certainly not convinced that our current implementation is worse than KGS, IGS, or Fox...
