### ISSUE TITLE
Disappeared even if 'Plan conditional moves' is registered.

### ISSUE THREAD

**Issue by teya333** [online-go/online-go.com#1139]
**Describe the bug**
Disappeared even if 'Plan conditional moves' is registered.

**To Reproduce**
1. Go to the game page.
2. Select 'Plan conditional move' at right menu.
3. Input.
4. Click on 'Accept Conditional moves'.
5. Go to another page.
6. Go to the game page again.
7. Select 'Plan conditional move' at right menu.
8. Disappeared.

**Expected behavior**
Be able to use it as before.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome

**Comment by teya333** [comment]
The same was true for Firefox. Both versions are the latest.

**Comment by AresUII** [comment]
Bump.

Vivaldi. Blocking googletagmanager.com. Same issue.
