### ISSUE TITLE
Profile text does not wrap

### ISSUE THREAD

**Issue by mark5000** [online-go/online-go.com#114]
### Summary

The text on the profile page no longer wraps.

### Environment

 * Operating system: Windows 10
 * Browser: All
 * Browser Version: All

### Steps To Reproduce:

1. Go to https://online-go.com/user/view/64817
2. See that the profile text does not wrap.

### Additional Information:

The text wrapped properly on an iPhone 5s with Safari browser.

Here's a screenshot of the Windows 10 desktop where the issue appears:

![profilewrap](https://cloud.githubusercontent.com/assets/13010650/23718589/e4bb0e82-03ec-11e7-8625-953b3690102e.png)

I also notice that the links that formerly displayed correctly are now displayed incorrectly. If the formatting of links has changed I'd like to know about that, and probably others would as well.

**Comment by anoek** [comment]
Actually it looks like https://github.com/online-go/online-go.com/commit/c053af35079dde473bbf6b58b14bbf2c8b7b2399 fixed this issue along the way
