### ISSUE TITLE
Endless Loading

### ISSUE THREAD

**Issue by spicyspyigo** [online-go/online-go.com#1144]
The game I linked is not read on page  https://online-go.com/game/24036995

**To Reproduce**
1. Go to 'https://online-go.com/game/24036995'
2. See error

**Expected behavior**
I don't remenber what I did.

**Screenshots**
![image](https://user-images.githubusercontent.com/65822063/82734766-02ed2400-9d58-11ea-9c9a-c6b3afa7fb66.png)

**Desktop (please complete the following information):**
 - OS: [Windows8.1]
 - Browser [chrome]

**Comment by benjaminpjones** [comment]
Related issue: https://github.com/online-go/online-go.com/issues/50
