### ISSUE TITLE
Scoring fails to remove groups, no time to react.

### ISSUE THREAD

**Issue by fsparv** [online-go/online-go.com#1146]
**Describe the bug**
Scoring incorrect for game vs AI, and not enough time to consider/object to the computer's group removal choices. 
**To Reproduce**
1. Play several dozen games against the likes of Spectral (4k)
2. Eventually a position with a large dead group fails to remove the dead group (e.g.. https://online-go.com/game/24196795) 
3. Within some small single digit number of seconds, the game is finalized and cannot be continued/disputed/corrected.

**Expected behavior**
A) Correct scoring, and removal of dead groups
B) Sufficient time to detect and object to incorrectly scored games

**Screenshots**
![image](https://user-images.githubusercontent.com/1226061/82764819-ce24af80-9ddf-11ea-8223-451cbcc53a0a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by BHydden** [comment]
> A) Correct scoring, and removal of dead groups

This is expected behaviour, but we are aware that the score estimator is FAR from perfect. A rewrite of the score estimator is planned, but it is a big project and won't be achieved any time soon.

> B) Sufficient time to detect and object to incorrectly scored games

This used to be the case, but players used it to abuse bots into tricking them into accepting a wrong score. The decision was made that this path was the lesser of two imperfect systems.

**Comment by yewang** [comment]
Now that OGS already has strong AI review available with engines like KataGo, one potential way to mitigate this issue is to use KataGo to estimate the life/death status of the stones during scoring.

Related discussion on the forums: https://forums.online-go.com/t/use-katago-for-scoring/29069

**Comment by wilkerlucio** [comment]
I just got bitten by this one, the score is greatly wrong in this case, it ignored all my top left area and many others.

<img width="1215" alt="Screen Shot 2021-07-30 at 01 17 10" src="https://user-images.githubusercontent.com/25736/127599444-23189f09-be8e-4a25-92f8-e6f6e3edeac5.png">

**Comment by wilkerlucio** [comment]
After reading some of the comments, I have a suggestion I didn't see anywhere else yet.

For the games with bots, what if the player could choose to accept the score or continue playing? Different from P2P where you can change the marked stones, against bots it could ask the option to accept or continue playing. This way in case the estimation is grossly wrong (like in my example above) the user could choose to keep playing to make it easier for the AI to figure the score correctly.

**Comment by benjaminpjones** [comment]
Is this still an issue? I thought bot games *were* automatically scored by Kata..

**Comment by benjaminpjones** [comment]
Closing. I believe the strong engine KataGo is used for this now.
