### ISSUE TITLE
Conditional moves work only for the first answer.

### ISSUE THREAD

**Issue by Adam314159** [online-go/online-go.com#1148]
**Describe the bug**
Even though longer sequences can be put into the conditional move planner, upon confirmation, only the first answer is automatically played out, NOT the rest of the sequence.

**To Reproduce**
1. Create a game
2. Click on "conditional moves" and set up a longer sequence
3. Convice the opponent to play the moves you have predicted
4. See that only the first answer from the planned sequence will be automatically played

**Expected behavior**
It should auto answer as long as the predicted sequence is being followed

**Desktop (please complete the following information):**
irrelevant

**Additional context**
Discussed here: https://forums.online-go.com/t/conditional-move-doesnt-seem-to-work-or-buggy/27896

**Comment by BHydden** [comment]
Possibly also related to #1139
