### ISSUE TITLE
Every time the first stone is placed the site asks if it can access vibration.

### ISSUE THREAD

**Issue by simonseyock** [online-go/online-go.com#1155]
**Describe the bug**
Every time I open online-go.com in firefox on my android phone after I placed the first stone (clicked submit), it asks me if I want to allow it to access vibration. It remembers the decision for as long as the site is kept open.

As firefox on android does not keep the page in memory but loads it every time the user switch to the browser this happens quite often.

**Expected behavior**
It should ask once on a device and then remember that decision.
**Smartphone (please complete the following information):**
 - Device: Fairphone 2
 - OS: Android 7.1.2
 - Browser: Firefox
 - Version: 68.8.1

**Comment by stephancurran** [comment]
This is a Firefox issue rather than OGS. You'll see the same behaviour on [this demo](https://googlechrome.github.io/samples/vibration/).
