### ISSUE TITLE
"Byo-yomi" announcement every time when opening a corr game in tab

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#1165]
**Describe the bug**
Every time i open correspondence game that is in byo-yomi into new tab from profile or overview page, i can hear claire's voice saying "byo-yomi" 

**To Reproduce**
1. Play correspondence with byo-yomi timing
2. be on byo-yomi
3. wait till its your turn
4. open game in new tab

**Expected behavior**
I dont want to hear "byo-yomi" every time i open some specific games, i know those games are on byo-yomi, i dont need to hear that every single time i open them.

**Comment by maurelio1234** [comment]
I cannot reproduce this bug anymore
