### ISSUE TITLE
Top navigation bar's My Move number stuck at 1 despite not having a move to make in any game

### ISSUE THREAD

**Issue by TheIronMarx** [online-go/online-go.com#1172]
**Describe the bug**
On the top navigation bar, in the white circle next to my notifications dropdown, I'm notified I have 1 game to make a move in. Clicking on the circle takes me to my most recent game wherein I have made a move. In this game, it is not my turn.

**To Reproduce**
I haven't seen this happen before, nor do I have exact steps to reproduce. Going through my games as normal, using the mentioned My Move indicator to bounce to my next game (because I have the setting which automatically will bounce to the next game I have to make a move in after I make a move turned off), I played a move in the last game in my list. After doing so, the counter was still stuck at 1 regardless of where I navigated to after. Clicking on that number takes me to the game where I played my last move.

**Expected behavior**
I expected the counter to drop to 0 or vanish or whatever it does when I don't have a move to make in any of my games.

**Desktop**
 - OS: OSX 10.14.6
 - Browser: Chrome
 - Version: 83.0.4103.97 (Official Build) (64-bit)

**Additional context**
It may be relevant that the game in which I made my last move is paused.

**Comment by Cdingo** [comment]
I ran into this today, though under different circumstances.

This would be difficult to reproduce, but the following events occurred:

1. Clicked accept for a game in Customs Games list
2. Someone else got there slightly before me, so the game was now between 2 other players, but I was redirected to it
3. One of the players timed out before making their first move, and the game was annulled

I now have a persistent notification that it's my turn to play in a game that is over and I'm not actually a player in.

Game ID is 33511504

Browser: Firefox 87.0
