### ISSUE TITLE
Uploading a non-square SGF to SGF library causes an error 500 et al.

### ISSUE THREAD

**Issue by sanderland** [online-go/online-go.com#1175]
**Describe the bug**
The SGF library part of the website seems to use different and incompatible code with the other parts of the website, particularly it gives an error 500 when using a non-square board size (SZ[x:y]).

**To Reproduce**
make an sgf file with

`(;GM[1]FF[4]RU[japanese]SZ[52:52];B[cd];W[Xd];B[VX];W[dW];B[XW];W[cP];B[ed];W[cU])`
upload to SGF library, error 500
SZ[52] here does not crash, but the results are .... interesting.

Also try downloading 
https://online-go.com/demo/view/497483
and uploading to the library. This is particularly concerning since it is an SGF generated by OGS itself at a board size which is supported.

for interesting results

More interesting results occur with SZ[large number], e.g. https://online-go.com/game/24746137

Suggested:
* Fix the parsing of non square boards of size <= 25
* Disallow board sizes > 25

**Comment by benjaminpjones** [comment]
This bug still exists.

**Comment by BHydden** [comment]
Almost all the stale bugs still exist 🤣

**Comment by benjaminpjones** [comment]
Haha I guess I should say, "the bug still exists, and I think it's worth fixing"
