### ISSUE TITLE
Searching for group by name should be "contains" instead of "start with"

### ISSUE THREAD

**Issue by AVAVT** [online-go/online-go.com#1177]
I have tried to search for the group "One Arbitrary Group" a lot of time but faileds, because I remember the name as "An Arbitrary Group".

Similar situation with famous global initiative "Teaching Ladder". Every go server have a "[Something] Teaching Ladder", but you can't search for "Teaching" here. You must search for "OGS" because the group name "OGS Teaching Ladder" start with OGS.

My point is, many times the signature word of a group's name is not the first letters. Changing from "start with" to "contain" will make the search more bloated, but at least the list will include groups that user was hoping to find.

**Comment by kobakitty** [comment]
Its not only groups, but users and and tournaments too. For example, if you want to find my profile ( https://online-go.com/player/85719/ ), you gotta search for "💖 " since searching for "koba" does not find me.
