### ISSUE TITLE
Add indication to challenge cards as to whether you sent the challenge or received it

### ISSUE THREAD

**Issue by cliffordwolf** [online-go/online-go.com#118]
### Summary

I have received a challange. There only seems to be an UI element to reject the challenge. How do I accept it? (Sorry if I'm just missing something obvious)

![image](https://cloud.githubusercontent.com/assets/619764/23745536/dffa9706-04b8-11e7-9f63-a64186672500.png)

### Environment

* Linux (Ubuntu 16.04, 64 Bit)
* Chromium 56.0.2924.76

**Comment by cliffordwolf** [comment]
Forget it. I think that is a challenge I myself sent a while ago. The new thing isn't that I've been challenged, the new thing is that challenges I sent are now displayed on the home screen.

**Comment by BarneyStratford** [comment]
I think closing this might be a bit premature, as it raises a valid UI issue. It’s very common for people to respond to a UI issue as if they’d made a mistake themselves, rather than there being a mistake in the design. Opinions?

Barney.

**Comment by cliffordwolf** [comment]
Hmm.. Good point. The code in `ChallengesList.tsx` already checks if `challenge.challenger.id === user.id`, but this only effects if the accept button is displayed and which user should be displayed as opponent. Maybe `<Player user={opponent}/>` should be preceded by something like "Sent to" or "Received from" depending on if we are the challenged user or the challenger.

Now that I have had a look at the code it is completely clear to me how to interpret the challenge cards. But I agree with Barney: It should not be necessary to have seen the code to understand how to use the UI. So I'm now reopening the issue.

**Comment by anoek** [comment]
Might as well add a date and time (or maybe relative time) for the challenge too

**Comment by mlopezviedma** [comment]
Does the challenge object have a timestamp field? It doesn't as far as I can see.

**Comment by anoek** [comment]
Hmm, that's an oversight, I'll add that in

**Comment by mlopezviedma** [comment]
Let me know, I have this and #142 ready on one same commit.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
