### ISSUE TITLE
tournament starting announcement stuck

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#1192]
**Describe the bug**
The announcement "Tournament "Live 9x9 Double Elimination Tournament 2020-07-07 02:30" will start in less than 5 minutes. Click here to join the lobby" is still showing hours after the tournament has ended.  

**To Reproduce**
- Join the next 9x9 double elimination tournament. 

**Expected behavior**
A time-limited announcement such as "tournament starting in 5 mins" should no longer be visible once the information is no longer correct.  

**Screenshots**
![Screenshot_20200707-004530](https://user-images.githubusercontent.com/27974470/86713210-d6c9f180-bfeb-11ea-845a-9677d8fc33ee.png)

**Smartphone (please complete the following information):**
 - Device: moto g(6) play
 - OS: Android 9
 - Chrome

![Screenshot_20200707-005732](https://user-images.githubusercontent.com/27974470/86714256-eb5ab980-bfec-11ea-80ca-132c758e4885.png)

**Comment by anoek** [comment]
This did eventually disappear I hope?

**Comment by alexmitrani** [comment]
Yes, the next day it had gone.
