### ISSUE TITLE
Tutorial: "Great job!" and "Puzzle failed!" strings cannot be translated

### ISSUE THREAD

**Issue by marant** [online-go/online-go.com#1197]
**Describe the bug**
`"Great job!"` and `"Puzzle failed!"` strings in the tutorial are hard coded values and thus cannot be translated.

**To Reproduce**
1. Change language to anything else than english
1. Go to 'Tutorial'
2. Submit an answer
4. See "Puzzle Failed!" or "Great job" text in english

**Expected behavior**
These messages should be translated to the target language

**Additional context**
I tried translating these parts of the tutorial and couldn't find them on `translate.online-go.com`. Checked the code and the strings are hard coded (`src/views/LearningHub/LearningPage.tsx`). The fix is really easy to do (I have it locally already) but I don't know how to add new strings to the translation.

**Comment by GreenAsJade** [comment]
You just put the harcoded string into the translation operator.

For example:

Hardcoded:

`      console.log("You can't translate me);`

Translatable:

`    console.log(_("You can translate me"));`

You submit a PR with this change, it gets accepted by anoek, then a new translation file appears with that string in it.

As I understand it.
