### ISSUE TITLE
"Your Move" emails are no longer being sent out

### ISSUE THREAD

**Issue by OneWeirdDude** [online-go/online-go.com#12]
### Summary

Hi, I no longer get any emails saying when it's my turn. I have all the boxes checked.

### Environment

 * Operating system: Windows 10
 * Browser: Google Chrome 
 * Browser Version: 56.0.2924.87 (64-bit)

### Steps To Reproduce:

I make moves and don't get emails when it's my turn until time starts running out.

**Comment by cliffordwolf** [comment]
Same here. (I'm using chromium on 64 bit ubuntu, but obviously this is some kind of server issue.)

In case this is a bug that somehow effects only some users: I'm [cliffordvienna](https://online-go.com/user/view/337285) on OGS.

**Comment by o0dano0o** [comment]
Same issue here.

**Comment by Sniveler** [comment]
Just copying cliffordvienna's post format if it can help.
Same here, Mozilla on64bit Ubuntu.
Sniveler on OGS.

**Comment by anoek** [comment]
Implemented on the backend, will be live in today's patch

**Comment by o0dano0o** [comment]
THANK YOU!

**Comment by nickeubank** [comment]
@anoek Just found this, but still having this issue. Was this resolved for most people?

**Comment by anoek** [comment]
It's generally working, any remaining issues are probably related to spam filtering and that sort of stuff, as far as I know

**Comment by nickeubank** [comment]
OK -- I'm pretty tech savvy, and I'm pretty darn sure it's not a spam issue (I've checked my filters repeatedly. Anything else I can try? Sorry, I know this kind of bug is a pain, but not sure what else to do... my account is JSeaTurtle if that helps.

**Comment by mlopezviedma** [comment]
Are you sure you are not logged in on another device?

**Comment by nickeubank** [comment]
@mlopezviedma Hmmm, interesting. I have logged in from ios devices. It's certainly not up and running anywhere, but I suppose maybe cookie status got confused? There a way to log off all devices?
