### ISSUE TITLE
Make site documentation translatable

### ISSUE THREAD

**Issue by marant** [online-go/online-go.com#1205]
**Is your feature request related to a problem? Please describe.**
Site documentation is not currently translatable. The documentation is currently available on Github and is thus not translatable through https://translate.online-go.com. Managing the translations on Github would probably be a lot manual work.

**Describe the solution you'd like**
An ideal solution would be either

 1) Make the site documentation part of the actual site. Translation would be done using http://translate.online-go.com
 2) Move the documentation to a service that supports translations (and preferably be able to track the progress of each language)

**Additional context**
Currently there is no way for user who do not understand English to learn about the features of OGS easily.

I looked into a couple of self hosted solution but nothing had an excellent support for translations. Here are the FOSS & self hosted options I looked at:

 * https://wiki.js.org/
 * https://www.bookstackapp.com/

I also looked at https://www.docsie.io/ which isn't FOSS but the pricing is only available on request.

**Comment by benjaminpjones** [comment]
If I could offer a third "solution": create a Documentation&FAQ page on the existing GitHub wiki in the language of your choice. Then we can link to it from the OGS menu. Ideally there would be a consistent naming scheme for pages that have English analogs. Something like "...wiki/es/..." for Spanish changes, for example.

I understand this is less ideal than the solutions you proposed, but it has the benefit that it can be implemented now with minimal infrastructure change.

Having properly fleshed out translations of the documentation would also provide some guidance on how to proceed with infrastructure-heavy changes.
