### ISSUE TITLE
New chat "Topic" feature allows anyone to change it.

### ISSUE THREAD

**Issue by juanchodepisa** [online-go/online-go.com#1217]
In the new chat layout, there's a topic for each chat. I was assuming that only group admins should be able to change it, however, that is not so.

**To Reproduce**
1. Go to any group chat you belong to.
2. Notice that the edit option (the little pen button) is available regardless of your membership level.
3. Change the Topic and Save.
4. Changes are actually saved.

**Expected behavior**
I expected an error message or for the topic not to change. In fact, I would expect the 'edit' option not to be present at all unless you were a group admin (or maybe a moderator, developer, etc.).

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/14313965/88928599-40799c00-d236-11ea-9195-de0cf49f6b30.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome
 - Version 84.0.4147.89 (Official Build) (64-bit)

**Additional context**

This does not work on global chats like "English" or "Off Topic".
I am quite certain it isn't just me seeing my own changes, because I have witnessed changes made by other players.

**Comment by anoek** [comment]
That's the intent, if it becomes a problem we can limit it more I suppose.
