### ISSUE TITLE
Removing dead stones in a game freezes PS4 browser with 'Unresponsive Script'

### ISSUE THREAD

**Issue by rmda** [online-go/online-go.com#1219]
Hi there! Long time fan of your site, it's wonderful and I love it. Great work.

When I play games in the PS4 browser, it is fine up until the point where both players pass and we remove dead stones. At this point the browser will freeze (usually with a blank page) before the browser reports an Unresponsive Script that requires closing the page.

Current workaround is to wait for the freeze to display a 'Unresponsive Script' message, close the window/tab, open a new tab and navigate back to the site/game. Typically at that point you can assume your disconnection has confirmed the dead stones, but I can't confirm this part easily on the browser at least.

From only a bit of research, the PS4 OS is based on Orbis OS/FreeBSD. The browser is reportedly WebKit core based, but I don't have any other details aside from that: 
https://en.wikipedia.org/wiki/PlayStation_4_system_software

Edit: Apparently it is 'NetFront NX', according to http://blog.greggant.com/posts/2016/04/07/exploring-and-developing-for-the-ps4-browser.html

If anyone has some possible solutions, I would be interested to help debug and provide more information if that is possible. I don't have a PS4 dev kit but I can think of maybe using debug scripts on the page to reproduce/get more information what script is possibly errant at the time of the issue.  Or how to reproduce this in a desktop environment easily.

Thank you!

**Comment by anoek** [comment]
You might try disabling the AI review, which can be done on the right side of the page. I've heard reports it can be rather cpu intensive on some systems, it's on the todo list to try and optimize, but for now, if you disable that I bet you'll be fine.

**Comment by rmda** [comment]
Disabling the AI review prevents a freeze with a blank screen that forces the browser to intervene with the unresponsive script message.

However it will freeze, just less severely-- the current freeze still has a visible UI but there is no capability to interact with dead stones or pass for the 2nd time. I think it will actually complete the dead stone timer and then show the Completed game screen.  That's somewhat better at least! 

FWIW, using a board editor in the browser works fine. I would guess that there is some kind of issue with dead stone removal specifically. I tested this on a 19x19 (larger freeze period) and 9x9 (seemed like a smaller freeze period but not sure.) against an AI bot with AI review disabled.

**Comment by anoek** [comment]
Ooh, I bet it's the score estimator that triggers to do a dead stone removal pass. That should be self resolving in a few months when we roll out the replacement system for that.

**Comment by rmda** [comment]
That would be correct, it seems just clicking Estimate Score can reproduce the same behavior. Thanks!
