### ISSUE TITLE
Can't drop out from ladder (Error 520)

### ISSUE THREAD

**Issue by soerface** [online-go/online-go.com#1220]
**Describe the bug**
It is not possible to remove oneself from the 19x19 ladder (and possible others, I've only tested 19x19)

**To Reproduce**
1. Be in the 19x19 ladder
2. Go to it (https://online-go.com/ladder/313)
3. Click "Drop out from ladder" on the top of the page
4. Confirm the dialog
5. Wait a couple of seconds - a red X appears. You can see more information in the network inspector of your browser.

**Expected behavior**
I will be removed from the ladder.

**Screenshots**
![image](https://user-images.githubusercontent.com/967243/89785593-f1c3e000-db1a-11ea-82a2-9e5e7804a4eb.png)

**Desktop (please complete the following information):**
 - Chromium Version 84.0.4147.105 (Official Build) snap (64-bit)

**Comment by BHydden** [comment]
I'm fairly sure this was fixed already.
