### ISSUE TITLE
Engine evaluation gives W+NaN

### ISSUE THREAD

**Issue by Modriem** [online-go/online-go.com#1225]
In the game https://online-go.com/game/view/26410562 on move 42 the engine evaluates the position as W+NaN. I don't know how this happened or what caused it but before this bug develops into something severe, I figured I should report it.

![FireShot Capture 010 - Game Finished - online-go com](https://user-images.githubusercontent.com/69406848/91085958-7f8ce880-e64e-11ea-8b99-7118d881ceb9.png)

**Comment by mmartin** [comment]
This is due to AI score being 0 and this line:
https://github.com/online-go/online-go.com/blob/a9bf9f122862ca7d5dfdd7fee6e96fa5f3689960/src/views/Game/AIReview.tsx#L360
