### ISSUE TITLE
Game total for month misses out final day

### ISSUE THREAD

**Issue by thomasathorne** [online-go/online-go.com#1230]
In the profile page, when you mouseover a month in the rank graph it shows the total counts of ranked games for that month in a pie-chart on the right. However, it appears not to include the final day of the month.

I first observed this on my own profile (https://online-go.com/user/view/82042) for the month of August 2020. However, I was able to find another example which requires a bit less counting to check:
1. Go to https://online-go.com/player/672895/
2. Mouseover the month of June 2020; total ranked games will show 2 (both losses vs. weaker)
3. If you look at this month in the user's game history (or mouseover individual days in the month) you will see 3 games for June 2020, the one game (win vs. weaker) on June 30th is missing from the total.

 - OS: Ubuntu
 - Browser: Chrome (version 84.0.4147.105)

**Comment by thomasathorne** [comment]
This issue is still showing up---any progress on fixing this?

**Comment by benjaminpjones** [comment]
Not that I'm aware of, but I can remove the stale label. Thanks for checking on that!
