### ISSUE TITLE
Audio countdowns don't run in submit-move mode

### ISSUE THREAD

**Issue by edhalter** [online-go/online-go.com#1231]
**Describe the bug**
In "Submit-move button" mode, a user in a live game submits a move and ends his turn by 1) clicking on the board, then 2) clicking a separate Submit button. Currently, audio countdowns don't play after (1), even though it's still the user's turn and his clock is running. (They do play if the user rescinds (1) by taking the stone off the board.) Audio countdowns should work after (1), and not stop until the user's turn ends at (2).

**To Reproduce**
1. In Settings -> Game Preferences, set "Live game submit mode" to "Submit-move button"
2. In Settings -> Sound Preferences, set "Count every second starting at" to a non-"None" value (e.g. "10 seconds")
3. Play a game. On your turn, place a stone on the board, but don't click the Submit button.

**Expected behavior**
Audio countdown starts when your clock has e.g. 10 seconds left

**Actual behavior**
Audio countdown never starts

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 68.12.0esr

**Smartphone (please complete the following information):**
 - Device: iPad (2009)
 - OS: iPadOS 13.7
 - Browser: Firefox (28.1) and Safari

**Additional context**
I found this behavior extremely surprising. I lost 1 game by timeout when I had placed a stone on the board but hadn't yet submitted it, and my clock ran out w/o the audio countdown ever starting. I thought it was a Safari bug, until I tried Firefox and finally realized the audio was stopping when a stone was placed.

I can't think of a reason for the countdown to stop before you've submitted your move, while it's still your turn and your clock is still running. However, if someone does like that behavior, there should be a setting for it, defaulted to "off".

**Comment by 8fledermaus8** [comment]
I encountered the bug too - it's not a minor issue imo, it lost me several games. There are several threads on the forum which adressed the same problem.
