### ISSUE TITLE
Scoring bug?

### ISSUE THREAD

**Issue by dima-asana** [online-go/online-go.com#1234]
**Describe the bug**
All groups/area look marked correctly here (except K7 is not a point, but that's minor).  However, the score calculation seems incorrect.
https://online-go.com/game/27384513

In particular, the "prisoners" calculation for black seems to be incorrect.  There were 11 captures and there are 2 white stones marked dead in the final game, but the "prisoners" count seems to be 23 rather than 13.  Maybe the group on the bottom left (which is 10 stones) is incorrectly calculated as dead but not shown this way in the UI?

**Comment by anoek** [comment]
The F3 group is marked as dead (indicated by the translucent stones), when you're in the scoring phase you can click the groups to toggle them as captured or not, that group should not have been marked dead. Sometimes the auto-scoring algorithm is pretty bad... always good to double check :) Although I'm working on significantly improving that system in the next little bit here.
