### ISSUE TITLE
Group Website Link not working

### ISSUE THREAD

**Issue by Fraze** [online-go/online-go.com#1235]
**Describe the bug**
The website link for groups does not send players to the intended destination. Instead, the link sends players back to the group itself

**To Reproduce**
1. Go to any group
2. Click the website url below the group name
3. The group page will load itself instead of the intended website

Example
![image](https://user-images.githubusercontent.com/19158908/95637868-e3ce0500-0a60-11eb-9f4f-2f83fa3a50e6.png)
Clicking the website hyperlink does not take you to the website.

**Comment by mmartin** [comment]
A bit too strict regex. :)
https://github.com/online-go/online-go.com/blob/189ac68bf2900de55ba2421825c5e123b696b9f2/src/views/Group/Group.tsx#L500

As a workaround, add `https://` at the beginning and it should work.

**Comment by BHydden** [comment]
my understanding of regex is super limited...

did this code make the `https` optional, but the two `/`'s after it required?

**Comment by mmartin** [comment]
It requires `http`, makes `s` optional, then requires `://` and the rest.

**Comment by BHydden** [comment]
aaah of course :) that makes more sense, thanks <3

**Comment by anoek** [comment]
Fixed in 3c15dc8d75c68677177131fc03e6c986cf4ba186
