### ISSUE TITLE
 Information during scribing a game is not updated

### ISSUE THREAD

**Issue by Mikaa** [online-go/online-go.com#1237]
It would be nice to be able to edit game information during broadcast of the go game. Now its only possible at start of the game.

**Solution**
When edit enable one could set information about players rank, players name, players colour, tournament name, tournament place, result, round number, even during on-going game.

**Additional context**
It would increase number of live games broadcasted at ogs.

**Comment by anoek** [comment]
To edit the game information click the 'i' info symbol on the right side of the page, you'll find the fields there to edit the game name, player names/ranks

**Comment by Mikaa** [comment]
If I edit players informations and press save, new information is not updated to the demo board.

**Comment by anoek** [comment]
This has been fixed on the backend and is visible on the beta server, will be deployed to production next update
