### ISSUE TITLE
Have a link to an explanation about ratings

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1241]
This thread made the suggestion, in the face of ongoing confusion about how ranks move:

https://forums.online-go.com/t/ratings-moving-opposite/30683/21?u=eugene

**Comment by BHydden** [comment]
obviously to be implemented *after* how the rankings are calculated actually reaches a state that anoek is happy with, since he's planning another full history recalculation later this year IIRC

**Comment by GreenAsJade** [comment]
I think it should be implemented regardless of what changes are coming.  Otherwise we'd never document anything, because it's all subject to change...

**Comment by BHydden** [comment]
I'll admit, when I said that I didn't realise how well set up the wiki already was in this area :P

**Comment by benjaminpjones** [comment]
@GreenAsJade is this still relevant after the January changes?

**Comment by GreenAsJade** [comment]
I reckon not.
