### ISSUE TITLE
Annulled games not clearly marked in the UI

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1244]
**Describe the bug**
If you go to an annulled game, you have to dig a little to see that it is annulled.  Often, annulled games have some funny business, so it can be disheartening to see an erroneous winner.

**To Reproduce**
1. Go to https://online-go.com/game/27029807
2. Observe that you cannot see that the game is annulled without clicking the info button.
3. Also note that on profiles, occasionally the Game Result column is too far to the right to see 'annulled'

**Expected behavior**
A notice that the game was annulled.  Should be at least as visible as the game result, given that the result is not valid.

**Screenshots**
https://online-go.com/game/27029807
<img width="794" alt="Screen Shot 2020-10-24 at 11 10 22 PM" src="https://user-images.githubusercontent.com/25233703/97098038-eaf33680-164e-11eb-98f0-c1bdf0f96ff9.png">
<img width="1450" alt="Screen Shot 2020-10-24 at 11 05 46 PM" src="https://user-images.githubusercontent.com/25233703/97098039-ef1f5400-164e-11eb-9ee6-388954a459fc.png">

**Comment by BHydden** [comment]
For this game in particular, please know that all games with less than 2 moves are automatically annulled, however, it is a great idea that the game result on the page should say "Annulled" I think that's probably a simple fix that one of us could implement soonish.

**Comment by BHydden** [comment]
If anyone wants to beat me to adding "annulled" option to the finished state display of a game, the code is [here](https://github.com/online-go/online-go.com/blob/5105fcd0d1923b2cd1f02321fb6cc4e1e0fcfe14/src/views/Game/Game.tsx#L2505-L2516).

**Comment by benjaminpjones** [comment]
Wow, BHydden, you are super on it tonight!  I actually have a pull request drafted.  I knew about the "2 moves" thing only because of a [report](https://forums.online-go.com/t/loss-by-disconnection-when-opponent-hasnt-played/30818) I made on the forums.

In the future, is it okay if I ask you for help navigating the codebase? It sounds like you are pretty knowledgable about the structure.

**Comment by benjaminpjones** [comment]
Additionally, if you could advise on translation- I can tell there is some i18n stuff going on, but not sure what I have to do when creating new UI elements.

**Comment by BHydden** [comment]
I'll help where I can :) there are definitely people around here who know way more than me :) 
for translation, you usually want to use `pgettext()` as it allows you to provide context that aids in the translation

usually, just guess at what you think is best and anoek will let you know if he wants it done differently 😄
