### ISSUE TITLE
Dynamic title does not work correctly for ongoing games when in analyze mode

### ISSUE THREAD

**Issue by mmartin** [online-go/online-go.com#1246]
**Describe the bug**
Dynamic title does not work correctly for ongoing games when in analyze mode.

**To Reproduce**
1. Enable “Dynamic title”.
2. Open an ongoing game, see that the window's title is “Black to move”.
3. Open Analyze mode.
4. When Black makes the move it appears on the board and is focused in the analysis' tree.
5. See that the window's title still is “Black to move”.

**Expected behavior**
The window's title should change to “White to move” (or “Your move”, if its my game).
Or maybe analyze mode should always have title “Analyze mode”.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/236237/97109699-5388f480-16dd-11eb-90b8-e31bff0ea660.png)

**Additional context**
This is seems like a problem in `Goban::updatePlayerToMoveTitle()`, because it does not emit `state_text` event on which Dynamic title depends.
https://github.com/online-go/goban/blob/02d56af899766d51394214e62fe02db2fdf5d24d/src/GobanCore.ts#L1763

**Comment by BHydden** [comment]
This is intentional, the current game state is more important than your position in ananlysis

**Comment by mmartin** [comment]
Maybe I was unclear. The current game state actually is “White to move”. In the screenshot you can see than I'm at the very last move in the game (black), but title still says “Black to move”.
