### ISSUE TITLE
Players not being added to group

### ISSUE THREAD

**Issue by Fraze** [online-go/online-go.com#1247]
**Describe the bug**
This group https://online-go.com/group/6971 has the same players as requesting to join. Myself and others have accepted their request however the request is not being granted

**To Reproduce**
1. Be a member of the group
2. Under list of players, click check mark for request
3. Refresh page (or come back later), those same names will still be there

**Expected behavior**
I expect those names to be granted access to the group and to no longer be on the list of requested player names

**Screenshots**
![image](https://user-images.githubusercontent.com/19158908/97125726-34a15700-170b-11eb-914f-c8d70fb9943e.png)

**Desktop (please complete the following information):**
 - OS: Chromium
 - Browser Chrome
 - Version idk

**Comment by BHydden** [comment]
for some reason I was able to accept them, when I'm not even in the group... maybe it's accidentally set to mod only rather than group admin only?

**Comment by Fraze** [comment]
Hmm, maybe. I'm not actually the group admin though. Is this an action that only the admin can make? I thought it was someone anyone can do because it worked for some of my checks.

That being said, it is possible that I checked the box and so did the admin. Therefor it appeared to me that I was accepting people even though I was not.

**Comment by yayayen11** [comment]
If your setting for the group "is request to join group" only the admins can accept even thought the members have a check mark and a X. It doesn't do  anything unless you are a admin. :)
