### ISSUE TITLE
Document the i18n functions

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1248]
Internationalization and localization is important, but there are a lot of moving parts, even for the smallest of fixes.  I think a good start for documentation would be:

- an i18n page on the wiki<sup>1</sup>
- jsdoc comments for _() and pgettext().

<sup>1</sup>if there is a better place for contributor-focused documentation, let me know!

**Comment by benjaminpjones** [comment]
Hmm not sure how to assign myself. I fully intend to do this!

**Comment by BHydden** [comment]
FWIW, the rest of us coders tend to just add the _() or pgettext() and leave the translations to the translators :P you're the first I've seen to actually test it



> not sure how to assign myself. I fully intend to take charge of this!

we don't normally get assignments, but in any case only anoek can do them... mostly he doesn't bother since we have such a small team

**Comment by benjaminpjones** [comment]
>the rest of us coders tend to just add the _() or pgettext() and leave the translations to the translators

I will probably just do that in the future! But for the first time, I wanted to get it right. That's part of the reason documentation on pgettext would be useful 😀

>we don't normally get assignments, but in any case only anoek can do them... mostly he doesn't bother since we have such a small team

Got it. I guess I didn't want to make it sound like I expected someone else to do this (unless they really want to!)

**Comment by BHydden** [comment]
apart from anoek we're all a volunteer team, so nothing to fear there haha, none of us do anything unless we really want to :P it's a passion for all of us who simply want OGS to be the best it can be

**Comment by benjaminpjones** [comment]
https://github.com/online-go/online-go.com/wiki/Internationalization-and-Localization
