### ISSUE TITLE
Rank bar on /overview doesn't work

### ISSUE THREAD

**Issue by mlopezviedma** [online-go/online-go.com#125]
### Summary

[Overview.tsx](https://github.com/online-go/online-go.com/blob/devel/src/views/Overview/Overview.tsx) uses `data.get("config.user")`, but that object doesn't have a `rating` field. As a result, the rank bar always shows 50%.

### Environment

 * Operating system: Any
 * Browser: Any

### Additional Information:

![screenshot-2017-03-09-16h49m00s](https://cloud.githubusercontent.com/assets/10748063/23767527/a218fc14-04e7-11e7-89e2-d391907fe931.jpg)

![screenshot-2017-03-09-16h50m37s](https://cloud.githubusercontent.com/assets/10748063/23767556/b4c12026-04e7-11e7-8c23-ba4c5053bcd3.jpg)

**Comment by anoek** [comment]
Fixed on the server side
