### ISSUE TITLE
Chat's “mailto:” markup parser problem

### ISSUE THREAD

**Issue by mmartin** [online-go/online-go.com#1251]
**Describe the bug**
Example: https://www.google.com/maps/@50.7006874,-3.0915427,13.75z
Currently this is parsed as an e-mail address and turns into an “mailto:” link.

**To Reproduce**
1. Post in chat https://www.google.com/maps/@50.7006874,-3.0915427,13.75z
2. It turns into `<a target="_blank" href="mailto:https://www.google.com/maps/@50.7006874,-3.0915427,13.75z">https://www.google.com/maps/@50.7006874,-3.0915427,13.75z</a>`

**Expected behavior**
Proper link to Google Maps.

**Additional context**
If anyone wants to work on it:
https://github.com/online-go/online-go.com/blob/02e083b78de56155d588c165a41b7c03eb079a1a/src/components/Chat/chat_markup.tsx#L122-L123

**Comment by benjaminpjones** [comment]
Should be noted that one-to-one chats break in a different way:

https://www.google.com/maps/@50.7006874,-3.0915427,13.75z

=>

https://www.google.com/maps/%4050.7006874,-3.0915427,13.75z

**Comment by benjaminpjones** [comment]
It looks like the google maps issue was actually fixed for Private chat (See commit https://github.com/online-go/online-go.com/commit/fdb42c4e14653aa8e0769027a76c5a5b3bb84bd2).  Seems like URL handling/message sanitizing should be shared between all the chats.

**Comment by BHydden** [comment]
Yeah flovo planned to copy his improvements in general chat over to PM and game chat but I don't think he had gotten around to it yet...

**Comment by benjaminpjones** [comment]
Moving to reopen

<img width="896" alt="Screen Shot 2020-11-22 at 2 20 34 AM" src="https://user-images.githubusercontent.com/25233703/99897663-6b668080-2c69-11eb-8940-7655e76a4370.png">

**Comment by mmartin** [comment]
I can't reopen this issue. Only someone with _Higher Powers_ can do it. @anoek?
