### ISSUE TITLE
Dev environment sticks at loading screen

### ISSUE THREAD

**Issue by RubyMineshaft** [online-go/online-go.com#1254]
I'm not really sure when this started happening for me, but when trying to load the dev environment I get stuck on the bouncy OGS logo screen. 

![Screen Shot 2020-10-31 at 4 59 08 PM](https://user-images.githubusercontent.com/42720842/97790852-50d54600-1b9a-11eb-986b-0cac5c12ea9d.png)

Yep, that's the one. 

I switched back to the devel branch, but it seems to be happening without any of my changes too. 
Has anyone run into this before or have any idea what I've broken?  I'm sure it's something really simple that I'm overlooking.

**Comment by GreenAsJade** [comment]
Yeah - I think that commit e56d07a0  broke the profanity filter.

I have branched from 02e083b7, the previous commit on devel to that one.

**Comment by GreenAsJade** [comment]
(Curiously, your bug report for this comes _after_ your fix for it ... but I'm pretty sure your fix is what's needed to get past that bouncy ball!)

**Comment by RubyMineshaft** [comment]
🤯  Wow... 

I saw that error while trying to figure out why nothing would load, fixed it, and switched back to another branch.  It never occurred to me that it was probably the reason or that once i switched branches it was no longer fixed.  This week has messed with my head.   Thanks GaJ 😅
