### ISSUE TITLE
Plurals not handled correctly for some languages

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1257]
**Describe the bug**
Not all languages follow the **1 => singular, !1 => plural** paradigm.  One example is Russian where you use different plural forms depending on if the number ends in a 2/3/4 or not. However, looking at translate.ts, we do not take this into account, even though there is evidence that there were plans to do this (`pluralidx()`, storing the plural forms in an array).

**To Reproduce**
1. Switch to Russian.
2. Find a game with more than 4 captures:

<img width="353" alt="Screen Shot 2020-11-01 at 11 45 01 PM" src="https://user-images.githubusercontent.com/25233703/97830826-4b602480-1c9c-11eb-84c1-3948cff2f8f4.png">

3. Note that it says "камня" instead of "камней"

I don't actually speak Russian, but I think it should say the latter.  In addition, note that the translators are putting in 2 plural forms, so nothing needs to change on the translation side:

<img width="1035" alt="Screen Shot 2020-11-01 at 11 40 50 PM" src="https://user-images.githubusercontent.com/25233703/97830919-8f532980-1c9c-11eb-8d7a-719c77d149bf.png">

**Comment by BHydden** [comment]
Welcome to the rabbit hole ❤

https://youtu.be/0j74jcxSunY

**Comment by benjaminpjones** [comment]
Okay, I took a look at the [CLDR's Language Plural Rules](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html) and it looks like we support 7 languages that have more than 1 plural form.  Here is a brief summary:

el : Greek : [one, other]
eo : Esperanto : [one, other]
en : English : [one, other]
vi : Vietnamese : [all]
ca : Catalan : [one, other]
it : Italian : [one, other]
cs : Czech : [one, few, many, other]
eu : Basque : [one, other]
et : Estonian : [one, other]
es : Spanish : [one, other]
ru : Russian : [one, few, many, other]
nl : Dutch : [one, other]
pt : Portuguese : [one, other]
zh-tw : Chinese (Traditional) : [all]
tr : Turkish : [one, other]
zh-cn : Chinese (Simplified) : [all]
ro : Romanian : [one, few, other]
pl : Polish : [one, few, many, other]
fr : French : [one or zero, other]
hr : Croatian : [one, few, other]
de : German : [one, other]
da : Danish : [one*, other]
fi : Finnish : [one, other]
hu : Hungarian : [one, other]
ja : Japanese : [all]
he : Hebrew : [one, two, many, other]
sr : Serbian : [one, few, other]
ko : Korean : [all]
sv : Swedish : [one, other]
uk : Ukrainian : [one, few, many, other]

Since there are only 9 different `pluralidx` functions that need to be written, I can do this by hand.  However, if a more robust solution (i.e. third-party library) is preferred, let me know!
