### ISSUE TITLE
Social login buttons should respond to dark mode styling

### ISSUE THREAD

**Issue by kevincoleman** [online-go/online-go.com#1268]
**Describe the bug**
The social login buttons appear to stay white even if the rest of the UI is in dark mode. Should be a quick fix. Just filing for record-keeping.

**To Reproduce**
1. Switch to dark mode
2. Visit login page
3. See shining beacons of light instead of svelte buttons

**Expected behavior**
Buttons should be dark like the rest of the UI

**Screenshots**
<img width="298" alt="Screen Shot 2020-11-16 at 11 53 43 AM" src="https://user-images.githubusercontent.com/445707/99301222-79984500-2802-11eb-9d80-4e4a28818e51.png">
<img width="298" alt="Screen Shot 2020-11-16 at 11 53 55 AM" src="https://user-images.githubusercontent.com/445707/99301247-82891680-2802-11eb-92a5-2bc24ba5f12d.png">

**Desktop (please complete the following information):**
 - OS: MacOS (latest)
 - Browser Firefox
 - Version Latest

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS (latest)
 - Browser FireFox, Safari
 - Version (latest)

**Comment by benjaminpjones** [comment]
Appears to be fixed?

<img width="376" alt="Screen Shot 2022-01-12 at 10 34 36 PM" src="https://user-images.githubusercontent.com/25233703/149278078-72e5fe3d-1a82-4e5a-a240-9724789804d1.png">
