### ISSUE TITLE
Have score estimator respect ruleset

### ISSUE THREAD

**Issue by JDNdeveloper** [online-go/online-go.com#1274]
Currently the score estimator always uses the Chinese ruleset. This differs from the final game scoring which does respect the ruleset.

For example, for a Japanese rules game: https://online-go.com/game/28155811

Final score:
![image](https://user-images.githubusercontent.com/4645409/99585046-a8492380-299a-11eb-8c5c-d046373e75a3.png)

Estimated score:
![image](https://user-images.githubusercontent.com/4645409/99585082-b139f500-299a-11eb-9910-1ff9f43a6c7f.png)

**Comment by BHydden** [comment]
This is because the current score estimator always estimates in Chinese, regardless of the games actual ruleset.

**Comment by JDNdeveloper** [comment]
I didn't know that, makes sense. I've updated the issue to reflect this.

**Comment by BHydden** [comment]
Worth noting that @anoek is currently working on some [AI scoring upgrades](https://forums.online-go.com/t/ai-backend-updates/31856?u=bhydden), so hopefully this issue will be resolved with that rollout

**Comment by GreenAsJade** [comment]
I hope the scoring _estimator_ is not getting improved by AI.    As has been discussed in the past, it's widely seen as a good thing that it is "approximate".

**Comment by BHydden** [comment]
Are you able to provide an rough metric on exactly how wrong the score estimate needs to be? If you have it at all the damn thing might as well know how to count. As long as it can be disabled at game creation I cant see an issue with it being a full strength KataGo number (I agree there is a strong argument for not showing the shadow count on the board).

**Comment by GreenAsJade** [comment]
Rough metric: it's about right now.

If we make it more accurate, it needs to be able to be disabled independently of analysis, and should be disabled by default.

**Comment by benjaminpjones** [comment]
Not exactly quantifiable, but here is the criteria that I would look for in judging an in-game score estimator:

1) The score estimator should speed up my counting.
2) The score estimator should not tell me anything I couldn't have figured out if given more time.

Kata would break rule 2 in the case of tricky life and death.  In my opinion in-game estimator should be *dumber* but *more controllable* (i.e. when you click the dots, things don't get all wacky).

> I agree there is a strong argument for not showing the shadow count on the board

This does fix many of the too-much-help issues...  Still, I prefer a score estimator that feels more like a tool than an oracle.  Maybe there is room for both options?

**Comment by pdg137** [comment]
The score estimator doesn't even know Chinese rules; it counts handicap stones incorrectly. For example, in [this game](https://online-go.com/game/33079596) it "estimates" a Black win by 2.5, when actually the game is over and White has won by 3.5.

I can't believe that it's desirable/intentional to obscure basic facts about how the rules work.

**Comment by benjaminpjones** [comment]
Looks like @pdg137 fixed this in #1610. Thanks!
