### ISSUE TITLE
The new profanity filter does not obey dark-mode setting.

### ISSUE THREAD

**Issue by mmartin** [online-go/online-go.com#1278]
**Describe the bug**
The new profanity filter (#1271) does not obey dark-mode setting.

**Screenshots**
![image](https://user-images.githubusercontent.com/236237/99867749-cf833900-2bc4-11eb-928b-9e4d17426a95.png)

**Comment by benjaminpjones** [comment]
So that's what the `ogs-react-select` classNamePrefix was for...

Good catch!
