### ISSUE TITLE
Player flags overlap the clock on mobile

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#128]
### Summary

When playing a game on mobile with @mlopezviedma 's patch #119 that fixed our missing player flag bug, you'll note the flag overlaps the clock on mobile.

### Environment

 * Operating system: Android 7.1.2
 * Browser: Chrome
 * Browser Version: 56

Alternatively any desktop browser with the mobile developer mode turned on

### Steps To Reproduce:

1. With #119 applied, visit a game with the mobile mode turned on in the chrome debug tools (or with an actual device too)

### Additional Information:

![ogs minibeast com-overview iphone 5](https://cloud.githubusercontent.com/assets/168460/23773307/a2ec90ec-04ec-11e7-9976-f93a2c7535e4.png)

**Comment by mlopezviedma** [comment]
Should I imitate the way flags are shown on PlayerDetails.tsx?

**Comment by anoek** [comment]
That'd probably work pretty good :)
