### ISSUE TITLE
Icons not rendering, showing empty square

### ISSUE THREAD

**Issue by JDNdeveloper** [online-go/online-go.com#1280]
**Describe the bug**
In game and review mode some icons are missing and just show an empty square. This appears to have just started today (11/21/2020). I can repro on both desktop (Windows 10 Chrome) and mobile (Android Chrome).

Game mode (see "Zen mode" and "Toggle coordinates"):
![image](https://user-images.githubusercontent.com/4645409/99888154-56ed9e00-2bff-11eb-8904-5deb23ebf1bd.png)

Review mode (see "Zen mode", "Toggle coordinates", and "Original game"):
![image](https://user-images.githubusercontent.com/4645409/99888156-5a812500-2bff-11eb-9a07-c81d9ced1a4f.png)

Analyze mode controls (see stone marking buttons):
![image](https://user-images.githubusercontent.com/4645409/99888159-5ce37f00-2bff-11eb-978f-bf2ff4304e60.png)

**Comment by benjaminpjones** [comment]
I noticed the Play icon was gone earlier today too (Android Chrome, MacOS Safari)

<img width="184" alt="Screen Shot 2020-11-21 at 4 50 49 PM" src="https://user-images.githubusercontent.com/25233703/99888294-b9539800-2c19-11eb-90d8-a3ecaaec3d26.png">

**Comment by BHydden** [comment]
Can confirm I too am experiencing this issue with icons for Play, Zen, and Toggle Coordinates not loading.
Windows 10
Brave Browser Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)

**Comment by JDNdeveloper** [comment]
Bisecting shows this as the problem commit (upgrading to webpack 5): 00b295ef6aa676ad5264c8f49e9c57e9d365b5b2

**Comment by JDNdeveloper** [comment]
PR with fix is out: #1281 

Took me longer than I'd like to admit to hunt down as I was convinced it was a webpack issue due to the nature of the offending commit and went down that rabbit hole.
