### ISSUE TITLE
Feature Request: User Notes

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#1285]
**Is your feature request related to a problem? Please describe.**
Many times it is difficult to remember in what context or scenario you met or associate with a particular user, especially your friends.

**Describe the solution you'd like**
Each player has a section on all other players' profiles or in their friend's list (or both) in which they can make private notes about the user.

**Describe alternatives you've considered**
An external notebook is possible but cumbersome, such an integrated feature would be beneficial. 

**Additional context**
Go is hard enough, without forgetting who your friends are!

**Comment by BHydden** [comment]
Existing discussion on the topic:
[May 2020](https://forums.online-go.com/t/suggestion-note-for-user-in-friend-list/27301?u=bhydden)
[June 2018](https://forums.online-go.com/t/weird-ideas-custom-user-information-for-your-friends/17361?u=bhydden)

**Comment by benjaminpjones** [comment]
Lol this feature was added forever ago
