### ISSUE TITLE
User profile popup not loading on first press

### ISSUE THREAD

**Issue by JDNdeveloper** [online-go/online-go.com#1286]
When browsing my game history and clicking on a player I noticed the first time I press it's not loading properly:
![image](https://user-images.githubusercontent.com/4645409/100004357-3eef5900-2d7c-11eb-8e8e-7e76d6dd9934.png)

Then if I click outside of the popup and press again it loads:
![image](https://user-images.githubusercontent.com/4645409/100004406-4d3d7500-2d7c-11eb-9dcb-9725ceb1c309.png)

In the console I'm seeing these errors when this occurs:
```
Attempted to fetch invalid player name:  ...
invalid player name
```

**Comment by BHydden** [comment]
I half fixed it a while ago, previously someone took the name `...` and it would actually take you to their profile instead of giving you the error message haha

**Comment by JDNdeveloper** [comment]
I'm working fixing it now.

**Comment by JDNdeveloper** [comment]
@BHydden Can you point me to the commit where you did the half fix? In my PR I just disabled fetching by username if username is `...` but I want to make sure that's a safe thing to do.

**Comment by BHydden** [comment]
No commit, I just found the user with that name and changed his username to break the link haha

**Comment by BHydden** [comment]
> In my PR I just disabled fetching by username if username is `...` but I want to make sure that's a safe thing to do.

that's technically a legal username, if someone should choose it again then they would have a very negative experience, perhaps the easiest solution is for @anoek  to add that username to the disallowed list?
