### ISSUE TITLE
Encode move tree position in URL for easy sharing

### ISSUE THREAD

**Issue by JDNdeveloper** [online-go/online-go.com#1289]
When in a review or a game's analysis mode it would be nice if there was a way to easily share the current move tree position. Some options:
1. Always encode the current move position in the URL so it can be easily copy and pasted.
1. Add button to analysis toolbar to generate (and copy to clipboard) a URL linking to the current move (or add it to "Link to game"/"Link to review" popup).

The biggest issue here is that custom move trees in game's analysis modes are only stored locally, so for now we could only support linking to moves in the main branch. Even with this limitation I think it would still be useful for sharing particular moves in a game.

**Comment by JDNdeveloper** [comment]
I forgot about named variations which mostly addresses this! I still think it would be nice to have a "jump to move" sharing URL for accessing quickly from other sites (such as [r/baduk](http://www.reddit.com/r/baduk)), but it's pretty easy to just say "click on variation x in the chat from this link". I may work on adding this sometime in the future.

I think having these two features would sufficiently cover it:
1. URLs for accessing named variations.
1. URLs for accessing numbered move positions from the main branch.

**Comment by mmartin** [comment]
URLs for moves from main branch already exist – e.g. https://online-go.com/game/28004671/42

**Comment by JDNdeveloper** [comment]
@mmartin Awesome! That + existing named variations covers it well enough. URLs for named variations aren't that important.
