### ISSUE TITLE
Can't return to game if score estimator was opened during conditional move planning

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1290]
**To Reproduce**
1. Go to an ongoing game where it is your opponent's turn
2. Click on "Conditional Moves" and place an *odd number of moves* (but *don't submit*)
3. Click "Estimate Score"
4. Click "Back to Game"

Get the following error: Can't enter conditional move planning when it's your turn.

Even once the error message is closed, right side controls are in an invalid state.

**Expected behavior**
Instead of getting the error, I would expect to be returned to the Conditional Move planner. To see "working" behavior, perform the above steps, but place an even number of moves instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/25233703/100282406-8707aa80-2f39-11eb-83a3-e28cfc9dc0e2.png)

**Additional Info:**
 - Browser: Chrome Desktop

**Comment by anoek** [comment]
@JDNdeveloper You were in this code most recently, any hunches by chance?

**Comment by JDNdeveloper** [comment]
This is likely a regression related to my change in Goban where we return to the previous mode (in this case conditional move planning) when exiting score estimator. 

Previously we would have re-entered play mode and jumped to the last move in the game, which is likely also incorrect behavior but at least it didn't corrupt the game state. I would look into `setMode()` code in Goban when re-entering conditional move planning and see if something doesn't get reset properly, or whether something in the `leaveScoreEstimator()`/`stopEstimatingScore()` in `Game.tsx` is messing it up.

**Comment by anoek** [comment]
Thanks for the fix @JDNdeveloper !
