### ISSUE TITLE
Using the score estimator while a staged move is placed confuses the engine into thinking a move has already been placed

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#1291]
Using the score estimator while a staged move is placed confuses the engine into thinking a move has already been placed once "Back to Board" is pressed.

To recreate this:

   1.  Go into a correspondence game you are participating in, where it’s your move to play
   2.  Place an unconfirmed move
   3.  Estimate score
   4.  Press ‘back to board’

**Comment by anoek** [comment]
This is likely related to the same issue as #1290 , any thoughts @JDNdeveloper ?

**Comment by JDNdeveloper** [comment]
We no longer `jumpToLastOfficialMove()` when leaving score estimator, so this is likey exposing a bug in `setMode(..., true)` or `stopEstimatingScore()`/`leaveScoringEstimation()` (maybe `sync_state()`?) when we partially reset board state without going back to a real board position.

**Comment by GreenAsJade** [comment]
Here's another seemingly related bug report:

[9:36] Fuminblue: Thanks! It was a great game, and he might well have won it, but it froze after estimating score right before a crucial move
[9:36] Eugene: When you say "froze" ... what was happening on your screen
[9:37] Fuminblue: i was allowed to place a stone, but it had a number on it
[9:37] Eugene: OK thanks that will help sorting out this problem
[9:37] Fuminblue: when i clicked return to game it would just say "calculating"
[9:38] Fuminblue: Thanks for the help.
[9:38] Eugene: Thanks for the info!

**Comment by JDNdeveloper** [comment]
This seems pretty severe. A quick fix would be to revert the latest Goban change. I'm away from keyboard till tomorrow so if someone wants to do that before then I think that would be good. 

If no one does anything I'll take a look tomorrow and try to fix-forward (rather than reverting).

**Comment by JDNdeveloper** [comment]
@GreenAsJade I'm having trouble understanding the bug report you mentioned (not sure if you have more context than what was given). I'm not sure in what situation the stone would have a number on it (is this when staging a move? when doing conditional moves?). I'm hoping to fix all of these bugs in one go. If this is a different issue from #1290 and #1291 it will be helpful to have a separate issue filed with repro steps.

I also want to add that refreshing the page fixes the board state in case anyone gets into one of these corrupted states.

**Comment by GreenAsJade** [comment]
@JDNdeveloper I answered a report that said "the game froze I could not play"

That transcript is what the person told me.

The way I read it is that they entered the estimator then tried to return to the game and got "stuck".


I just managed to reproduce it, and found their description was just slightly off ... it says "Estimating" not "calculating"

![Screen Shot 2020-11-29 at 10 23 36 am](https://user-images.githubusercontent.com/61894/100528474-2922dd80-322d-11eb-84da-58fb06e62896.png)

I think the key to reproducing is is to manage to hit "go back to board" from the estimate screen while the estimator is still running.

I achieved this by clicking the "estimate" button a few times and quickly hitting "back to board"

It's conceivable this was a latent bug before the recent changes!

**Comment by JDNdeveloper** [comment]
@GreenAsJade Fantastic, thank you! I'll fix this as well.

**Comment by JDNdeveloper** [comment]
@GreenAsJade I couldn't repro this in my dev setup. The score estimation was "too fast" for me to click back to board, and if I added timeouts or artificially slowed down my CPU (using Chrome dev tools performance tab) it would just freeze after pressing "Estimate score". Can you open a new issue for this so it can be tracked separately? I'll try to fix it once I can repro it on my end.

In terms of this being a regression, I've semi-reverted the change (https://github.com/online-go/goban/pull/15) so that we only do the "new behavior" if we were previously in analysis or conditional move planning mode. If after this merges you can only repro in those two modes (but not, for example, in regular play mode) than it is likely caused by these new changes, otherwise it's likely a latent bug. Either way, refreshing the page should fix the corrupt board state.

**Comment by anoek** [comment]
Thanks for the fix @JDNdeveloper !
