### ISSUE TITLE
On mobile during a game, the game board size is not optimized for screen when you switch from horizontal view to vertical view.

### ISSUE THREAD

**Issue by zeemai** [online-go/online-go.com#1292]
**Describe the bug**
When you play on the phone, if you starting from a vertical view, the game board is properly optimized for the screen, but if you switch to horizontal by accident and change back /or starting from horizontal view and change to vertical view, the game board doesn't go back to the original optimized size for the screen which will become too small, need to refresh or tab to regain normal size.

**To Reproduce**
Steps to reproduce the behaviour:
1. View any game,
2. Starting from a horizontal view or staring from a vertical view and change to horizontal view
3. Switch to Vertical view
4. The game board size is too small for the screen

**Expected behavior**
It should go back to the original optimized screen size. 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11 plus]
 - OS: [e.g. iOS14]
 - Browser [e.g, safari]

**Screenshot** 
![img_4686](https://user-images.githubusercontent.com/46029164/100462968-01b00180-30c3-11eb-8930-608d4cdfdb7f.jpg)

**Additional context**
This is my first issue. Apologies if there are any mistakes. ps. recently discover this go platform. Absolutely love it.

**Comment by BHydden** [comment]
Can confirm the same bug happens on Android phone

![Screenshot_20201128-064915_Brave.jpg](https://user-images.githubusercontent.com/28991649/100483815-dfab9300-3145-11eb-9ec3-437c81450912.jpg)![Screenshot_20201128-064821_Brave.jpg](https://user-images.githubusercontent.com/28991649/100483819-e508dd80-3145-11eb-8db0-8f75d4f10821.jpg)
