### ISSUE TITLE
Can an admin change my rank on the beta site for testing?

### ISSUE THREAD

**Issue by JDNdeveloper** [online-go/online-go.com#1295]
Not sure if there's a better place to post this than here (maybe the forum?). 

Can someone with admin access set my account deje2 on the beta site to the same rank as deje1 so I can challenge myself and test playing games? I can't seem to "level up" any of my dev accounts so they're around the same rank so I can test out playing games.

This will make it easier for me to test out fixes for #1290 and #1291.

If there's an easier way to test out playing games (not just review or demo) on the beta/dev site I'd be interested in learning about it.

**Comment by BHydden** [comment]
admin can't change your rank, but you can log into two separate accounts at the same time using incognito mode since login details are saved in a cookie, and brand new accounts can play ranked against each other, and unranked can be played between any accounts

**Comment by JDNdeveloper** [comment]
Ah got it. Does this mean you have to sign up for a new account each time? I've already done that a few times (I'm up to deje3 or deje4 I think), but I'd prefer to just have two accounts in separate Chrome profiles that I play against each other so I don't need to sign up each time (plan would be to alternate win/lose between the two so they stay near the same rank).

Is there some way I can increase the rank of deje2 to get up to the 9k of deje1? I can't seem to play any of my new accounts due to the rank difference so I can't change the rank of either deje1 or deje2.

Anyone on the beta server who's ranked that can lose a match or two to me to make my testing easier? :joy:

**Comment by BHydden** [comment]
just 2 accounts should be sufficient, as long as you remember their passwords :P haha, is there some reason it needs to be a ranked game? just play unranked ?

**Comment by JDNdeveloper** [comment]
Oh wow...totally forgot about just playing unranked games!! So I should be able to play unranked games between deje1 and deje2 even if their rank difference is too large right (on mobile, so I can't try it out right now)?

Although, I was testing stale overview ranking a couple days back where I needed the rank to change to test it, but needing that should be pretty infrequent.

**Comment by BHydden** [comment]
a 9d can play unranked with a 30k

if you need ranked, just use 2 brand new accounts and alternate winner to keep them even

**Comment by JDNdeveloper** [comment]
Got it, thanks!

**Comment by JDNdeveloper** [comment]
As a follow up, I was able to rank up deje2 (20k -> 13k) so now deje1 and deje2 can play against each other:
1. I had deje3 and deje4 (both unranked) play against each other and have deje3 win most of the time to get it ranked as 17k.
2. I had deje2 (20k) play against deje3 (17k) to uprank deje2 to within 9 ranks of deje1.
