### ISSUE TITLE
Joseki layout broken when in firefox (mobile)

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1300]
**Describe the bug**

**To Reproduce**
0. Open firefox on an android device
1. Go to 'online-go.com/joseki'
2. Note the board covers the text

**Expected behavior**
The layout shouldn't overlap. See chrome for an example of the correct layout.

**Screenshots**
![Screenshot_20201129-214423](https://user-images.githubusercontent.com/25233703/100563703-0a543380-328d-11eb-944c-4dc414f3c041.png)

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser: Firefox

**Comment by anoek** [comment]
FYI @GreenAsJade

**Comment by JDNdeveloper** [comment]
I'm planning on fixing this in the next few days.

**Comment by benjaminpjones** [comment]
Thanks @JDNdeveloper! My friend, who reported this to me, will be very happy he can use this on his phone now.
