### ISSUE TITLE
On home page, for the active games, it would be nice to have the List-board toggle button like what it's shown on the Game page

### ISSUE THREAD

**Issue by zeemai** [online-go/online-go.com#1309]
**Is your feature request related to a problem? Please describe.**
As you have more and more correspondence games (absolutely love this btw), you will realize you have a long list of games which are displayed as a board in active games, it's getting hard to navigate especially for mobile users as numbers of active games increases. For mobile users, imagine you have 10-15 games, and you need to scroll sometime to find the game you want. I spent 99% of the time playing on the mobile, and I started to find this a bit difficult to get to the game I want. 

**Describe the solution you'd like**
Add the List-Board toggle button like what it has in Game page next to the filter button. Let user (especially for mobile user) have the option to display a list of text info a or a list of board. 

**Describe alternatives you've considered**
It doesn't even need to be displaying the option for a user to show how many games on the page they like, which is what it did in the Game page, a list toggle button with a fixed page number would really increase/create better gaming experience for the mobile users.

**Additional context**
N/A

**Comment by mmartin** [comment]
Did You try to lower “Settings > General preferences > Game thumbnail list threshold”?
I have set mine to “0”, so I always have a list.

**Comment by zeemai** [comment]
Thanks a lot! I didn't know it existed. If I set it to 0 and it will become a list. I will close this issue now.
