### ISSUE TITLE
Changing username to an existing one gives error 500

### ISSUE THREAD

**Issue by juanchodepisa** [online-go/online-go.com#131]
### Summary

Trying to change your username for one that already exists should no doubt be impossible. However, trying to do so simply pops-up a dialog that says "Server Error (500)".

The error message in these cases should probably be more specific, and less intrusive (ie: maybe an error message "This username already exists" next to the username field in light red background color, so that the user may simply try to put something else there).

### Environment

 * Operating system: n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:

1. Go to your profile
2. Click edit
3. Change your username to that of another user
4. Save

**Comment by anoek** [comment]
Fixed on the server side, will be deployed soonish
