### ISSUE TITLE
AI review chart does not show score graph if a move has a score of “0”

### ISSUE THREAD

**Issue by mmartin** [online-go/online-go.com#1319]
**Describe the bug**
AI review chart does not show score graph if at least one move has a score of “0”.

**To Reproduce**
1. Open a game where one of the moves has a score of “0”
2. Switch to “Score” mode
3. Everything switches to “Score” mode, except
4. AI chart still shows “Win %” mode

**Expected behavior**
AI chart also switches to “Score” mode

**Screenshots**
![image](https://user-images.githubusercontent.com/236237/102003347-d3f7c900-3d0e-11eb-942d-3a4db5904805.png)

**Additional context**
This is due to the line 261. Not sure what author meant by it.
https://github.com/online-go/online-go.com/blob/b3fde06d24cb33e62d68ecb091baa48a366e528e/src/views/Game/AIReviewChart.tsx#L259-L261

**Comment by sallmard** [comment]
It's a wild guess from someone who doesn't know the codebase at all :) but could be a proxy for checking that the review generated successfully, i.e. this should have read 'review contains values > 0'? 

Which in turn might make this broken:

if (use_score_safe) {
            let yRange = this.max_score - this.min_score;
            gradient_transition_point = (this.max_score / yRange) * 100;
        }
