### ISSUE TITLE
Empty error box on browse to Ladders page

### ISSUE THREAD

**Issue by diegovillafuerte1** [online-go/online-go.com#1323]
**Describe the bug**
When browsing to the "Ladders" page, an empty error box appears and the console contains a 502 error

**To Reproduce**
1. Click on 'Ladders' from the top navigation bar
2. See error

**Expected behavior**
No errors when browsing to Ladders page

**Screenshots**
<img width="1671" alt="Captura de Pantalla 2020-12-14 a la(s) 9 08 13 a  m" src="https://user-images.githubusercontent.com/43355685/102112356-6e7a0a00-3dec-11eb-8b12-132ccfaba6e7.png">
<img width="1665" alt="Captura de Pantalla 2020-12-14 a la(s) 9 08 44 a  m" src="https://user-images.githubusercontent.com/43355685/102112361-720d9100-3dec-11eb-884c-fcf1aaf904e2.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser Chrome
 - Versión 87.0.4280.88 (Build oficial) (x86_64)

**Additional context**
Has happened to me multiple times, but not every time. Maybe due to network issues? Possible resolution is just to fail more gracefully with 502s?

**Comment by BHydden** [comment]
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www.googletagmanager.com/gtag/js?id=UA-37743954-2:1 
```

Could be related to all of Google's servers going down 5 hours ago?

**Comment by JDNdeveloper** [comment]
I just started seeing these today too. Here's an example of an overview request failing with a 502:
![image](https://user-images.githubusercontent.com/4645409/102136081-c5dca200-3e0d-11eb-815c-22c2f70f4c28.png)

**Comment by zeemai** [comment]
Get the same error only today.

**Comment by JDNdeveloper** [comment]
Relevant discussions on the forum:
https://forums.online-go.com/t/server-instability-14-dec/32392/4
https://forums.online-go.com/t/ogs-game-server-load-issues/28884/60
