### ISSUE TITLE
AI move numbering bug on captured stones

### ISSUE THREAD

**Issue by achandlerworth** [online-go/online-go.com#1329]
There appears to be a bug on the AI recommended movement numbering of stone where there is a captured stone.
In the example provided, there are 12 total recommended moves, however, you'll notice move 7 is missing. Move 7 is numbered is the same move as move 12.  After making move 7 (on the stone numbered 12), it will stay labeled move 12 until you finally make move 12, at which point it goes back and labels it move 7. 

As a Go player, I should see the moves that are available to make in the numeric order I should make them, therefore, moves 1-11, should be listed, after making move 7, it could then be relabeled move 12, but not before.

<img width="632" alt="1" src="https://user-images.githubusercontent.com/36549563/102695984-ff8c1f00-41f8-11eb-8198-16712b47dac0.png">
<img width="582" alt="2" src="https://user-images.githubusercontent.com/36549563/102695988-0450d300-41f9-11eb-986f-a2c0c92da1d1.png">
<img width="571" alt="3" src="https://user-images.githubusercontent.com/36549563/102695987-031fa600-41f9-11eb-9bb0-53f0cab6f32f.png">
<img width="604" alt="4" src="https://user-images.githubusercontent.com/36549563/102695985-0155e280-41f9-11eb-80c7-6acbff456a68.png">

**Comment by BHydden** [comment]
I'm inclined to agree that the top/visible number should be the next in the sequence, not the last.

How hard would this be to fix?

**Comment by achandlerworth** [comment]
Please keep issue open

**Comment by achandlerworth** [comment]
This issue should remain open

**Comment by benjaminpjones** [comment]
> How hard would this be to fix?

The hard part would be finding the root cause (maybe look around [AIReview.tsx](https://github.com/online-go/online-go.com/blob/devel/src/views/Game/AIReview.tsx)?) I don't imagine the fix would require much more than a few lines of code.
