### ISSUE TITLE
Sign-in in embedded iframe

### ISSUE THREAD

**Issue by wabu** [online-go/online-go.com#1333]
**Is your feature request related to a problem? Please describe.**

For an online-event with a virtual map (via https://workadventu.re), I want to include some goban to play go like normally we'd do every year. Therefore, we can open online-go inside an iframe, but the sign-in current just fails.

**Describe the solution you'd like**
I'd like to be able to sign into ogo inside in iframe. I'd guess it would be enough to change the cookie policy to "SameSite=None; Secure;", so the login will work when ogs is embedded on another site (see https://web.dev/samesite-cookies-explained/)

**Additional context**
You can test our current setup by visiting https://test.visit.at.wa-test.rc3.cccv.de/_/global/raw.githubusercontent.com/nerdhof/remote-hof/master/main.json and sit on one of the goban there.

**Comment by benjaminpjones** [comment]
Howdy @wabu, #1895 doesn't fix the sign-in issue, but you may be able to use it in your map.  When clicked, it redirects to the game.

@anoek do you have thoughts on the cookie policy suggestion?  It seems like a relatively easy win if you think it's safe.

**Comment by anoek** [comment]
I think it should be safe, afaik the only cookie we use is the Django session id
