### ISSUE TITLE
Obvious 73.5 point black win scored as a loss?

### ISSUE THREAD

**Issue by ctinsley1** [online-go/online-go.com#1335]
In my most recent live game (username ctinsley1, opponent's name danielsas236) I captured almost all of my opponent's stones, leaving only 3 on the board (which were all dead) to my 28, which surrounded every quadrant of the board. The Score Estimator (correctly, so far as I understand the rules) gave me a 73.5 point win. But when we both passed, the game was recorded as a 14.5 point loss (which doesn't even make sense if it scored us having 0 territory each). What's going on here?

![Screenshot_20201224-164834_Online Go](https://user-images.githubusercontent.com/76573020/103108126-69963100-460a-11eb-90bd-0e296c8ca4ce.jpg)

![Screenshot_20201224-164844_Online Go](https://user-images.githubusercontent.com/76573020/103108132-731f9900-460a-11eb-89ba-651e407892dd.jpg)

![Screenshot_20201224-165626_Online Go](https://user-images.githubusercontent.com/76573020/103108133-7a46a700-460a-11eb-81b2-3df8bb050f1c.jpg)

**Comment by BHydden** [comment]
I suspect either you or your opponent, whether accidentally or not, marked a selection of the black stones as dead, and thus they were converted to white points.

In any case, this is either a case for the moderators on OGS to investigate, which you can request from the game page through the main site, or else it is a problem with the app you are using, which is not developed here but rather by a fan of the server over at https://github.com/acristescu/OnlineGo and discussed further on the [OGS Forums](https://forums.online-go.com/t/are-you-a-developer-want-ogs-on-a-mobile-device/1419/589?u=bhydden)

**Comment by benjaminpjones** [comment]
https://online-go.com/game/29468712

This was a case of incorrect scoring. The game has been annulled. I think we can close this.

**Comment by benjaminpjones** [comment]
Related: https://www.reddit.com/r/baduk/comments/m1aemb/i_got_scammed_by_ogs/

I'm still not convinced these were anything but user error, but the additional evidence may be helpful.
