### ISSUE TITLE
Filtering bots in the "observe games page" seems buggy

### ISSUE THREAD

**Issue by TeXitoi** [online-go/online-go.com#1351]
Hi, and thanks for the great OGS!

**Describe the bug**

In the observe games page with "Bot games" unticked (live games) some games disapear even if the game is not finished. It seems that the filter is inconsistent and filter non-bot games.

**To Reproduce**

1. Go to 'observe games'
2. Click on 'filter'
3. Find a game with strong players and no bot
4. Untick 'bot games'
4. Search for the game

**Expected behavior**

I expect the "Bot games" filter to work properly.

**Desktop (please complete the following information):**

 - OS: Debian linux
 - Browser firefox esr
 - Version 78.5.0esr-1~deb10u1

**Comment by mmartin** [comment]
Also reported here:
https://forums.online-go.com/t/pros-are-not-bots/31455
