### ISSUE TITLE
Marking with right click

### ISSUE THREAD

**Issue by Syn-Tax** [online-go/online-go.com#1355]
I have always found it difficult to describe positions/possible next moves whilst playing. The chess site chess.com allows you to draw arrows using right click to indicate moves and maybe something similar is possible for OGS by having either a context menu allowing you to choose between the different marks available in analyze mode or just by having a default that can be changed.

**Comment by yayayen11** [comment]
I think OGS has markers too in analyze mode

**Comment by Syn-Tax** [comment]
I originally meant without being in analyze mode because I think that when you're playing faster games it can take too much time to go into analyze mode. I am currently doing this with analyze mode however I think it would be a nice quality of life improvement.

**Comment by flovo** [comment]
Ctrl+Click on a intersection will paste it's coordinates into chat. Is this what you are looking for?

**Comment by Clossius** [comment]
Well, I've been telling people to turn off analyze mode xD I think this would be a feature that would be good for streamers but I've been encouraging people to read things out in their head and not play it out. I even suggest moving the mouse away from the goban :|
