### ISSUE TITLE
AI SGF downloads broken

### ISSUE THREAD

**Issue by anahata0108** [online-go/online-go.com#1356]
**Describe the bug**
AI SGF downloads are currently broken, resulting in a 128 byte file containing an error message

**To Reproduce**
1. Go to any page for any game, e.g. [my first victory against a human here](https://online-go.com/game/29495197)
2. Click on 'SGF with AI Review'
3. Examine the downloaded file, named `sgf`
4. See error in file

**Expected behavior**
I would expect a proper SGF file with AI review.

**Contents of file**
Error: GET ai.online-go.com:443//api/ai-review/dd6c4cc8-a764-4ee8-937e-ff8c718a1a48 -- 0  unable to verify the first certificate

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 14.0.2

**Comment by anoek** [comment]
This was fixed a bit ago
