### ISSUE TITLE
Tournament trophy displayed twice

### ISSUE THREAD

**Issue by tomasmcz** [online-go/online-go.com#1357]
**Describe the bug**
A tournament trophy for one tournament is displayed twice.

**To Reproduce**
1. Go to https://online-go.com/player/84297/ 
2. See the box with trophies.
3. It appears to have 2 golden trophies, but both of them are the same tournament.

**Expected behavior**
I would expect the trophy to be displayed just once.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  Firefox
 - Version: 84.0.2 (64-bit)

**Comment by shinuito** [comment]
I think this bug has been around for quite a while but is just low on the list of things to fix next.

https://github.com/online-go/online-go.com/issues/679#issue-347718300

It would be handy to see it fixed though

**Comment by anoek** [comment]
Closing as dumplicate of #679
