### ISSUE TITLE
Typo: Change "Uneligible" to "Ineligible"

### ISSUE THREAD

**Issue by jonrubens** [online-go/online-go.com#1359]
The checkbox on the Play page has a typo. "Uneligible" is not a word, change to "ineligible".

**Screenshots**
![image](https://user-images.githubusercontent.com/7488974/105398701-87d65900-5bd7-11eb-8929-39c26acf0999.png)

**Comment by BHydden** [comment]
![image](https://user-images.githubusercontent.com/28991649/105467669-bdffff80-5ce1-11eb-8b30-7687a34d1387.png)
