### ISSUE TITLE
Pros rank not showing right in game chat messages

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#136]
This was fixed in main chat room by adding the professional flag to the user object I believe that is sent for chat messages. However it doesn't work in game chat. Does the same flag need added to game chat messages as well?

http://puu.sh/uDCbs/428e31a05f.png

#2

**Comment by anoek** [comment]
Fixed on server side, will be deployed later this week

**Comment by roy7** [comment]
@anoek This bug might be back? Perhaps because of the glicko-2 move? 

https://online-go.com/game/8031217

For instance, shows Ten as 8d in the chat room history, not 1p.
