### ISSUE TITLE
Have a button to count the triangles and squares on the board.

### ISSUE THREAD

**Issue by Clossius** [online-go/online-go.com#1363]
**Is your feature request related to a problem? Please describe.**
I would like to show viewers what I count as territory visually and it would be nice to click a button to tell me how many triangles and squares are on the board so I could quickly show the count in my head.

**Describe the solution you'd like**
Push a button to count the squares and triangles on the goban.

**Comment by GreenAsJade** [comment]
Can you clarify what you mean by "the squares and triangles" ?

**Comment by BHydden** [comment]
various board marking options

**Comment by BHydden** [comment]
Why don't you just use the number tool?

![image](https://user-images.githubusercontent.com/28991649/149673164-08e8095d-a018-416e-a8fc-5c23a716b78d.png)
