### ISSUE TITLE
Improve top menu tappability & appearance

### ISSUE THREAD

**Issue by kevincoleman** [online-go/online-go.com#1367]
**Is your feature request related to a problem? Please describe.**
The top menu is not particularly tappable in mobile environments.

**Describe the solution you'd like**
I’d like to make the menu a little larger with a bit more spacing. See sample video
https://user-images.githubusercontent.com/445707/106070354-29b6e380-60b9-11eb-8f7f-de0459fd7272.mov

**Describe alternatives you've considered**
This change is pretty small. I’m open to other suggestions of what it might look like.

**Additional context**
The one drawback I see to this is that the menu will take up a little more space. I tried to tailor it so the space loss is minimal, and I think the gain in a11y is still worth the change in this sample.

I’m happy to make a PR for this issue. Just filing it for early feedback.

**Comment by kevincoleman** [comment]
PR at https://github.com/online-go/online-go.com/pull/1368

**Comment by benjaminpjones** [comment]
Looks pretty snazzy. I wonder if this will fix an issue I've been seeing on Chrome/Android where the bottom pixels of the OGS logo are cropped:

![Screenshot_20210127-215717~2](https://user-images.githubusercontent.com/25233703/106089676-6ead3b00-60f6-11eb-8d08-6101d0ae55f8.png)

**Comment by kevincoleman** [comment]
Perhaps! Here’s a close-up from Chrome (latest) on MacOS.

![Screen Shot 2021-01-27 at 8 24 50 PM](https://user-images.githubusercontent.com/445707/106089900-cd19ef80-60dd-11eb-835c-e77319f72ca3.png)

**Comment by kevincoleman** [comment]
I believe this is still sitting in testing somewhere. @anoek ?

**Comment by BHydden** [comment]
I thought it was already implemented with `Enable experimental interface changes` at https://online-go.com/settings/general

**Comment by kevincoleman** [comment]
Is that intended to be where this change dies? I’m new to this... but is there a time frame in which the experimental changes can become merged into normal production?

**Comment by BHydden** [comment]
They're already in normal production, they're just not the default right now but that's an easy toggle to flip when anoek is happy to.

**Comment by BHydden** [comment]
Seems it'll be default (and only) option Soon™ #2099

**Comment by kevincoleman** [comment]
Oh cool! Sorry, “in production” was the wrong term there. “The default option” is more like it. And again, I don’t propose to bully my way to making my changes always be the default option. It just seemed to me that it would make sense to not mark an issue as stale before the timeline of it being realized has played out. Thanks for looking into this!

**Comment by BHydden** [comment]
Completed with https://github.com/online-go/online-go.com/pull/2099
