### ISSUE TITLE
MODTOOLS: Automatically connect games to user reports

### ISSUE THREAD

**Issue by sousys** [online-go/online-go.com#1372]
**Is your feature request related to a problem? Please describe.**
Its time-consuming to find relevant games when a user reports another user. 

**Describe the solution you'd like**
Automatically search the reported users last 10 games and include any games between reporter and reported and include it in the report-ticket

**Comment by BHydden** [comment]
follow-on; any reported game should include automatically a link to their opponent's profile

**Comment by BHydden** [comment]
I'm pretty sure both these features are in the new mod centre.
