### ISSUE TITLE
2021 New Rating, rating decreases on win

### ISSUE THREAD

**Issue by LeibnizGW** [online-go/online-go.com#1376]
With the new 2021 rating system, ratings are supposed to increase after a win, and decrease after a loss.

But something different happened on my account, please, check my profile (LeibnizGW).

On January 21, I lost two gams, my overall rating dropped to 1695+-73.
Nothing else happened untill January 30.
On January 30, I won a game, with a lower rated opponent. My overall rating dropped again, to 1690+-72.

Is this a little bug?

**Comment by flovo** [comment]
I can confirm this. The game history shows a rating loss after a win.

|ended	|game_id	|played_black	|handicap	|rating	|deviation	|volatility	|opponent_id	|opponent_rating	|opponent_deviation	|outcome	extra	|annulled	result|
|-|-|-|-|-|-|-|-|-|-|-|-|
1612064089	|29388673	|0	|0	|1690.82	|72.45	|0.059980	|741225	|1310.20	|63.64	|1	|null	|0	Resignation
|1611267195	|28464256	|0	|0	|1695.82	|72.93	|0.059982	|308797	|1660.34	|63.05	|0	|null	|0	|
Resignation|

[https://online-go.com/termination-api/player/537071/v5-rating-history?speed=overall&size=0](https://github.com/online-go/online-go.com/files/5914262/v5-rating-history.txt)

---

In the time between both games an earlier game got annulled. As the game was a loss for LeibnizGW, this should have increased the rank if it would be the cause of the problem, but maybe it's related.

**Comment by LeibnizGW** [comment]
I didn't notice the annulled game, I was not notified. Was my opponent computer cheating?

Anyway, the annulled game ended on October 3, but in that day there is no change to my rating. So I think my entire rating history was recalculated after the game was annulled, and it is like the annulled game didn't exist at all. So in principle it should not play a role in the problem we are discussing here.

**Comment by flovo** [comment]
Rating history of player [937137](https://online-go.com/player/937137/JohnPaul_Willfred888) is strange as well: https://online-go.com/termination-api/player/937137/v5-rating-history?speed=overall&size=0

With game 3 the rating suddenly increases dramatically after a loss (1061.98 -> 1748.87).
Between game one and two the deviation didn't change much (297.62 -> 293.39). 

|ended	|game_id|	played_black|	handicap	rating|	deviation	volatility|	opponent_id	|opponent_rating|	opponent_deviation|	outcome	extra	|annulled|	result|
|-:|-:|-:|-:|-:|-:|-:|-:|-:|-:|-:|
|1613525272|	31154916|	1|	0	|1720.25	|128.82	|0.060017	|127273	|1894.33	|62.33	|0	|null	|0	|Moderator Decision|
|1613520966	|30998973	|0	|1	| **1748.87**	|136.33	|0.060019	|718253	|1373.00	|62.15	|0	|null	|0	|167.5 points|
|1613107006	|31001926	|0	|0	|**1061.98**	|**293.39**	|0.060004	|57115	|1867.53	|65.56	|0	|null	|0	|47.5 points|
|1613025320	|30996201	|1	|0	|1067.25	|**297.62**	|0.060004	|906408	|1132.62	|91.77	|0	|null	|0	|28.5 points|
|1612938920	|0	|0	|0	|1500.00	|350.00	|0.060000	|0	|0.00	|0.00	|-1	|{"special":"initial rating"}	|0	|

**Comment by GreenAsJade** [comment]
This one https://online-go.com/player/941286/ is an example of a related but different problem, should ideally be looked at at the same time.   This person is still 10k after winning couple of [?] games early on then losing a whole bunch.

People are surprised to find a 10k not knowing how to play.

**Comment by shinuito** [comment]
> This one https://online-go.com/player/941286/ is an example of a related but different problem, should ideally be looked at at the same time. This person is still 10k after winning couple of [?] games early on then losing a whole bunch.

I was kind of alluding to something like this https://forums.online-go.com/t/2021-rating-and-rank-adjustments/33389/626?u=shinuito

It looks like they played a bunch of games against the same [?] player https://online-go.com/player/927847/ and all the while the deviation is going down. Then it ends up being quite low where it is now ±70 ish which seems pretty certain. 

I would've expected lots of consecutive losses to start bringing the devaition up. even a loss vs an 18kyu the deviation keeps going down. Maybe I'm misterpreting what the ±/deviation means?

**Comment by GreenAsJade** [comment]
If you loose a lot of time surely we become more sure that your rank is lower, therefore the deviation decreases.

Deviation increases if your result is not what we expected, like a win vs a higher rank, or loss vs lower rank.

**Comment by flovo** [comment]
)As the new implementation uses single game windows (the rating system only seeing one game at a time), the rating algorithm has no knowledge about "consecutive" or "often". Deviation might increase if you get unexpected results (wins against much stronger, losses against much weaker opponents), but the effect is minor at best.

(You can find the glicko2 math at http://www.glicko.net/glicko/glicko2.pdf)

**Comment by GreenAsJade** [comment]
I think the only significance of "consecutive" in shinuito's comment is that "repeating the same thing should cause more and more of the same effect.   IE it's not saying that mathematically the formula should "notice" that this is the same as last time, but rather, each time you do the same thing you should get more of the effect you were expecting.

Shinuito was expecting losses to increase deviation.   My own expectation is that the thing that increases deviation is a result that was not predicted.

**Comment by shinuito** [comment]
Well the thing that really confuses me is that theres a very steady decrease in deviation. Massively decreasing when playing against another ? mark player. Then continuing to decrease with both losses against stronger and weaker players.

It just doesn't seem to make sense to me, why the deviation never seems to go up.

Suppose I'm a new player and I lose 100 games to 1dans, the rating system should have no idea what my rank is really, other than I'm definitely below 1dan right? So if the deviation drops significantly, I was under the impression it takes much longer for the rating to change than if it was high? The volatility isn't really changing a whole lot it seems.

**Comment by GreenAsJade** [comment]
Isn't it the case that each time you lose to a 1 dan from a position below them, we become _more_ sure that your rank is less than 1 dan, and more sure that it is lower than we thought before?

IE each time I would expect the maths to say "Oh, a person lower than 1 dan lost to a 1 dan, so I will decrease their rank, and increase my confidence in this assessment".

**Comment by benjaminpjones** [comment]
While it is true that we are sure that the player is less than 1d, we have no Idea where they fall in the kyu range.  Hence, the deviation should (in an ideal world) be something wide like +/- 10k or so.

Whether Glicko is built to handle pathological cases like this, I don't know.

**Comment by GreenAsJade** [comment]
It's not true (form Glicko's point of view) that we have no idea.  We in fact state that we know within +/- 5k that they are 12k.

So Glicko should be fully expecting them to lose to a 1d, and increasing confidence that they are less than 1d.

Because the gap is so wide, I think that any effect on their rating in this hypothetical scenario would be (should be) minimal anyhow - you get almost no information from the loss of a 12k to a 1d.

In the _real_ example shinuito started with, the person was consistently losing to a [?] who was at the time 2k +/- 2k.   Conceivably as low as 4k.   As I claim you would expect, the person's rank went down a little in the process, and their uncertainty also went down.   Makes sense to me.

I think we should be focussing on more pressing and disturbing problems like "rating increase on a win".

Right now, I think the rating system in place at the moment has a pall of low confidence over it while this persists.

**Comment by benjaminpjones** [comment]
Ah, I was only responding to the thought experiment of a player losing to 1d 100 times.  I looked for the real-life example, but it seems unrelated to the example - [this player](https://online-go.com/player/927847/) has quite a few wins and losses in their rated game history.

It sounds like we agree that the player's certainty should decrease very little when the outcome is predetermined.

I don't follow your point that a fresh player who lost 100 games to dan players should be 12k+/-5k, but I agree that faulty deviation would not be a top concern.  (although if there is a real problem, investigation may help solve the other problems!)

**Comment by GreenAsJade** [comment]
LOL I was meaning to disagree that with your comment that "we have no idea where the new player falls in the kyu range".   In fact, a new player is known to be 12k +/- 5k according to our system.   They are 12k +/-5k _before_ they start losing games to the 1d.  That is very different to "we have no idea where they fall".   That's what I was trying to say.

Therefore, if we know that they are 12 (and not 1k for example) then _definitely_ we expect them to lose to a 1d, and so when they _do_ lose, it increases our confidence in their rating.

**Comment by shinuito** [comment]
You're all probably right. I need to finally sit down and read some of the Glicko papers too to really wrap my head ahead it as well. I just keep putting it off.

**Comment by GreenAsJade** [comment]
Me too.

**Comment by BHydden** [comment]
Quite sure anoek fixed it so all losses lose rating and all wins gain rating.
