### ISSUE TITLE
MODTOOLS: Ability to set ban length / expiration date

### ISSUE THREAD

**Issue by sousys** [online-go/online-go.com#1379]
**Is your feature request related to a problem? Please describe.**
Bans today are rather arbitrary and permanent/manual. Its hard to be consistent or standardize mod actions. 

**Describe the solution you'd like**
The ability to set expiration date for a ban. 

Alternativly perhaps have a selection or set ban lengths. 
1h, 
24h, 
3d,
7d,
permanent

**Comment by anoek** [comment]
Yeah this is long overdue..

**Comment by GreenAsJade** [comment]
I've posted my issues with this proposal in the moderator discussion forum.

**Comment by anoek** [comment]
Actually this was done, hooray!
