### ISSUE TITLE
I cannot mark groups as seki

### ISSUE THREAD

**Issue by zbence** [online-go/online-go.com#1381]
**Describe the bug**
At the scoring phase when we mark the stones dead or seki it sometimes not picking up sekis.
At this game: https://online-go.com/game/30690430   I cannot mark the  F14 white and F15 black groups as seki.

**To Reproduce**
1. Go to my game. The link can be found above.
2. Click on Estimate Score
4. See error you cannot make the groups as seki

**Expected behavior**
I click the stones and it grays out and not counting extra points for the the players.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Ubuntu Linux
 - Browser Firefox
 - Version 84.0.2 - 64bit

**Additional context**
If  AI scoring would be availble that would be nice. The AI at the end picked up the final scores correctly with the seki.
So if I'm not satisfied with the counting that the Score Estimatior provides there should be a button which calls the ai to 
determine the final score.

**Comment by benjaminpjones** [comment]
After the game concluded, did you click on the stones that should be alive?  I just tried to reproduce with the same board layout, and was able to mark a seki:

Before clicking the white group:

<img width="860" alt="Screen Shot 2021-04-06 at 4 12 39 AM" src="https://user-images.githubusercontent.com/25233703/113680032-6e996080-968e-11eb-8ec9-fffa2557082c.png">

After clicking the white group:

<img width="892" alt="Screen Shot 2021-04-06 at 4 09 49 AM" src="https://user-images.githubusercontent.com/25233703/113680082-7a852280-968e-11eb-8d92-33d1e46d69cb.png">
