### ISSUE TITLE
IncidentReportTracker permanently displayed with count of zero

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1385]
**Describe the bug**
I have an "IncidentReportTracker" button in my navbar showing a count of zero. When I click it there's a popup with some information about an incident I reported a few days ago and a moderator's username, but no message or action to take. I think it's just stuck there in some bad state. Maybe because two moderators tried to take action simultaneously?

It might also be worth mentioning that this mysterious popup does not scroll like the rest of the page.

**To Reproduce**
Steps to reproduce the behavior: no idea except logging into my account at this time. My incident was handled (game decided by moderator) but I never received any direct messages about it.

**Expected behavior**
There shouldn't be anything displayed in the navbar unless there's some useful information or action to take.

**Screenshots**
![image](https://user-images.githubusercontent.com/466760/107112842-8c258780-680f-11eb-97b6-85c41e490c5c.png)

Visible in latest Brave on Android and Windows.

**Comment by BHydden** [comment]
The 0 means you have 0 unclaimed reports, that's also why it is purple. If you had unclaimed reports the triangle would be red and would display the count of unclaimed reports. The report is still open, but has been claimed by the moderator AdamR. Ideally, he will close the report when he is finished and the triangle will disappear from your screen, though when dealing with many reports in a row sometimes you can forget to close one. I will touch base with Adam to make sure all is well, but everything appears to be functioning as designed. 

(whether it needs a re-design is another matter, but outside the scope of this issue) :P

**Comment by Adam314159** [comment]
Yup, that was my fault, sorry about that, I wanted to keep the reminder for some finish-up on my side, should be all clear for you now. Sorry to have kept you waiting that long.

**Comment by pdg137** [comment]
Oh, I had no idea it wasn't resolved. I considered messaging AdamR but didn't want to bug him over something that was already done. As a user this widget seemed totally mysterious to me, even if it was working as designed. I'm skeptical about this thing of "claimed" issues mattering to users, but if you want to keep that, something as simple as adding text like "0 unclaimed issues / 1 unresolved issue" to the popup would help. Thanks for listening!

**Comment by GreenAsJade** [comment]
@pdg137  Can you close this one? :)

**Comment by pdg137** [comment]
I still think it's an issue that this mysterious UI element can appear with no obvious action for the user to take. I don't want to be annoying, but if you think it would be helpful, I'd be happy to open a new issue for it clarifying the point.

**Comment by GreenAsJade** [comment]
@pdg137  I see what you mean.  I think it would make sense to do that.
