### ISSUE TITLE
Patreon support 

### ISSUE THREAD

**Issue by lemurek** [online-go/online-go.com#139]
### Summary

Integrate with general purpose Supporter network instead of manually managing the Contributions. 

### Environment

 * Operating system: Any
 * Browser: Any
 * Browser Version: Any

### Steps To Reproduce:

1. Go to patreon.com
2. See how easy it is to configure contribution there
3. Appreciate outsourcing Contributions management
4. Have tons and tons of new supporters

**Comment by anoek** [comment]
Feel free to open up this suggestion on the uservoice forums and we can see how much interest there is in it. There are some technical considerations (like how does one ensure we are marking patreon's as supporters) that would need to be figured out first as well. I'm going to close this here though until the idea has been vetted on uservoice and some baseline of interest has been established.

**Comment by lemurek** [comment]
Good point. It wasn't the greatest idea to put it as an issue. However from practical point of view Patreon should make your Supporter management easier (not more difficult):
https://patreon.zendesk.com/hc/en-us/articles/206525646-Does-Patreon-have-an-API-

I'll put the suggestion somewhere on forums ;)
