### ISSUE TITLE
Provide game metadata in the Goban div

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1392]
People would like to [customize their experience based on the context of the game they are playing.](https://forums.online-go.com/t/features-everyone-secretly-want-on-ogs-but-will-never-be-implemented/32125/63?u=eugene)

**Describe the solution you'd like**

They want metadata in css classes:

```
<div class="Goban" data-game-id="123" data-tournament-id="1234">
<div class="Goban" data-game-id="123" data-ladder-id="1234">
```

**Comment by GreenAsJade** [comment]
1) Will this really get used?

I implemted a similar convenience feature a while back based on some enthusiasm, it never saw use that I'm aware of.

2) Do we really need the game id?   What would be done with that?

**Comment by GreenAsJade** [comment]
I couldn't see a good reason to prepend the property names with data-.

To me, it's a "Goban" with"game-id=123"

**Comment by GreenAsJade** [comment]
Also, it turned out that game-id was trivially available, so I wacked that in anyhow.

**Comment by benjaminpjones** [comment]
> I couldn't see a good reason to prepend the property names with data-.

I don't think any browser is going to complain, but there are good reasons to prepend with `data-`: https://stackoverflow.com/questions/2450585/why-should-i-prepend-my-custom-attributes-with-data

**Comment by pdg137** [comment]
Hey, thanks for doing something with this so quickly!

1. No idea if this will actually be useful, but I'll try to promote my frivolous use for it! Looking at the HTML, I was disappointed that this info wasn't immediately available. When playing games on OGS I often feel that it takes too many clicks to figure out what a game is about, and this seemed like an easy way to push for making some basic game information available in more parts of the UI.
2. Perhaps people will want to customize the look of particular favorite games that don't fall under a tournament or ladder? I'm not sure, but it seemed like game/ladder/tournament id are the basic pieces of information that locate a game within the OGS world. I don't think it would be a big loss to leave the game id out.

As for data, JQuery's [`.data()`](https://api.jquery.com/data/) method is handy.
