### ISSUE TITLE
Ability to gift supporter subscription

### ISSUE THREAD

**Issue by RubyMineshaft** [online-go/online-go.com#1394]
https://forums.online-go.com/t/site-support-for-a-friend/34117

**Describe the solution you'd like**
Relaying request from forums. User wants the ability to gift supporter status to friends. I think this sounds like a great idea

**Comment by benjaminpjones** [comment]
This has been asked for in the past as well: https://forums.online-go.com/t/gift-donation/32122.

I think it's a great idea because currently, supporters are effectively capped at $10 per month.

**Comment by BHydden** [comment]
> supporters are effectively capped at $10 per month, can donate as much as you want, it just all goes to your account not a friend's.

Didn't notice the slider and editable text field?
![image](https://user-images.githubusercontent.com/28991649/107552351-1e1dfd80-6c1f-11eb-83aa-0d5429a27ba8.png)

**Comment by BHydden** [comment]
@anoek is this possible or not really? Seems like a nice gesture

**Comment by anoek** [comment]
It's certainly possible and I'd like to have it, but it is a lot of work and I don't have a good feel for how popular it'd be, so it's not hit the top of the priority queue.
