### ISSUE TITLE
Miniature stone rendering

### ISSUE THREAD

**Issue by lemurek** [online-go/online-go.com#140]
### Summary

Miniature game previews (especially 19x19) render is unnecessarily ugly. Because stone spacing is fixed, in lower resolutions stones seem to be misplaced and misaligned.

I believe it might be a problem as this is usually one of the first screens newcomers see after logging.

### Environment

 * Operating system: Any
 * Browser: Any
 * Browser Version: Any

### Steps To Reproduce:

1. Navigate to 'Watch' section.

### Additional Information:

I believe that this:
![image](https://cloud.githubusercontent.com/assets/12175058/23822721/8622a078-064a-11e7-8ab7-35dfe5c28ba0.png)
Could be easily fixed by scaling stone spacing proportionally to stone sizes, and applying some a little bit of floating points to the transforms.

**Comment by ihoover** [comment]
I honestly can't see anything that looks particularly misaligned in the example screen-shot you give. Is it very subtle or am I just missing something obvious?

**Comment by lemurek** [comment]
Well... let's zoom in a little bit. 

![screen shot 2017-03-11 at 11 11 15](https://cloud.githubusercontent.com/assets/12175058/23822779/a46b1b72-064b-11e7-9d73-0b67eab9de81.png)

I wouldn't say it's a major problem, but since Go is visually pleasing game, we should make sure that the Main preview screen is pleasing to look at. I'm not sure why stones get smaller in low resolution, but space between them have to stay at exactly 2 pixels.

**Comment by lemurek** [comment]
Btw. problem only affects rendered stones. Plain stones are aligned perfectly! :) The distance between stones could be still reduced in that case, but that's a rather subjective matter.

![image](https://cloud.githubusercontent.com/assets/12175058/23823087/69f0e16e-0652-11e7-8149-ad108eecc6df.png)

**Comment by lemurek** [comment]
Ok, so I noticed that line paths are traced at 0.5 pixel to make sure they are as thin as possible, i.e. just 1 pixel wide. At the same time rendered stones are centred at full-pixel number. That inconsistency produces this 1 pixel shift. If it's easy enough I'll try to submit suggested fix in form of pr
