### ISSUE TITLE
"join group" notification is not complete on the website

### ISSUE THREAD

**Issue by vaurienLL** [online-go/online-go.com#1401]
**Describe the bug**
Group is not indicated for admin when he gets notified on the website. Even if it is by mail.

**To Reproduce**
1. Ask people to join a group you're admin of
2. Watch the notifications on the website
3. See error, plus when you click on it, it will only lead you to the profile of the person asking to join.

**Expected behavior**
Add the name and the link of the group which is asked to be joined

**Screenshots**
![image](https://user-images.githubusercontent.com/79278953/108421445-7e232e00-7235-11eb-93d5-55985d93656d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Browser [e.g. firefox]
 - Version [e.g. 85.0.2]

**Additional context**
-

**Comment by oldyew** [comment]
The same  for me. It's very frustrating that I need to go inside the each group to find which one this request belongs to...
