### ISSUE TITLE
Can't invite 25k player to "25 Kyu and above" tournament

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1403]
**Describe the bug**
If I try inviting a particular player rated 25k to https://online-go.com/tournament/71615 with Rank restriction "25 Kyu and above", it says "Player's rank is not within what is allowed by the tournament".

Maybe they are really 28k and it's just not shown?  There's apparently no option to allow 28k players into a tournament.

**To Reproduce**
1. Go to [the tournament page](https://online-go.com/tournament/71615)
2. Enter the "Makoto Akagi" into the invite box.
3. Click "Invite"

**Expected behavior**
Player should be allowed.  Or there should be a setting to allow all ranks.

**Screenshots**
![image](https://user-images.githubusercontent.com/466760/108568369-d3efe880-72be-11eb-8009-28f9c6376e56.png)

![image](https://user-images.githubusercontent.com/466760/108568387-dce0ba00-72be-11eb-81c0-6cc709e4e7af.png)

![image](https://user-images.githubusercontent.com/466760/108568721-6ee8c280-72bf-11eb-86da-4e7c7e168cb2.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: Latest

**Comment by pdg137** [comment]
Verified that this bug is still occurring:

![image](https://user-images.githubusercontent.com/466760/135705492-1ebc5c15-94f8-45e4-abda-842a43ab5a8f.png)

![image](https://user-images.githubusercontent.com/466760/135705507-25dbc6fa-0cbe-4e31-b634-a9cca0436d70.png)

**Comment by anoek** [comment]
Finally fixed this on the backend
