### ISSUE TITLE
Darker shade of gold for site supporter names on light backgrounds

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1404]
**Is your feature request related to a problem? Please describe.**
The contrast ratio for our yellow (#dfba00) on white (#fff) is only 1.88:1.  For off white or other backgrounds, the ratio is even worse.  For reference, WGAC recommends 4.5:0 for text, but I think we can follow the guidelines for bold text which is 3:0.

**Describe the solution you'd like**
I think #a48200 is a nice shade of gold that has a contrast ratio of 3.63:1 on a white background.  My proposal is to update the colors of site supporter names to #a48200.

**Describe alternatives you've considered**
Badges instead of colorful names.  I still think badges would be a fun, accessible indicator, but there was little support for removing color (which I can understand).

**Additional context**
The proposed color scheme:
<img width="435" alt="Screen Shot 2021-02-20 at 3 26 24 PM" src="https://user-images.githubusercontent.com/25233703/108607989-ca838080-7391-11eb-8e12-5d86a3b11025.png">

In the player boxes (note gold on dark has not changed)
<img width="438" alt="Screen Shot 2021-02-20 at 3 25 38 PM" src="https://user-images.githubusercontent.com/25233703/108607990-ceaf9e00-7391-11eb-9b06-1c1443f4e904.png">

**Comment by benjaminpjones** [comment]
Hi @anoek, I'd like to know whether I'd have support to implement this one.  The yellow isn't a big deal to me, but there have been complaints in the past that the contrast with light backgrounds is not ideal.

Please let me know, and if you hate it feel free to close!

**Comment by benjaminpjones** [comment]
Some compare and contrast:

Old:
<img width="107" alt="Screen Shot 2021-02-20 at 3 51 49 PM" src="https://user-images.githubusercontent.com/25233703/108608216-8db88900-7393-11eb-9212-06b614912c2f.png">

New:
<img width="106" alt="Screen Shot 2021-02-20 at 3 51 31 PM" src="https://user-images.githubusercontent.com/25233703/108608195-81ccc700-7393-11eb-9154-e6e91ba15891.png">

Old:
<img width="91" alt="Screen Shot 2021-02-20 at 3 46 36 PM" src="https://user-images.githubusercontent.com/25233703/108608123-d1f75980-7392-11eb-9b07-a172a36663ed.png">

New:
<img width="95" alt="Screen Shot 2021-02-20 at 3 47 49 PM" src="https://user-images.githubusercontent.com/25233703/108608140-0f5be700-7393-11eb-8e8a-f192289d1866.png">

Old:
<img width="65" alt="Screen Shot 2021-02-20 at 3 49 30 PM" src="https://user-images.githubusercontent.com/25233703/108608153-39ada480-7393-11eb-8032-20bc779e9e67.png">

New:
<img width="71" alt="Screen Shot 2021-02-20 at 3 49 03 PM" src="https://user-images.githubusercontent.com/25233703/108608150-2ac6f200-7393-11eb-9946-9ae10fe3f0d6.png">


I'm not sure if these side-by-sides make it particularly obvious that there is an improvement, but I think the higher contrast makes for better viewing in suboptimal conditions, like being on a mobile device on a sunny day.

**Comment by BHydden** [comment]
Relevant ongoing discussion in the forums is [here](https://forums.online-go.com/t/yellow-on-white-is-an-awful-color-choice-for-text/34275?u=bhydden).

**Comment by anoek** [comment]
Yep that'd be awesome, thanks! Color picking is a challenge for me.

**Comment by benjaminpjones** [comment]
Sweet! PR incoming.  I'm not that confident in color picking myself, but I think I wrote it in such a way that we can fidget with dark.supporter and light.supporter until it's perfect.
