### ISSUE TITLE
9x9 auto handicaps do not correspond to current rank differences

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1406]
**Describe the bug**
In [this tournament](https://online-go.com/tournament/71615) there are some games with handicaps that make no sense. My wild guess is that they might still be using the old ranking system.

**To Reproduce**
1. Make a 9x9 auto handicap tournament with various ranks; invite a lot of players of varying strengths.
2. Immediately after tournament starts, record ranks and handicaps.
3. Sort the list by rank difference.  (Remember 1d - 1k = 1, not 2.) Consider various rounding options.
4. Note that the handicaps are not sorted:

(here I have used positive #s for dan ranks and negative for kyu, also I just copied these out by hand so please let me know if there are mistakes)

game | black | white | handicap | komi | diff | winner |
-- | -- | -- | -- | -- | -- | --
31309623 | -21.3 | 4.1 | 8 | -5.5 | 24.4 | B
31309625 | -20.3 | 2.8 | 7 | -2.5 | 22.1 | B*
31309635 | -22.2 | -0.9 | 6 | 0.5 | 21.3 | B
31309629 | -23.5 | -3.1 | 6 | 0.5 | 20.4 | B
31309622 | -13.2 | 6.5 | 7 | -2.5 | 18.7 | B
31309640 | -19.4 | -6.1 | 5 | 3.5 | 13.3
31309634 | -18.2 | -6.3 | 4 | -5.5 | 11.9
31309636 | -20.3 | -8.5 | 4 | -5.5 | 11.8
31309626 | -11.8 | -0.2 | 4 | -5.5 | 11.6
31309632 | -13.7 | -4.8 | 3 | -2.5 | 8.9
31309624 | -5.8 | 3.4 | 3 | -2.5 | 8.2 | B
31309630 | -13.2 | -7.2 | 2 | 0.5 | 6 | B 
31309631 | -7.2 | -3 | 2 | 0.5 | 4.2 | B*
31309638 | -10.5 | -6.4 | 2 | 0.5 | 4.1 | W
31309643 | -18.7 | -14.6 | 2 | 0.5 | 4.1
31309642 | -16.6 | -12.6 | 2 | 0.5 | 4
31309641 | -10.8 | -7.6 | 1 | 3.5 | 3.2 | W
31309637 | -11.3 | -8.5 | 1 | 3.5 | 2.8 | B
31309644 | -18.2 | -15.4 | 1 | 3.5 | 2.8 | W
31309633 | -5.5 | -3.6 | 1 | 3.5 | 1.9
31309645 | -15.4 | -13.9 | 1 | 3.5 | 1.5
31309639 | -9.2 | -8.6 | 1 | 3.5 | 0.6

\* - resigned immediately

**Expected behavior**
The handicaps should be in order in at least some version of this table.

**Screenshots**
* [Game A](https://online-go.com/game/31309629) - 23.5k vs 3.1k gets handicap of 6:
  ![image](https://user-images.githubusercontent.com/466760/108630083-f3e6ef80-7417-11eb-89f3-121dc459d851.png)

* [Game B](https://online-go.com/game/31309622) - 13.2k vs 6.5d gets handicap of 7:
  ![image](https://user-images.githubusercontent.com/466760/108630095-02cda200-7418-11eb-934b-5eef35e4847b.png)

**Additional context**
Possibly related bug: #833.

But ... [according to gennan](https://forums.online-go.com/t/2021-rating-and-rank-adjustments/33389/537) these handicaps correspond to rank differences of at least 22 and 25, far more than the actual rank differences of 20.4 and 18.7. There's a closed but similar bug: #676, making it sound like this also happened after a major rank update in 2017. Any chance the handicapping code is still referring to the 2020 ranks??

EDIT: updated with latest game result.

**Comment by benjaminpjones** [comment]
>The handicaps should be in order in at least some version of this table.

Does your table account for humble ranks?

**Comment by pdg137** [comment]
No, what are these? It wouldn't make sense to use something other than the actual rank for handicapping, would it? Anyway, all the players in my two main examples seem to have a deviation well under the 160 mentioned at that link, assuming that's the ± number shown here:

![image](https://user-images.githubusercontent.com/466760/108631832-c5b9dd80-7420-11eb-8021-ca196e9e12db.png)

**Comment by pdg137** [comment]
So far, out of 16 games with meaningful (>1) handicap, Black is winning 8:1. The other 7 games are still ongoing.  It seems like the handicaps are indeed way too strong.

It would be great if someone who knows how this is *supposed* to work could at least comment before the next round of the tournament!

**Comment by pdg137** [comment]
Looking into how it's "supposed" to work, I found [this old post](https://forums.online-go.com/t/aga-rules-handicap-and-komi-calculations-incorrect/5853/3) in which @anoek says that OGS uses the "[Old Japanese Recommendation](https://senseis.xmp.net/?HandicapForSmallerBoardSizes#toc8)" for 9x9. From my experiment, it seems that we use that system but with only a single komi value for each handicap level.  So this is how I think it is supposed to work vs. how it actually happens now:

rank diff | handicap | komi | observed rank diff in my tournament
-- | -- | -- | -- 
0-4 | 1 | 3.5 | 1-3
5-8 | 2 | 0.5 | 4-6
9-12 | 3 | -2.5 | ~8-9
13-16 | 4 | -5.5 | ~11-12
17-20 | 5 | 3.5 | 13
21-24 | 6 | 0.5 | ~20-21
25-28 | 7 | -2.5 | ~20-23
29-30 | 8 | -5.5 | ~24-26
\>30 | ? | ?

(The \~ indicates that I'm not sure exactly what to call it due to rounding.)

**Comment by pdg137** [comment]
Handicaps seem excessive in [this 19x19 tournament as well](https://online-go.com/tournament/71754).  Isn't it supposed to be 1 stone per rank difference? It seems to be getting set one or two stones higher.

**Comment by pdg137** [comment]
I have a pretty clear-cut wrong handicap (7) in [this 19x19 game](https://online-go.com/game/31548002).

* [The game API](https://online-go.com/api/v1/games/31548002) shows that it started at time 1614506455.
* [Rating history for pdg137](https://online-go.com/termination-api/player/309835/v5-rating-history) shows rating of 1405.72 at the last entry *before* this time. So this is the rating that should have applied to the game.
* [Rating history for LikeToDieInGote](https://online-go.com/termination-api/player/738650/v5-rating-history) shows rating of 1767.03.
* It doesn't look like either of us has had anything recently annulled by a moderator.

Using the current rating to rank formula:

`ln(1767.03 / 525) * 23.15-ln(1405.72 / 525) * 23.15 = 5.29...` which should round down to a handicap of 5.

Using the old rating to rank formula:

`ln(1767.03 / 850.0) / 0.032-ln(1405.72 / 850.0) / 0.032 = 7.14...` which would round down to a handicap of 7, the handicap we got.

So I really suspect that auto handicaps are using the old rank formula, at least for tournaments.

**Comment by pdg137** [comment]
After more careful analysis on recent tournament rounds I think this is working fine now. I don't know whether anything changed, though.
