### ISSUE TITLE
Planning Moves is disabled for me, but enabled for opponent

### ISSUE THREAD

**Issue by CRDE** [online-go/online-go.com#1409]
At least in some games, e.g. https://online-go.com/game/31071308

**Comment by benjaminpjones** [comment]
What does this setting look like for you? (Settings-> Game Preferences)

![Screenshot_20210222-090246_Chrome](https://user-images.githubusercontent.com/25233703/108718942-f6ffdf80-74ec-11eb-905c-dc13de546c9c.jpg)

**Comment by CRDE** [comment]
aha, ok. That solved the prob. thank you!

Should i skip the issue?

Christoph Rottmann
Am Hüttekotten 3b
45891 Gelsenkirchen
0176/305 41 711

**Comment by benjaminpjones** [comment]
Yes, unless you have an idea on how to make this clearer in the UI, I think it's okay to close.
