### ISSUE TITLE
Can't sort puzzles

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#141]
### Summary

Bug report from Eidolonia.
On the old site, the Puzzles section was sortable (so e.g. I could arrange the collections by difficulty, or by number of puzzles). The new site doesn't seem to let me do that, at least in Chrome. I found this pretty useful. Could we have it back please?

### Environment

 * Operating system: iOS
 * Browser: Chrome
 * Browser Version: ?

### Steps To Reproduce:

1. Go to https://online-go.com/puzzles
2. Try to sort the puzzles

**Comment by tnan123** [comment]
Also having this problem. On windows 10, I've tried both firefox and chrome with no luck :(

**Comment by stephancurran** [comment]
This should be closed now.
