### ISSUE TITLE
Multiple server login

### ISSUE THREAD

**Issue by freysgodi** [online-go/online-go.com#1412]
**Is your feature request related to a problem? Please describe.**

OGS allows multiple server login from different hosts. It allows malversions during official tournament games  

**Describe the solution you'd like**
To develop a unique login with autodisconnect or forbidding alternative connect from another host. 

**Describe alternatives you've considered**
Hmmmm.. No alternatives, definetily

**Additional context**

Anybody can play my game from another place of world using my login/psw. I need just to have a good friend with Tesla GPU to be a world champion

**Comment by anoek** [comment]
This is a feature, folks like to be logged in on their mobile device as well as their desktop and laptops. 

Bot detection stuff is in the works to address your concern about botting.

**Comment by freysgodi** [comment]
Do you understand that any other person can play somebody's game from another host? Not a bot, but just other strong player.

**Comment by benjaminpjones** [comment]
Just wanted to chime in, and say that as a user, I find the benefit of multiple logins *way* greater than the risk of cheaters.  The mod team is in place to handle cheaters.  I would expand, but I think this topic is perhaps better suited for the [Forums](forums.online-go.com).

**Comment by BHydden** [comment]
Even if there was only single logon, that is not a hindrance to giving your login details to a strong player to play for you...
