### ISSUE TITLE
Suggestion: make presence indicator in games mean the same thing that it does elsewhere

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1415]
**Is your feature request related to a problem? Please describe.**
In a correspondence game, it's desirable to know if your opponent is online, since then they are more likely to respond to your moves.  However, unlike everywhere else, the "chat presence indicator" displayed in games only shows if the user is on the page. This seems unintuitive; I didn't realize it until after playing more than 500 games.

![image](https://user-images.githubusercontent.com/466760/109439482-55442b00-79e3-11eb-8e37-a3d62cb83c95.png)

Why is it considered relevant if a player stays on the page? For a correspondence game it's normal to click around to other games while waiting for your turn; in fact, the site default is that playing a move navigates you to your next game.  So the indicator will be gray most of the time, even for a user who is online and responding quickly.

For a live game, the indicator is not very useful either; if they navigate away you will see the disconnect timer instead of a gray circle.

The "Users" button at the bottom of the chat lets you see who is present on the page, if you care about that.

**Describe the solution you'd like**
Make the chat presence indicator mean the same thing that it does everywhere - green if the user is on the site at all.

**Describe alternatives you've considered**
As an alternative you can try adding everyone you are in a game with as a friend, open chats with them, or join the same groups as them, but this is a lot more effort than just looking at the indicators on the page.

**Additional context**
There was some discussion on the forum [here](https://forums.online-go.com/t/why-not-online-offline-indicator-also-on-overview-page/34467/5?u=pdg137).

**Comment by anoek** [comment]
The intent of that indicator is that the user has the game page open and is ready to play, the chat indicator means they are on the site - very different things sometimes, and I think it makes sense to keep them distinct.

**Comment by pdg137** [comment]
For the record, I understand that they are very different things; the point I was trying to make was that presence on the site is the more relevant one for correspondence, and for live games we already have the disconnect timer.

Thanks for your consideration!
