### ISSUE TITLE
Corrupted display of double elimination tournaments after first round ends

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1416]
**Describe the bug**
This is what a double elimination tournament page looks like after round 1 ends:

![image](https://user-images.githubusercontent.com/466760/109608371-a1c06100-7ade-11eb-830a-1eaa13ccafef.png)

"[NULL USER]" all over the place and lots of overlapping images and text.  It has been like this for as long as I can remember. Looks just fine after a reload.

**To Reproduce**
1. Load a double-elimination tournament right after it starts.
2. Keep the tab open until round 1 is over.
3. See corrupted display.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)

**More**

Here's another view in a later round, from a browser window that was not logged in, with no extensions enabled:

![image](https://user-images.githubusercontent.com/466760/109609821-bc93d500-7ae0-11eb-9988-6034e14f7866.png)

**Comment by anoek** [comment]
Can you provide a link to this tournament?

**Comment by pdg137** [comment]
This one: https://online-go.com/tournament/72105

But it always looks fine afterward or after a reload. The bug occurs when a round ends while you have the page open.

**Comment by pdg137** [comment]
I found a way to reproduce this bug consistently:

Visit [Handicap Elimination Blast 1](https://online-go.com/tournament/71145) (or any elimination tournament, probably). Observe the correctly-formatted tree:

![image](https://user-images.githubusercontent.com/466760/117579871-d259e380-b0a9-11eb-971f-8f5fa85f27ad.png)

Enter "elimination blast" in the search and select one of the other tournaments:

![image](https://user-images.githubusercontent.com/466760/117579856-c2420400-b0a9-11eb-9236-1d22d4d077e7.png)

Observe the corrupted display:

![image](https://user-images.githubusercontent.com/466760/117579963-53b17600-b0aa-11eb-99cf-3750b51e6ee5.png)

**Comment by pdg137** [comment]
Still happens.

**Comment by dexonsmith** [comment]
> Can you provide a link to this tournament?

This happens to me every time when creating test tournaments (at least in Safari)... if I leave the tournament page open, then when a round ends I get graphical corruption. Seems like there's detritus left behind from the old graph when the new graph is drawn.

**Comment by dexonsmith** [comment]
> I found a way to reproduce this bug consistently:

I missed this comment before; cool repro.
