### ISSUE TITLE
In games player popup, rating/ranks sometimes wrong or out of date

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1420]
**Describe the bug**
In the player popup on a player card in a game, the rating and rank are sometimes wrong or out of date.

**To Reproduce**
0. Log in as pdg137. For me this only happens when I am logged in to my account.
1. Go to https://online-go.com/game/view/31760082 now!
2. Click on Sofiam, who is currently at 1615/4.0k
3. See 1550/5.0k.  According to [the API](https://online-go.com/termination-api/player/126739/v5-rating-history), this actually corresponds to her rank about 2 days ago.

**Expected behavior**
Should show the correct current rating and rank.

**Screenshots**
![image](https://user-images.githubusercontent.com/466760/110228892-ae1b3400-7eb9-11eb-964c-aa00d4e85072.png)

**Additional context**
Observed in latest Brave on Windows and Android.

**Comment by philipkd** [comment]
Possibly related: #1490

**Comment by pdg137** [comment]
I don't know how to reproduce this bug anymore so will close the issue.
