### ISSUE TITLE
Sorting gets broken on 'observe-games' page

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#1435]
**Describe the bug**
Correspondence games are not sorted by rank on "games" page. Also unchecking "bot games" will hide all games by professional accounts. 

**To Reproduce**
1. Go to https://online-go.com/observe-games
2. Click on "correspondence games" and uncheck "bot games" on the filter list
3. Scroll down and see that the sorting does not work and games by pros are hidden thanks to unchecking "bot games"

**Expected behavior**
Seeing the games with strongest average rank at the top of the list. Also i would expect seeing pro games in the list, but for some reason those are counted as bot games. 

**Additional context**
When i started typing this, the very top of corr games list is 1d vs 1d game (https://online-go.com/game/32286941) when "bot games" is unchecked. When including the bot games too, the strongest is 1p vs 5k (https://online-go.com/game/29264655)

**Comment by benjaminpjones** [comment]
Are there examples where pro v pro games are ranked below dan v dan?  I imagine  5k v 1p could be prioritized below a 1d v 1d game if you are looking at min rank.

**Comment by mmartin** [comment]
Probably duplicate of https://github.com/online-go/online-go.com/issues/1351?

**Comment by kobakitty** [comment]
> Are there examples where pro v pro games are ranked below dan v dan? I imagine 5k v 1p could be prioritized below a 1d v 1d game if you are looking at min rank.

No you dont understand, they are not below amateur games when bot games have been filtered, they simply are not there at the first place. Games where one or both players are pros will be filtered by unchecking that "bot games" filter.
