### ISSUE TITLE
Should have Submit button on Live mode when play in mobile phone

### ISSUE THREAD

**Issue by huytbt** [online-go/online-go.com#1436]
Hi there,

Could you please allow Submit button on Live mode when we use mobile phone?
It's really easy to make mistakes when using a mobile phone.
The reason is because the mobile phone screen is quite small.

Best Regards,
Thanks

**Comment by BHydden** [comment]
This is already a feature, and is device specific so easy to have different settings for desktop and movile, just go to https://online-go.com/settings/game and under `Live game submit mode` select `Submit-move button` 😃 hope this helped

![image](https://user-images.githubusercontent.com/28991649/112795767-546aeb80-90ac-11eb-968b-e03895111e30.png)

**Comment by huytbt** [comment]
@BHydden Cool! Thanks you very much
