### ISSUE TITLE
issue of stones graphics in edition mode

### ISSUE THREAD

**Issue by vaurienLL** [online-go/online-go.com#1437]
**Describe the bug**
instead of showing black/white stone, black stone and white stone in analyse mode in a game, it only shows "alternate"

**To Reproduce**
1. Go to a game
2. Click on analyse mode
3. See error

**Expected behavior**
may the stones come back :D

**Screenshots**
![image](https://user-images.githubusercontent.com/79278953/112829018-cc2b1d00-9090-11eb-8401-b537666de225.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : firefox / chrome
 - Version 87.0 / 89.0...

**Comment by anoek** [comment]
Whoops, sorry about that! Fixed.
