### ISSUE TITLE
Wrong message displayed for requesting a full AI review as supporter for someone else's game

### ISSUE THREAD

**Issue by Marnoris** [online-go/online-go.com#1438]
**Describe the bug**
Wrong message displayed when trying to request a full AI review of a game I didn't play. 
It says I must be a supporter to request one while i'm actually one.

**To Reproduce**
1. Go to https://online-go.com/game/32388960 (for example)
2. Click on 'Full AI review' on the right sidenav while being site supporter.

**Expected behavior**
There should be another message such as "You can't request a review for a game you didn't play.".

**Screenshots**
![image](https://user-images.githubusercontent.com/32698216/112869181-24781400-90bd-11eb-90de-fc0c26b4ba29.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 89.0.4389.90

**Additional context**
The http status from the API is 403.

**Comment by anoek** [comment]
Thanks for reporting this, this should be fixed now in the sense that that isn't visible anymore when it's not reviewable.
