### ISSUE TITLE
500 status error when requesting a full AI review on a review

### ISSUE THREAD

**Issue by Marnoris** [online-go/online-go.com#1439]
**Describe the bug**
I'm getting a 500 status error when requesting a full AI review on a review of a game.

**To Reproduce**
1. Go to https://online-go.com/review/642319
2. Click on 'Full AI review' in the right sidenav

**Expected behavior**
I don't really know if it's a possible behavior to request full AI reviews in reviews. 
The expected behavior depends on the answer.

**Screenshots**
![image](https://user-images.githubusercontent.com/32698216/112870077-1c6ca400-90be-11eb-9ef9-81b88375f419.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.90

**Additional context**
In the network tab, the request url is wrong. The game id is zero for the different tries i made. This is the possible explanation of the 500.
![image](https://user-images.githubusercontent.com/32698216/112870252-4f169c80-90be-11eb-8cdb-ab5429a9e406.png)

**Comment by anoek** [comment]
Sorry that item shouldn't have been visible. The full review button should only be visible in games you've played or have uploaded. This has been fixed now.
