### ISSUE TITLE
Turn Indicator Button is broken

### ISSUE THREAD

**Issue by crysanthemus** [online-go/online-go.com#1442]
**Describe the bug**
There used to be a turn indicator near the profile button in the upper right-corner of OGS.
It showed the number of correspondence games where it was my turn.
Clicking on it would conveniently cycle through every game where it was my turn.
It disappeared, but the HTML elements for it remain.

**To Reproduce**
Prerequisites:
* User is playing at least one correspondence game where it is his/her move
1. Login to OGS as the prerequisite User
2. Look in the upper-right corner for the turn indicator

**Expected behavior**
Turn indicator should be visible, show how many correspondence games where it is the User's turn, and be clickable to cycle through those games.

**Screenshots**
![OnlineGoTurnIndicatorBug](https://user-images.githubusercontent.com/38768100/113443581-dfebc180-93b7-11eb-8de2-b6a1598e88cc.PNG)

**Desktop:**
 - Windows 10
 - Chrome version 89.0.4389.114
 - also Edge version 89.0.774.63

**Smartphone:**
 - Galaxy Note8
 - Android version 9
 - Chrome version 89.0.4389.105

**Comment by anoek** [comment]
Should be better again, let me know if it's not
