### ISSUE TITLE
Puzzle export/import

### ISSUE THREAD

**Issue by mih4ajlo** [online-go/online-go.com#1445]
**Is your feature request related to a problem? Please describe.**
Importing existing sgf into puzzles collection. Export puzzle collection as single/multiple sgf file.

**Describe the solution you'd like**
To have an option to import sgf file with a single problem into a single problem of collection.

**Comment by benjaminpjones** [comment]
Just an FYI, you may be interested in this project: https://github.com/merrillite/puzzle2sgf
