### ISSUE TITLE
[API] Game list route does not rerieve all player games

### ISSUE THREAD

**Issue by Judas** [online-go/online-go.com#1447]
It seems that the API does not return all games of players. It did not notice this discrepancy before.

**Reproduction**
1. In-game, most recent game is 5th Apr. : https://online-go.com/player/858250/
2. API, most recent game is 28th Feb. : https://online-go.com/api/v1/players/858250/games?page=last

**Comment by benjaminpjones** [comment]
I can't tell what the default sort order is on the api, but have you tried sorting by date ended?

This is the request the web client makes:

```
https://online-go.com/api/v1/players/858250/games/?ended__isnull=false&ordering=-ended&page=1&page_size=10&source=play
                                                                       ^^^^^^^^^^^^^^^
```

**Comment by Judas** [comment]
You're right, I was under the impression that ordering=started was the default in the API (or at least it was when I did my tests months ago).
Thank you!
