### ISSUE TITLE
Option to mark ko/seki/atari status 

### ISSUE THREAD

**Issue by saizai** [online-go/online-go.com#1460]
# Suggestion: 

*Primarily for new players, as a teaching aid when making puzzles or demonstration videos*, or particularly complex ko rules, allow ko, seki, & atari status to be marked.

# Implementation suggestion:

## Option

In the create game menu, add new checkboxes, default off:
* ⬜ Mark ko status [?] ← ? shows definition of ko, small summary of statuses below, and example of marking
* ⬜ Mark seki [?] ← ? shows definition of seki & dame, and example of marking
  * only enableable to the extent seki & dame exists in the chosen ruleset
* ⬜ Mark atari [?] ← ? shows definition of atari & example of marking

Even if on at the game level (i.e. *allowed* to be on), further allow disabling temporarily and per player in the below game bottom option buttons, or as preference — same as with e.g. analysis.

## Marking

If the option is on, add a distinct CSS class to each of the following. Style can override; suggestions below would be default.

1. Atari
   1. the threatened group
      light red transparent halo around the group as a whole — eg straight lines for orthogonal stones, nothing for surrounded stones within a group
   2. the liberty point
      red transparent circle ○ around the point
2. Ko
   1. a currently prohibited simple ko
      orange transparent circle around the point
   2. a currently prohibited ko under this ruleset, but which wouldn't be prohibited under simple ko (i.e. to hint that it's triggering the SSK/PSK/etc rule), whose hover (or a message below the board) links to the prior move(s) that trigger the ko prohibition
      orange transparent dotted circle ◌ around the point 
   3. a formerly prohibited ko that is now legal to play
      blue transparent circle around the point
   4. a formerly prohibited ko that is now legal to play, but doing so would itself result in a different ko threat [this one is probably not necessary, and hard to define, but may be useful]
       blue transparent dotted circle around the point
3. Seki
   1. all groups that are in a single seki, with each set also receiving an extra index class (seki_1…n) so that they can be colored distinctly
      green transparent halo around each group in the set, same color for all groups in the same set (regardless of owner), different shade of green for each index class
   2. dame points
      gray transparent circle around the point

# Note

I'd be willing to try to code this, but I don't want to waste my time if it'd be rejected as a feature.

So, I'd like to first know whether or not y'all approve (or would change it somehow) before starting.

I've intentionally avoided red-green and blue-yellow as *contrasts*, so it'd be colorblind friendly. Atari can't be confused with seki (because the latter highlights both black and white stones, and doesn't highlight points); orange is colorblind distinguishable from blue.

**Comment by benjaminpjones** [comment]
TBH I don't like that this would add three options to the already-crowded game menu.  But that's just me, you might get more diverse feedback in the forums.

**Comment by shinuito** [comment]
The site forums might a good place to get feedback on the idea, whether people would use it regularly etc. That or even just the main site chat. I think not many people read through all the GitHub issues.
