### ISSUE TITLE
Player unable to play (after API game creation)

### ISSUE THREAD

**Issue by Fraze** [online-go/online-go.com#1464]
A user of OGS reported that they were unable to play a move after a game was created using an API call I sent. The game was created successfully and the API call has worked fine hundreds of times before.

The player is https://online-go.com/player/864544
The games were:
- https://online-go.com/game/33177727
- https://online-go.com/game/33178372

Oddly enough, if the player first passed, then the opponent played, they could then play as seen in this game
- https://online-go.com/game/33178046

The expected behavior is to be able to play. The user was logged in, they tried refreshing their screen (has worked for others), and they tried using another browser as well.

**Comment by AlastairM-E** [comment]
Hi @Fraze,

I don't know how to create a game with the API call. Can you list the steps to do so?

 I checked the [API docs](https://ogs.readme.io/docs/real-time-api), but the docs show how to connect to an existing game, not create.

I am interested in working on this issue, but I need to know how to and be able to reproduce the bug before working on the issue.

Kind regards,
Alastair

**Comment by benjaminpjones** [comment]
@AlastairM-E 

I think @Fraze (Hi Devin!) will still need to share the exact API call they were using, but I wanted to point you to a few resources:

First, have you found the [REST API docs](https://ogs.docs.apiary.io)? The link in your post is to the Live API which is as you noted mostly only in-game stuff.

However I don't think those docs are updated regularly, so you might also check out the source for examples of API usage. One example is [ChallengeModal.tsx](https://github.com/online-go/online-go.com/blob/c0c6093a0343041bb75ca8843cadc5121f3c3570/src/components/ChallengeModal/ChallengeModal.tsx#L454), which uses the `players/%id%/challenge` endpoint to create a game.

**Comment by Fraze** [comment]
Hi @AlastairM-E , not sure if you're asking in attempts to help me with the issue. I've since created hundreds of games using the API and not experienced the issue again. So I was either doing something wrong or the player was.

That being said, @benjaminpjones is exactly right (hi Ben!), I used the challenge endpoint to create matches.
Let me know if you need help with this, but I'm going to close this issue as it doesn't seem to exist for me anymore.
