### ISSUE TITLE
PM box header shrunk, online indicator not aligned in "Chat with friends" box

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1468]
![Screen Shot 2021-05-01 at 10 15 26 am](https://user-images.githubusercontent.com/61894/116765844-73bbb680-aa66-11eb-9e5d-174535be89bf.png)

Note: This change was introduced by the combination of 3dd254cb and  62e6f791 , which were made to fix a problem ~~that I can't reproduce~~  with chat which I can reproduce, so I'll take a look at this!

**Comment by anoek** [comment]
I do believe @GreenAsJade fixed this a bit ago
