### ISSUE TITLE
"score breakdown" incorrectly includes handicap points under Japanese rules

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1469]
The "score breakdown" popups activated by clicking in the lower area of the play boxes seem to know most of the details of scoring.  However, they incorrectly assign compensation points to White for handicap stones under Japanese rules:

Example game: https://online-go.com/game/33079596

![image](https://user-images.githubusercontent.com/466760/116820962-7c76c000-ab2c-11eb-9188-182f44a7ba72.png)

Adding up the points for white, which usually works, you would get 89.5, but actually the score is 83.5.

Points for handicap stones should only be added when using area counting (except not with NZ rules?), [as described here](https://online-go.com/docs/go-rules-comparison-matrix).

**Comment by pdg137** [comment]
Still an issue.

**Comment by dexonsmith** [comment]
Note that the current state isn't even consistently showing the number of handicap stones:

- For Chinese/Ing, it shows both the handicap scoring bonus and the handicap, which happen to be equal.
- For AGA, it shows the handicap scoring bonus (which is `handicap-1`).
- For Japanese/Korean/New Zealand, it shows the handicap (handicap scoring bonus is 0).

PR https://github.com/online-go/goban/pull/146 should fix this (indirectly) by making the `goban.computeScoring()` API consistently return the handicap scoring bonus in the `handicap` field.
