### ISSUE TITLE
CSRF Failed:CSRF token missing or incorrect

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#147]
Conrad Melville wrote in Help:

> When I try to challenge one of the bots (Kugutsu, GnuGo, etc.), I get this message: "CSRF Failed:CSRF token missing or incorrect." What does that mean?

I tried to get more info but he left chat.

**Comment by anoek** [comment]
Yeah we'd need more info, like if he was using the ogs web interface or something different. He shouldn't see that at all with the web interface (and we'd be hearing about it everywhere if it was a systemic problem on the ui I think). For a third party interface, they'd need to submit the CSRF token ;)

**Comment by mlopezviedma** [comment]
@anoek https://forums.online-go.com/t/please-explain-csrf-failed/11253 seems like Conrad is using OGS web interface on latest Firefox. Reopen maybe?

**Comment by anoek** [comment]
Probably fixed via: https://github.com/online-go/online-go.com/issues/158
