### ISSUE TITLE
Total game count in Profile page is off by one

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1483]
**Describe the bug**

The total game count reported over the pie chart in the Profile page is one less than it should be.

**To Reproduce**
Steps to reproduce the behaviour:

* Go to a player's Profile (ideally one with few games)
* Look at the total games counted over the pie chart.
 * See that it is one less than the ranked games they have played.

**Expected behavior**

Correct total displayed

**Additional context**

The problem is that the initial rating RatingEntry is being created on the back-end with the weak-wins value set to -1:

![Screen Shot 2021-05-16 at 11 29 33 am](https://user-images.githubusercontent.com/61894/118383217-09487000-b63b-11eb-9c93-308516dcc7c9.png)

**Comment by GreenAsJade** [comment]
The back-end response for the above game data is:

https://online-go.com/termination-api/player/997910/v5-rating-history?speed=overall&size=0

ended	game_id	played_black	handicap	rating	deviation	volatility	opponent_id	opponent_rating	opponent_deviation	outcome	extra	annulled	result
1621123029	33742861	1	0	1131.75	221.97	0.060004	801151	906.98	64.78	1	null	0	Timeout
1621121924	33742666	0	0	1043.98	272.73	0.060005	997058	624.83	87.95	1	null	0	Resignation
1621121593	33742631	1	0	997.65	310.22	0.060006	978244	1057.22	62.06	0	null	0	Resignation
1621035193	0	0	0	1500.00	350.00	0.060000	0	0.00	0.00	-1	{"special":"initial rating"}	0	


This has two problems in the final row:

1)  The final data column is missing
2) The "outcome" value is -1

The second is the cause of this bug.

**Comment by anoek** [comment]
Well it's not a win or a loss, we need a separate value there. I suppose we could put "null" there or something but -1 seemed just as good, we need to check either way on the client whether that value is ok or not.

**Comment by BHydden** [comment]
The problem is that it persists... no matter how many games you play, `Wins vs weaker opponents` and `total ranked games` will always be one less than it should be.

**Comment by anoek** [comment]
To followup, we probably shouldn't change it to null, just keep it as -1 since iirc Conquest of Go uses this data too, no need to cause churn. 

I'm not arguing the problem, the solution is simple though i think, filter out that special initial rating row

**Comment by GreenAsJade** [comment]
Righto - filter out on front end: will do!

**Comment by BHydden** [comment]
Just out of curiosity, so I understand exactly what you're proposing @anoek 

Are you suggesting
1. When we scrape the completed games list, we start at position 1 instead of position 0 so that the initial rating set isn't included
or, 
2. visually on the front end, display `total games +1` and `wins vs weaker opponents + 1` to counteract the errant data?

**Comment by GreenAsJade** [comment]
I'm not sure what anoek was proposing, but what I am currently intending is

if (extra->special->initial_rating) { set_all_counts_to_zero }

everything else the same.

**Comment by GreenAsJade** [comment]
> Well it's not a win or a loss, we need a separate value there. I suppose we could put "null" there or something but -1 seemed just as good, we need to check either way on the client whether that value is ok or not.

Hmm - actually null would have been better because it would have bombed out (correctly) the convert to integer, flagging that this value is not intended to be used in the normal way in this entry.

**Comment by BHydden** [comment]
I agree with GaJ's position that NULL would have been better than -1 

Possibly something is better still than NULL, but given that it's a result column for a non-game, either NULL or ""  seem appropriate 🤷‍♂️

**Comment by GreenAsJade** [comment]
Well, that much is academic  now that we have detected the issue anyhow :)
