### ISSUE TITLE
Double elimination tournament fails to double-eliminate

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#1488]
**Describe the bug**
Live sitewide 9 x 9 tournament gave winning player a bye in final round, there was no final match, but there was another player with only one loss.  

**To Reproduce**
1. Go to https://online-go.com/tournament/75485
2. Note that donutm was declared winner with a bye in the final round and no final match.
3. Note that alemitrani only had one loss.
4. That can't be right, and is inconsistent with normal behavior where a match-up is repeated if necessary to determine a winner.  

**Expected behavior**
There should have been a final match between donutm and alemitrani.  In general, a double-elimination tournament should continue until every player except the winner has lost twice.  

**Additional context**
Possibly related to #1046 

Thanks

Alex

**Comment by BHydden** [comment]
Apparently, it's very common practice for the final of double elim to secretly be single elim and lots of people think this is fine for some reason. Makes no sense to me either.

**Comment by alexmitrani** [comment]
It's not even consistently like that, either, because many times I have had to play the same person twice in these tournaments, the second time in the final.  In those cases it also seems a bit arbitrary if one person wins one of those matches and the other person wins the other one, because the person with the last victory wins the tournament.  But that is another issue.  I'm not sure how it is programmed but it doesn't seem to be a case of the same logic being applied consistently.

**Comment by BHydden** [comment]
Anyone who loses two games will be kicked but also anyone who loses the final will be kicked, regardless of how many losses they have.

**Comment by alexmitrani** [comment]
That may be so, but how is the final defined as such?  In this tournament donutm's final match was a bye.  

https://online-go.com/tournament/75485

If Sofiam had won then perhaps there would have been a donutm vs Sofiam final.  It isn't clear to me.

**Comment by BHydden** [comment]
oh wow yeah I would say that's definitely a bug.... you and donutm only played the semi final and the final never took place at all... that's very weird

**Comment by alexmitrani** [comment]
Correction.  It seems like I was given gold but donutm won all their games.  Maybe donutm dropped out and that is why I was left feeling the final was missing.  

https://online-go.com/tournament/75485

**Comment by BHydden** [comment]
I think if you withdraw from an uncompleted tournament it says "resigned" next to your name... this just looks like for whatever reason the tournament ended early without playing the final... possibly a bug due to donutm having already played both of you and tricking the server into thinking the final had already been played? not totally clear from what I can see, maybe @anoek  will have more details about why it ended on the back end

**Comment by alexmitrani** [comment]
Interesting.  I figured out the details of the podium: 

gold - alemitrani
silver - Sofiam
bronze - Atorrante  

![Screenshot_20210523-204317](https://user-images.githubusercontent.com/27974470/119282442-abea8b00-bc07-11eb-91d1-b6e6eeb91c3c.png)

What happened to donutm who won all their games?


I can't see  anything  that says  they  resigned.  I asked them in chat and am awaiting their reply.

**Comment by shinuito** [comment]
The api suggests that donutm resigned form that tournament.

https://online-go.com/api/v1/tournaments/75485/players

`"resigned": true,`

I know it's a bit random to comment so far on, but it did seem a bit unresolved :)

**Comment by dexonsmith** [comment]
(Found this because I'm looking at old double-elimination bugs.)

> The api suggests that donutm resigned from that tournament.

In that case, seems like we should close this as resolved!
