### ISSUE TITLE
Leaderboards broken

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#1489]
**Describe the bug**
The OGS leaderboards appear to be broken.  

**To Reproduce**
1. Go to https://online-go.com/leaderboards
2. Click on some of the top players.
3. Note that many have not played in live tournaments for a long time.  E.g. Quackๆ in the live 9 x 9 has not won gold in 12 months.   According to the most recent documentation there is supposed to be a 6-month rolling window.  
4. Also note that many players with many recent tournament wins to not appear on the leaderboards.  E.g. Sofiam, Atorrante, He Who Walks in Shadows.  

**Expected behavior**
I expect the leaderboards to present an up-to-date ranking of the best and most active players in each type of tournament. 

There are several options: 
1) Leaderboard behaviour could be fixed to be  consistent with most recent documentation: https://ogs.readme.io/docs/leaderboards
2) Leaderboard behaviour could be otherwise improved and documentation updated
3) Leaderboards could be removed from the site. 

Any of these would be much better than doing nothing and leaving it as it is.  

**Additional context**
There is a forum discussion of this issue here:
https://forums.online-go.com/t/fix-or-remove-ogs-tournament-leaderboards/36028

Thanks

**Comment by benjaminpjones** [comment]
Fixed (well actually just removed) by #1804

**Comment by alexmitrani** [comment]
Thanks!
