### ISSUE TITLE
Different ratings displayed in different places of OGS

### ISSUE THREAD

**Issue by sphynx** [online-go/online-go.com#1490]
**Describe the bug**
Ratings next to the avatar in the top right corner still shows outdated rating. So on the profile page I can see one rating and when I click on the top left corner on the avatar -- it shows another rating (presumably still not updated from the previous game).

**To Reproduce**

1. Play a game
2. Click on the avatar rating next to "sphynx [10k]" -- see, for example, 9.9k +- 1.5
3. Go to the main profile page: https://online-go.com/player/992656/ -- see 10.3k +- 1.4

Note that after some time -- like 5-10 minutes, those ratings are synchronized and start to show the same number.

**Expected behavior**
Ratings accesse via avatar and via main profile page should be the same after the game.

**Screenshots**
Screenshot is available here: http://tinyurl.com/68497tdc

**Desktop (please complete the following information):**
 - OS: both macOS and iOS
 - Browser: Firefox
 - Version: 88.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2
 - OS: iOS 14.4.2
 - Browser: Firefox

**Comment by philipkd** [comment]
Interesting. I wonder if this is related to #1576.
