### ISSUE TITLE
Unreadable AI evaluation text when using dark theme boards

### ISSUE THREAD

**Issue by abaisero** [online-go/online-go.com#1491]
**Describe the bug**
When using one of the three darkest board themes, it becomes very hard if not impossible to read the AI evaluation values on the board.

**To Reproduce**
1. Go to the theme selection menu, and select the dark gray board.
2. Go to a game which has an AI evaluation.
3. Have hard time to distinguish the values on the board.

**Expected behavior**
I'd expect that the text with which these values are written are adjusted to have maximum contrast with the board theme.

**Screenshots**
This is how it looks with one of the light themes:
![image](https://user-images.githubusercontent.com/1794938/119901079-6a155980-bf13-11eb-866d-97f2a35d649e.png)

This is how it looks with one of the dark themes:
![image](https://user-images.githubusercontent.com/1794938/119901130-80231a00-bf13-11eb-882c-3b4c2ec5205b.png)

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Firefox
 - Version 86

**Comment by AlastairM-E** [comment]
Hi,

Would I be able to try fix this issue?

I would be changing the text to white so the text is more understandable.
![image](https://user-images.githubusercontent.com/47124313/134065693-d3740d70-165b-4d3f-b758-e07829ba20d3.png)

Examples of similar issues below has been given. Can I change them all to have white text as well?
<hr />
Similar issues can be see on the dark blue board and granite grey board:
![image](https://user-images.githubusercontent.com/47124313/134052738-8cd8902d-a1f7-4f3e-98ec-e36fef8bf8a5.png).
![image](https://user-images.githubusercontent.com/47124313/134065459-39a58e18-a375-41fb-b8af-493ece54c31a.png)

Lesser degree to the bright light blue board:
![image](https://user-images.githubusercontent.com/47124313/134065597-82eb351c-1de6-4f10-8b35-897523a8a08d.png)

**Comment by anoek** [comment]
Yep definitely you can fix it. I believe the relevant code will be here: https://github.com/online-go/online-go.com/blob/devel/src/views/Game/AIReview.tsx#L382

**Comment by AlastairM-E** [comment]
Ok, thanks for the link 😄.

**Comment by AlastairM-E** [comment]
Hi, I need a little guidance on this issue (I know it is a minor change, but I am finding it difficult to locate where I need to make the code change):

- Would the code change definitely be in AIReview.tsx, or would it be one of the stylus files as part of the css or goban library?
- Do you know what the color code is for the writing, e.g. for the dark board, would it be #888888 hex code is something else?

<hr />

## Context

* I have checked out the link and it does seem to set the color of the text there.
* However, it does have a set mark property, which I traced to the goban library.
* The goban library has a grey color of #888888, I replaced all of those in the chrome overrides, I could not see the change working. Chrome overrides was working correctly (see below).
![image](https://user-images.githubusercontent.com/47124313/135773195-1100fb7b-1cc1-4117-adb8-867f3da8026e.png)

**Comment by anoek** [comment]
I'm sorry, I screwed up in my pointer previously. The file I pointed you to is just for changing the color of the blue circle, which isn't the problem, you want where the text color is changed.

You're right with your digging that it'll be in the goban library, specifically https://github.com/online-go/goban/blob/main/src/themes/board_plain.ts and https://github.com/online-go/goban/blob/main/src/themes/board_woods.ts 

To do development on the goban library and see the results quickly in your ogs development environment, we use the `yarn link` magic to get those linked up so we're not viewing a bundled version of goban.

In your goban directory run
```
yarn link
```

Then in the online-go.com ui directory run
```
yarn link goban
```

In one console window in your goban directory run `npm run dev` (or just `make` which does the same thing)

In another console have your online-go.com build system up like you've presumably had with `npm run dev`

Now, modifications to the goban library should be visible to you.

If it's just changing the text value for the entire board, then it should be a matter of just twiddling those values in those theme files. If you want to conditionally draw different colors then you'd add a new color(s) to the themes and update the rendering code in the `GobanCanvas.ts` file, if you go down that route let me know if you want a rundown of where that'd happen and whatnot.

**Comment by AlastairM-E** [comment]
Hi Anoek,

Pull request for changes is on goban repository ([link here](https://github.com/online-go/goban/pull/42)) for to decide to merge.

It has a summary of the change and pictures relevant for the change.

Thank you for your direction on where the change was and how to use yarn link on the goban package. I had some trouble getting the yarn link to work at first, but once I figure out I need to fork then git clone goban separate rather than use the node_modules goban in online-go, I was all set.

Kind regards,
Alastair

**Comment by anoek** [comment]
Thanks for the fix @AlastairM-E !
