### ISSUE TITLE
Forked games start with zero (0) prisoners

### ISSUE THREAD

**Issue by jivanpal** [online-go/online-go.com#1498]
**Describe the bug**
When a game A is forked to create a new game B, game B will report that both players have captured 0 stones, even if that is not the case in game A.

**To Reproduce**
1. Start a game and play it, with each player capturing some stones.
2. Fork the game at some point. The forked game reports that each player has 0 prisoners.

**Expected behavior**
The forked game ought to report the same number of prisoners as the initial game.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Should not be applicable, but reporting this info anyway:

 - OS: macOS Catalina 10.15.7
 - Browser: Chrome
 - Version: 91.0.4472.114

**Additional context**
Example games:
- Source game (white accidentally resigned): https://online-go.com/game/34851457
- Forked game, forked from the penultimate move of the above source game: https://online-go.com/game/34853646

In the source game, at the point of the fork, black has 7 prisoners, white has 2 prisoners. After forking, black captures an additional 6 prisoners, and white an additional 2 prisoners. We would expect the totals of 13 and 4, respectively, to be used when computing the winner, but instead the figures of 6 and 2, respectively, are used.

**Comment by mmartin** [comment]
Duplicate of #508?

**Comment by BHydden** [comment]
> * Source game (white accidentally resigned): https://online-go.com/game/34851457
> * Forked game, forked from the penultimate move of the above source game: https://online-go.com/game/34851457

you linked the same game twice FYI

The forked game appears to be https://online-go.com/game/34853646

which for some reason your opponent threw away their lead by playing 3 times needlessly in their own territory???

**Comment by jivanpal** [comment]
@BHydden oops, you're right, that is the actual forked game — fixed in OP.

> for some reason your opponent threw away their lead by playing 3 times needlessly in their own territory?

We are beginners 🙂 Also, no points are lost by black since we are using area scoring, not territory scoring.

**Comment by jivanpal** [comment]
@mmartin I agree, it is a duplicate. Closing in favour of that one.
