### ISSUE TITLE
Malkovich log message is too long

### ISSUE THREAD

**Issue by lemurek** [online-go/online-go.com#150]
### Summary

Key part of Malkovich log message is invisible

### Environment

 * Operating system: any
 * Browser: any
 * Browser Version: any

### Steps To Reproduce:

1. Start a game
2. Click 'Chat' to switch to Malkovich log

### Additional Information:

![screen shot 2017-03-12 at 10 01 11](https://cloud.githubusercontent.com/assets/12175058/23831343/1ee533ee-0717-11e7-9010-5fae58c8447b.png)

How about 'Notes become visible after the game' ?

**Comment by arnaudgo** [comment]
Hello @lemurek :)

 Based on your screenshot and feedback:

'Notes become visible after the game' are composed of 35 characters

But the truncated text 'Leave a note that will only be v' is only 32 characters.

As a suggestion, 'Hidden until the game ends' are only 26 characters.

:)

Arnaud

**Comment by lemurek** [comment]
Fair point :) I'd prefer a positive phrasing which would highlight how the notes could be used. How about:

- "Memo, visible after game"
or
- "Visible after the game"
