### ISSUE TITLE
Old username lingers on observe-games and playercards

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#1502]
**Describe the bug**
Old username from the start of the game is shown on Games page and playercards despite user having changed the name long ago.

**To Reproduce**
1. Go to https://online-go.com/observe-games or to the chat and open the ongoing games list at the top
2. Click on correspondence games 
3. Scroll down to until you find games where at least one user has changed their name after the game has begun, for example these two below.

![Screen Shot 2021-07-03 at 13 52 50](https://user-images.githubusercontent.com/29932807/124352201-b9803100-dc07-11eb-8861-05c41792c596.png)
![Screen Shot 2021-07-03 at 14 33 40](https://user-images.githubusercontent.com/29932807/124353004-75435f80-dc0c-11eb-8627-f83be901ef42.png)

Doesn't matter whether you're using list view or thumbnail view, same thing happens in both
https://online-go.com/game/16567891
https://online-go.com/game/16567892

Click blacks username for the small playercard thingy, see what name is shown for them

![Screen Shot 2021-07-03 at 13 54 15](https://user-images.githubusercontent.com/29932807/124352334-59d65580-dc08-11eb-9366-12837d359657.png)

**Expected behavior**
I would expect to see the current username being shown in both games list/thumbnails at observe-games page and in the small playercard which opens when clickin on users name. 

When seeing those same games from users profiles, the current username is shown on list /thumbnail, so this seems to be limited to Games page, games seen on chat view, and on the playercards when you navigate to the game via either of those routes.

**Comment by anoek** [comment]
This kind of thing happens in a number of places because it's a pita to get fresh data to some of those places. It doesn't seem to be *that* big of a deal, so closing as wont fix for the foreseeable future.

**Comment by BHydden** [comment]
The main place it's a problem is offensive or vile names in English chat channel, but it's not the end of the world to PM you to reset the server when that happens.
