### ISSUE TITLE
Ability to report private messages

### ISSUE THREAD

**Issue by RubyMineshaft** [online-go/online-go.com#1507]
It would be great to have a report button in the PM window that provides moderators access to the conversation being reported.  

We currently have to rely on players to copy and paste the conversation or provide a screenshot, which opens the possibility of the reporter spoofing parts of the conversation or removing things.

**Comment by BHydden** [comment]
YES! I don't know how we didn't think of this sooner 😅

**Comment by RubyMineshaft** [comment]
I've been poking around the code, and I think I should be able to implement this if a `conversation` text column is added to the report table. 

The object returned for reports currently looks like this:
```json
{
    "id": "86568",
    "created": "2021-08-02 22:33:56.557385+00:00",
    "updated": "2021-08-02 22:33:56.557400+00:00",
    "state": "pending",
    "source": "user report",
    "reporting_user": { },
    "reported_user": null,
    "reported_game": 35834434,
    "reported_review": null,
    "url": "",
    "moderator": null,
    "cleared_by_user": false,
    "was_helpful": false,
    "reporter_note": "",
    "moderator_note": "",
    "system_note": ""
}
```

@anoek Would it be possible to add a `conversation` field?

**Comment by anoek** [comment]
@RubyMineshaft Added. It should accept any JSON blob you put in there, array, object, string, whatever fits your needs best. I did a quick test that adding it to the posted object works, and it shows up on the pushed incident report data. If it's not provided, it defaults to `null`.

It's active on the beta site, not on the live site yet of course.

**Comment by anoek** [comment]
And thanks for tackling that, much needed :)

**Comment by RubyMineshaft** [comment]
Awesome, thanks! I'll get to work 🙂
