### ISSUE TITLE
Game listing. 

### ISSUE THREAD

**Issue by lemurek** [online-go/online-go.com#151]
### Summary

Game listing isn't useful. 

### Environment

 * Operating system: Any
 * Browser: Any
 * Browser Version: Any

### Steps To Reproduce:

1. Go to 'Watch'
2. Click 'Show 20' 
3. Try to think about how the screen can be used. 

### Additional Information:

![screen shot 2017-03-12 at 11 27 54](https://cloud.githubusercontent.com/assets/12175058/23831495/a34865cc-071a-11e7-976d-f0b1d0f7e984.png)

Followup in comments.

**Comment by lemurek** [comment]
In order of subjective relevance

A and B - Player strength and names - the key information is mixed with timing data that's constantly changing. Little bit of chaos.
C - This is slightly confusing, as numbers in the first column of the table usually mean something else
D - Game description is important, but because their length is variable it doesn't look good right now
E - Remaining time in game for each player. Why would I need this information on Game List screen? They make sense in miniatures view where they resemble 'mini' game screens, but not here.

What information is missing:
1. Friends/tagged players (you could be interested in your friends playing)
2. Time setting of a game (it's easier to grasp than E, and this could be your criteria of choice)
3. Number of viewers (oh! something interesting is happening here)

**Comment by lemurek** [comment]
One simple improvement that should be easy to implement would be to reverse the order of last 2 columns (White and his time), and align 'White' to the right.

**Comment by anoek** [comment]
I don't disagree that this view could be improved upon, but I'd like the discussion for this to happen on the forums so it's a bit more visible to the community. Once there's been some form of consensus feel free to re-open an issue.
