### ISSUE TITLE
iframe for games no longer working

### ISSUE THREAD

**Issue by Fraze** [online-go/online-go.com#1513]
**Describe the bug**
When displaying an OGS game in an iframe the game loads/reloads continuously (causing a negative visual experience and an inability to view the game).

**To Reproduce**
1. https://www.iframe-generator.com/
2. Input the url of any game (eg. https://online-go.com/game/36191471)
3. Preview the game via an iframe
4. See error (game reloads continuously) 

**Expected behavior**
Game would load smoothly without issue.

**Screenshots**
https://www.loom.com/share/e2cd3dd99ca14da4bf8a1b9bc474e133

**Desktop (please complete the following information):**
 - Browser: chrome and firefox

**Additional context**
My best guess is that the issue has something to do with the ai-review loading. This issue did not used to occur a few months ago. I'm not sure when it started to occur, but it isn't recent.

**Comment by anoek** [comment]
No hunches as to why this is happening. An interesting note though, when left open for a minute or so, I eventually hit a `429` when requesting the config endpoint, at which point the reloading stopped and things loaded fine (including the AI review)

**Comment by Fraze** [comment]
Yeah, I've also noticed that it will eventually stop reloading. It seems to be a hit and miss as well.
In fact the first time I went to film the issue, it only reloaded twice and then worked fine.

Thanks for looking into it! Hopefully we can uncover the mysterious cause.
