### ISSUE TITLE
Create custom game button unclickable on chrome mobile.

### ISSUE THREAD

**Issue by davidbstein** [online-go/online-go.com#1515]
**Describe the bug**
The chrome mobile browser places navigation controls at the bottom of the window which overlaps the create button in the custom game dialogue. Because the game option box is scrollable there is no way to scroll to the button and click it. A workaround is to scroll down the page before opening the custom game dialogue

**To Reproduce**
On either android or iOS chrome browser, open the play tab and, before doing any scrolling, press the create button.

**Expected behavior**
The create button is visible on the screen Or it is possible to scroll to the button.

**Screenshots**
![C6C5A357-4FE0-4F54-9FE3-339B46E983B8](https://user-images.githubusercontent.com/1490241/129490051-baf58fea-f02e-4682-b55a-fadd0a054645.png)

**Desktop (please complete the following information):**
 - OS: Either android or iOS
 -  device: reproduced on a pixel3 and iPhone 12 mini.
 - Browser: chrome

**Additional context**
I am happy to do my best effort to write a patch, but this app is really beautiful and functional and I don’t think I have the aesthetic sense for it.

**Comment by AlastairM-E** [comment]
Hi @davidbstein,

Sorry for the delayed reply, I was installing Xcode on a old-ish mac, which was "fun".
I can't reproduce the Xcode ios simulator, since I can't install apps on the simulated phone.

As I can't reproduce the bug, I cannot work on the issue, it is open to anyone else who can.

Kind regards,
Alastair
