### ISSUE TITLE
Oauth2 Flow (Authentication/Authorization)

### ISSUE THREAD

**Issue by Fraze** [online-go/online-go.com#1516]
**Is your feature request related to a problem? Please describe.**
Some users of my site claim to be deeply disturbed by the current auth-flow when integrating their BadukClub account with OGS (They dislike providing me with their username and password so I can get their OGS token). In general though, it certainly would be better practice to simply follow the current standard for OAuth2 flow authentication.

**Describe the solution you'd like**
I actually don't think that this would be too much work to implement.
1. I'd send users to a new OGS url where they authenticate their account (steps 1-3)
2. If authentication is a success they are sent back to my website and the url contains some params that expire shortly (steps 4-6)
3. My site interprets the params, sends OGS a request for the user token with those params (step 7)
4. OGS does the normal oath api stuff here and I am returned a token and expiration (etc) (steps 8,A-D)

![image](https://user-images.githubusercontent.com/19158908/129654160-d014f7c3-de8d-45fb-bd11-833d04a58a76.png)

**Comment by anoek** [comment]
From https://online-go.com/developer click the 'OAuth2 Application Manager' to generate that oauth stuff, that's some very old code and written by matburt years ago, but it's all baked in to django so should work good I think.

**Comment by Fraze** [comment]
I'm embarrassed, I thought for sure I had seen on the forums that this
wasn't possible. I don't know why I didn't just check the OAuth2
application manager and try stuff out. Thank you Akita.

**Comment by Fraze** [comment]
@anoek Do I need to do anything to list multiple Redirect URIs in the the 'OAuth2 Application Manager'?

Currently I've tried just returning between them. It seems to work fine for when I send a user to get their 'code", but then fails when I send their code to get a token.

I've found a workaround by programatically choosing between two different client ID's for the two different url's I'm making calls from (aka the dev and live versions), so this isn't critical, but it's certainly annoying.

**Comment by anoek** [comment]
I'm not really sure, matburt was the one who set all that up, we're using https://pypi.org/project/django-oauth-toolkit/ to power all of that though if that helps.

**Comment by Fraze** [comment]
Thank you, that was helpful! Unfortunately for me, it looks that this is a [known bug](https://github.com/jazzband/django-oauth-toolkit/issues/867).

**Comment by Fraze** [comment]
I figured it out! I needed to send specify the redirect_uri in the params of my token call.

**Comment by anoek** [comment]
Awesome 👍
