### ISSUE TITLE
Chat in sgf with variation shows up as \[object Object\]

### ISSUE THREAD

**Issue by Dorus** [online-go/online-go.com#1518]
My bots show chat messages that include winrate, playouts etc.

Looks like this:

![afbeelding](https://user-images.githubusercontent.com/4461459/130126845-ad3cad8d-2eda-4991-b36f-9987eb356b1d.png)

If you download the sgf, you see this:
```
C[15bTurboLeela: \[object Object\]
]
(;W[rp]
(;B[om]
C[15bTurboLeela: \[object Object\]
]
(;W[ri]
(;B[si]
C[15bTurboLeela: \[object Object\]
]
(;W[sh]
(;B[hh]
C[15bTurboLeela: \[object Object\]
]
(;W[cf]
(;B[ja]
C[15bTurboLeela: \[object Object\]
]
(;W[ia]
C[15bTurboLeela: Thanks for playing]
```

**Comment by anoek** [comment]
This is where the issue is and can be fixed, we just need to do something smart with `message` when it's an object. 

https://github.com/online-go/goban/blob/a36c53c93ffdbc1f1d8452ba36e4ba68e87140eb/src/MoveTree.ts#L978-L979
