### ISSUE TITLE
Using the API in a script and getting my elo score over time

### ISSUE THREAD

**Issue by CassenH** [online-go/online-go.com#1525]
This is actually a question. I hope it's ok to ask here. So I want to use the API to get my elo score over time (the data that is displayed in the line graph on the profile page).

I have two issues. 

1. How can I authenticate myself inside a simple script? I do not have a redirect uri or an app. Not sure how I would set an application specific password for myself.
2. What is the correct endpoint for the elo score?

**Comment by anoek** [comment]
No auth required, just fetch https://online-go.com/termination-api/player/<ID>/v5-rating-history?speed=overall&size=0
