### ISSUE TITLE
Duplicate key error message when joining a game (that has already started)

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#153]
I assume the match already started by the time my trying to join the match made it to the server. The result popup I got back said:

> duplicate key value violates unique constraint "go_app_player_games_player_id_44dc93fcb6f523d0_uniq"
> DETAIL: Key (player_id, ga

I assume that sort of situation should be detected and a clean error message sent back to the player.

**Comment by trezker** [comment]
Seconded. I got it today just a couple minutes ago.

**Comment by anoek** [comment]
Going to not worry about this one, afaik this has pretty much gone away visibly since we've gotten the server a bit more stable, and shouldn't really be an issue after automatch rolls out anyways.
