### ISSUE TITLE
"Your color" = "Automatic" assigns black to the stronger player. 

### ISSUE THREAD

**Issue by steinbeck** [online-go/online-go.com#1533]
When I (16k) used "Create Challenge" with "Your color" = "automatic", the challenge was accepted by a 14k player who received black as the auto-assignemet. The player was stronger than me in all categories (9x9, 13x13, 19x19). I think this should not have happened. 

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Browser Chrome Version 94.0.4606.71 (Official Build) (x86_64)

**Comment by AlastairM-E** [comment]
Due to the difficult in reproducing the issue, I am not working on it any more. It is open to anyone else who wants to work on this issue.

**Comment by benjaminpjones** [comment]
If this issue is not reproducible, can it be closed?

**Comment by steinbeck** [comment]
I guess closing is fair, given the difficulty in reproducing this.
