### ISSUE TITLE
API endpoint to query an entire collection's solved state for a/the player

### ISSUE THREAD

**Issue by bqv** [online-go/online-go.com#1550]
Working on code for the android app, I assume you'd rather not get the puzzles/%%/solutions endpoint spammed for an entire collection at once since they can be over 1000 in count

**Comment by anoek** [comment]
That's correct, you'll hit some rate limits pretty fast doing that.

I'll look into it when I get a chance, doing that for the main site is something I've wanted to do for awhile too.
