### ISSUE TITLE
Feature request: LibreJS compliance

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1554]
Since OGS is released under a free[^1] licence, I think it would be nice to have it work with LibreJS.  This would involve adding a LibreJS-detectable table that links scripts to repos.  More info at [LibreJS: Setting Your JavaScript Free](https://www.gnu.org/software/librejs/free-your-javascript.html).

[^1]: as in freedom

**Comment by anoek** [comment]
Sure? It's not quite clear to me how this manifests for anyone, but I'm not opposed to it or anything

**Comment by benjaminpjones** [comment]
Basically there's this plugin called LibreJS (made by GNU) that blocks all non-free JS.  It's kind of smart in that it knows about popular free third-party scripts.  Unfortunately it's not smart enough to detect that online-go.com is libre, and so the JavaScript doesn't run unless a LibreJS user manually whitelists:

<img width="1081" alt="Screen Shot 2021-11-28 at 8 30 11 AM" src="https://user-images.githubusercontent.com/25233703/143769924-14fa027d-f472-4255-a3ae-32dee01512f8.png">

I thought the process to get LibreJS to accept would be relatively simple, but I looked into it last night, and it seems like it's nearly impossible for webpack projects because there's no way to automatically figure out all the licenses in all the scripts that go into the bundle[^1].  Closing as infeasible 😕

[^1]: Same issue on other notable projects: [GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/15196), [Pleroma](https://gitlab.com/gitlab-org/gitlab/-/issues/15196), [PeerTube](https://github.com/Chocobozzz/PeerTube/issues/1254)

**Comment by TechnologyClassroom** [comment]
If anyone wants to work on this issue, there is a [generate-weblabels-webpack-plugin](https://forge.softwareheritage.org/source/swh-web/browse/master/assets/config/webpack-plugins/generate-weblabels-webpack-plugin/) from Software Heritage.
