### ISSUE TITLE
Game chat user list sort by rank broken

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#1558]
**Describe the bug**
Game chat user list sort by rank broken

**To Reproduce**
1. Go to game
2. Click on chat users
3. See wrong sorting

**Expected behavior**
Pros top, then dans, then kyus.

**Screenshots**
![Screenshot_20211203-203540_Brave.jpg](https://user-images.githubusercontent.com/28991649/144588803-2ee0a87f-0b2b-4267-80af-2cb17f698cf8.jpg)![Screenshot_20211203-203609_Brave.jpg](https://user-images.githubusercontent.com/28991649/144588827-beca164e-1238-4ebe-9d6b-d79d129652da.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A90 5G
 - OS: Android 11
 - Browser Brave (Chromium)
 - Version 1.32.112

**Comment by anoek** [comment]
Huh, wonder when that broke

**Comment by mmartin** [comment]
This is broken:
https://github.com/online-go/online-go.com/blob/9aed1cc08cd7afc3df55078c3ba3cc4f91bf451f/src/lib/misc.ts#L774-L785

Example:
```javascript
let test = [];
const cmp = (a, b) => a.localeCompare(b);

insert_into_sorted_list(test, cmp, 'b');
insert_into_sorted_list(test, cmp, 'c');
insert_into_sorted_list(test, cmp, 'a');

console.log(test); // [ 'a', 'c', 'b' ]
```

**Comment by BHydden** [comment]
Fix is already live ❤ great work everyone!

![Screenshot_20211204-193918_Brave.jpg](https://user-images.githubusercontent.com/28991649/144704904-8116835d-a1f8-410f-9721-180c1022e9ba.jpg)![Screenshot_20211204-193948_Brave.jpg](https://user-images.githubusercontent.com/28991649/144704907-e0628a40-8d69-468e-87ad-1a0aef199b34.jpg)
