### ISSUE TITLE
Tournaments in which the user participated but already ended are showing up in the main page

### ISSUE THREAD

**Issue by FlyingPumba** [online-go/online-go.com#156]
This is not happening in the user's profile (only active tournaments show up).

**Comment by anoek** [comment]
Hm, I'm not seeing it but I could be looking in the wrong place. You're talking about the overview page, when you first log in? Which tournament(s) are showing up for you that have ended?

**Comment by FlyingPumba** [comment]
Sorry, I think I saw an ended tournament, but now I can't find it. In the overview screen there are some tournaments listed:

![screenshot from 2017-03-13 15-08-37](https://cloud.githubusercontent.com/assets/1159078/23868752/62a7b618-07ff-11e7-8dd0-74c66514197d.png)

I thought it was the tournaments I'm currently involved, but there are many more which I'm not participating. I don't know if this is an intended feature or not, but it's a bit confusing.

**Comment by Saxmaam** [comment]
I'm not sure what "main page" means, but I have zombie tournaments on my profile page and in the chat room list:
https://online-go.com/tournament/2872
https://online-go.com/tournament/11607
https://online-go.com/tournament/11608
https://online-go.com/tournament/3128
https://online-go.com/tournament/3253

**Comment by BHydden** [comment]
resolved.
