### ISSUE TITLE
Can't register new account

### ISSUE THREAD

**Issue by robodendron** [online-go/online-go.com#1563]
Not sure if this is the right place, it's kind of hard to reach anyone when I don't have an online-go account.
I tried signing up by email which always gave me a "username already taken" error message, even with obscure usernames. When using Google sign-in there was a Server Error 500 or something like that. I also tried using a VPN to no avail.

**Comment by BHydden** [comment]
Weird, sorry about that. What username do you want? I (or someone else on the mod team) can make the account for you and then you can email me to get the password (which of course you can change after loggin in) if you wish. Not sure what else to do really if no names are working at all. 

Can I just confirm you are on the Sign Up page and not the Log In page?

**Comment by BHydden** [comment]
The link for sign up is https://online-go.com/register

The two pages look pretty similar though.

**Comment by robodendron** [comment]
Yes, weird but I asked a buddy of mine and he had the same issue. Definitely on the login page too!
If it's just server hiccup then I'm fine with waiting until it is fixed. But if it's no trouble I'd also be grateful if you could make an account! Name doesn't matter too much, anything random is fine, even letters and numbers. Where can I find your email address?

**Comment by anoek** [comment]
@robodendron Whoops, thanks for letting me know. Should be fixed now!

**Comment by robodendron** [comment]
> @robodendron Whoops, thanks for letting me know. Should be fixed now!

Works! Thanks both of you!
