### ISSUE TITLE
Two ladder games with the same opponent

### ISSUE THREAD

**Issue by juanchodepisa** [online-go/online-go.com#157]
### Summary

There's a player who appears to be playing two ladder games with the same person simultaneously, within the same ladder:
* https://online-go.com/game/7970173
* https://online-go.com/game/7970177

### Environment

 * Operating system: n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:

1. Not
2. a
3. clue

**Comment by mlopezviedma** [comment]
May this be related to the server upgrade? In fact, there are still some finished games stuck in ladders, which take away a challenge to those users.

**Comment by anoek** [comment]
This actually happened to me too, but it was a few weeks before these two games.

@mlopezviedma can you send me some links to those games? Perhaps open another issue for those?

**Comment by anoek** [comment]
I'm not seeing this happen these days. I suspect the problem could still exist, but I haven't been able to reproduce it. I'm going to chalk it up to high load and things failing in various small ways that would take more effort to debug and fix than it's worth (it's not *that* big of a deal when it happens...)

**Comment by arnaudgo** [comment]
Hello,

I'm very sorry to comment on a closed bug with a label wontfix but I just saw it and the opponent doesn't appear with the same rank. See the enclosed screenshot.
As you correctly says, it's not very critical but maybe it's a side-effect of another problem and not the consequence of high load for example.

Arnaud

![ladder_games_same_opponent_different_rank](https://cloud.githubusercontent.com/assets/26174230/25540929/b3321c36-2c44-11e7-98dd-85e12951e3a3.png)
