### ISSUE TITLE
Won't let me play

### ISSUE THREAD

**Issue by jeromej123** [online-go/online-go.com#1572]
**Describe the bug**
The moderator of the Go OGS site told me to post a bug report based on how I explained the problem.  Lately when I log in as usual and try to start a game it lets me make my first move and then nothing happens.  The other player's move does not appear.  The moderator Kosh said I should not use the site anymore until I get someone on the forums to help me because my account is, in his words, very dysfunctional.  He said to post the issue on the regular forum but there was a notice there directing me to not post bug reports there, but to come here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]- Chrome OS (not sure what version but it is an older chromebook)
 - Browser [e.g. chrome, safari]- Google Chrome
 - Version [e.g. 22]-93.0.4577.107 (Official Build) (64 bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benjaminpjones** [comment]
Have you tried playing games on other devices or browsers? Does that work?

Are you sure your opponents are playing a move? Are you able to talk to them via chat when this happens?

IMO, you will have better luck in the forums. There isn't really enough information here to find or fix a bug.

**Comment by anoek** [comment]
Feel free to re-open if you want to provide some of the details requested (browser usage, console output, etc.)
