### ISSUE TITLE
Cannot play games

### ISSUE THREAD

**Issue by piskvorky** [online-go/online-go.com#159]
After I fill in my rank and click "Finish" at https://online-go.com/play, I get a weird empty dialog pop-up -- only a red cross at the top, and blue "OK" at the bottom. Clicking neither seems to get me past the "play" page.

In the console (OS X, Chrome 56.0.2924.87 64-bit) I see the error `The requested URL /api/v1/players/-90579 was not found on this server.`.

<img width="1440" alt="screen shot 2017-03-13 at 13 57 45" src="https://cloud.githubusercontent.com/assets/610412/23901990/d15d4042-0902-11e7-87ff-b240f08adfff.png">

Is that on purpose? Am I doing it wrong?

I found https://online-go.com/play through googling, because on visiting online-go.com it wasn't clear to me how to actually play a game on OGS. There's no information at all. I could only spectate games.

**Comment by anoek** [comment]
Do you see any error messages when you attempt to sign in?

**Comment by piskvorky** [comment]
I never attempted to sign in. Is that required?

What is the connection between signing in and playing games -- does OGS allow guests?

**Comment by anoek** [comment]
We don't currently support guest playing, though it's something we'd like to add eventually. But currently, you have to create an account.

**Comment by piskvorky** [comment]
OK. Out of curiosity -- is the page from the OP supposed to work, or is this its "desired behaviour"?

**Comment by juanchodepisa** [comment]
I think this behavior is confusing though. There's no reason to have that page be accessible without signing in, if it won't really allow you to do anything.

Maybe the error message could be more specific? (Like "You have to sign in with an OGS account in order to play")

**Comment by anoek** [comment]
Yeah you shouldn't have been able to get to that page, that's a bug
