### ISSUE TITLE
API Documentation in Django is missing some items and incorrect in others.

### ISSUE THREAD

**Issue by andrewallred** [online-go/online-go.com#1590]
This is not comprehensive, but I can see that a few different items are either wrong or missing in the Django API documentation.

Some examples:
1) "Library" is missing from https://online-go.com/api/v1/ even though you can access it at c.f. https://online-go.com/api/v1/library/875272?
2) URLs are incorrect in https://online-go.com/api/v1/me/ (c.f. mesettings rather than me/settings)

If possible I'd be happy to contribute to fixes here and to making this comprehensive, so please let me know if I can help.

**Comment by pe5ha** [comment]
About Group Ladders http://online-go.com/api/v1/groups/id/ladders/ also incorrect?
I tried to get the current rank of the players in the ladders, but there is no data about the players. Is there some way through the api to get this?
