### ISSUE TITLE
Setting OGS_BACKEND doesn't work on first-run

### ISSUE THREAD

**Issue by philipkd** [online-go/online-go.com#1594]
When you run `OGS_BACKEND=PRODUCTION npm run dev`, the dev server will point to the BETA backend the first time you run it.

**Steps to reproduce:**

1. `yarn`
2. `OGS_BACKEND=PRODUCTION npm run dev`

Notice output: "pointing at BETA (https://beta.online-go.com)"

**Expected behavior**

OGS should point to the specified backend the first time you run it.

**Screenshots**

<img width="397" alt="Screen Shot 2022-01-03 at 1 03 03 AM" src="https://user-images.githubusercontent.com/195001/147913867-a1b328b5-cf52-414e-8cf1-1334e7014ce3.png">

**Desktop**
- OS: macOS 12.0.1
- Chip: M1
- Terminal: Terminal and iTerm2

**Comments**

- If you Ctrl+C out, then re-run the command, OGS will point to the PRODUCTION server. If you close and re-open your terminal, though, the bug will start again.

- I will likely work on this bug, but I wanted to see if anybody wants to comment.

**Comment by BHydden** [comment]
If you edit your local copy of `Gulpfile.js` you want to comment out line 4 and uncomment line 5 and then it will always point to production.

**Comment by benjaminpjones** [comment]
FWIW, I was not able to reproduce this on my machine (non-M1 Mac, MacOS 12.1)

Here is my output after running `OGS_BACKEND=PRODUCTION ... OGS_BACKEND=BETA ... OGS_BACKEND=PRODUCTION` in succession: [OGS_BACKEND_output.txt](https://github.com/online-go/online-go.com/files/7808936/OGS_BACKEND_output.txt)

**Comment by philipkd** [comment]
Okay, thanks for attempting to repro. Probably something off with my environment.

**Comment by philipkd** [comment]
As a workaround, I put `export OGS_BACKEND="PRODUCTION"` in my zshrc file. It's still a weird glitch, but maybe I'll get to it another day.
