### ISSUE TITLE
Player names overlap other info in the game info dialog for rengo games

### ISSUE THREAD

**Issue by jb361** [online-go/online-go.com#1596]
**Repro steps**
1. Open a rengo game, such as https://online-go.com/game/40150437
2. Choose 'Game information' from the pop-up menu at the right of the screen.

**Expected behaviour**
The scrollable panel should be repositioned to appear below the last player listed in the teams.

**Screenshots**
![2022_01_07_13_37_37_](https://user-images.githubusercontent.com/1145329/148493583-56e4a2fe-6067-47fa-ba23-4c65c3b33638.png)

**Desktop**
 - OS: Windows 10 Pro
 - Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)

~ 

Thanks to all involved for this new feature!

**Comment by pdg137** [comment]
It's not just rengo, but normal games too, at least on mobile:

![image](https://user-images.githubusercontent.com/466760/148571051-b8b4506d-8f23-4d77-b04c-b636f4ab20ee.png)

I'm not sure if this is a new problem or not.  It's more noticeable when the names are long enough to wrap.

**Comment by cassidoo** [comment]
This doesn't appear to be an issue anymore @jb361, ccing maintainer @anoek to confirm

**Comment by anoek** [comment]
Thanks
