### ISSUE TITLE
Presense indicator changed colour

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#1598]
**Describe the bug**
https://github.com/online-go/online-go.com/commit/4a1d9b4d69713300c9c9f86ed57705a97efd615c was supposed to be a non-functional change but accessible.chat-offline was changed from accessible.bg `#1a1a1a` to dark.chat-offline `#cccccc`

@GreenAsJade

**Comment by GreenAsJade** [comment]
PR welcome :D

**Comment by GreenAsJade** [comment]
(Thanks for point out what the inadvertent change was, easy to miss that just looking by eye!)

**Comment by BHydden** [comment]
> PR welcome :D

Yeah I wasn't sure if to just change accessible back or change dark at the same time to match accessible haha, thanks for the quick fix ❤
