### ISSUE TITLE
Ranking shown on profile game list inconsistent with how games show rankings

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#160]
When you start a game, your rank for that game is based on your rank from the blitz/live/corr game speed that matches the game's speed. The rank persists for the life of the game, even if your rank changes before the game ends.

When you go to Profile and view your active games, your rank showing there is your average overall rank. It doesn't show either the rank specific to that game speed, or the rank you have in the game itself.

I'm not sure this is a bug per se, but since it is pretty inconsistent, I'm going to suggest games on your profile page (and I presume the Watch list) should either show the player's current ranking for that game speed (not overall ranking), or their ranking that shows up inside the game itself for them.

**Comment by BHydden** [comment]
resolved / obsolete. can be closed.
