### ISSUE TITLE
Tournament page player names have conflicting features bound to a tap/click

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1604]
**Describe the bug**
On a tournament page, there are multiple events bound to a tap or click on a player name, and they don't work together.  They don't all always work, either, so it's often a surprise what will happen if you tap a player in a tournament.

**To Reproduce**
1. Go to a double-elimination tournament on mobile: https://online-go.com/tournament/78957
2. Tap on a player name
3. See three things happen simultaneously: the player is highlighted in green, the player card is shown, and you are quickly directed to the player's page so you don't get to look at the green highlights or player card for more than an instant.

In a Simultaneous McMahon tournament, it used to only *sometimes* perform the redirect to the player page, but while testing just now it seems to always happen for me.

**Expected behavior**
A tap/click should not do multiple things that don't work together.  Probably best if it just stays on the tournament page, since going back and forth doesn't work well with big tournaments anyway, and opening the player card is the normal behavior on the rest of the site.

**Screenshots**

Slightly before the redirect happens:

![image](https://user-images.githubusercontent.com/466760/148572393-64735844-3dc6-4cba-95dd-daa00de43bb4.png)

You only get to see this for a fraction of a second.

**Comment by benjaminpjones** [comment]
I get the redirect too (Fennec, Android; Firefox responsive design mode iPhone size, MacOS)

**Comment by shinuito** [comment]
> So you don't ever get the action that takes you directly to the player page? Maybe that's completely unintentional.

I don’t think so. How long do I have to wait for it to redirect? Unless it’s several minutes then it’s probably a no.

iOS with Safari.

![C477DEB2-0A22-4B71-A5CE-343E2AB02241](https://user-images.githubusercontent.com/26803867/149517142-6488e86e-7be0-42fe-838d-c5689406ec92.jpeg)

It doesn’t do it on Safari on a laptop too either?

I thought the way to get to their profile page was to click the name in the player card that pops up?

**Comment by shinuito** [comment]
Oh wait, on iOS on mobile, the screen is by default somewhat zoomed in and the double elimination goes off to the right out of view.

However if I zoom out from the default view, I also get the redirect effect. I've no idea how that works.

**Comment by shinuito** [comment]
I think it depends on my zoom level. The default zoom when the page loads on iOS doesn't redirect when I tap it. Neither does the Safari responsive design using an iPhone setting.

When I zoom out though it does do the redirect when I tap a name.
