### ISSUE TITLE
Score estimator mistake in counting Japanese handicap games (really a bug, not a feature request!)

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1610]
**Describe the bug**

The (weak in-game) score estimator adjusts the score according to the ruleset.  For handicap N:

* Chinese: N points to White
* AGA: N-1 points to White
* Japanese: no adjustment

While this sounds correct (see [rules matrix](https://online-go.com/docs/go-rules-comparison-matrix)), it gives the *wrong result* for Japanese rules because the actual scoring is always done with Chinese rules! The reason Japanese rules don't give handicap compensation is that Black is already penalized for having played the extra stones, since stones don't add to his score.

This is a simple mistake - not a missing feature - that causes surprise outcomes for anyone who uses the score estimator for help counting in a handicap game.  [Actual game showing confusion](https://online-go.com/game/38712850).

**To Reproduce**
1. Play a handicap game with Japanese rules
2. Use the score estimator in the endgame
3. Finish the game and see the very different score

**Expected behavior**

It should just use the Chinese scoring for Japanese games.

**Screenshots**

Score estimator:

![image](https://user-images.githubusercontent.com/466760/148670720-93a62af9-d807-4f73-9e64-413c422d22b2.png)

Final score:

![image](https://user-images.githubusercontent.com/466760/148670829-28f5fddf-6af3-4713-878e-d4ba0c9f852a.png)

EDIT: looks like I accidentally Alt+Clicked a single point of Black's territory when trying to get this game scored. The correct score for Black should be 352, not 351, and the game result should be B+351.5, which is the SE score minus N.

**Additional context**
See also #1274.

**Comment by BHydden** [comment]
The end game result is correct. For some reason I find unfathomable, the in-game score estimator was left *intentionally bad* because apparently it doing its job properly, even though both sides can either use it or not based on the game settings, was considered cheating by a majority of the OGS player base.
So this, unfortunately, comes under the category of "feature, not a bug".

**Comment by pdg137** [comment]
Was the community ever polled about whether SE should be intentionally wrong just for Japanese handicap games? This is not about being smart or not, just about adding correctly. There's a handicap adjustment being added to the score in some rulesets that was left off of Japanese rules, and I'm sure that's just a mistake.

**Comment by benjaminpjones** [comment]
Related: https://github.com/online-go/online-go.com/issues/1274

**Comment by pdg137** [comment]
Here is the commit that fixed handicap adjustment for everything *except* Japanese rules:

https://github.com/online-go/goban/commit/c9be8369cc107780bb422f5e453f6e7ff05f906a

I will try to fix it over in the goban repository.

**Comment by pdg137** [comment]
With the changes to goban in effect this should be resolved.
