### ISSUE TITLE
Player clock font should be larger in portrait mode

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1625]
**Description**
The clocks are relatively small on portrait/mobile displays.  Byo-yomi periods are even smaller.  This is a request to make the clocks bigger given the importance they have during gameplay.

See https://forums.online-go.com/t/clock-font-is-too-small/40166 for more details.

**To Reproduce**
1. Go to an ongoing game.  These can be found at https://online-go.com/observe-games
2. Resize the screen so that it is narrower than it is tall.  Many modern browsers have a [Responsive Design mode](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) in the developer toolset that can come in handy here.
3. Notice the size of the clocks

**Screenshots**

<img width="479" alt="Screen Shot 2022-01-12 at 7 37 37 PM" src="https://user-images.githubusercontent.com/25233703/149262269-c41f2498-99f8-407d-809e-b064cf2666b5.png">

**Prerequisites**

- Some familiarity with [Stylus](https://stylus-lang.com/).  Stylus is the stylesheet preprossesor used in this repo.  If you already know CSS, it won't be too difficult to learn enough stylus to work on this issue.
- Some familiarity with [responsive web design](https://en.wikipedia.org/wiki/Responsive_web_design).  Any solution needs to look okay on a wide variety of display sizes.

**Code points**

- [Players.styl](https://github.com/online-go/online-go.com/blob/45afea9aea9423c6b15ec63c22e73f9150fbfc99/src/views/Game/Players.styl#L376): specifically `.MainGobanView.portrait .Clock`, where the styling for this is currently done.

If you have any questions, please leave a comment!

**Comment by anoek** [comment]
That is pretty small, I'm in favor of increasing the size but please note to test the display on small format mobile devices (simulated through the browser is fine), with both live and correspondence clocks.

**Comment by benjaminpjones** [comment]
Awesome, and I went ahead and added "familiarity with responsive web design" to the list of prereqs!
