### ISSUE TITLE
Players can create games with null x 10s byo-yomi

### ISSUE THREAD

**Issue by shinuito** [online-go/online-go.com#1628]
**Describe the bug**
When creating a custom challenge a player can leave the number of byo-yomi periods empty and it will create a game with null x () byo-yomi.

For example a game with 2mins + nullx10s byo-yomi will behave like a 2 min absolute time game, but will ignore the warning symbol (I believe) that would normally come with it. It also displays like `2mins + nullx10s`.

**To Reproduce**
1. Play page, create custom challenge
2. Choose Blitz byo-yomi and leave the number of periods blank

**Expected behavior**
This shouldn't be a possible option

E.g.

https://online-go.com/game/40320471

**Comment by maurelio1234** [comment]
I want to take a look at this one

**Comment by shinuito** [comment]
This one still seems to be an issue

A game with 2mins + null 10s on February 2nd

https://online-go.com/game/40900277

**Comment by maurelio1234** [comment]
Can someone reproduce the bug?
the steps on the issue description don't work anymore... 
I wonder if we can get more information on how this game was created.

**Comment by maurelio1234** [comment]
Ok... I look at the creator's profile and they create LOTS of games with this configuration... i wonder if it is not something that stayed on their local storage... 

I will take a look at it later.

**Comment by benjaminpjones** [comment]
There is of course the issue that the server should probably be rejecting these. (After all, even if all bugs are eliminated from this repo, a third party app could create a challenge with the null time settings)

**Comment by shinuito** [comment]
> i wonder if it is not something that stayed on their local storage...

I think that might be it, because I could create such a challenge, only because it seemed to remember I had left the byo-yomi box empty. Once I made another with it not empty, it's not letting me empty the box again.

**Comment by maurelio1234** [comment]
> There is of course the issue that the server should probably be rejecting these. (After all, even if all bugs are eliminated from this repo, a third party app could create a challenge with the null time settings)

The funny thing is that we had the same bug on canadian time, and the server blocks it as it should.
But to me we still need to fix it on the front-end. We shouldn't be able to create invalid challenges from here anyway.

**Comment by shinuito** [comment]
This still seems to be an issue with null x byo yomi if the user has the settings in local storage, or I haven't tested if one could do it with saved settings either.

Also one can create negative byo-yomi games. 30s+ -1x10s byo-yomi times you out when you reach 10s main time.

https://beta.online-go.com/game/11901

**Comment by maurelio1234** [comment]
Oh yes, there's a conversation about that here... 
https://github.com/online-go/online-go.com/pull/1714#discussion_r809486035
i'm trying to fix it on my new PR... I just need bandwidth to finish the things I started.... @shinuito

**Comment by shinuito** [comment]
Nice, I wasn't sure the best place to continue the conversation. Everything looks closed :) Thanks for looking at it!
