### ISSUE TITLE
SGF Library shows all-markup SGF at start instead of finish?

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#163]
### Summary

Now that SGF uploading is working I uploaded an SGF file, but when I go to view it I get a blank board and no controls on right hand side, such as:

http://puu.sh/uKQrX/10ee98a4b0.jpg

Once I click any movement button to bring up Analysis mode, everything is drawn on the board correctly. I'm not sure if this is working as intended or not.

My hope was to have the board laid completed if someone clicks the link into my library item, to see the beginner shapes demo board I made. Not need to click navigation to pop up analysis first. But maybe the boards always open at turn 0?

Perhaps because finished games open in final state I expected an sgf in the library to do the same. Is this a bug?

### Environment

 * Operating system: Windows 10
 * Browser: Chrome

### Steps To Reproduce:

Go to https://online-go.com/game/8078909

**Comment by anoek** [comment]
The recent patch fixes the initial loading issues, however to get the functionality you'd expect and want from viewing this SGF will take some additional enhancements to the system, so i've switched this to be labeled as an enhancement from bug.

**Comment by roy7** [comment]
Now that this works (thanks!), a couple other enhancement ideas. If there's no result/player names the "Tie By ?" could maybe just be hidden completely. Should the name of the SGF in the library appear on this screen someplace? It might be nice in the SGF Library list itself to be able to rename the files you've uploaded.

Basically my thought was, in my library list and on the actual view screen itself, have it named/labeled "Basic Shapes" someplace. :)

**Comment by anoek** [comment]
Tracking in https://github.com/online-go/online-go.com/issues/417
