### ISSUE TITLE
Tournament Icon missing

### ISSUE THREAD

**Issue by newmanth** [online-go/online-go.com#165]
### Summary

*Briefly describe the issue you are reporting 

The tournament icon and link is missing in portrait mode on my tablet, but is present in landscape mode

### Environment

Samsung Tab S2 8.0

 * Operating system:  Android 6.01
 * Browser: Chrome
 * Browser Version: 56.0

### Steps To Reproduce:

Also seeing same issue on Nexus 6p phone using Chrome browser. After rotating to landscape mode it appears. 

1. Go to ...
2. Click ...
3. See that X wrong 

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
Yeah, I couldn't figure out where to put it on those tiny screens without it being in the way.. Anyone have any ideas?

**Comment by newmanth** [comment]
It looks to me like the move control buttons are spaced far apart relative to their size. What if you moved them closer together? In landscape they start at C on the board and end at P. In portrait they start at A and end at T. Could you keep the same spacing?

This is a very minor issue. I only noticed it when I started a new game and could figure out where it came from.
