### ISSUE TITLE
Private message boxes block game chat

### ISSUE THREAD

**Issue by mark5000** [online-go/online-go.com#166]
### Summary

When chatting with friends, I can't type greetings or thank my opponent in a game because the chat boxes appear on top of the chat bar. The solution, to move the box, is cumbersome and requires the box to be open. The solution, to close the box, means you have to remember who messaged you, which discriminates against older users.

### Environment

 All desktop systems

### Steps To Reproduce:

1. Go to a game page.
2. Open a couple of private message boxes.
3. See that the boxes cover the chat entry bar.

### Potential Solution:

Reduce the vertical space of the chat box so that there is some empty space below where a PM box can appear without blocking game chat.

### Additional Information:

![chatblock](https://cloud.githubusercontent.com/assets/13010650/24027941/5c31d738-0a88-11e7-8916-529ca3bd4734.png)

**Comment by anoek** [comment]
Anyone have any ideas on a good fix?

**Comment by apetresc** [comment]
Maybe have some Javascript apply padding to the container if there's any PM tabs?

**Comment by arnaudgo** [comment]
Hello,

Please, do as a buddy list :) And when you clicked on the little pictogram it would list all incoming or in progress private chats.

Below, you display the number of open chats. When you reduce one chatbox, it goes there, when you close it, it disappears.

When more than one chatbox is open, use the same area with one tab per buddy.

What do you think of that implementation ?

Arnaud

**Comment by anoek** [comment]
That could work really well, I'd be happy with that implementation I think @arnaudgo

**Comment by Nazgand** [comment]
That private chats could also be on the left side of the webpage, and stacked vertically. There is almost enough room for the chat on my screen when I drag the private chat there: it covers the numbers on the board but not the stones. The board could be shifted to the right a bit to make it fit.

I like @arnaudgo 's idea, it works well.
When the chats are open, they should be on the left side of the screen, not the bottom. This way they won't get in the way even if you keep them open.

**Comment by Nazgand** [comment]
If @arnaudgo 's idea is implemented, we should have an option in settings to choose whether messages from a new correspondent open a new chat window or simply increase the number under the correspondent list pictogram which indicates either the number of correspondents or the number of unread messages. Speaking of which, what should the number indicate? I vote unread messages.
As previously stated, this problem could be solved for widescreen by having the private chat on the left instead of the right, but it does not solve the problem for half widescreen because they would still be in the way.

**Comment by arnaudgo** [comment]
Hello,

imho, it has to be the number of unread messages, it's the only way to get notified of new unread messages, obviously. 

Arnaud

**Comment by Nazgand** [comment]
While I do agree, it is not the only way. E.g. we could have the number of correspondents who sent a new message shown. Anything other than 0 means a new message. An advantage to this method is that if there is someone so chatty that you ignore what they say until a few minutes pass, then you will be on the lookout for a number larger than 1.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
