### ISSUE TITLE
Clicking variation exits the score estimator while leaving the estimate on the board

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1664]
**Describe the bug**
Clicking a variation in chat exits the score estimator while leaving the estimate markings on the board. You can proceed with the game and do other things, and it's a mess.

**To Reproduce**
1. Go to a game with a variation in chat, such as https://online-go.com/game/39979281
2. Click on "Estimate score"
3. Click on the variation in chat
4. See that the markings are still on the board from the original position, but you are in a totally different position, and there's no more numerical score estimate.
5. Click "Back to game".
6. See the markings still on the board!

**Expected behavior**
It should *either* clear the score estimate or redo the estimate on the variation.

**Screenshots**
![image](https://user-images.githubusercontent.com/466760/150667482-5dbf942e-8a5c-4a47-8749-54f13a453552.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.34.80

**Comment by benjaminpjones** [comment]
Related (but not duplicate): #1109

**Comment by pdg137** [comment]
Still an issue

**Comment by pdg137** [comment]
🎉
