### ISSUE TITLE
Score estimator hides captured stones

### ISSUE THREAD

**Issue by pdg137** [online-go/online-go.com#1666]
**Describe the bug**
When in the score estimator, the count of captured stones is invisible. I don't see any reason for this, and it will be especially confusing with the changes to goban.js accounting for Japanese rules. I'm pretty sure it's intentional, maybe someone thought that estimating the score would actually remove some stones on the board, possibly making these counts misleading? But it doesn't do that.

**To Reproduce**
1. Go to a game
2. Click on "Estimate Score"
3. See the captured stone counts disappear

**Expected behavior**
Should not hide captures.

**Screenshots**
![image](https://user-images.githubusercontent.com/466760/150825442-ab1a3a20-ece8-491a-9574-fe1479aeebae.png)

**Comment by pdg137** [comment]
Right, but captured stones are shown during the rest of Chinese games - why just hide them in the SE?

**Comment by anoek** [comment]
:shrug:

**Comment by anoek** [comment]
I'm fine with it being enabled for all games, I don't think there was a particular reason not to, other than no one has complained about it loud enough to me, at the right time when I could pay attention :)
