### ISSUE TITLE
Instructions on announcement center 

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#1667]
Lets add some text box on announcement center for instructions on how to use it, this would save mods lot of effort on explaining these every time when giving someone announcement rights. 

I was thinking something along these lines:

> At the bottom of the left side menu you have announcement center
> 
> There are 4 parameters you need to set: Type, Expiration, Text and Link.
> For Type, put "streaming" if you're streaming, "event" if you want to announce an event.
> For Expiration, put the time when you would like it to disappear. Use your local timezone. Max time is 6 hours. If you want to make it last longer, contact anoek.
> In Text and Link put the text and the link that you want to announce.
> When everything is filled, double-check and click on the blue "create announcement" button. When you click on it the announcement will be published, there won't be any pop-up.
> 
> General guidelines:
> - Be reasonable with the time: don't make the announcement too long and never make it last more than the event/stream.
> - Keep the text short and descriptive, for example for streams use words like "streaming" or "on twitch" so people can expect a link outside OGS.
> - Keep the text safe for work and kids.
> - Always double check before clicking the blue button.
> 

Anything to add or change? Or something else?

**Comment by kobakitty** [comment]
oh right, prolly worth noting that im asking someone else to do the thing, i have no idea how to implement some sort of text box there so i'm basically saying "could you please" >___>

**Comment by yewang** [comment]
Could we also mention some sort of policy to avoid several simultaneous announcements? Here is some suggested text:

> Do not have two or more simultaneous announcements for the same event (i.e., tournament). If you need to publicize multiple links (like several games/relays, commentary streams, review boards) at the same time, you must consolidate them on some other page (like a forums thread, group news post, or external website), and announce that instead.

**Comment by kobakitty** [comment]
About that "expiration", since anoek is the only one who can set announcements for more than 6 hours, it would make sense to change that calendar+clock thing into some 6-hour timer. I tried looking how to make that change but couldnt figure it out, if someone wants to tackle this instruction thing maybe it would be good idea change the expiration thing too at the same time.
