### ISSUE TITLE
Feature-Request: Switch Chatwindow sorting of messages

### ISSUE THREAD

**Issue by picpromusic** [online-go/online-go.com#167]
### Summary

The Chatwindow shows the Messages in chronological order. There should be a user setting that switches the order of chats to anti-chronological. This would help on mobile devices to not miss a message from the follow go student ( sometimes called opponent ).

Also an Icon at the top of the screen would help that indicates "new messages from another user" since the last visit of the game and since the last own move of the game. 

### Environment

 Android Chrome

### Steps To Reproduce:

1. Write many messages to Chat. Than you have to scroll-down.

**Comment by anoek** [comment]
I can see the logic but to maintain consistency with other chat applications and thus user expectations, I think we'll keep the current setup.
