### ISSUE TITLE
Ladders: "players-updated" not emitted when a player drops from Ladder

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1674]
**Describe the bug**
Ladders are updated when players join, but not when they drop.  This is because the socket event "players-updated" is not emitted when a player drops.

**To Reproduce**
1. Go to **Ladders** in two different browsers
2. Join a ladder in one browser.
3. Note the other browser is updated accordingly
4. Drop from the ladder in a browser
5. Note the other browser does not update

**Expected behavior**
A player dropping should trigger an update as well.

**Screenshots**
You can verify that this issue is at the API level by filtering on players-updated messages.
<img width="502" alt="Screen Shot 2022-01-26 at 11 38 10 PM" src="https://user-images.githubusercontent.com/25233703/151312920-8c7db969-5bb7-4ce8-b289-172077e3a12a.png">

**Comment by anoek** [comment]
Fixed on the backend, thanks!

**Comment by benjaminpjones** [comment]
Thanks @anoek !
