### ISSUE TITLE
Feature-Request: indicates to malkovich log at the top

### ISSUE THREAD

**Issue by picpromusic** [online-go/online-go.com#168]
### Summary

I would like to see at the top of the screen that there are malkovich logs that are not older that x moves. Maybe there could be an Icon that indicates the move-age of the newest own malkovich log entry. 

It would also be very helpful to have another indicator when there move sequence in malkovich log that matches the actual gameplay. 

If this Feature-request is marked interesting i can write down some test case to visualize the expected behavior in more detail.

**Comment by mraraujo** [comment]
Could you better describe what you are proposing?
I imagined a "There is a Malkovich log of one of your games." notification, similar to the game requests/tournaments/etc. that currently exist. However, you mention "older than X moves". What exactly do you have in mind?

**Comment by anoek** [comment]
Closing, feel free to reopen with clarification
