### ISSUE TITLE
Your move indicator disappeared

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#1682]
**Describe the bug**
Sometime in the last 5 hours my turn-indicator completely disappeared. I have several active games, some my turn some not, and the indicator both visually and functionally is not there at all.

Tried force refreshing (ctrl+shift+R) and logging out and in and also tested on beta server and problem persists.

**To Reproduce**
1. Go to any page while logged in
2. See no move indicator

**Expected behavior**
See move indicator 

**Screenshots**
![image](https://user-images.githubusercontent.com/28991649/151915267-995bfb70-13eb-4e20-96e4-ce13848ea7e0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave (Chromium)
 - Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Samsung A90 5G
 - OS: Android
 - Browser Brave

**Additional context**
https://forums.online-go.com/t/your-move-indicator-disappeared/41248

**Comment by pdg137** [comment]
I see the same (also on Brave/Android.)

**Comment by benjaminpjones** [comment]
Thanks for fixing @GreenAsJade !
