### ISSUE TITLE
Analyze Mode broken during Stone Removal Phase

### ISSUE THREAD

**Issue by mmartin** [online-go/online-go.com#1687]
**Describe the bug**
Analyze Mode broken during Stone Removal Phase

**To Reproduce**
1. Open a game in Stone Removal Phase;
2. Switch to Analyze Mode;
3. Marked territories are still shown on the board;
4. Try to place a stone;
5. Stone is not placed, but instead state of the territory is toggled and the green acceptance check-mark is removed.

**Expected behavior**
Stone should be placed, or Analyze Mode should be disabled during Store Removal Phase.

**Desktop (please complete the following information):**
 - Browser: Firefox 96.0, Chromium 97.0.4692.99

**Additional context**
At least passing works. :-)

![image](https://user-images.githubusercontent.com/236237/152231155-822eed72-471c-4af6-9c78-035826f3013b.png)

**Comment by benjaminpjones** [comment]
Is this the same as https://github.com/online-go/online-go.com/issues/1109?

**Comment by mmartin** [comment]
Yes.
I searched the existing issues by “stone removal” and didn't find that one. :sweat_smile: 
Thanks, @benjaminpjones!
