### ISSUE TITLE
Win Loss Statistics on  Profile Page

### ISSUE THREAD

**Issue by newmanth** [online-go/online-go.com#169]
### Summary

The statistics page on a user profile shows Green for the win and Blue for a loss, but the icons are green check for win and red x for a loss.  Red is also used for loss in the game history. 

Recommend using red for loss instead of blue for consistency. 

If the choice is a  response to different cultural preferences, perhaps a way to set this in the user preferences (as long as it is consistent)  

### Environment

 * Operating system: 
 * Browser:
 * Browser Version:

### Steps To Reproduce:

1. Go to ...
2. Click ...
3. See that X wrong 

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
Thanks @DmitriyKirakosyan!
