### ISSUE TITLE
Pieces are broken if you deny access to HTML5 canvas image data in Firefox

### ISSUE THREAD

**Issue by LongJohn-Silver** [online-go/online-go.com#1696]
**Describe the bug**
If you deny access to HTML5 canvas image data to the web site, the pieces are broken and it seems glitchy.

**To Reproduce**
1. Open the web site
2. Deny HTML5 canvas image data on Firefox
3. See the error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: elementary OS 6.1 Jólnir, built on Ubuntu 20.04.3 using LTSLinux 5.13.0-28-generic
 - Browser: Firefox
 - Version: 97.0 (64-bit)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by anoek** [comment]
Yeah, don't do that. Our stones are procedurally generated, we draw them onto canvases, and compose those images together to make a go board. Disabling that will of course make things look awful :)

**Comment by benjaminpjones** [comment]
https://github.com/online-go/online-go.com/issues/1429

(Linking for related context)
