### ISSUE TITLE
Custom board size cannot be changed 

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#1697]
**Describe the bug**
cannot change the board size when choosing custom board size 
**To Reproduce**
1. Go to 'play'
2. Click on 'create'
3. Choose board size  'custom size' and try to change it

**Expected behavior**
To be able to choose custom board size by using those tiny arrows or by rewriting a number to the field

**Screenshots**

![image](https://user-images.githubusercontent.com/29932807/153064060-64a95424-bd58-4648-b856-37f420dc41da.png)

Seems to happen regardless of browser / OS

**Comment by GreenAsJade** [comment]
^^ @benito, I saw your comment in email, but can't find it here?   Am I blind?  Did you change your mind?

**Comment by benjaminpjones** [comment]
No mind still there, just GitHub not doing redirects haha.. I think the upstate/setState conversion might have something to do with this?  At least those two functions update_width/height seem to be related.

<img width="726" alt="Screen Shot 2022-02-08 at 1 47 02 PM" src="https://user-images.githubusercontent.com/25233703/153081186-7144cbba-8cbc-4ac7-a765-4b86acb8015f.png">

**Comment by GreenAsJade** [comment]
Hah - funny, when I got to that page, I don't see your comment ... possibly because the conversation is resolved?

Anyhow, that darn upstate thing eh??

It seems to be a smoking gun, and yet it's not obvious just from reading it how that breaks it...

**Comment by benjaminpjones** [comment]
Yeah I don't know what the problem is either.. just thought I'd tag you in case you had a better idea haha

**Comment by benjaminpjones** [comment]
@GreenAsJade took another look - looks like `challenge.game.width` became `challenge.board_width` in your PR.  Not sure what the best fix is though.. nested `Object.assign` seems a bit tangly.

I tried changing it back to:

```
    update_board_width = (ev) => this.upstate("challenge.game.width", ev);
    update_board_height = (ev) => this.upstate("challenge.game.height", ev);
```

I am able to change the values again, but when I submit, I get a server error.  So I don't know what the fix is, but I hope that helps you or @anoek get to the root of this!
