### ISSUE TITLE
the handicap drop-down list is shown even if handicap is disabled.

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#171]
### Summary

When creating a custom game, it shows the handicap drop-down list even handicap is disabled.
None option seems selectable but it took me few seconds before realizing I had forgotten to enable handicap.

### Environment

Possibly any

### Steps To Reproduce:

1. Go to "create a game" and chose custom
2. Leave "Enable handicap" unchecked
3. See that you still can browse the selection/drop-down list from the handicap stones number

### Additional Information:

https://forums.online-go.com/t/no-need-to-show-handicap-drop-down-list-when-handicap-is-disabled/10960

![unecessary_drop_down_list_when_disabled_handicaps](https://cloud.githubusercontent.com/assets/26174230/24069887/ca96dff2-0baa-11e7-877b-11c2189001bd.png)

**Comment by BarneyStratford** [comment]
Related to this, is there a reason why “enable handicaps” is separate from the “handicap” menu? Isn’t disabling handicaps the same as selecting Handicap: None?

Barney.

**Comment by anoek** [comment]
Thanks @DmitriyKirakosyan !
