### ISSUE TITLE
Chromecast stream

### ISSUE THREAD

**Issue by vidfamn** [online-go/online-go.com#1710]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
When watching a game, I want a button that would stream the game on my TV through Google Chromecast. 

**Describe alternatives you've considered**
None. 

**Additional context**
None.

**Comment by BHydden** [comment]
OGS is a webpage, the feature already exists that you can cast a specific browser tab... 

![image](https://user-images.githubusercontent.com/28991649/153782105-bc6dc3da-009e-49e5-ac3f-8b3e90369347.png)

**Comment by vidfamn** [comment]
> OGS is a webpage, the feature already exists that you can cast a specific browser tab...
> 
> ![image](https://user-images.githubusercontent.com/28991649/153782105-bc6dc3da-009e-49e5-ac3f-8b3e90369347.png)

Thanks, I didn't know that. I found the setting on my computer in Chromium. However I can't find this feature from my android mobile phone app Chrome. If it doesn't get exist, maybe this would be a feature request for the Chrome app instead.

**Comment by benjaminpjones** [comment]
https://support.google.com/chromecast/answer/3228332?hl=en&co=GENIE.Platform%3DAndroid&oco=1

**Comment by vidfamn** [comment]
> https://support.google.com/chromecast/answer/3228332?hl=en&co=GENIE.Platform%3DAndroid&oco=1

This explains how to cast my entire mobile phone screen to the Chromecast. This is not what I want to do. I want to cast the game only and still use my mobile phone for other things.

**Comment by BHydden** [comment]
Since we just got rid of a lot of Google dependencies in #1656 I think it's probably unlikely that we're going to add the ability to Chromecast natively to the website.

**Comment by anoek** [comment]
I wouldn't be opposed, my understanding is it's an API exposed by the browser and it'd only be activated upon request by the user, so it's not like a tracking thing or anything of the sort.

That being said, I have no idea if this is even feasible or not, our canvas and stones are rendered in javascript, I don't know what the limits are with casting something to a chromecast device.

**Comment by BHydden** [comment]
The note's at the bottom of [this dicussion](https://stackoverflow.com/questions/44999267/how-to-chromecast-enable-a-website/49089116) sound to me like it only works in Google Chrome, which is where it already works... it's not immediately obvious that there is a way to get it working in the background on a mobile device (from what I've read so far).
