### ISSUE TITLE
Paginated Table won't update if on a greater page # than filter allows

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1717]
**Describe the bug**
I was looking at the Game History and tried to filter on a player, the table was not updating.  Realized it's because I was on a page that was higher than the number of pages returned for that player.

**To Reproduce**
1. Go to https://beta.online-go.com/player/1420/
2. View Game histor
3. Go to page 3/3
4. Try to filter by opponent = GnuGo
5. Notice the table doesn't change

**Expected behavior**
Games shown should only be the player specified.

**Screenshots**
<img width="806" alt="Screen Shot 2022-02-18 at 12 23 30 AM" src="https://user-images.githubusercontent.com/25233703/154645450-3f08eaa1-43b0-4d8b-8cfa-ebf7ca48448a.png">

**Comment by mmartin** [comment]
Filters which where added in #1822 have the same issue.
