### ISSUE TITLE
submit mode is not a single click, the byoyomi sound will stop playing.

### ISSUE THREAD

**Issue by yuki2006** [online-go/online-go.com#1723]
**Describe the bug**
If the submit mode is not a single click, the
If you temporarily place stone, the countdown sound will stop playing.

**To Reproduce**
1. Set the submit mode "Double click to Move"
2. Single-click on the board to place a stone temporarily.
3. The byoyomi sound does not work.

**Expected behavior**
The sound of the byoyomi plays correctly.

**Desktop (please complete the following information):**
 - OS: mac OS 12.1
 - Browser chrome
 - Version 98

**Comment by mmartin** [comment]
Same as #1231?

**Comment by yuki2006** [comment]
@mmartin sorry it's same.

**Comment by anoek** [comment]
Fixed in online-go/goban#83
