### ISSUE TITLE
Server Error (500) when trying to challenge

### ISSUE THREAD

**Issue by Harleqin** [online-go/online-go.com#1727]
I am getting a 500 Server Error when trying to send a challenge.

**To Reproduce**
- I am https://online-go.com/player/4928/
- I am in the group https://online-go.com/group/9655 and on that group page
- I click yeonwoo in the Admins frame and choose Challenge (german „Herausfordern“)
- I set
  - Game name: Awesome teaching game
  - Private: no
  - Ranked: no
  - Board size: 19×19
  - Rules: Japanese
  - Speed: correspondence
  - Time: Fischer
  - Starting time: 3 d
  - Time increment: 1 d
  - Time cap: 3 d
  - Pause on weekends: no
  - Handicap: 3
  - Komi: custom, 0
  - Colour: Black
  - Deactivate analysis: yes
- Then I click send challenge

**Expected behavior**
A challenge is sent.

**Instead**
A modal window appears saying »(X) Server Error (500) [OK]«

**Screenshots**
![ogs-error](https://user-images.githubusercontent.com/2151072/154978596-14c6182e-6907-46b5-9900-ce89b5d86787.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Firefox 97.0 (64-Bit)

**Comment by Harleqin** [comment]
Here is the JSON of the challenge request.  I am a bit confused that the challenged player appears nowhere, and that Komi is the empty string.

```
{
  "initialized": false,
  "min_ranking": -1000,
  "max_ranking": 1000,
  "challenger_color": "black",
  "game": {
    "name": "Awesome teaching game",
    "rules": "japanese",
    "ranked": false,
    "width": 19,
    "height": 19,
    "handicap": "3",
    "komi_auto": "custom",
    "komi": "",
    "disable_analysis": true,
    "initial_state": null,
    "private": false,
    "rengo": false,
    "time_control": "fischer",
    "time_control_parameters": {
      "system": "fischer",
      "speed": "correspondence",
      "initial_time": 259200,
      "time_increment": 86400,
      "max_time": 259200,
      "pause_on_weekends": false,
      "time_control": "fischer"
    },
    "pause_on_weekends": false
  },
  "aga_ranked": false,
  "rengo_auto_start": 0
}
```

**Comment by Harleqin** [comment]
OK, since the Komi handling was so strange, I changed it from 0 to 0.5 and this worked.  I guess that the frontend should be fixed not to send the empty string and the backend might also need some love.  I find it also a bit astonishing that nobody tried 0 komi to date.  That's usually the komi for handicap games, isn't it?

**Comment by benjaminpjones** [comment]
If only everyone could post the request JSONs 😍

So I've sent `komi=some string` (usually something like `komi="0.5"`) before, and it does cause issues server-side. I'm not sure why it's happening to you, just wanted to add info.

As far as the player ID, that's probably encoded in the endpoint itself: `players/%player_id%/challenge`, right?

**Comment by benjaminpjones** [comment]
Harlequin, can you try changing it back to 0.0 again and see if it works? Possible the empty string was saved in your cache from earlier

**Comment by Harleqin** [comment]
You're right, the challenged player id is in the request URL.

I had set the Komi to just `0` before (no decimal point), and that lead to the problem.

**Comment by benjaminpjones** [comment]
@maurelio1234 I know you mentioned doing better input sanitization in the ChallengeModal. This issue seems like it would be prevented from that kind of update.

I wonder if we should have the sanitization step go right before the data gets sent off to the server.. LMK what you think

**Comment by maurelio1234** [comment]
Yes @benjaminpjones, that's the same kind of problem: the input controls letting users input values that do not make sense. 

I will take a look at the issue reported here the next time I have to time to work on it.

**Comment by Harleqin** [comment]
Ah, sorry to bicker, but the input of komi `0` makes perfect sense.  What doesn't make sense in my view is that it is converted to the empty string.  I would expect the input to be restricted to decimal numbers, maybe internally rounded to the next half integer (0, 0.5, 1, 1.5, …), and I would expect this number to be sent as a number to the server.

**Comment by Fraze** [comment]
One thing to keep in mind is that some rulesets (New Zealand) use 0 komi for handicap games, not 0.5.

**Comment by benjaminpjones** [comment]
>input of komi 0 makes perfect sense.

>One thing to keep in mind is that some rulesets (New Zealand) use 0 komi for handicap games, not 0.5.

I don't think anyone is saying that we should remove the option to have komi=0. The "input value that does not make sense" in this case is the empty string.

>What doesn't make sense in my view is that it is converted to the empty string.

My guess is that you entered the empty string *at some point* and it got cached. Then, when you opened the challenge modal the second time, it showed zero even though it loaded a `""` from the cache.  That is why when you changed komi to 1 then 0 again, it worked properly.

**Comment by benjaminpjones** [comment]
In fact, I found a way to reproduce that supports my suspicion.  Typing:

```
data.get("challenge.challenge.live").game.komi = ""
```

into the [JavaScript console](https://www.digitalocean.com/community/tutorials/how-to-use-the-javascript-developer-console) before opening the challenge modal, (and don't change the komi setting!) I get the same 500 message.  If I change to 1 then 0 again, then the error is fixed.

**Comment by maurelio1234** [comment]
@benjaminpjones An easy way to reproduce these kinds of problems is changing the values directly on the local storage.
The app should behave well even if the storage is corrupted.
