### ISSUE TITLE
Tournament window notification + sound

### ISSUE THREAD

**Issue by Clossius** [online-go/online-go.com#1729]
**Is your feature request related to a problem? Please describe.**
When a tournament game starts you are not automatically pulled into it.

**Describe the solution you'd like**
Hear a sound link a ping so that even if you are tabbed or away from the pc you can know when your match has started. Then have a popup window asking you to join the game. (Auto switching may interfere with something the user is doing.)

**Describe alternatives you've considered**
Perhaps open a tab automatically with the game?

**Comment by benjaminpjones** [comment]
Maybe for live tournaments you should be automatically pulled into the new game (maybe not even a new tab) just like when you create a live challenge. Idk wdyt?
