### ISSUE TITLE
Finished games still stuck on ladders

### ISSUE THREAD

**Issue by mlopezviedma** [online-go/online-go.com#173]
### Summary

I have this particular game: https://online-go.com/game/7309685 still as an active ladder game, which reduces to two the number of challenges that I can give in that ladder.

This game was finished by the server on v5 update, so there may be more cases like this, although I couldn't find any.

**Comment by mlopezviedma** [comment]
I just found one more https://online-go.com/game/7137637

**Comment by mlopezviedma** [comment]
Another one: https://online-go.com/game/9129541
cf. https://forums.online-go.com/t/ladder-tournament-game-finished-but-still-on/13370

**Comment by StanTraykov** [comment]
Have the same issue in one of my games: https://online-go.com/game/13700480. Opponent seems to have dropped out of the ladder, his number is now displayed as #-1. Maybe that's one of the occasions that trigger the bug? The game is finished but is still "active" in the ladder (appears under "Challenging" and decreases my limit).

Would be great if someone could manually remove the game from the ladder, if this is not going to be fixed soon.
