### ISSUE TITLE
Joseki explorer - comment box allows empty submission

### ISSUE THREAD

**Issue by jaysephjw** [online-go/online-go.com#1733]
_**Describe the bug**_
When using the comment box in the joseki explorer, bumping enter before typing anything submits an empty comment. 

e.g. comment 2 at https://online-go.com/joseki/22711

_**Expected behavior**_
Box does not submit if no text has been entered.

_**Screenshots**_
![image](https://user-images.githubusercontent.com/3268245/156404071-b23e1c02-9905-483a-a532-6a9ae8e419be.png)

_**Desktop:**_
Windows / Chrome

_**Additional context**_
This is super minor :) I'm just thinking of it as a candidate for a first contribution.

**Comment by benjaminpjones** [comment]
For a newcomer who wants to solve this, the Joseki page is in Joseki.tsx. Most likely, you will want to update the ExplorePane.onCommentChange() callback to not fetch if the content is `""`.

https://github.com/online-go/online-go.com/blob/d533e3501ea25e61b58634b93af8f8f1d5463749/src/views/Joseki/Joseki.tsx#L1737-1747
