### ISSUE TITLE
Preferred challenge settings: items not translated

### ISSUE THREAD

**Issue by JLTFRA** [online-go/online-go.com#1734]
**Describe the bug**
When your language is not English, and when you create a custom game, some items are still in English. They don't seem to appear on the translation interface https://translate.online-go.com/

**To Reproduce**
Steps to reproduce the behavior: set you language to 
1. Go to https://online-go.com/play
2. Click on 'Create'
![a](https://user-images.githubusercontent.com/21128573/156900311-ab0975a5-aad1-430f-a0df-56eb58092355.png)

**Comment by BHydden** [comment]
[The code](https://github.com/online-go/online-go.com/blob/87407d2b543ee38292a97dafd2c3de197292dde0/src/components/ChallengeModal/ChallengeModal.tsx#L1465-L1499) is correctly sending those strings to the translator, so I'm guessing the translator hasn't been updated yet. 
I can't remember whether that's something that will eventually happen on its own or if @anoek needs to do it manually.
