### ISSUE TITLE
Ladder pages use the term "rank" incorrectly

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1738]
**Describe the bug**
When you click on a player in a ladder that you are ineligible to challenge, it says either "your rank is too low" or "your rank is too hitgh".

It is trying to say that you are placed to low or too high on the ladder: nothing to do with rank.

It should say "this player is beneath you on the ladder" or "this player is too far above you on the ladder", or similar.

**Comment by benjaminpjones** [comment]
I wouldn't say this is an incorrect use of the word "rank", but yeah it is confusing given that the term is also used for the Glicko stuff

**Comment by GreenAsJade** [comment]
I wonder if "incorrect" is a relative term?

Relative to OGS, I find this use of "rank" fairly comparable to the use of "rengo" to mean "lame" ;)

It might work find in some conversations, but I _would_ go as far as describing _this_ use of the term "rank" as contextually incorrect. 

I literally looked at my rank, and the rank of the other player, and wondered "WTF?" for a moment...

**Comment by BHydden** [comment]
> It should say "this player is beneath you on the ladder" or "this player is too far above you on the ladder", or similar.

I find these a tad on the wordy side, how about this?

"your ladder position is too low/high"

**Comment by benjaminpjones** [comment]
> It might work find in some conversations, but I _would_ go as far as describing _this_ use of the term "rank" as contextually incorrect. 

I think one reason that it *is* contextually correct is that it's called "Rank" in the column headers as well:

![Screenshot_20220309-211946_Fennec.jpg](https://user-images.githubusercontent.com/25233703/157594986-65836fef-4c0e-4b40-a242-fe92c250b01b.jpg)

Perhaps that would need be changed as well? I'm not sure what the right word would be, maybe "postion" or "rung"

> I literally looked at my rank, and the rank of the other player, and wondered "WTF?" for a moment...

NGL I've had this reaction too.

>how about this?
>"your ladder position is too low/high"

And just to throw another option out there:

"Your rank (#8) is too low/high"

Although it still uses rank, it may be clear from the #number that we aren't talking about kyu/dan

**Comment by GreenAsJade** [comment]
While the "other option" is plausible, I'd find it a lot nicer if we can find a way to use something like "position" - why would we use the work "rank" if have have to then attempt to disabiguate it :)

I think that labelling the column "rank" is also part of the bug :D    But in _that_ context it is not _in itself_ remotely jarring, precisely because of the context: it is immediately clear that this column is a number starting from "one", and in fact the title is superfluous :)    However, in as much as it encourages us to put messages that use the word "rank" in a context that is not at all clear, then it's part of the problem :)
