### ISSUE TITLE
Unplayed moves appear in public review after a while

### ISSUE THREAD

**Issue by ckang244** [online-go/online-go.com#1747]
**Describe the bug**
If I leave a review window open, often when I come back during another session I see a bunch of empty moves and/or random stones that have been placed.

**To Reproduce**
1. Create a new public review.
2. Add some moves/variations - regular usage.
3. Leave the browser open, or close it - doesn't matter.
4. Open the review again in a new browser session at a later time. 

**Expected behavior**
There should not be any new moves added.

**Screenshots**
random moves that I didn't play:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/48226300/159047832-92bc8f88-dc59-4906-b7df-3a25e14622cb.png">

above moves in game tree:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/48226300/159047874-0094fe6e-38fd-43c0-980a-7819d5885db6.png">

lots of pass moves before this:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/48226300/159047753-3c5dd03f-b0dc-4751-b5f0-b4c60357fd32.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey / MacBook Pro

**Additional context**
Here's a link to the review, in case you can see logs: https://online-go.com/review/835992

**Comment by shinuito** [comment]
I've also come across this on safari mobile. Making a review, going to another tab and coming back to see a bunch of passing moves.

I'm not exactly sure what causes it or how to reproduce it perfectly each time.

**Comment by anoek** [comment]
Anyone know about how long this has been going on? @GreenAsJade we were in there for the rengo stuff recently, any chance this could have been introduced then?

**Comment by shinuito** [comment]
@anoek It was mentioned here for example, so at least since december

https://forums.online-go.com/t/auto-generation-of-new-almost-empty-main-branch-in-demo/40309?u=shinuito

**Comment by anoek** [comment]
Sounds like before rengo, thanks
