### ISSUE TITLE
Your mods are lazy, ignorant and do not respond.

### ISSUE THREAD

**Issue by Muku784** [online-go/online-go.com#1750]
Dude's rocking a official drawing of  the Standard of the [President of the Russian Federation] aka. Putin flag: 
https://online-go.com/player/1116406/

https://en.wikipedia.org/wiki/President_of_Russia#/media/File:Flag_of_the_President_of_Russia.svg

Is the colouring of the OGS logo lip service or do you remove the flag from the account? He's certainly not rooting for Yeltsin.

https://knowyourmeme.com/memes/i-support-the-current-thing

Thanks in advance for your clarification.

**Comment by Muku784** [comment]
Oh and German names + Russian national flags indicate Nazis:

https://commons.wikimedia.org/wiki/File:Victory_Day_(2013-05-09)_in_Moscow._A_man_with_a_swastika_tattoo..JPG
https://en.wikipedia.org/wiki/Wagner_Group
https://en.wikipedia.org/wiki/Dmitry_Utkin

Presumption of innocence is good and fine, but this a little suspicious.

**Comment by Muku784** [comment]
This guy knows exactly what he is doing, the flag stands for this: https://www.youtube.com/watch?v=Mb3_R__r7Go

**Comment by Muku784** [comment]
Also Standard of the President of the Russian Federation != people of Russia || Russian flag

**Comment by BHydden** [comment]
We do stand with Ukraine. That doesn't mean we silence any and all opposing views. Just as we are free to openly show our support for Ukraine, this Russian user is allowed to openly show his support for his president.

**Comment by BHydden** [comment]
We've discussed political statements as a username or game name, and the moderation team feels that as long as the user is respectful in conversation with other users, it is fine for them to publicly state their political standings. This applies for flags too.

**Comment by anoek** [comment]
The difference between the swastika and the z or the standard is the swastika is used by hate groups as a symbol of hate very knowingly. The z, and in this case the standard, is (in my understanding) used as a show of support for their (in my opinion, flawed) view of what's going on. It may be that someday that will change, but I do not get the impression that the symbol is used as a symbol of hate at this time. Everyone always thinks they're on the right side of history when they wave a flag like that, it's up to you (and others) to enlighten them, and to listen to what they have to say as well. Discourse is the only way these situations get better. So, it is of my opinion that engaging with them to inform them of the other side is a much more productive thing to do than to just ban users so all they have access to is a pro-putin echo chamber.
