### ISSUE TITLE
Profile page: Tournament icons not provided in the API

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1758]
**Describe the bug**
I was browsing the profile page code (as one does), and noticed that tournaments expect an icon:

https://github.com/online-go/online-go.com/blob/74362331ca17d45a04e3fbed8267653ac5c85595/src/views/User/User.tsx#L628

However, players/%%/full does not provide icons with tournaments:

```
    "tournaments": [
        {
            "id": 76293,
            "name": "10 Lines: Even Board Sizes Series"
        },
        {
            "id": 72781,
            "name": "11 Lines: Unusual Board Sizes Series"
        },
        {
            "id": 77155,
            "name": "12 Lines: Even Board Sizes Series"
        },
        {
            "id": 74059,
            "name": "15 Lines: Unusual Board Sizes Series"
        },
```

**To Reproduce**
1. Go to from https://online-go.com/api/v1/players/309835/full
2. Scroll down to the tournaments section
3. Notice no icon
4. Verify no icons are shown at https://online-go.com/player/309835

**Expected behavior**
Icons should be passed back from the API and rendered in the Activity card.

**Screenshots**
<img width="379" alt="Screen Shot 2022-03-31 at 8 54 00 AM" src="https://user-images.githubusercontent.com/25233703/161097884-453d4762-8a12-459f-9d22-de76256af250.png">

**Comment by anoek** [comment]
Whoops, fixed, thanks for the report!
