### ISSUE TITLE
Timer fails to time out

### ISSUE THREAD

**Issue by mark5000** [online-go/online-go.com#177]
### Summary

Sometimes when the timer for one player in a live game hits 0:00, the timer may not time out and may instead start counting into negative digits. Below are three games in which this situation occurred, although each has been ended manually.

https://online-go.com/game/view/8113580
https://online-go.com/game/view/8113862
https://online-go.com/game/view/8116992

### Environment

 All operating systems and browsers

### Steps To Reproduce:

1. Create a live game with 10m + 5 x 30s byo yomi.
2. Let one player time out.
3. Under unknown circumstances, the clock may skip zero and continue counting into negative digits.

### Additional Information:

All three games were 10m + 5 x 30s byo yomi, and in all three games it was the black player who failed to time out. It is unknown if this bug is limited to these settings. Here are screenshots of two game timers before they were ended manually.

![negativetimer1](https://cloud.githubusercontent.com/assets/13010650/24086742/5d0d7c38-0cd2-11e7-8baa-faf23a795d61.png)

![negativetimer2](https://cloud.githubusercontent.com/assets/13010650/24086743/5ee48ca4-0cd2-11e7-9b0b-1535f70facad.png)

**Comment by mark5000** [comment]
This occurred in a bot game here: https://online-go.com/game/view/8227896

**Comment by BarneyStratford** [comment]
Next time you see it, rather than terminating the game straight away, can you let me or one of the others know by PM (barney.stratford) and I’ll take a look. Much easier to diagnose the problem while it’s occurring.

Barney.

**Comment by anoek** [comment]
I haven't heard any complaints recently about this, ever since the patch that solved the lag issues (which I think this was related to). Closing unless we start seeing this again.

**Comment by mark5000** [comment]
This issue arose again in https://online-go.com/game/9125303
