### ISSUE TITLE
I hear "game started" when I do not have open game request

### ISSUE THREAD

**Issue by hunterpp** [online-go/online-go.com#1776]
I will hear "game started" at all the wrong times:
1. in the middle of a game
2. In the middle of the night.

It is driving me crazy. Thank you.

**Comment by anoek** [comment]
I think this should be fixed with https://github.com/online-go/online-go.com/commit/27647a49555e081460e9de31cc3ba9c997e7082d

**Comment by hunterpp** [comment]
How can I verify what version of the source code the website is using?

**Comment by anoek** [comment]
You can see the version on https://online-go.com/docs/about - I haven't pushed that update out yet though, it'll probably be Monday or Tuesday.

**Comment by hunterpp** [comment]
Just heard game started randomly. Have not played in a day but window was open.
