### ISSUE TITLE
Sgf related issues

### ISSUE THREAD

**Issue by shinuito** [online-go/online-go.com#1788]
Here's a collection of sgf related issues either to do with downloading or uploading sgfs to the site that I've been collecting recently:

1. I mentioned here https://github.com/online-go/online-go.com/issues/1348#issuecomment-901805035 that if an uploaded sgf has an incomplete result like "W+" the sgf will upload but the game itself won't show as it must be trying to uppercase something like an empty string, other wise I don't know why "W+R" would be fine. This seems to be issue https://github.com/online-go/online-go.com/issues/1519. I suppose it might be fixable here https://github.com/online-go/goban/blob/c7716bca217ff79563c6c818b0bfcabf86281710/src/GoEngine.ts#L2479-L2486 where the issue is that if `result=match[1]` is `""` then `result[0]` is `undefined` and so `toUpperCase` is probably erroring on that. I haven't tried editing goban before.

3. https://online-go.com/game/41965806 - there's an issue with games like this where downloading a bot game with Chinese rules with two handicap like this seems to have the issue that it places handicap stones with AB, which then if uploaded to the sgf library seems to break the ai review. All the scores are wildly off see [親睦戦](https://online-go.com/game/42243088) -- technically a private game.. Changing the AB moves to actual moves, two consecutive moves for Black like in the original game seems to fix it, B[];B[]; etc.3. 

4. There was also this problem with downloading the AI reviews, where it used add black and add white AB and AW so it wouldn’t show up properly in sgf editors. I think there was also issues with the move ordering or something, like the ai review move being misaligned or in the wrong place in the tree. I believe this is issue https://github.com/online-go/online-go.com/issues/1725, and they mention some more details about AW and AB in the sgf format.

5. There seems to be a problem when trying to download the sgf of reviews of games https://forums.online-go.com/t/cannot-download-sgf-file-from-review/31714/5?u=shinuito. I feel like there was some reviews I was able to download, but the error is "Error: TypeError: Cannot read property ‘replace’ of undefined".

**Comment by anoek** [comment]
We should break these out into separate addressable issues so folks can tackle them in chunks
