### ISSUE TITLE
When waiting for a game, all UI components are disabled

### ISSUE THREAD

**Issue by betterworld** [online-go/online-go.com#179]
### Summary

*When you challenge a user or create an open challenge, you will see the "waiting for game" screen. In this screen, the menu buttons and chats cannot be used. The only button that works is "cancel"*

### Environment

 * Operating system: Debian
 * Browser: Firefox, iceweasel
 * Browser Version: Firefox 45.8.0 and others

### Steps To Reproduce:

1. Click "Play", then "create game".  Or, after a game, click "rematch".

### Additional Information:

This issue has appeared with the last OGS upgrade.

There are several kinds of situations where you would want to use the UI components while having a challenge open:

 * I like to open the "chat" or "observe" pages in other tabs while waiting for an opponent. Also I like to open the "play" screen in another tab to be able to look at other open challenges. This used to work by clicking the links in the top bar using the right or middle mouse button to select "new tab".  Now you need to open a tab by Ctrl-T and type in online-go.com.

 * Often I am chatting with a friend and send them a challenge or hit rematch. Often they do not notice it right away, so I need to use the chat to tell them that I challenged them, or I need the chat to negotiate other time settings. However I can't do that if the chat is dysfunctional.

**Comment by benjaminpjones** [comment]
I'm not sure when this was addressed, but it seems the UI has been fixed and this issue can be closed.
