### ISSUE TITLE
"go to next game" - button missing

### ISSUE THREAD

**Issue by CodeIrregularity** [online-go/online-go.com#180]
In IE 11 the button for going to the next open game is missing.
In Edge it is visible.

**Comment by anoek** [comment]
Can you paste a screen shot of this?

**Comment by CodeIrregularity** [comment]
Of course, if you like it:
![missing_button](https://cloud.githubusercontent.com/assets/26691491/24372924/e8bb1462-132f-11e7-9a96-1c630fd25c7c.png)

In the red marked area in Edge/Windows10 appears the "go next"-button, but not in IE11/Windows7

**Comment by CodeIrregularity** [comment]
Ups, not closed - Problem continuing :-)

**Comment by anoek** [comment]
Does anything happen if you click that little graphic thing just to the right of the red box but left of the icon?

**Comment by CodeIrregularity** [comment]
No, there is no functionality -> and if I click there nothing is happen.
The missing button is not "not  visible" -> there is nothing

**Comment by anoek** [comment]
Ok thanks for checking, then it's another bug to figure out what the artifact is to the left of the icon.. though i imagine it's related.

**Comment by CodeIrregularity** [comment]
there is an other issue with the same appearance.
the small cup-icon in the left lower corner is missing for ladder games.
for normal tournament games it is showed.
