### ISSUE TITLE
Flag display errors on game page

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#1816]
**Describe the bug**
Flag for all users reset on game page, and misaligned on mobile

**To Reproduce**
1. Go to game page
2. See flags wrong

**Expected behavior**
Flags displaying correctly.

**Screenshots**
![Screenshot_20220503-190552_Brave.jpg](https://user-images.githubusercontent.com/28991649/166429486-9086232a-9e30-4bd6-a79b-b43831aa70d7.jpg)

**Additional context**
[Forum Discussion Thread](https://forums.online-go.com/t/country-displaying-unspecified-in-game-for-every-player-right-now/43053?u=bhydden)

**Comment by pdg137** [comment]
Before this bug I believe we did not show flags at all, except for Rengo games, which happen to still show the correct countries.

**Comment by BHydden** [comment]
Fixed with https://github.com/online-go/online-go.com/commit/f41f357ac58aa2e438fe1aea108de8948174ba6d
