### ISSUE TITLE
"Undo" button display broken.

### ISSUE THREAD

**Issue by mmartin** [online-go/online-go.com#1834]
**Describe the bug**
"Undo" button is displayed for games where I'm not even playing.

**To Reproduce**
1. Go to someone else's ongoing game;
2. See "Undo" button.

This was broken in #1825, I think. @benjaminpjones 

https://github.com/online-go/online-go.com/blob/e817825048eb108c266e492bccaad2d551ea80ae/src/views/Game/PlayControls.tsx#L763

**Comment by benjaminpjones** [comment]
Thanks for the report Martins, assigning myself.  I thought `player_not_to_move === id` was equivalent to `player_to_move !== id` 😅

**Comment by BHydden** [comment]
Don't not unforget double negatives 😅
