### ISSUE TITLE
Toggling between goban/list on “observe-games" page is broken

### ISSUE THREAD

**Issue by mmartin** [online-go/online-go.com#1852]
**Describe the bug**
Toggling between goban/list on “observe-games" page is broken. When you're in “goban” mode and then switch to “list” mode, it breaks.

**To Reproduce**
1. Go to “Games” section;
2. Switch to “Goban” mode;
3. Switch back to “List” mode;
4. See that the list is missing game info.

**Screenshots**
![image](https://user-images.githubusercontent.com/236237/168474675-db9a57fd-88b6-42a3-b37a-bba9fa65d004.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox, Chromium

**Additional context**
Seems like when switching to “list”, the `Goban` objects from `MiniGoban` component send `game/disconnect` after the `Goban` objects from `GobanLineSummary` have sent `game/connect`?
![image](https://user-images.githubusercontent.com/236237/168475031-7821a52d-fe38-4021-a11d-27b92e80c5f3.png)

**Comment by mmartin** [comment]
For some reason I can't reproduce it in my local dev environment. In my local env when switching from “goban” to “list” it creates & destroys an extra `GobanLineSummary`, so the disconnect/connect sequence is like this:
```
GobanLineSummary: game/connect
MiniGoban: game/disconnect
GobanLineSummary: game/disconnect
GobanLineSummary: game/connect
```

**Comment by anoek** [comment]
Thanks for digging into this @mmartin , I put a hack in to work around the issue for now. It's going to be a bit of work for a proper fix I think. I suspect what's happening is React 18 might be doing some deferred unmounting now, which would explain why we only recently started seeing this behavior, but I'm not entirely sure. In any case, I've been meaning to make a game connection manager that should properly fix this sort of stuff as well as making transitioning between games faster, so maybe it's time to prioritize that a bit.
