### ISSUE TITLE
Identify bots on game screen/elsewhere automatically?

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#187]
Since a number of times people have asked "Is X a bot?" during bot matches, I think it'd be helpful if bots were identified in some way on the game screen. Two quick ideas that came to mind were replace the grey/green online status light with the letters "AI" or perhaps show bot rating as "[4dAI]" any time a bot's rating is shown. Other things could be done of course.

Posting this as a suggestion and/or for feedback from anyone else's opinions.

Also atm a bot has opened open correspondent challenges. Since there's no identifying features on the open game list, people joining those matches wouldn't know ahead of time they are about to play a bot.

Another thought, on game screen, open challenge list, etc, might be to append "(AI)" or "(Bot)" or "-AI" or similar to every username that is flagged as an AI account when their names are displayed? Not a requirement for the actual name in the system, just a suffix added automatically by OGS.

**Comment by arnaudgo** [comment]
Hello, 

This is up to bot's developers but it would be nice if bots could drop an introduction line in the chatbox :)
And, it doesn't replace an OGS flag indeed.

Arnaud

**Comment by anoek** [comment]
They *should* have gray names as well, however it appears they do not. I'd be in favor of a bot flag or something like that as well

**Comment by anoek** [comment]
Closing in favor of tracking the desired fix in #190
