### ISSUE TITLE
Ranking bars missing

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#189]
### Summary

Ranking bars are not always visible in user profile

### Environment

 * Operating system: Mac OS X 10.11.6
 * Browser: Safari 10.1 and Firefox 52.0.2

### Steps To Reproduce:

1. Go to the page of any user whose rating comes less than half-way between ranks. Mine is currently in this state: https://online-go.com/user/view/351937
2. Whenever the rating comes less than half-way between ranks, the coloured bar has height 0 and so becomes invisible.

### Additional Information:

![ranking](https://cloud.githubusercontent.com/assets/5913995/24450111/80501b8c-1471-11e7-81a3-0c01e7a8bb35.png)
I know what is causing this and will submit a pull request in due course.

**Comment by anoek** [comment]
Confirmed on firefox, chrome renders it correctly though.

**Comment by anoek** [comment]
Fixed by #191
