### ISSUE TITLE
Outdated move notifications persist even after making a move

### ISSUE THREAD

**Issue by turtoise0** [online-go/online-go.com#1896]
**Expected behavior**
The move notification should disappear after you make a move in the corresponding game if it's no longer close to timing out.

**Screenshots**
Notification says I have 18 minutes left to make a move, but the game with the least remaining time has 7 hours left.
![online-go com_overview](https://user-images.githubusercontent.com/99894371/172132058-a32431a3-4740-40f2-b4c3-2e2c77123216.png)

When I clicked on the notification, I got sent to this game, in which I already made a move.
![online-go com_game_43560993](https://user-images.githubusercontent.com/99894371/172133989-08c0db44-a149-4e77-bf43-a373b025f995.png)

1. Play a correspondence game with > 12 hour increments
2. On your turn wait until you have less than 12 hours left to get a move notification
3. Play a move
4. Don't clear or click on any notifications
5. Wait several hours
6. Look at notifications
7. Panic because you think you're about to time out

**Comment by anoek** [comment]
Yikes thanks
