### ISSUE TITLE
Add an option to bookmark puzzle collection

### ISSUE THREAD

**Issue by oldyew** [online-go/online-go.com#1899]
**Is your feature request related to a problem? Please describe.**
There are a lot of puzzle collections now and I can't mark those I'd like to review.
Every time I need to search a list to find those I'd like to play.

**Describe the solution you'd like**
Add an option to bookmark puzzle collection to have a list of them in user profile

**Comment by shinuito** [comment]
For the moment, you could consider bookmarking the pages in your browser. You could create a bookmark to hold all those puzzle bookmarks.
