### ISSUE TITLE
Bot names are not 'gray' on the game page

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#190]
### Summary

Bot names are supposed to be gray on the game screens, however they are now.

### Steps To Reproduce:

1. Play a game vs a bot
2. Notice the bot name on the game page is blue instead of gray.

Addresses #187 and #188 (at least in part)

**Comment by roy7** [comment]
Should they also be grey on the open challenges list as a subtle warning those aren't human challenges? (If we are okay with bots posting open challenges at all.)

**Comment by anoek** [comment]
Yep, they should be gray everywhere

**Comment by roy7** [comment]
They aren't actually grey on watch page when viewing 9 or less games, though. Should I open a new issue?
