### ISSUE TITLE
Board lines appearing as partially white

### ISSUE THREAD

**Issue by ErueWoad** [online-go/online-go.com#1902]
![image](https://user-images.githubusercontent.com/57076936/173168543-35673643-95ef-4c06-a40a-e9889e1908d2.png)

And getting a same/similar issue when attempting to view AI review of a game

![image](https://user-images.githubusercontent.com/57076936/173168578-351d7caf-5b4f-41d3-87d9-4a8d481b05d2.png)

And if I mouseover the white lines they turn black after hovering

![image](https://user-images.githubusercontent.com/57076936/173168623-e2995bdf-5c08-4654-b339-03129a92f46c.png)

**Comment by anoek** [comment]
What browser are you using? This looks like a canvas rendering bug, possibly related to the anti-fingerprinting canvas work that some browsers fiddle with which tends to break things. I believe I saw someone else report this on the latest firefox after their privacy settings were cranked up or something similar.

**Comment by ErueWoad** [comment]
This was on chrome as a progressive web app, but it does also happen in chrome standalone.

**Comment by benjaminpjones** [comment]
See also: https://forums.online-go.com/t/grid-turning-white-as-stones-are-played/43270
