### ISSUE TITLE
An SGF that can't generate

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#192]
https://online-go.com/game/8223049

This was an odd game. Was server paused, and didn't unpause. Somehow that caused gtp2ogs/leela to get stuck. Opponent let me know and I restarted the bot, and game continued. Later on game ended by moderator.

Trying to download the SGF though generates an ERR_INVALID_RESPONSE in Chrome.

**Comment by anoek** [comment]
If you log in as RoyalLeela to download the game it should work, you were getting a 403 because it was a private game.

**Comment by roy7** [comment]
Ahh thanks.  Now it's obvious since I can't view private games. :)
