### ISSUE TITLE
Issue with chat variations in game reviews

### ISSUE THREAD

**Issue by mmartin** [online-go/online-go.com#1923]
**Describe the bug**
Chat variations are behaving wonky when I'm in sync with the reviewer.

**To Reproduce**
1. Open someone else's review and be in sync with the reviewer
2. Hover over chat variation's name in the chat
3. Chat variation is displayed, and also "Sync" button appears
4. Because of the "Sync" button appearing chat window is pushed down and mouse cursor is no longer over the chat variation
5. Normal review is displayed and "Sync" button disappears
6. Because of the "Sync" button disappearing chat is pushed back up and mouse cursor is hovering the chat variation again
7. Go to the step 3.

**Screenshots**

https://user-images.githubusercontent.com/236237/175829268-1ea6ea3f-40f5-42c1-9482-0b7607d9e943.mp4

**Comment by mmartin** [comment]
Could fix it with something like this – use previously calculated value when hovering over chat variation
```diff
diff --git a/src/views/Game/PlayControls.tsx b/src/views/Game/PlayControls.tsx
index 1f046da7..d44eb39d 100644
--- a/src/views/Game/PlayControls.tsx
+++ b/src/views/Game/PlayControls.tsx
@@ -49,6 +49,7 @@ import {
     useShowUndoRequested,
     useUserIsParticipant,
 } from "./GameHooks";
+import { game_control } from "./game_control";
 import { useGoban } from "./goban_context";
 import { is_valid_url } from "url_validation";
 import { enableTouchAction } from "./touch_actions";
@@ -1034,14 +1035,18 @@ const useReviewControllerId = generateGobanHook(
     (goban: GobanCore) => goban.review_controller_id,
     ["review_controller_id"],
 );
+let review_out_of_sync: boolean;
 const useReviewOutOfSync = generateGobanHook(
     (goban: GobanCore) => {
+        if (game_control.in_pushed_analysis) {
+            return review_out_of_sync;
+        }
         const engine = goban.engine;
-        return (
+        review_out_of_sync =
             engine.cur_move &&
             engine.cur_review_move &&
-            engine.cur_move.id !== engine.cur_review_move.id
-        );
+            engine.cur_move.id !== engine.cur_review_move.id;
+        return review_out_of_sync;
     },
     ["cur_move", "review.updated"],
 );
 ```

**Comment by GreenAsJade** [comment]
@andymarden   This is coming up as a problem in relayed games into OGS ... if you happen to still be around and interested, it'd be a good one to have a fix for...

**Comment by andymarden** [comment]
@GreenAsJade Still around but been busy lately

**Comment by GreenAsJade** [comment]
Happily the OP's proposed solution appears to have "just worked" :)
