### ISSUE TITLE
OpenGotha is broken

### ISSUE THREAD

**Issue by EricHaung** [online-go/online-go.com#1928]
Hey here,

I and trying to host a Tournament with type OpenGotha.

it broke sometime.

This time after I click “close registration” button with around 28 player join

I saw it send https://online-go.com/api/v1/tournaments/91909/start API to server.

and get response {“success”:“Start pending”,“id”:91909}

… my Tournament disappear lol

Can anyone help me?

I am so desperate since the tournaments will start at today 11 hours after.

**Comment by anoek** [comment]
Can you send me the opengotha xml file? You can upload it here or email it to anoek@online-go.com

**Comment by EricHaung** [comment]
> Can you send me the opengotha xml file? You can upload it here or email it to [anoek@online-go.com](mailto:anoek@online-go.com)

Thank you!! I already send you the xml file.

**Comment by anoek** [comment]
Alrighty, "it works for me".. so for the immediate future, what group are you creating this under, and what's your ogs username? I'll get it created and transfer it over to you

**Comment by EricHaung** [comment]
Thank you.

My group is 11838 and my username is 小幫手

Maybe is encode problem?

I an Editing XML in VScode and UTF-8

**Comment by anoek** [comment]
Well it works fine over here, so I don't think it's an encode problem. I don't see anything in the logs, it's still very much an open question about what's going on.

**Comment by EricHaung** [comment]
is work now!! Thank you so much!!!
