### ISSUE TITLE
Epileptic Demo Board Bug

### ISSUE THREAD

**Issue by zureliano** [online-go/online-go.com#1929]
When you are in a demo board or a review controlled by someone else and there are shared variations in the chat, hovering over the variations cause an oscillation of the chat window and the variation tree, causing the cursor to go between chat and a variation at a very fast pace making it impossible to navigate and causing extreme annoyance to the viewer.

To reproduce: Create a demo board. Make a (big?) variation tree, share multiple variations on chat (and perhaps chat some). Then enter with a secondary account and browse/hover through variations while also taking actions with the initial demo controller account.  (shortcut: ready-made demo board to test https://online-go.com/review/900806 )

Expected: OGS chat window and variation tree will oscillate at a fast pace.

Screenshot: Not available due to the nature of the issue.

**Comment by mmartin** [comment]
Is this the same issue as #1923?

**Comment by zureliano** [comment]
Yes, seems so, thanks - Should i withdraw? My first time reporting a bug.

**Comment by zureliano** [comment]
Ok, seems that report is very well-made so no need for this.
