### ISSUE TITLE
Slate and shell stones are clipped and too large on mobile devices

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#193]
### Summary

The slate and shell, and other rendered stones, appear to be too big and cropped on mobile devices. 

### Environment

 * Operating system: Android 7.x
 * Browser: Chrome
 * Browser Version: 57

### Steps To Reproduce:

1. Select Slate and Shell as your stone themes
2. View a game

### Additional Information:

This is probably a side effect of https://github.com/online-go/online-go.com/pull/144 as those have been the only changes to the affected theme code. Pinging @lemurek to see if he might have any insight.

![image](https://cloud.githubusercontent.com/assets/168460/24548818/8941f822-15e4-11e7-8346-045dde521006.png)

**Comment by lemurek** [comment]
Hey! I'll take a look. I don't have experience with testing on Android, so any suggestions on how to connect a phone to my local dev environment would be helpful.

**Comment by anoek** [comment]
@lemurek awesome thanks! As for debugging on android, they make it really easy see: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/ 

Basically follow those instructions and you can access the chrome developer console on your desktop's chrome.

As for accessing the development site from your phone, simply go to http://<your local ip>:8080/ where local ip is the ip of the machine running `npm run dev`

**Comment by lemurek** [comment]
That should be sufficient, I'm on it :) Expect some pr today

**Comment by lemurek** [comment]
Hmm... I think I run into the same problem before (I did try to test it on my phone when submitting original change). 

![screen shot 2017-04-01 at 12 06 07](https://cloud.githubusercontent.com/assets/12175058/24578211/ac41f094-16d3-11e7-8117-d612b7b08b9c.png)

When connecting from a phone service sees the request (see 'GET /' and 'GET /game/868' ) but somehow the communication breaks.

Luckily Chrome has a built in mobile emulator, which allows me to recreate the issue on my laptop.

**Comment by lemurek** [comment]
Hm, so I understand the problem now. Not sure about the right solution yet. See this log:

![screen shot 2017-04-01 at 13 04 08](https://cloud.githubusercontent.com/assets/12175058/24578615/b83d75e6-16db-11e7-9b5c-ad61adbe64a1.png)

When scaling is applied stones are pre-rendered with a different radius than the one passed in render phase. 

49/23.9399 = ~2.046
21/9.12 = ~2.302

Prerendered stones have filled the 49x49 square quite fully, while for the radius in which we are rendering the logic expects the margins to be much larger. 

I'll look around the code to understand how we can adjust for this discrepancy.

**Comment by lemurek** [comment]
Looks like accounting for that are getting ss and center based on 'descaled' radius does the trick:

![image](https://cloud.githubusercontent.com/assets/12175058/24578746/cc1dc9c8-16de-11e7-829f-a8c3f87506cb.png)

I'll wrap it up and sent the pull request soon ;)

**Comment by lemurek** [comment]
This is a quick fix that addresses the scaling problem:

https://github.com/online-go/online-go.com/pull/194

I don't know enough about mobile environment to understand if we could pre-render the stones for the canvas resolution - I assume it would improve the graphics quality a lot on mobiles. Any ideas how to do it properly?


Also this code needs some love and refactoring around how do we pass metrics around (I think the purpose of that object is to capture all kinds of interesting dimensions). Unfortunately I'm a bit too time constrained recently to do the cherry-on-top kind of work.

**Comment by lemurek** [comment]
Forget the previous comment 😜  It's actually really simple to pre-render the stone for the canvas. Just needed to delete one line. I think the graphics look much better now. 

Updated the Pull Request.

Since I went through testing on a range of devices I hope you'll forgive me slipping through a 2% increase in the stones sizes. After my original change gaps on the 13x13 board on full screen felt glaringly big.

The paragraph about love and refactoring for metrics still applies 🤣

**Comment by lemurek** [comment]
After some trial and error, I think I found the correct solution 😀  https://github.com/online-go/online-go.com/issues/193

**Comment by lemurek** [comment]
I guess we can call this one done ✌️

**Comment by anoek** [comment]
Indeed, thanks @lemurek !
