### ISSUE TITLE
Analysis of finished game reset after network failure

### ISSUE THREAD

**Issue by lykahb** [online-go/online-go.com#1932]
**Describe the bug**
When reviewing a finished game, the state of the board resets when the internet connection is flaky. The game resets to the last move, and the alternative branches of moves disappear.

I did some debugging. After the websocket re-establishes the connection, the game engine sets the board to the game data received from the socket. On re-connection, the event `this._socket_on(prefix + "gamedata", ...)`  fires in GobanCore.ts and it passes the `obj` to `load` that resets the state.

This seems to be an old issue. Here are a few complaints:
- https://forums.online-go.com/t/game-analysis-randomly-resets/691
- https://forums.online-go.com/t/analyze-game-sessions-disappearing-during-use/23137
- https://forums.online-go.com/t/why-does-ogs-analysis-randomly-update-to-the-last-move/42177/8

#### Idea for fix
It looks like the fix would need to check the game phase and either ignore the state from the network, or intelligently merge it with the state on the page. It seems that the simplest solution is to check the game phase at the beginning `load` and quit early, after setting the chats from the state. The game state does not contain anything that may change after the game is over other than chats.

I think that the client has to listen to websockets for the finished games. Otherwise, the chats would stop working after it's over.

If you think that the suggestion for the fix is good, I can try doing this.

**To Reproduce**
1. Open a finished game
2. Go to one of the older moves. Optionally, create a branch in the move tree.
3. Disable the network and wait for half a minute. Or more precisely, until you see the failing websocket requests in the network panel.
4. Enable the network and wait till the websocket requests succeed. The board state is reset.

Not sure how to reproduce with the locally running server.

**Expected behavior**
The analysis remains after reconnection. The new game data only affects the parts that have changed compared to the local state.

**Screenshots**

**Desktop (please complete the following information):**
MacOSX, Vivaldi 5.3.2679.55

**Comment by jmoudrik** [comment]
## Reproducing locally:
1) get local dev env running
2) make an analysis branch in a finished game
3) disconnect the PC
4) reconnect
5) analysis branch disappears

this works (== is broken) because even the local dev server communicates with https://beta.online-go.com

**Comment by jmoudrik** [comment]
I'll investigate whether this can be fixed easily or not..
