### ISSUE TITLE
Add a separate toggle for the score estimator

### ISSUE THREAD

**Issue by rabbit-time** [online-go/online-go.com#1943]
**Is your feature request related to a problem? Please describe.**
The toggle for game analysis is a very useful option to have. It's understandable that it also disables planning conditional moves and forking/reviewing until the game is over, since those features could also be used for the same purpose.

However, this does not apply to the score estimator since it cannot be used for game analysis, just for a score estimate.

This is an issue since many players would consider it unfair to use a game analysis tool instead of using their reading skills. Many of those same players also benefit from a score estimator tool and consider it fair to use.

**Describe the solution you'd like**
A separate toggle for the score estimator in the Custom Game options.

**Describe alternatives you've considered**
As an alternative, simply have the score estimator enabled for all games, regardless of whether game analysis is enabled.

**Additional context**
Several other Go servers including KGS include a score estimator tool but not a game analysis tool.

**Comment by anoek** [comment]
I don't personally feel strongly one way or another, but I think we should probably get a community discussion and vote going before proceeding with this change

**Comment by anoek** [comment]
Feel free to re-open if this is discussed by the community at some point
