### ISSUE TITLE
Have "Don't show these" and "Skip" options for RDH helps

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#1955]
Interactive help like we're adding is one of those things some folks find really helpful and some folks really hate. The two options we should probably add in before releasing is to be able to click a "Don't show these", and "Skip" - where "Skip" skips that entire chain, so wont' show progression of the set password help for instance.

![image](https://user-images.githubusercontent.com/168460/182693729-72fa482a-ad19-4bae-a94a-bc0f2a0e8e41.png)

**Comment by GreenAsJade** [comment]
If you press the dismiss 'x' then the whole flow is dismissed.   It is saying "yeah, I know about passwords, don't show me any more about them".  

I do kind of like the explicit way your mockup does it, compared to the current silly little 'x' though - I'll experiment with that.

I'd thought that the popups should be as "economical as possible", but actually being very clear seems to be better!   Who would have thought :D

**Comment by benjaminpjones** [comment]
closed by #1958
