### ISSUE TITLE
Blank RDH help settings lines are appearing

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#1956]
I'm seeing this on my help settings page:

![image](https://user-images.githubusercontent.com/168460/182694949-395dc189-b281-4a24-9131-7384127d3701.png)

A quick look at the code looked like we're iterating over some some stuff that might be pulled from settings or something, so it might be that I just have stale settings, but we should probably figure it out so that as we muck with identifiers and help strings as time goes on, we don't get ghost settings like this showing up.

**Comment by GreenAsJade** [comment]
Yes that's exactly it - if you press the "reset rdh" button (enabled by `data.set("debug-dynamic-help", true)`) (and maybe reload the page) they will go away.

Or at least, if they don't then it's a different bug :)

It's in the todo list for rdh to check if the flows in the saved flow state match the current ones it sees being rendered by react, for the reason you mention.

**Comment by GreenAsJade** [comment]
Fixed by #1958
