### ISSUE TITLE
Demo boards are empty after loading

### ISSUE THREAD

**Issue by Saxmaam** [online-go/online-go.com#196]
### Summary

frequently,  the move tree is empty after opening a demo board.

### Environment

 * Operating system: ios 10.2
 * Browser: safari
 * Browser Version: same as ios version I believe

### Steps To Reproduce:

1. go to my profile page
2. Open desired demo under reviews and demos 
3. See empty demo about half the time

### Additional Information:

Demo board can also empty itself after viewing a different tab in browser and returning to demo board tab.

**Comment by anoek** [comment]
Should be resolved by a31ace7ad63a220081dc61260967fd9e08264ace
