### ISSUE TITLE
When you change your username, it doesn't change immediately in the NavBar

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#1966]
**Describe the bug**
When you change your username, it doesn't change immediately in the NavBar

**To Reproduce**
1. Go to Settings -> Account
2. Enter a different username, and your password
3. Save
4. See "account updated" popup
5. See username still showing the old one

**Expected behavior**
It should show the new one immediately

**Comment by benjaminpjones** [comment]
Possibly related: when you log in, the nav bar still shows "Sign in"
