### ISSUE TITLE
Chat notification settings unintuitive

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1971]
Context: https://forums.online-go.com/t/disabling-the-new-chat-notification/28104/18

A couple issues with the chat settings widget:

<img width="153" alt="Screen Shot 2022-08-17 at 10 38 48 AM" src="https://user-images.githubusercontent.com/25233703/185206110-ad1226bc-1266-4f33-a924-ab073d0d25c6.png">

- [x] The layout is such that "unfollow mentioned" is not fully visible, so it gets truncated to "unfollow..." (Fixed in #1986)
- [ ] Negative verbs (**un**follow vs follow) obscure the meaning of actions.

Proposal:

Borrow UI from chat apps Discord and Slack by specifying which notifications we want to **follow** (not unfollow) and changing this to a radio button (to communicate that you can only select one):

<img alt="Slack" src="https://ogs-forums.s3.dualstack.us-east-1.amazonaws.com/original/3X/a/2/a2822c045accca7f08849ef62b7cba9e2aea2abc.jpeg" width="250"/>
<img alt="Discord" src="https://ogs-forums.s3.dualstack.us-east-1.amazonaws.com/original/3X/8/7/87a3148f31eea5f6afb4090b59576c6fc066b5c0.jpeg" width="250"/>

**Comment by hakanyilmazz** [comment]
Hi Benjamin,
I fixed that problem (The layout is such that "unfollow mentioned" is not fully visible, so it gets truncated to "unfollow..."). You should see it.
[Pull Request Link](https://github.com/online-go/online-go.com/pull/1986)
