### ISSUE TITLE
AI suggestions are still shown after disabling AI review

### ISSUE THREAD

**Issue by gezabohus** [online-go/online-go.com#1984]
**Description**
I disable AI analysis and still shows me continuations on variations that I looked at earlier.

**To Reproduce**
1. Go to a finished game, let AI do the analysis. Suppose you made a move at X and AI tells you Y would have been better.
2. Click on Y. It shows the continuation that it finds best. Now your game tree consists of the actual game plus your move at Y.
3. Disable AI review.
4. AI suggestions disappear except they don't disappear if you click on Y.

**Expected behavior**
All AI suggestions should disappear.

**Screenshots**
<img width="1808" alt="Screen Shot 2022-09-01 at 16 13 49" src="https://user-images.githubusercontent.com/10329508/187935917-23a863de-b8f5-4306-9f1b-f3a61be6d1c3.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Brave
 - Version 1.42.97

** Workaround**
You can leave the game and come back and it seems to work.

**Comment by benjaminpjones** [comment]
Thanks for the report! I went ahead and added the "bug" label

**Comment by anoek** [comment]
This was fixed with #2019 afaik

**Comment by gezabohus** [comment]
Thanks everyone.
