### ISSUE TITLE
Unable to remove rengo games from active games list after timeout/resign game

### ISSUE THREAD

**Issue by hackeysack01** [online-go/online-go.com#1985]
**Describe the bug**
Unable to remove rengo games from active games list after leaving game

**To Reproduce**
1. join rengo
2. timeout or resign
3. game stays in active list

**Expected behavior**
Game is removed from active list.

An opt out option such that the game is removable but the default action is to continue watching would satisfy my need.

Am willing to concede this may be a feature request.

Might also expand to a 'follow games' opt in feature with similar flags to be able to watch other correspondence games that are public.

edit:
My forum post to ogs.
https://forums.online-go.com/t/remove-rengo-from-active-list-after-leaving-game/44660

**Comment by benjaminpjones** [comment]
Thanks for opening the GitHub issue, I'm linking several other reports from the forums:

- https://forums.online-go.com/t/rengo-status/40415/17
- https://forums.online-go.com/t/rengo-issue/44262
- https://forums.online-go.com/t/removing-game-from-start-page/41388
- https://forums.online-go.com/t/how-to-close-finish-this-game/44057
