### ISSUE TITLE
Enable donation with cryptocurrency

### ISSUE THREAD

**Issue by PabloLION** [online-go/online-go.com#1989]
**Is your feature request related to a problem? Please describe.**
As some supporters (like me) wants to donate in cryptocurrency.

**Describe the solution you'd like**

Allow user to pay to

- [metamask](https://metamask.io/)
- [Binance Custody](https://www.binanceinstitutional.com/)

with multiple tokens.

My suggestion is to start with stable coins since they are easy to convert to USD.

**Describe alternatives you've considered**
Manual process on first 33 donations to see how many users are making donation with crypto.

**Additional context**

Related to https://github.com/online-go/online-go.com/issues/366 . Back in 2017 crypto was not so popular. But this issue is mostly extending "pay in my own currency"

**Comment by anoek** [comment]
We tried it, it was a lot of work and no one used it
