### ISSUE TITLE
Broken Puzzle: "TypeError: Cannot read property 'left' of null"

### ISSUE THREAD

**Issue by mark5000** [online-go/online-go.com#199]
### Summary

A puzzle I designed on beta.online-go.com is giving an error message that reads "TypeError: Cannot read property 'left' of null."

### Environment

 All devices and browsers

### Steps To Reproduce:

1. Go to https://beta.online-go.com/puzzle/9
2. See an error message "TypeError: Cannot read property 'left' of null"

### Additional Information:

This error occurred after I had deleted all branches of the puzzle and attempted to save.

**Comment by anoek** [comment]
Fixed by https://github.com/online-go/online-go.com/pull/200 thanks to @BarneyStratford
