### ISSUE TITLE
[rengo] Rengo columns misaligned in active games table

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#1998]
**Describe the bug**

In casual rengo games that you are no longer an active participant in, a player appears in the "Opponent's clock" column, shifting remaining columns to the right.

**To Reproduce**
1. Have casual rengo games going.
2. **Resign or timeout from them**
3. Go to the home page
4. Observe the table entry for rengo game looks like:

```
Move    | Game         | Opponent    | Clock  | Opponent's Clock | Size
10      | Rengo Match! | some_player | 5 Days | another_player   | 18h46m | 19x19
```

**Expected behavior**

```
Move    | Game         | Opponent    | Clock  | Opponent's Clock | Size
10      | Rengo Match! | some_player | 5 Days |      18h46m      | 19x19
```

**Screenshots**
<img width="1064" alt="Screen Shot 2022-09-11 at 10 41 57 PM" src="https://user-images.githubusercontent.com/25233703/189581809-277a2d0c-aed3-4c30-a1bc-a066fa78141c.png">

**Additional context**
I believe the same component is used on the ObserveGames page, but the columns do include both White and Black's name since it makes sense in that context.  Possibly related?

**Comment by turtoise0** [comment]
I was sure this was fixed by #1927. Can you confirm, @benjaminpjones?

**Comment by benjaminpjones** [comment]
Unfortunately the screenshots are from September.  And I just double checked my homepage.  You may be able to see what I'm seeing by going to my profile page (https://online-go.com/player/568679/benjito).

Interestingly it's only one of my ongoing rengo games that's "broken":

![Screenshot_20221005_235202](https://user-images.githubusercontent.com/25233703/194234371-4feaedca-6cb4-4bba-9699-f5135b8f941b.jpg)

**Comment by benjaminpjones** [comment]
This user has many examples: https://online-go.com/player/1032638/amateurplaying

![Screenshot_20221010-203525_Firefox](https://user-images.githubusercontent.com/25233703/194991473-ed7f77f0-3783-4d2a-bc66-d3e86185c924.jpg)
