### ISSUE TITLE
Wrong message for the reporter when report gets claimed by moderator

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#2001]
**Describe the bug**
When user makes a report and that report gets claimed by a moderator, the user will see report triangle showing 0 pending reports.

**To Reproduce**
1. Make a report
2. Wait till moderator claims that report
3. Click the red triangle
4. <img width="269" alt="Screenshot 2022-09-13 at 17 46 32" src="https://user-images.githubusercontent.com/29932807/189933883-54587a50-184a-435f-9f4a-06c368b68d78.png">

**Expected behavior**
Show the report instead the message meant for the mod team. Or some "Your report is being processed, thank you for reporting" message. Or just hide the triangle or something.

**Comment by anoek** [comment]
I think this might be a special case, can you try opening up the javascript console and running the following:

```
preferences.set("hide-claimed-reports", false);
```

I think that should fix it for you
