### ISSUE TITLE
Let new players set their rank

### ISSUE THREAD

**Issue by bryancheny** [online-go/online-go.com#2002]
When I first created an account on the site, I remember being very confused because when I tried to play a ranked game against the computer, it will say "Can not play a ranked game with rank difference > 9", when I had no clue what my starting rank was. Obviously this was very frustrating and I had to find out which bot I could play by trial and error.

I would suggest to make it more newbie-friendly by allowing users to set their rank and change the prompt of "Can not play a ranked game with rank difference > 9" to something more specific like "Your rank is too low/high ..." or "You can only play ranked games against players of the range 18k - 1k" or make it such that when you try to play against someone outside your range, the options will default to free game and make the ranked option greyed out.

**Comment by hadim** [comment]
I agree here. That would make OGS more new comers friendly.

**Comment by pe5ha** [comment]
+1, this is a very necessary feature for the OGS

**Comment by BHydden** [comment]
Resolved with https://github.com/online-go/online-go.com/pull/2568
