### ISSUE TITLE
SGF Library not sorted by last uploaded anymore

### ISSUE THREAD

**Issue by gezabohus** [online-go/online-go.com#2013]
The SGF library used to place the most recently uploaded file on top, it doesn't any more. It seems to do it alphabetically, but the earlier system was much more logical.

1. Go to SGF Library
2. Upload a game
3. It won't be on top unless its name happens to be at the beginning of the list.

**Expected behavior**
Newly uploaded file should be on top or one should have a way of sorting by upload date.

**Screenshots**
<img width="465" alt="image" src="https://user-images.githubusercontent.com/10329508/193073839-3a6b552c-967b-4eb5-a740-a45bac710595.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Brave, Safari

**Smartphone (please complete the following information):**
 - Device: Android
 - Browser: Brave

Also, there seems to be limit on the number of games one can upload before starting a new directory, but it doesn't say so, just fails quietly.

**Comment by benjaminpjones** [comment]
This would be because of #2010, although that PR actually fixed a bug.  The fact that it was sorted by most recent was possibly a happy accident.

Maybe good to discuss on the forums what should be the default sort?

**Comment by gezabohus** [comment]
Thanks for the info @benjaminpjones. My vote would be for last uploaded on top, but perhaps others think differently. One could also have a clickable header to sort whichever way, but that requires a bit more development.

**Comment by anoek** [comment]
SGF sorting was implemented so takes care of this issue
