### ISSUE TITLE
Joseki Library: Translation is censored if it is coincidentally an English Swearword

### ISSUE THREAD

**Issue by hf-mrdachner** [online-go/online-go.com#2021]
**Describe the bug**
In the Joseki Library, when using translations, word, that coincidentally are written like Englisch swear words are censored. In the example it is the German translation of "thick" which is "dick" that is shown as "$*!%".

**To Reproduce**
1. Set your language settings to German
2. Go to ['The Joseki Library and play a 3-3 invasion'](https://online-go.com/joseki/22739)
3. See error:
"Die schwarzen Steine sind nicht $*!%."
"der traditionelle Hane, macht Schwarz $*!%."

**Expected behavior**
The German Translation of "thick" is "dick". I expect the totally normal German word not to be censored, even if it is coincidentally written like the English Swearword "dick"

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10063494/193903261-3bdb1556-f94b-4e49-a16b-27e4132b4b53.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox / Chrome
 - Version: 105.0 (64-Bit)

**Comment by BHydden** [comment]
Try going to [settings](https://online-go.com/settings/general) and either turning language filter off or changing it from English to German.

**Comment by hf-mrdachner** [comment]
Yes, that works. But then it would not work in a chat, which would bei mostly in English.
Maybe it is a good idea to turn off the filter in the Joseki library completely, since it is save against vandalism and thus swear words.

**Comment by anoek** [comment]
Pinging @GreenAsJade for his opinion on that.

**Comment by GreenAsJade** [comment]
I agree that Joseki position entries (the description and position title) are safe enough from vandalism.

Note that Joseki comments are not safe, though.

**Comment by GreenAsJade** [comment]
... and, I think it's non-trivial to change this, unless there's a switch I'm not seeing, because `markdown` appear to apply `profanity_filter` unconditionally, and markdown is inside autotranslate... so that's a bit of messing around.

Not "difficult", just non-trivial :)
