### ISSUE TITLE
"You have no time left to make your move!" notification while having >12 hours in clock 

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#2022]
**Describe the bug**
Getting this notification despite the game in question still has plenty of time (about 21 hours when writing this)

<img width="253" alt="Screenshot 2022-10-05 at 14 54 08" src="https://user-images.githubusercontent.com/29932807/194055615-c4fb9d63-9c97-4c7a-9c3f-34b23bf9ed3d.png">

Game where it leads me is https://online-go.com/game/45308036

No idea why

**Comment by BHydden** [comment]
`WHAT YOU SAY!`

![image](https://user-images.githubusercontent.com/28991649/194133177-6c2623b8-9935-463e-bc59-61360a8113c7.png)

(Sorry, couldn't resist 😅 )

**Comment by turtoise0** [comment]
Duplicate of #1896?
