### ISSUE TITLE
Timecontrol "none" triggers "You already have 2 outstanding open live or faster challenges" error when attempting to create >2 open challenges

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#2029]
**Describe the bug**
If you already have 2 open challenges with "none" as the time control, you cannot create any more new open challenges with "none" setting, nor any live or blitz setting.

**To Reproduce**
1. Go to "play" as an user with restricted simultaneous open challenges
2. make 2 open challenges with "none" as the time control 
3. try making new challenges with "none" or any of the live/blitz game speeds 
4. See the error message

**Expected behavior**
To not have "none" control count toward blitz/live game restriction

**Comment by anoek** [comment]
Thanks for the report, fixed on the backend!
