### ISSUE TITLE
Auto scoring seki in Chinese games

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#203]
I know auto scoring isn't fully accurate and it's a very hard problem to solve. But when the scoring algorithm detects stones are in seki, such as in this game:

https://online-go.com/game/8272401

where both center groups are marked dead, in Chinese those stones are still counted towards the total score. Even false eyes within sekis have territory counted.

Is it possible to tweak the scoring algorithm so that when a game is Chinese and stones are marked 'dead' for being in seki, the stones and any fully surrounded territory within those stones is still scored?

Or is it more simple, leave seki stones alive in Chinese scoring but make them dead in Japanese scoring?

**Comment by anoek** [comment]
Score estimator code is here: https://github.com/online-go/score-estimator

have at! ;)

**Comment by roy7** [comment]
Is that the same code used for actual scoring on the web site after a game? I thought auto scoring and score estimate in front end didn't provide same results?

**Comment by anoek** [comment]
Yep same code, it's Monte Carlo and the number of iterations is more on the
server, so results can be different
