### ISSUE TITLE
"Black wins by Player's account was removed" is confusing result for a game 

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#2031]
**Describe the bug**
When user removes their account, all their ongoing games will end by "Player's account was removed".

It's not correct sentence in english (or any other) language, and its bit confusing since its not the winner who was removed but their opponent. Also it is stretching the last column in game history because its quite lengthy.

Maybe for the sake of cleaner UI, just use "disqualification" or "resignation"?

<img width="700" alt="Screenshot 2022-10-11 at 17 00 29" src="https://user-images.githubusercontent.com/29932807/195118693-8a0c5644-ff29-4c1e-baf3-8a0e6e852503.png">

**Comment by benjaminpjones** [comment]
What about `B+Account Deletion`

I agree the wording is weird, but I like the additional information since this is a little different from 'Resignation' and 'Disqualification'

**Comment by benjaminpjones** [comment]
The good news is that translators aren't required to use a perfect translation, so if the direct translation is prohibitively long, they are free to pick a shorter phrase even if it's not an exact match.
