### ISSUE TITLE
Provisional loss lowering rank of non-provisional player

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#204]
Saw this mentioned in chat, game # 8275406 was vs a provisional page (profile comfirms 2 games left to go), but the loss still lowered the non-provisional player's ranking.

**Comment by EricJHan** [comment]
As explained above, I played a game with a provisional player(it only showed him provisional in his profile, and not in the actual game) and lost. My rank was lowered in the process.

**Comment by EricJHan** [comment]
![image](https://cloud.githubusercontent.com/assets/26904971/24668181/a1f2e396-192b-11e7-8b98-2a62fe2901a5.png)

**Comment by anoek** [comment]
Confirmed, sorry for the delay.

**Comment by anoek** [comment]
I'm not exactly sure what went on here still. However, it's a bit of a moot point, next month we'll be getting rid of the provisional game system and that process will implicitly correct this error both historically and going forward.
