### ISSUE TITLE
Invalid username when trying to accept a game invitation on Beta

### ISSUE THREAD

**Issue by Sofia-mal** [online-go/online-go.com#2046]
![immagine](https://user-images.githubusercontent.com/100384001/196782744-0e0f2d65-95e7-472f-9380-9f914cec8a1d.png)

I will probably investigate this further later, I just found it very weird.

Edit: it seems to happen every time with <s>[this game](https://beta.online-go.com/welcome/?linked-challenge=3UYrowBeSMb79genkSmjjo) </s> every game

**Comment by anoek** [comment]
@GreenAsJade I suspect this is from our translation of "HonouredGuest", in Italian that's translated to "Ospite d'onore" - I suspect the `'` is messing things up. I reckon we should either let that through on the backend as a valid username character, or clean it on the front end?

**Comment by GreenAsJade** [comment]
My initial reaction is "I guess folk should be able to be called "Count d'monte Cristo" or whatever if they want to?   IE that ' is a character that seems to be used in namey kind of things, so let's let it through?

**Comment by anoek** [comment]
I'm inclined to agree
