### ISSUE TITLE
Some players can't accept invitations from games' links (?)

### ISSUE THREAD

**Issue by Sofia-mal** [online-go/online-go.com#2047]
I tried several times and from different browsers with https://beta.online-go.com/user/view/2391 and https://beta.online-go.com/user/view/2392 and it just doesn't work.  Empty screen.

**Comment by benjaminpjones** [comment]
Which one creates the invite and which one tries to accept?  And is a different error than #2046 ?

**Comment by Sofia-mal** [comment]
Yes. And it happens also with https://beta.online-go.com/player/1876/ so apparently not only new accounts. The other one was about the impossibility to create HonouredGuest accounts, here they are already registered.

I'm creating games with https://beta.online-go.com/user/view/1775
