### ISSUE TITLE
Game's name out of the box if the name is too long

### ISSUE THREAD

**Issue by Sofia-mal** [online-go/online-go.com#2049]
See 
![immagine](https://user-images.githubusercontent.com/100384001/196791449-7ed0088f-c013-460f-8fb6-1cb4fb556e22.png)
![immagine](https://user-images.githubusercontent.com/100384001/196791582-19f74f4a-1c8b-4443-a5a7-e22e74071bb7.png)

**Comment by benjaminpjones** [comment]
For anyone looking to take this issue, there are two places you'll want to fix:

- [ChallengesList](https://github.com/online-go/online-go.com/blob/f88d0954d7610737988dcf7b4d133b8c2a0f0bc9/src/views/Overview/ChallengesList.tsx#L95) (outgoing or incoming direct challenges)
- [InviteList](https://github.com/online-go/online-go.com/blob/f88d0954d7610737988dcf7b4d133b8c2a0f0bc9/src/views/Overview/InviteList.tsx#L244) ("invite only" challenges)
