### ISSUE TITLE
Play graph improvements

### ISSUE THREAD

**Issue by bhostetler18** [online-go/online-go.com#2050]
When I started using OGS, I was completely mystified by the colors in the graph on the play page. I eventually found [this forum post](https://forums.online-go.com/t/play-graph/34662/2), but it seems worthwhile to create some kind of legend explaining what the colors mean. To that end, I started messing with a layout like this:

<img width="557" alt="legend" src="https://user-images.githubusercontent.com/35665417/196793561-4a9a0c4e-2917-4862-9432-dae7287a08ae.png">

I was thinking that mousing over/tapping on each box in the legend would display the type of game challenge  (either in a popup or in canvas text directly below the legend). Before I continue, any alternative ideas or suggestions? Also, while I'm messing around with this code anyway, does anyone have improvements/changes they would like to see made to the play graph?

**Comment by BHydden** [comment]
For some reason I can't initiate reactions on mobile so

`+1` 😅🔥

**Comment by anoek** [comment]
I would merge that, that'd definitely be an improvement.

As for alternative idea's, improvements, and all of that - I'm very open here. This code is pretty darn old by now and it looks antiquated, I'd welcome an overhaul so sky is the limit here.
