### ISSUE TITLE
Move circle doesn't work 

### ISSUE THREAD

**Issue by JLTFRA** [online-go/online-go.com#2067]
**Describe the bug**
It's my turn in the game https://online-go.com/game/47281147 but the circle has a 0 inside.

This happens on Chrome on my Android smartphone as well as on Firefox on my computer. I didn't try other browsers or devices.
![Screenshot_2022-11-09-01-58-31-552-edit_com android chrome](https://user-images.githubusercontent.com/21128573/200711869-899e1dcb-d8c2-47fc-810a-189be66db9a7.jpg)

**Comment by JLTFRA** [comment]
It's my turn: I haven't played yet so the number in the circle should be 1.
Instead, as you see on the picture, it's a 0.

**Comment by PabloLION** [comment]
It's like a notification system showing the count of the games that you need to respond. Once you "checked the message", then it's not there anymore.

**Comment by JLTFRA** [comment]
What do you mean by "checked the message ?" There is one (1) game I need to respond but the counter shows zero (0). It's the first time I encounter that bug, usually the counter works correctly.

**Comment by anoek** [comment]
Theres a backend component that sometimes gets out of sync still that causes it, I'll restart it in a bit and it should "fix" this for you.

**Comment by anoek** [comment]
I think it should be "fixed" for you, let me know if you continue having troubles.
