### ISSUE TITLE
Player's name out of the box if it is too long

### ISSUE THREAD

**Issue by Sofia-mal** [online-go/online-go.com#2069]
Similar to https://github.com/online-go/online-go.com/issues/2049

See 
![immagine](https://user-images.githubusercontent.com/100384001/201758929-2ce52f3c-55f5-4eea-b817-9e1bd71609dc.png)

**Comment by benjaminpjones** [comment]
For anyone interested in fixing this, this component lives in [VersusCard.tsx](https://github.com/online-go/online-go.com/blob/32f3db0251b8948cd78ce2377b37893f9fe11963/src/views/User/VersusCard.tsx#L38-L47)

**Comment by hanbin9775** [comment]
Hi! Can I take this issue? Thanks

**Comment by hanbin9775** [comment]
Is anyone working on this issue? If not want to make pr on this issue. Thanks.

**Comment by benjaminpjones** [comment]
Hi Hanbin, I just added you as the assignee. Thanks!
