### ISSUE TITLE
Feature Request: Audible and visual alert when game commences

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#207]
### Summary

This request is coming repeatedly in the forums, and is captured here:

https://ogs.uservoice.com/forums/277766-online-go-com-suggestions-and-feature-requests/suggestions/18785674-can-we-have-an-audible-warning-that-a-challenge-ha

Basically, for a live game, you have little choice but to sit there watching the screen saying "waiting for opponent", because you need to be ready for when they accept.   You can't go finish your homework or look at cat photos or anything.

### Environment

OGS 

### Steps To Reproduce:

1. Create a game
2. Go look at cats on facebook
3. Come back to find you lost your game on time out

**Comment by Nazgand** [comment]
This isn't only a problem for live games; I recently have been playing all my games without a timer even when I want to play it like a live game; this gives freedom to leave the game at any time for any reason.

**Comment by anoek** [comment]
I believe this has been implemented
