### ISSUE TITLE
Add mousewheel support for game-move scrolling

### ISSUE THREAD

**Issue by christiancodes** [online-go/online-go.com#2075]
**Is your feature request related to a problem? Please describe.**
We would like to add mousewheel scrolling to move through the game.

**Describe the solution you'd like**
Discussed here: https://forums.online-go.com/t/mousewheel-to-navigate-moves-in-games/45007/7

**Additional context**
Maybe also adding a setting so players can opt into this behaviour.

**Comment by anoek** [comment]
This has been implemented, not stale!
