### ISSUE TITLE
Reports' text can't include "#"

### ISSUE THREAD

**Issue by Sofia-mal** [online-go/online-go.com#2085]
**Describe the bug**
A user (Sarielowicz) reported that he was unable to submit a report. Upon investigation, we realized that the problem was that his text included a hash mark. 
The error text, "There was an error submitting your report", is unclear, it doesn't explicit what prevents the report from being submitted. 

Possible fixes are changing the error text or allowing "#" (and possibly also other blocked characters) in reports.

**Comment by Sarielowicz** [comment]
Logs: https://imgur.com/a/POhImDd (http 500 error)
