### ISSUE TITLE
Vacation time does not seem to expire

### ISSUE THREAD

**Issue by cliffordwolf** [online-go/online-go.com#209]
(This is obviously a back-end issue. Please point me to the right place to report this, if here is the wrong place.)

Yesterday I watched the vacation time for this user count down to zero: https://online-go.com/player/110971/

To my surprise, when he had 0 seconds vacation time left, the timer jumped up to 6 days. I assumed that this was simply a bug in the front-end an reloaded the page, but even after reloading the page the vacation time was still 6 days. Is it possible that there is a bug with expiration of vacation time?

(I've been watching the vacation time for that user count down for weeks now, since him being on vacation is delaying [this tournament](https://online-go.com/tournament/23487) that I am participating in. I'm player 337285.)

Update: The vacation time for that user is now stuck at "6 days" for at least 36 hours. So it clearly is not counting down anymore either.

**Comment by anoek** [comment]
Fixed on the server side, will deploy either today or tomorrow
