### ISSUE TITLE
Minor display bug in scoring theme colouring 

### ISSUE THREAD

**Issue by shinuito** [online-go/online-go.com#2094]
**Describe the bug**
I think the colouring of players areas in scoring, which is conditional on the theme of the players (that I can see in Goban) seems to be conditional only on the choice of the Black theme.

What I mean is that the White stones/area won’t change colours unless the appropriate Black theme is also chosen.

Probably the clearest instance of this is say changing the white stones to Red in the flat colour theme and then toggling the theme of the black stones from the flat theme to another theme. You can see white’s area toggled from being coloured white to Red conditional purely on the Black. 

I haven’t had time to look up where this is controlled in the code itself.

![91132D79-A3B9-4AAF-BEE0-9E4FC4DCC324](https://user-images.githubusercontent.com/26803867/210071602-51012aae-c366-4b60-996d-1a66932aff7c.jpeg)
![4685FC97-772E-4609-8A2D-C75776D6C51D](https://user-images.githubusercontent.com/26803867/210071607-863ce442-3c2b-44cb-b71a-ba00a7a9b58c.jpeg)

**Comment by anoek** [comment]
Looks like this was fixed at some point
