### ISSUE TITLE
Announcement center crushes when entering time/date manually

### ISSUE THREAD

**Issue by Nemurius** [online-go/online-go.com#2097]
**Describe the bug**

**To Reproduce**
1. Go to 'https://online-go.com/announcement-center'
2. Click on 'Expiration'
3. Select time (minutes or hours)
4. Click on any number to enter
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/121455675/210189040-00e05264-f204-4b4b-bf29-869e0c9195fb.png)
![image](https://user-images.githubusercontent.com/121455675/210188978-1b75f09a-b265-4cc2-afc1-7ea01159bb58.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 108.0.5359.125 64-bit

**Comment by BHydden** [comment]
I feel like it would be better if the UI used a sliding scale instead of a calendar so that only legal entries can be submitted. Current setup can be quite fiddly.

**Comment by anoek** [comment]
I agree this would be better as a slider or something of the sort, pretty much anything but what we have

**Comment by BHydden** [comment]
I was about to reopen this but actually the issue is quietly resolved. It now has  a slider 👍
