### ISSUE TITLE
Popup windows too small

### ISSUE THREAD

**Issue by VincentCB** [online-go/online-go.com#210]
### Summary

In Safari, popup windows such as the one displayed when you click "Game info" in a game are too small vertically and you need to scroll to see the info at the bottom, even though there's enough space to display everything.

### Environment

 * Operating system: macOS Sierra 10.12.4
 * Browser: Safari
 * Browser Version: 10.1

### Steps To Reproduce:

1. Go to a game
2. Click on "Game info" or "Fork game" in the right-hand menu
3. See that the popup has a scroll bar

**Comment by alex-mac** [comment]
Wasn't able to easily downgrade my safari version.

May be specific to an older version of safari. On Safari 11, no scrollbars were present. 

<img width="1333" alt="game info safari v11" src="https://user-images.githubusercontent.com/14145199/31208871-897f5c80-a93c-11e7-9cad-c8f8e0dac0d9.png">

<img width="1309" alt="fork game safari v11" src="https://user-images.githubusercontent.com/14145199/31208888-963e3d88-a93c-11e7-94be-7bb00f26cb07.png">

**Comment by benjaminpjones** [comment]
@anoek Perhaps okay to close this as obsolete? Safari is now on version 14 and still no issues.

<img width="1086" alt="Screen Shot 2021-02-17 at 12 44 34 AM" src="https://user-images.githubusercontent.com/25233703/108161588-560ec000-70b9-11eb-9b54-43f9ff0b62ab.png">

**Comment by anoek** [comment]
Awesome, thanks!
