### ISSUE TITLE
Random game opens when trying to navigate someones profile via game history

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#2109]
**Describe the bug**
When i go to game history on someones profile, click their opponents name twice in order to get to that oppos profile, a random game of the first player opens. 

**To Reproduce**
1. Go to any users profile
2. scrolld down  till you reach game history and click on their opponents name
3. click again their name
4. game that you didnt click opens

**Expected behavior**
Have the opponents profile open

**Screenshots**

https://user-images.githubusercontent.com/29932807/211588365-21129b1a-ca64-4b92-acf1-6ebf717cec52.mp4

**Comment by iib0011** [comment]
I cant replicate this in local and in the live website

**Comment by bhostetler18** [comment]
I actually get this one a lot, but it can be hard to reproduce.On Jan 14, 2023, at 1:29 PM, Ibrahima G. Coulibaly ***@***.***> wrote:﻿
I cant replicate this in local and in the live website

**Comment by turtoise0** [comment]
This game isn't so random. It's the game under the popover.
I think this happens when you double click on the player name in the popover.
