### ISSUE TITLE
Unable to place move via Socketio

### ISSUE THREAD

**Issue by maelrawn** [online-go/online-go.com#2113]
I'm trying to place a stone on the board through the socketio API, but some part(s) of the process is failing and I can't understand which one(s) it is.

I have attempted solutions suggested on the forums [here](https://forums.online-go.com/t/unable-to-figure-out-how-to-post-a-move-with-the-api/27186/7). Then I attempted to follow the form of solutions from [Rengo-bot](https://github.com/dylanross620/Rengo-Bot/blob/main/api/realtime.py)'s code for the realtime API; specifically the code for authenticating, connecting to, and playing a move in a game. Then I used my browser's network monitor to figure out everything the web client sends to the server and send it myself; this includes emitting hostinfo and net/ping. 

When I run this code, it exits successfully but no state change occurs. I'm not sure what the issue is by now, and would appreciate a point in the right direction.

Here is the most recent code I've attempted to run:

```
from datetime import datetime, timedelta
import requests as rq
import socketio
import time
import random

HOST = "https://online-go.com"

# These were acquired through the /api/v1/me/ and /api/v1/megames endpoints
USERNAME = ~~username~~
PASSWORD = ~~password~~
MY_PLAYER_ID = 1269991
MY_GAME_ID = 50062346
CLIENT_ID = ~~client_id~~

def get_credentials():
	oauth_resp = rq.post(f"{HOST}/oauth2/token/", {
		"grant_type": "password",
		"username": USERNAME,
		"password": PASSWORD,
		"client_id": CLIENT_ID
	})

	auth_token = oauth_resp.json()["access_token"]

	config_response = rq.get(f"{HOST}/api/v1/ui/config/", headers={
		"Authorization": f"Bearer: {auth_token}"
	}).json()

	return {
		"bearer": auth_token,
		"jwt": config_response["user_jwt"],
		"chat": config_response["chat_auth"],
	}


def main():
	tokens = get_credentials()

	sio = socketio.Client()

	def Callback(*args):
		print(f"Event received: {args}")

	sio.on("*", Callback)

	sio.connect(HOST, transports="websocket",)

	time.sleep(5)

	sio.emit("hostinfo")
	sio.emit("net/ping", data={
		"client": random.randint(1673471878295, 1673471878295 + 999999999)
	})

	# sio.emit("notification/connect",
	# 	data={
	# 		"auth": tokens["notification"],
	# 		"player_id": MY_PLAYER_ID,
	# 		"username": USERNAME
	# 	})

	# time.sleep(1)

	sio.emit("authenticate",
		data={
			"auth": tokens["bearer"],
			"player_id": MY_PLAYER_ID,
			"username": USERNAME,
			"jwt": tokens["jwt"]
		})

	time.sleep(1)

	sio.emit("chat/connect",
		data={
			"auth": tokens["chat"],
			"player_id": MY_PLAYER_ID,
			"username": USERNAME
		})

	time.sleep(1)

	# sio.emit("incident/connect",
	# 	data={
	# 		"auth": tokens["incident"],
	# 		"player_id": MY_PLAYER_ID,
	# 		"username": USERNAME
	# 	})

	# time.sleep(1)

	sio.emit("game/connect",
		data={
			"game_id": MY_GAME_ID,
			"player_id": MY_PLAYER_ID,
			"chat": True
		})

	time.sleep(1)

	sio.emit("remotestorage/sync",
		data=(datetime.now() + timedelta(hours=1)).strftime('%Y-%m-%dT%H:%M:%S.000Z'))

	time.sleep(1)

	sio.emit("game/move",
		data={
			"game_id": MY_GAME_ID,
			"player_id": MY_PLAYER_ID,
			"move": "aa"
		})

	time.sleep(1)

	print("got to end")
	time.sleep(10)
	sio.disconnect()


if __name__ == '__main__':
	main()

```

The output is all just data blobs; I receive a hostinfo, pong, score-estimator-enabled-state, /gamedata, /clock, reset-chats, and several latency events. I can provide them on request but don't think they are helpful so I omitted them.

If there is anything clearly incorrect, or any other context required, please let me know and I will gladly provide it. A friend and I have been banging our heads against this for quite a few hours.

**Comment by benjaminpjones** [comment]
Hi! I wonder if the forums is a better place to ask for help debugging, since the folks who have written Python scripts like this probably aren't monitoring this repo.

You can also check this relatively recent thread, maybe modify the posted script for your purposes: https://forums.online-go.com/t/api-python-recap-help/44477

**Comment by anoek** [comment]
Another resource, if you're not already aware, would be the https://github.com/online-go/gtp2ogs script which hooks up bots that speak gtp and allows them to play on OGS, so it will have examples of socketio stuff to make moves, chat, and that sort of thing.
