### ISSUE TITLE
The "resume" button doesn't appear unless you refresh the page.

### ISSUE THREAD

**Issue by Sofia-mal** [online-go/online-go.com#2117]
The title explains it well. It used to be a rengo-only thing, but now it applies also to normal games.

Ah, I'm talking about paused games if it wasn't clear.

**Comment by benjaminpjones** [comment]
Oops, this was caused by #2096 (sorry!) I just opened PR for a fix.  Thanks for the report Sofia!

**Comment by benjaminpjones** [comment]
>It used to be a rengo-only thing

I should note, if there is a bug in rengo pausing, my patch will not fix it.
