### ISSUE TITLE
"User not found" for every user

### ISSUE THREAD

**Issue by mKurrels** [online-go/online-go.com#2126]
**Describe the bug**
Any time I click on a user's name to see their profile I get this message: "User not found"

**To Reproduce**
1. Go to any profile as far as I can tell. For example: https://online-go.com/player/627280/absurdmike

**Expected behavior**
see the normal profile

**Desktop (please complete the following information):**
 - OS: mac 12.2.1
 - Browser [brave and, safari]

**Comment by benjaminpjones** [comment]
Looks like the server is passing out 500 codes at players/%%/full (e.g. https://online-go.com/api/v1/players/699827/full).

**Comment by anoek** [comment]
Yep, should be fixed now, my bad
