### ISSUE TITLE
"Pauses on weekends" display is reversed.

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#213]
Games that don't pause on weekends say "Pauses on weekends", games that pause on weekends don't say this.

See my comments on:

https://github.com/online-go/online-go.com/issues/142

I looked at a bot live game vs DarkGo and it says "pauses on weekends" too.

**Comment by anoek** [comment]
Do you have an example game? All the ones I'm pulling up are correctly labeled, at least so far as the flag and text are concerned.
