### ISSUE TITLE
Android chrome : Board and stones disappearing 

### ISSUE THREAD

**Issue by nreboud** [online-go/online-go.com#2149]
Since a few days I often encounter problems with the web version of the site on Android (pixel 6, android 13, chrome version 109.0.5414.118). 
The stones and the goban disappear. 
I tried clearing the cache but the problem persists. 

![Screenshot_20230209-215155](https://user-images.githubusercontent.com/1408027/217936481-a8c7e898-7426-4095-9f91-e06f5eff819b.png)

**Comment by nreboud** [comment]
I don't have the bug anymore. Maybe this has been fixed somehow?

**Comment by BHydden** [comment]
It's almost always an upstream issue that gets fixed by the browser, usually Safari though, strange to see it from Chrome.

**Comment by anoek** [comment]
Thanks for confirming it's fixed! In this case we had to switch to the software renderer, it's a bug in their hardware renderer. They haven't fixed it yet, but pretty much all hardware renderers are buggy these days and the software renderer works great all around, so software it is.
