### ISSUE TITLE
Reviews disappearing and glitching

### ISSUE THREAD

**Issue by Adam314159** [online-go/online-go.com#215]
### Summary
After a review is made it loads blank when visited later and/or some comments from the main branch disappear.

### Environment

 * Operating system: Win 8.1 Pro x64
 * Browser: Firefox 
 * Browser Version: 52.0.2

### Steps To Reproduce:

1. Create a review
2. After finishing and closing try to access it later via the url.
3. See that someting is wrong.
4. Reloading and disregarding cache usually partially helps, but some comments from the main branch seem to have the habit of disappearing

### Additional Information:
You can try this one: https://online-go.com/review/237305
I am sure there were comments on at least 1st, 2nd, 4th, and 19th move. Yet I cannot see them.

Appearently more people are having the same issue:
https://forums.online-go.com/t/review-has-disappeared/11485/8
https://forums.online-go.com/t/review-analysis-glitching/11481?u=kickaha&source_topic_id=11564

**Comment by anoek** [comment]
Likely related to #196

**Comment by anoek** [comment]
Should be resolved by a31ace7ad63a220081dc61260967fd9e08264ace
