### ISSUE TITLE
Feature Request: Zen Mode Default Option 

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#2150]
**Is your feature request related to a problem? Please describe.**
Each time a new game starts zen mode must be manually selected. Users typically prefer it either on or off.

**Describe the solution you'd like**
Persistent toggle.

**Describe alternatives you've considered**
Game page toggle or settings toggle

**Additional context**
First requested on the [forums](https://forums.online-go.com/t/feature-request-zen-mode-default-option/46700?u=bhydden) .

> Add toggle switches or a dropdown to the game preferences tab in settings, allowing players to default to zen mode for each of the 3 types of games (blitz, normal, correspondence).

**Comment by csessh** [comment]
This looks interesting.
You mind if I took a jab at it? @BHydden

**Comment by anoek** [comment]
That'd be awesome @csessh :)
