### ISSUE TITLE
Possibility to hide rank of others players ingame

### ISSUE THREAD

**Issue by chingucoding** [online-go/online-go.com#2156]
**Is your feature request related to a problem? Please describe.**
Knowing the rank of the player I'm playing with doesn't interest me and I feel like takes away some of the fun.

**Describe the solution you'd like**
Ideally an option to just hide the rank of all players when ingame.

**Describe alternatives you've considered**
"Not looking at the opponent" doesn't really work if we are honest.

**Additional context**
If this is something that only involves the UI, I can try work on that feature if accepted.

**Comment by benjaminpjones** [comment]
In [General Preferences](https://online-go.com/settings/general), there's an option "Hide Ranks and Ratings".  Does this fit your need?

**Comment by chingucoding** [comment]
It does indeed, no idea how I missed that. Thank you so much @benjaminpjones !
