### ISSUE TITLE
Bots needs their own sign at chat.

### ISSUE THREAD

**Issue by Mikaa** [online-go/online-go.com#216]
### Summary 
Bots need their own sign like ⑂ or ⊡.
Admins has chat sign 🔧 or 🔨, Supporters has yellow ●.
Would be nice that bots had their own sign too.

Now there is no visuals about bots on chat.
http://i.imgur.com/vpPrg2w.png

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
