### ISSUE TITLE
hovering over dropdown menu icons gives in consistent area highlighting

### ISSUE THREAD

**Issue by ZxNashx** [online-go/online-go.com#2167]
when hovering over the Home / Play / Learn / Watch / Community / Tools, you can hover over "Play" and hover over "Play" or "Tournaments" or "Ladders". Tournaments and ladders select a different area than hovering over play or any other icon. 

Also: Community: "Groups" are highlighting the wrong area

The full menu bar of tournaments and ladders should be highlighted, not just on the left side. 

 - OS: Windows 11
 - Browser: Chrome
 -  Version : Version 110.0.5481.104 (Official Build) (64-bit)
![Screenshot 2023-02-19 192433](https://user-images.githubusercontent.com/25257266/219995319-b78e86c7-0e6d-4ee5-8e9f-c6853bf9a59a.jpg)
![Screenshot 2023-02-19 192420](https://user-images.githubusercontent.com/25257266/219995321-9aa929e7-c38b-4575-86b2-217d61dc3bb4.jpg)
![Screenshot 2023-02-19 192643](https://user-images.githubusercontent.com/25257266/219995577-79d26bb1-23eb-4d6f-93f3-391ad3716542.jpg)

**Comment by BHydden** [comment]
Was this fixed too? I'm on mobile and can't test it.
