### ISSUE TITLE
Dropped rengo games keep showing up in Active Games section

### ISSUE THREAD

**Issue by csessh** [online-go/online-go.com#2172]
**Describe the bug**
I joined a Rengo game, which I then resigned/quit. 
The game went into `Dropped Games` section as expected.
However, said game showed up again in `Active Games` section. 

Looking at the chat, I can see this message `[11:22] system [9d+]: 'csessh' left: Resignation`. 

**To Reproduce**
1. Go to a rengo game
2. Click on `resign` -> Click on `Yes` 
3. This message shows up in chat `[11:22] system [9d+]: 'csessh' left: Resignation`. 
4. Click on `Home` -> The dropped game shows up in `Dropped Games` section 
5. After awhile (I suspect after someone in that game made a move), the dropped game shows up on `Active Games` section again. 

**Expected behavior**
Dropped games should have stayed in `Dropped Games` section

**Screenshots**

Here's an example of a game I dropped but keeps on creeping back: [This game](https://online-go.com/game/44531856)
 
![Screenshot 2023-02-24 at 11 25 45 am](https://user-images.githubusercontent.com/5171823/221065600-06f57932-6955-4d28-b73b-1a37124951dd.png)

![Screenshot 2023-02-24 at 11 25 54 am](https://user-images.githubusercontent.com/5171823/221065604-42babcbe-8b7c-4022-9f15-1dae10bcaaa4.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version:  110.0.5481.100 (Official Build) (arm64)

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS 16.2
 - Browser: Chrome
 - Version: N/A

**Comment by benjaminpjones** [comment]
Thanks for the report.

I think this is the same issue as the one discussed in this forums thread: https://forums.online-go.com/t/stuck-in-rengo-game/46798

**Comment by csessh** [comment]
Yeah that looks to be the same issue

**Comment by anoek** [comment]
@GreenAsJade

**Comment by GreenAsJade** [comment]
I swear I'm going to regret agreeing to Casual Mode till my dieing day 😅

**Comment by csessh** [comment]
I had a poke around in beta server and I just could not reproduce this issue. 
It definitely still happens on prod/live site, though. 

interesting ...

**Comment by GreenAsJade** [comment]
Thanks very much for trying!

We too have not been able to reproduce or find a definite cause.

However, in the process we are tidying up various apparently unrelated issues - it is conceivable that one of those may have been the underlying cause of this.

We are continuing to investigate, and fix other stuff as we go.

**Comment by GreenAsJade** [comment]
> It definitely still happens on prod/live site, though.

On this topic - we're improving logging.   If there's a recent game that's done it, it'd be handy to know the game number...

**Comment by GreenAsJade** [comment]
Interesting indeed.  And you are player 1182443.

I found this:

INFO **2023-02-28T05:16:24.268185702Z** [resource.labels.containerName: ogs-gameserver-004] Game.ts:1370 [44531856] Django seemed happy with player 1182443 drop update


... which says that at that time (about a day ago?) you resigned apparently successfully.

Is that the case?

**Comment by GreenAsJade** [comment]
Actually, I found the corresponding entry in the game chat log, so this much is good.

**Comment by GreenAsJade** [comment]
I wonder if I dare close this now.  I'm really really hoping that all the recent cleanups made this go away...

**Comment by csessh** [comment]
I haven't seen this issue since I last commented. I'd say it's safe to close
