### ISSUE TITLE
Receiving false Firefox notices that my game is over

### ISSUE THREAD

**Issue by David263** [online-go/online-go.com#2177]
**Describe the bug**
I have received about three notices that "my game is over" during the past day. I am a member of the 9x9 Ladder and have not played any games outside of the Ladder. The notices are incorrect: the opponent has not even moved.

**To Reproduce**
The error is not reproducible from OGS through any steps.

**Expected behavior**
I expected to get no notices other than by email when my opponent moves.

**Screenshots**
I just decided to submit this report, so I will add a screenshot if it happens again.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Home on Laptop
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 110.0.1 (64-bit

**Smartphone (please complete the following information):**

**Additional context**
I had OGS open in a browser tab when these notices happened.

**Comment by David263** [comment]
I just got the notice again, but by the time I reacted to take a screenshot the notice disappeared. I will keep trying. It says "Game is ended".

**Comment by anoek** [comment]
Do you happen to have a notification of an old ended game that hasn't been cleared yet? Try clicking the (probably blue) bell in the upper right to see.

**Comment by David263** [comment]
I see what happened now. I keep challenging people in the 9x9 Ladder, and they ignore me, so after three days the game is annulled. The notice fails to say whose game is ending and why it is ending. Can more information please be added to the notice? Ideally, it should say, "one of your Ladder games has been ignored by your challenged opponent, and so annulled" or equivalent.

**Comment by anoek** [comment]
I'll put it on the todo list
