### ISSUE TITLE
Kick deleted user accounts from ongoing tournaments 

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#2183]
**Describe the bug**
Whenever an user removes their ogs account in the middle of multi-round tournament, they will still be paired for the next round as deleted accounts. This causes games which cannot be played, its annoying for the opponent who gets paired with a deleted account (effectively same as 'bye' but with a small risk of first-move timeout when the deleted account get white), and it can possibly screw tournament tables later on

**To Reproduce**
1. Make an account and join multi-round tournament
2. Finish your game(s) and delete your account before tourney proceeds to the next round
3. See the deleted account being paired for the next round

**Expected behavior**
Automatically remove/resign user from any ongoing tournaments when they remove their user account. 

For example, see game https://online-go.com/game/51636396 

ps. i think i've reported this earlier too, but wasnt able to find my report on github. Sorry if its a duplicate >__>

**Comment by BHydden** [comment]
Yeah this is fair, resignation from all ladders and tournaments should be one of the steps in the account deletion process.

**Comment by anoek** [comment]
I fixed this 3 days ago actually :) It's not a retroactive thing though, however I did disqualify that user.
