### ISSUE TITLE
Email notifications of Ladder games inconsistent

### ISSUE THREAD

**Issue by David263** [online-go/online-go.com#2197]
**Describe the bug**
When the opponent moves in a 9x9 Ladder game, I sometimes receive an email notification, and sometimes not. The OGS home page notification circle this morning contains a 2, meaning there are two games waiting for my move, yet I did not receive an email notification. In the last week I think I did receive one or two email notifications, but did not receive many others.

**To Reproduce**
I'm sorry. I have no idea how to reproduce the behavior. Either join the 9x9 Ladder and actually spend a few days waiting to see if you are notified (don't forget to enable email notifications in the Settings), or else trace the email notification code.

**Expected behavior**
I expect to be notified on each and every 9x9 Ladder game that is ready for my move, without any optimizing to remove notifications.

**Screenshots**
I can't see how a screenshot would help.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Home
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**
 - Version [e.g. 22] Version 111.0.5563.65 (Official Build) (64-bit)

**Additional context**
My email client is Thunderbird. I have no evidence that my usual emails other than from OGS are not received, and evidence that expected emails other than from OGS are received. My spam email folder contains no OGS notifications. The most recent OGS notification received in the past was around midnight of a full day ago, which was several moves back.

**Comment by anoek** [comment]
Do you happen to leave a browser window open to online-go.com somewhere? Notifications wont be sent out if there is.

**Comment by David263** [comment]
Yes, I always leave a browser window open to my home page, so I can check to see if there is a game waiting for me even though I received no OGS notification. It makes no sense to me to optimize away the notification just because a window is open--I didn't even think of that. Please remove this useless optimization. Just because a browser window is open doesn't mean that it is VISIBLE to the user (unlike OS notifications, which are visible). If email notifications are requested, they should be sent. Did you conduct a poll to find out what other players think? If not, I suggest a poll, so that OGS developers do not make a decision that users don't expect.

If you must retain this "feature", for any reason, please describe it prominently in the Ladder and Correspondence game windows, so that users will know about it. Thanks.

Let me explain a little further, so you won't think I am being unreasonable. I rely on email during the day. When I receive an email saying I can move in one of the slow Ladder games, I want to move right away. So I want a window to OGS available in my open browser tabs so I can switch to it immediately. There is no good reason why I should have to find and select a bookmark to OGS when browsers support open tabs.

**Comment by anoek** [comment]
You might want to consider enabling desktop notifications: https://online-go.com/settings/general That will give you desktop notifications right away when it's your move when the browser is open.

People don't want a flood of move emails all the time, and we're talking more than an order of magnitude more emails being sent out (which would bump our email costs to the several hundreds of dollars, which is a bad use of funds considering desktop notifications are free and don't kill your inbox).

At some point here I'm going to overhaul the notification system to better support intelligent email batching and push notifications for browsers and phones, but the trend will be more towards pushing the real time notifications towards the push notification systems and moving away from email being so fast to notify players it's your turn probably (though I'll probably include some preferences with that so for those that want a flood of emails can tune it to their wants).

Anyways, yes to answer the original issue here, it's because the browser is open, turning on desktop notifications is the best option currently.

**Comment by David263** [comment]
My desktop notifications setting has been On (blue and to the right) for a long time. I do recall that I received OS notifications some time ago, but they may have stopped when I switched from using Firefox to using Chrome (because Firefox had gotten so buggy). When my browser asks me whether I want to enable notifications, I answer 'yes'.

So I would like to turn off email notifications and turn on OS notifications, but this apparently doesn't work.

But your main issue seems to be the expense of sending email as compared to OS notifications. I don't understand this, as email should be free, as part of the Web infrastructure.

I have written several applications that send email, using the MIME standard directly and also using the PHP library available right here at https://github.com/PHPMailer/PHPMailer . The library works very reliably and is FREE.

**Comment by anoek** [comment]
If you go to https://online-go.com/settings/general is the desktop notifications option still on? It should work fine on chrome and firefox unless something got turned off somewhere along the line.

Re Email, if you want any sort of reliability in terms of deliverability,  then no, email is not free. A ridiculous amount of work goes into getting good messages to willing recipients  while keeping out all of the riffraff. Even with professional services from big companies there's still failures in delivery, but it's a whole lot less than if you setup some random VPS to do outbound email (which will simply be blacklisted by the majority of the big email receivers.)

That said, cost isn't the primary concern, but I don't think it's a common desire to have emails for every move even when you're actively on the site, that'd be a lot of email in everyones mailbox! 

Anyways, browser notifications are the better solution for this all around, those already work you've just gotta go enable them. Those can also be disabled within the browser, if you ever accidentally say "no" to notifications you have to go digging through your browser settings to turn those back on. On chrome, open settings > Site Settings > Notifications and make sure it hasn't been blocked by accident.

**Comment by David263** [comment]
Concerning OGS notifications, as I said, they are ON in the Settings. But I get no notifications. I checked in the Chrome settings and notifications are allowed for online-go.com. I don't understand this, but it is not working.

Concerning email, notifications are only outgoing from the OGS server, so there is no issue about spam here. Also, as I said, the PHP library is reliable. It is used in many quality products on the Web. The developer once sent me an impressive list. Even if OGS programming never uses PHP, a one-file PHP interface to the PHP email library is easy to write--I can even send you mine to use as a sample/model. PHP can be called from most programming languages, or can be run by HTTP get or post.

Concerning "many" email notifications, there should be a separate option for blitz, live, and correspondence games, because it is obvious that sending an email notice for every interactive game would rarely be wanted. Yet sending an email notice for correspondence games could be quite useful, except for people who don't care if they timeout.
