### ISSUE TITLE
Blocking players is buggy [bug]

### ISSUE THREAD

**Issue by jmdingess** [online-go/online-go.com#220]
### Summary

Can't think of a way to sum this up succinctly:
If you click a player's name and hit block, on the menu that pops up, there are two boxes:
- Ignore chats and private messages
- Block user from accepting my open games

Clicking the second box, refreshing, and pulling up the menu again gives unexpected behavior.
I expected to have the second box ticked and the first unticked, but instead, the first was ticked and the second unticked. 
Checking the chat, I could still see the user's messages even though 'ignore chats and private messages' was ticked.

I unticked the first box and reticked the second, refreshing again, and this time, both boxes were ticked. 
I now wanted to un-block them, so I unticked both boxes.
Refreshing again, only the second box was ticked. I unticked it and refreshed
The second box was still ticked. Repeating this step ad nauseum has changed nothing, and refreshing without changing anything doesn't help either.

I conducted this experiment in the first player since someone mentioned in chat that it was glitching for them, too, except their issue was that they WANTED to block someone and couldn't get it to stay ticked.

### Environment

 * Operating system: Windows 10
 * Browser: Google Chrome
 * Browser Version: 57.0.2987.133 (Official Build) (32-bit)

### Steps To Reproduce:

1. Go to OGS
2. Click A user's name and the block button, hit either buttons, refresh
3. Repeat 2 until it bugs out for you too
4. See that buttons are not ticked or unticked as they should be

### Additional Information:

OGS username: jmdingess
User I blocked: cici

I don't actually want to block them, I only did so because they mentioned it was bugging out.

https://youtu.be/dbE0qpdmwAo

**Comment by anoek** [comment]
Thanks for the recording, helped to spot it much faster :)
