### ISSUE TITLE
"Stalls game at start" could be added to reasons for reporting

### ISSUE THREAD

**Issue by nicolasrochette** [online-go/online-go.com#2207]
I've had the problem twice within a few days; new unranked users that disconnect at start. This doesn't seem to fit into "Escaping" nor into "Game stalling ("User is stalling at the end of a game to annoy their opponent.").

There's always "Other". I'm not sure reports are handled on the mods' side so I'm not sure if this would be helpful to have a separate case, but from the player side it would be comfortable not to have to improvise and explain a reason, and reassuring to know that such cases are a known occurrence and are treated accordingly

Thanks!

**Comment by GreenAsJade** [comment]
Thanks for your suggestion.

The intent is that "Escaping" is synonymous with "disconnection" - you can definitely use that in this case.
