### ISSUE TITLE
The tournament is finished but the rankings are not generated

### ISSUE THREAD

**Issue by SuperIRabbit** [online-go/online-go.com#221]
### Summary
*Briefly describe the issue you are reporting*
This tournament (https://online-go.com/tournament/2495) is finished but the rankings are not generated
### Environment

 * Operating system: MacOS
 * Browser: 
 * Browser Version:

### Steps To Reproduce:

1. Go to https://online-go.com/tournament/2495
2. The rankings are not shown

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
Fixed this yesterday
