### ISSUE TITLE
Feature Request: Date and time of move in Analyze Game

### ISSUE THREAD

**Issue by cliffordwolf** [online-go/online-go.com#222]
I don't know if this information is stored on the server side, but if it is, it would be nice to have a way to display the time and date a move has been played, when in Analyze Game mode.

I've missed this a couple of times, but now I am missing it for a petty reason: In one of my correspondence games my opponent paused the game some time ago and I only noticed it now. I'd like to know when his last move was so I know when he stopped playing.

**Comment by Nazgand** [comment]
A current workaround is to say something in chat after each of your moves. Certainly not perfect, and I have wanted the same thing.

**Comment by purpleyuan** [comment]
Is this still in the pipeline if it's been marked "Done"? This feature is still widely requested.

**Comment by benjaminpjones** [comment]
No, it was just closed as stale (not done). But there's a duplicate issue that's still open, so that is why we didn't re-open.

**Comment by purpleyuan** [comment]
Gotcha. I saw the duplicate but didn't see it on the issue organization project, so I wasn't sure if it was still on people's radar. Thanks!

**Comment by benjaminpjones** [comment]
Oh hmm.. I didn't think about the issue tracker. Maybe we should close the other issue, and re-open this one?
