### ISSUE TITLE
How to generate Application Specific Password?

### ISSUE THREAD

**Issue by Hong-yu1999** [online-go/online-go.com#2220]
I want to use the API, but I can't find where to generate the Application Specific Password, and I don't seem to find it on the setting page.Please help me. (..•˘_˘•..)

**Comment by anoek** [comment]
Are you referring to an oauth token? That'd be here: https://online-go.com/oauth2/applications/ 

I'm not sure how necessary that is these days though. If you just want read access, pretty much all endpoints are wide open, just https GET and away you go.

**Comment by Hong-yu1999** [comment]
I want to use my Go engine to compete with bots on OGS to evaluate my engine's chess power

**Comment by Hong-yu1999** [comment]
In the Authentication section of the API documentation, it is pointed out that username and password are Application Specific Passwords, but I do not know where to generate them. (I have already generated an application)

**Comment by anoek** [comment]
Ah, that API key is still on the profile page of the bot. You have to be logged in as the bot operator, visit the bot's profile page, and it'll be there on the right side.

**Comment by Hong-yu1999** [comment]
Logged in as the bot operator?How should I register myself as a bot operator?

**Comment by anoek** [comment]
Message a moderator (you can message me, anoek) from your main account and let us know what account you'd like activated as a bot. Once activated, go to that bot's profile page and you'll see the place to generate the key.

**Comment by Hong-yu1999** [comment]
Sorry, this is my first time using OGS. Can you tell me how to send you an email

**Comment by anoek** [comment]
There's a search box at the top of the nav bar. Type in `anoek` , click my name, click 'anoek' on that page and it'll make a popup box with a "Message" button. Click that, and you can send me a direct message there.

**Comment by Hong-yu1999** [comment]
OK.Thank you very much.
