### ISSUE TITLE
UI Enhancement request -- add tooltips to the right-hand-side slide-out menu buttons.

### ISSUE THREAD

**Issue by bradwood** [online-go/online-go.com#2229]
**Is your feature request related to a problem? Please describe.**

It's not really a problem, but more of an annoyance. I'd like to keep the slide-out menu on the right permanently minimised so I can see the stuff behind it. But, I keep forgetting what the icons do when I do this.

**Describe the solution you'd like**

My request is simple: add a descriptive tool-tip which pops up on hover over those buttons, describing what they do. This way I can keep the slide-out menu permanently minimised, but still remember what each button does.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by benjaminpjones** [comment]
Seems to be fixed by #2259 - @bradwood @loganbruce let me know if I'm missing anything!
