### ISSUE TITLE
Add prompt system for translation help

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#226]
We have a lot of translations that need updating, I imagine if people were nicely prompted requesting help and knew how easy it is to do so, we'd be able to keep our transitions much more up to date and fill in some of the big language gaps

**Comment by roy7** [comment]
Yeah that'd be awesome. Someone in chat the other day wanted to update Portuguese translations, said he had put some better ones in forums last year but they were never imported in. I had no idea where to suggest he go if there's a better way to submit them...

**Comment by joachimneumann** [comment]
Hi,

I have clones this git repository in the hope to be able to correct some translations, but I could not find where the translations are stored (or generated). How can I contribute, being a experienced programmer, but without much web app experience?

**Comment by anoek** [comment]
@joachimneumann The translations are stored and generated from here: https://translate.online-go.com/ 

What this issue is tracking is some system of

a) Detecting when a user's browser has a preferred language setting that we don't support
b) Detecting when a user's current translation is incomplete
c) Create a easily dismissable but perdiodically recurring (like every few weeks or so) message somewhere letting them know that if they would like to help translate, head on over to https://translate.online-go.com/

I think on the server side I need to add some ways of supporting `b`

**Comment by joachimneumann** [comment]
Hi anok, thanks for answering my question (although not related to this issue).
I am happy to see that my the German Translations that bothered me are already corrected on the OGS Translation Server and (unrelated) I am also happy to see that white circle that indicates the last move is now centred correctly. Keep up the good work!
