### ISSUE TITLE
OGS enters Place White Stones mode unexpectedly

### ISSUE THREAD

**Issue by David263** [online-go/online-go.com#2263]
**Describe the bug**
From Analyze Mode, clicking in the move tree enables Place White Stones mode unexpectedly.

**To Reproduce**
In game https://online-go.com/game/53708243, starting in Analyze Mode from move 25, I clicked on Estimate Score, then clicked on Back One Move arrow, then clicked on move 26, which is white, then hovered the mouse cursor over the board. It is shown as faint white instead of black, and when I click it, it makes a second white move in a row both on the board and in the displayed move tree. I can then make any additional moves and they all show up as white. I never clicked Place White Stones icon.

**Expected behavior**
I expected mouse clicks to place alternating colors, and not starting with white.

**Screenshots**
I don't see a way to add a screenshot. When I went back to my Chrome tab to make a screenshot, the game tree has become pruned and the problem no longer appears.

**Desktop (please complete the following information):**
Windows 10 Home
Chrome:
"Nearly up to date! Relaunch Chrome to finish updating.
Version 113.0.5672.126 (Official Build) (64-bit)"

**Additional context**
Windows has been trying to get me to move to Windows 11, but the installation fails due to insufficient disk space, if that is relevant. I will try restarting Windows. After restarting Windows and Chrome, these instructions failed to reproduce the bug. I guess this was a Windows or Chrome bug. I don't see any way to mark this bug as "not reproducible".

**Comment by benjaminpjones** [comment]
I took a look at that game, and did the same steps in the "To reproduce" section:

- move to move 25
- clicked Estimate
- back one move
- click move 26

And my hovering is black as expected.  @David263 are you able to reproduce again and provide detail on how to recreate this bug?  Otherwise, I am inclined to close this issue.

**Comment by anoek** [comment]
Feel free to re-open if it's still an issue and reproduction steps can be made
