### ISSUE TITLE
UI does not display user after SSO sign in

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#2302]
**Describe the bug**
When I log in using Google SSO, I am redirected to the Watch page and it looks like I am not logged in.  Refreshing the page fixes this issue.

**To Reproduce**
1. If logged in, log out.
2. Go to the Sign In page (`https://online-go.com/sign-in`)
3. Click **Sign In with Google**
4. Observe: you are redirected to the homepage, but it looks like you are logged out.
    - In the top right, a link to the sign in page
    - The central content is the **Observe Games** page, not the user's games

**Expected behavior**
The nav bar should show the user that is logged in, and the central content should be the user's games and other info.

**Screenshots**

https://github.com/online-go/online-go.com/assets/25233703/29ef97be-c580-44fb-8272-980db076eb5d

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4
 - Browser: Firefox 114.0.1 [64-bit]

**Comment by JoshuaNascimento** [comment]
This seems like a relatively simple fix as when you login with a direct account the login method also forces a refresh of the window which then allows it to update the user information. 

But with logging in through third-party this functionality doesn't exist. I could definitely take a crack at this but I am unsure how I would get these social logins to work on a local server to do testing.

@anoek or perhaps @GreenAsJade would you mind pointing me in the right direction to get social logins to work locally? 

Looking at the Network Activity in browser it's clear that when running locally a call is made to "http://dev.beta.online-go.com:8080/login/google-oauth2/" but the auth flow stops there and i'm simply redirected back to the site.

**Comment by anoek** [comment]
Yeah unfortunately I don't think it's going to work locally, SSO providers lock down the urls that you can redirect to pretty tightly.

**Comment by JoshuaNascimento** [comment]
Would there be anyway for me to test this prior to making an official PR?

**Comment by GreenAsJade** [comment]
I think not, which is perhaps one reason why it's a laid there for a while.   Does SSO work on beta, when logging in direct?   If that's the case, then you can make a PR and get it deployed there for testing.    

It's painful enough that personally I think we'd love you to try no matter what ... let's get it fixed eh 😅
