### ISSUE TITLE
See game challenge after closing notification alert

### ISSUE THREAD

**Issue by gmanzur** [online-go/online-go.com#2313]
**Is your feature request related to a problem? Please describe.**
A few days ago I was playing a tournament and noticed that if I missclick and close the game challenge notification by pression the "x" button I could not regain access to that challenge (or maybe the place to find such challenge after dissmising if by mistake is too obcure)

**Describe the solution you'd like**
A easy way to get access to current game challenges that I have not rejected yet. Closing the notification should not count as a rejection.

**Comment by BHydden** [comment]
All pending challenges should be visible on your home page.
https://online-go.com/

**Comment by gmanzur** [comment]
Got it! Thank you!
