### ISSUE TITLE
Stone drawing can leave artifacts on the board in some cases

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#232]
### Summary

From: https://forums.online-go.com/t/minor-graphics-bug-tiny-black-white-lines/11710

At some board sizes, stones will leave behind small lines as you hover around the board.

![image](https://cloud.githubusercontent.com/assets/168460/25304590/5aefdba0-2738-11e7-9cd8-f5783be4e6aa.png)

I have also seen this, it only happens with particular board sizes. This is probably related to the stone being drawn slightly outside the box that gets redrawn to erase a square.

Possibly related to changes introduced by #144 and/or #198 since it seems to be a recent thing.

**Comment by lemurek** [comment]
What resolution was it ?

**Comment by lemurek** [comment]
Oh I see! :) It's Macbook's Air native resolution :D
