### ISSUE TITLE
Cancelling a custom game challenge shows "Are you sure you want to delete this Rengo challenge" even when it isn't rengo

### ISSUE THREAD

**Issue by jmdingess** [online-go/online-go.com#2340]
**Describe the bug**
When you cancel a custom game challenge, it displays a modal with "Are you sure you want to delete this rengo challenge?" even when the challenge is not for a rengo game

**To Reproduce**
1. Go to Play page
2. Click on the 'Create' button for a custom game
3. Create any challenge -- even one that isn't rengo
4. Cancel the challenge
5. See that "Are you sure you want to delete this rengo challenge?" appears, even if your challenge isn't rengo.

**Expected behavior**
Only rengo challenges display the modal asking about rengo

**Screenshots**
![image](https://github.com/online-go/online-go.com/assets/18383541/66900650-9a69-422e-8fbf-581a8f77eecd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 115.0.2

**Comment by jmdingess** [comment]
Just for my opinion - I prefer not getting asked to confirm when cancelling the challenge rather than just fixing the wording -- but will get used to whatever you choose

**Comment by benjaminpjones** [comment]
Should be fixed by https://github.com/online-go/online-go.com/pull/2339
