### ISSUE TITLE
No group specified when someone wants to join it

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#2344]
When you are admin of a group that is NOT open for public and someone requests to join it, you get a notification like this without any info about which group they want to join.  In case you happen to be an admin on multiple closed groups it would be nice to see which group they want to join. 

<img width="217" alt="Screenshot 2023-08-13 at 14 13 03" src="https://github.com/online-go/online-go.com/assets/29932807/e5451ba8-4cd1-40f2-a9eb-5ca3eb57faa4">

**Comment by benjaminpjones** [comment]
Duplicate of https://github.com/online-go/online-go.com/issues/1401?

**Comment by kobakitty** [comment]
Ah yeah indeed ^_^
