### ISSUE TITLE
Ranked/Tournament games sometimes don't affect rating. and it's a jarring experience. 

### ISSUE THREAD

**Issue by csessh** [online-go/online-go.com#2345]
**Describe the bug**
Sometimes, a ranked game ends without affecting players' rating. 
For example: https://online-go.com/game/55745366
This tournament game ended as Black resigned. 
However, this game doesn't seem to be counted towards each player's rating. 

**To Reproduce**
I, unfortunately, do not know how to reproduce this. It sometimes happens.

**Expected behavior**
If neither of the player mass timeout, their ratings should change according to the game result.

**Comment by csessh** [comment]
Another game: https://online-go.com/game/56118490
So that's two consecutive ranked/tournament games that ended the same way.

**Comment by csessh** [comment]
![Screenshot 2023-08-17 at 3 07 03 pm](https://github.com/online-go/online-go.com/assets/5171823/906f2af6-2fc2-4cc1-94b4-f03f7eb9cfe0)

The last game that shows up on this graph was on the 15th. It left out two games. 

![Screenshot 2023-08-17 at 3 07 41 pm](https://github.com/online-go/online-go.com/assets/5171823/45642925-81d4-48fe-a734-a4008b28783f)

**Comment by csessh** [comment]
Make it 3 in a row: https://online-go.com/game/56019101

**Comment by kobakitty** [comment]
Yeah seems like there is currently some lag with the rating system, i hope it will be resolved soon. Theres probably some backlog now but i think it wont take long update once its been fixed

**Comment by csessh** [comment]
thank you for the clarification, @kobakitty
I'll close this one then
