### ISSUE TITLE
Display warning message when connection loss is detected

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#235]
### Summary

When our pings start not coming back or are severely lagged, or we otherwise get a hard `disconnect`, we should display a warning message to the user.

**Comment by Nazgand** [comment]
This warning should also make a sound.

**Comment by BHydden** [comment]
I believe this has been implemented now with Zeus.

**Comment by anoek** [comment]
Sorry this is actually referring to notifying the player that got disconnected, that they are disconnected from the site. In v4 we had a banner pop up on the top of the screen that let you know you, this appeared anywhere, in a game, on the chat page, etc.

**Comment by BHydden** [comment]
huh... I'd have thought disconnecting was self-evident, but fair enough my mistake

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
