### ISSUE TITLE
Add filter for handicap games

### ISSUE THREAD

**Issue by fnoaman** [online-go/online-go.com#2358]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I enter a game from the game list and find out it's a handicap game (It's hard to always remember to check). I then cancel it and I imagine the other person to be frustrated as well as they have to recreate the challenge.

**Describe the solution you'd like**
Being able to filter in/out handicap games from the game list.

**Current filters**
![Current state](https://github.com/online-go/online-go.com/assets/4604419/f6799f05-e8c1-4ead-bf93-bbe405689c76)

I've poked a bit in the code and managed to make it work. 
The following are different layouts i have implemented :

- **The crude way**
![proposal 1 - crude](https://github.com/online-go/online-go.com/assets/4604419/ef8611d4-4600-415f-8c41-fd17f5e5d499)

- **Grouped by rows**
![proposal 2 - rows](https://github.com/online-go/online-go.com/assets/4604419/4d834e3b-7c2c-4efc-9f91-f22b13dc95f1)

- **Grouped by columns**
![proposal 3 - columns](https://github.com/online-go/online-go.com/assets/4604419/7c651224-753b-4967-b834-bd3de3407603)

My personal favorite is the third one which I think makes more sense.
I don't know what to do about the icon however, it's a copy of the "ineligible" icon for now, I'd love to know your thoughts on what color and shape to use.

**Describe alternatives you've considered**
A cleaner alternative would be to have drop-down filters on each of the columns in the list, something like the following (not implemented yet) :
![Clean way](https://github.com/online-go/online-go.com/assets/4604419/1c511d19-acae-4dc5-a3be-49dd65d7f604)

What do you guys think ?

**Comment by anoek** [comment]
I agree on both accounts, the third option for an easy add, and adding support for drop down filters is probably even cooler.

As for an icon / color to use, I guess if we're going around the color wheel, purple is unused, so are red and yellow but those seem sub optimal for readability on white and for being the "danger" color.. so purple I guess?
