### ISSUE TITLE
Placing stone does not always make sound in 'Plan Conditional Moves'

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#236]
### Summary
see title

### Steps To Reproduce:

It doesn't happen all the time, but:
Step 1: Go to 'Plan Conditional Moves' and place two stones.
Step 2: Repeat step 1 until you notice that a move does not make a sound. The soundless move seems to usually if not always be the first move after opening 'Plan Conditional Moves'.
Edit: it sometimes also happens without closing 'Plan Conditional Moves', and the silent move does not need to be the first one.

**Comment by Nazgand** [comment]
This also sometimes happens in 'Analyze Mode'.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
