### ISSUE TITLE
Pressing the up and down arrow keys in 'Plan Conditional Moves' can show variations from 'Analyze Game'

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#237]
### Summary

Said variations do not need to be in the conditional move tree.

### Steps To Reproduce:
Haved variations on the 'Analyze game' tree.
Open 'Plan Conditional Moves'.
Mess around with the arrow keys, specifically the up/down ones.
Find that the arrow keys do not always work to traverse the conditional move tree.

### Additional Information:
![screenshot 2017-04-22 20 35 22](https://cloud.githubusercontent.com/assets/499794/25308054/482daf74-279c-11e7-8785-7318fb051b6e.png)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
