### ISSUE TITLE
Community Tab UI Improvements

### ISSUE THREAD

**Issue by kevincoleman** [online-go/online-go.com#2375]
### Discussed in https://github.com/online-go/online-go.com/discussions/2373

Result of discussion: go ahead and try the improvements, possibly including some niceties like resizing the sidebars manually (maybe iteration number one will just use media queries wisely).

![](https://user-images.githubusercontent.com/445707/269775120-e80ca64a-75ac-4376-9dff-ba889c78e93a.png)

- [x] Add padding throughout interface
- [x] Improve sidebar colors for visual heirarchy
- [x] Test in both light and dark mode
- [x] Test in variety of sizes (media queries)
- [ ] Consider/implement resizable sidebars

**Comment by kobakitty** [comment]
Hi! Is the  "Consider/implement resizable sidebars" still on the table? Would be nice to make those boxes smaller

**Comment by kobakitty** [comment]
> @kobakitty Definitely still on the table. Just not the first iteration. You're welcome to PR it as well!

Heh i'd love to, but i dont know how xD

I feel like best would be some "click and drag" solution so people could fit those panels according to their screen and personal preferences, current ones are maybe bit too wide for laptop screen ^^
