### ISSUE TITLE
Allow requesting an undo to any previous move using the 'Analyze Mode' tree

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#238]
When undoing multiple moves, it is a bit annoying. I suggest that when the 'Analyze Mode' is positioned on any move that has been played, pressing the trash button should result in a request to undo that move and all the following moves. Currently the trash button just shows a 'The current position is not an explored branch, so there is nothing to delete' error. It would also be nice if the trash bin had a different icon when pressing it would result in undoing moves.
The undone moves should not actually be deleted so that they could be looked at later.

This would be very helpful when tutoring new players; instead of them [resigning the game which is probably unranked anyway and replaying the first n moves from the last game that seemed reasonable] or doing a large amount of undos, they could just immediately undo all their moves after their last good move.

**Comment by Nazgand** [comment]
Also, when it is your turn, outside 'Analyze Mode', there should be an 'Undo' button that should request the last 2 moves undone.

**Comment by koshogs** [comment]
I like the second part better. It often happens that after a misclick or atrocious move, your opponent responds very quickly (preventing a standard undo request) so it would be useful to be able to request an undo when it is your own turn and that request would simply go back to your previous turn (ie. 2 moves back).

Analyze mode is often disabled anyway so I see that option as more of a cool extra feature and probably harder to implement.

**Comment by koshogs** [comment]
See also: https://github.com/online-go/online-go.com/issues/328
