### ISSUE TITLE
Game constantly resetting to current position when in analysis or conditional moves mode

### ISSUE THREAD

**Issue by adamreisnz** [online-go/online-go.com#2397]
**Describe the bug**
Whenever you go into analysis or conditional moves mode for an extended period of time (e.g. more than 20-30 seconds), the game position will randomly reset itself to the current position, causing you to lose all your analysis progress.

This is highly frustrating and has been a bug for as long as I can remember. I had hoped since this is such an obvious bug that it would be found and addressed, but it seems it's not on the radar of the developers so I'm raising a ticket for it here.

**To Reproduce**
1. Go into analysis mode
2. Do analysis
3. Observe the game being reset at some point to the current state

**Expected behavior**
For the board position not to be reset when you're in analysis mode or conditional moves mode.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4XL
 - OS: Android 12
 - Browser Chrome
 - Version Latest

**Comment by anoek** [comment]
Hello, this is most likely because your internet connection is dropping every 20-30 seconds. Once a connection is re-established we have to synchronize the game state, and because things might have changed in the meantime this means the analysis and conditional moves might be invalid, hence the resets.

**Comment by adamreisnz** [comment]
No, that is not correct. My Internet connection is very stable and nit
dropping every 20 seconds.

Can you please implement a simple throttle to delay this message, it really
shows up way too frequently.

**Comment by adamreisnz** [comment]
Sorry thought this was about the other issue I raised.

But same answer applies. My Internet connection is stable and nit dropping.

Also, this is for correspondence games, so nothing has changed in the
meantime.

Surely ogs can detect if something has changed, and if it hasn't just leave
my analysis moves as they were instead of resetting the whole position?

**Comment by anoek** [comment]
> No, that is not correct. My Internet connection is very stable and [not] dropping every 20 seconds.

Given you're seeing the disconnect message frequently as reported in https://github.com/online-go/online-go.com/issues/2398 , something is definitely going on with your connection. What I suspect is going on is your wireless provider is terminating "long running" HTTP connections after 20-30 seconds or whatever it may be. This used to be pretty common about 10 years ago, though with the advent of 4g and 5g most carriers have stopped doing that (thankfully), but I suspect your carrier, whether it be the one you give money to or a regional provider that might contract with them for the tower you are on, is terminating "long running" TCP sessions.

> Surely ogs can detect if something has changed, and if it hasn't just leave my analysis moves as they were instead of resetting the whole position?

A couple attempts have been made to do that in the past but it's not as straight forward and simple as you might think. It should very well be possible, it's just not that big of an issue these days and it is more work than you might think, so it hasn't gotten much attention recently.

**Comment by adamreisnz** [comment]
This has been happening out with full 4g connection, inside with full and
stable running wifi, abroad overseas at various Airbnb's, etc.

I find it very unlikely that I've been plagued by poor Internet connections
all this time.

I think it's more likely that this has to do with how the app runs as a PWA
app, which I know can be notoriously challenging to deal with.

It's worth noting that I don't experience these problems on other devices
at home, so hence why I suspect it's only affecting mobile.

I know quite a bit about app development for web given that I've developed
and have been running a successful SaaS company for 8 years, so if this is
an area you are having trouble with I am more than happy to take a look and
see if there is anything I can do to help.

Finding the time will be a challenge though.

**Comment by anoek** [comment]
If you have the capability to extract some sort of logs that might lend a clue as to why this might be happening on your device, that might be very helpful in diagnosing and resolving the issue.
