### ISSUE TITLE
New "offline" indicator shows up too quickly and too often (false positives)

### ISSUE THREAD

**Issue by adamreisnz** [online-go/online-go.com#2398]
**Describe the bug**
There appears to be a new red "offline" indiciator in the app. But it appears way too quickly and often, and I see it every time I open the app on my phone. Given its bright red colour this is very distracting and annoying.

**To Reproduce**
1. Don't use the app (PWA) for a while
2. Open the app again
3. See offline alert as the connection is established
4. Note this can even be reproduced just by keeping the app active, letting your display time out, and then unlocking your phone again. Even in this case the alert shows up for a brief moment.
5. It will also appear very briefly randomly while being normally connected. Just now while writing this sentence, I've seen it pop up 4 or 5 times. It's way too sensitive at the moment.

**Expected behavior**
For there to be a grace delay before showing the red offline indicator. Give the app a few seconds to try and establish connectivity. It's natural for it to not be online when the app is not in use.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4XL
 - OS: Android 12
 - Browser Chrome
 - Version Latest

**Additional context**
Can easily be resolved by applying a timeout/delay before showing the message.

**Comment by GreenAsJade** [comment]
I'm hoping that this is fixed by https://github.com/online-go/online-go.com/pull/2399 (as mentioned [here](https://forums.online-go.com/t/slow-internet-disconnected-warning/49465/10?u=greenasjade) )

When that's in Prod (soonish I think) ... if this still isn't fixed then we'll need more info, like screenshot of the warning (to be sure what you are talking about) and ideally console log (not easy in PWA, but ... ideally :) )

**Comment by adamreisnz** [comment]
Thanks, I will keep an eye out for the fix.

I do think this has to do with #2397 as well, as I've observed that the "offline" warning showing up coincides with the "analysis" board position resetting itself.

So the game clearly things I've lost connection, but looking at my Wifi or 4G connection there are no drops. Other apps don't have any issues and are not reporting any internet outages, e.g. streaming videos, chat, work related apps, etc.

Have checked wifi and internet connectivity log and it's at 100% with no drops/lag.

I wonder if Android is at times cutting off internet to the PWA, but that seems unreasonable.

As I mentioned in the other thread, I've built a SaaS app with PWA as well, it's used by ~300k people, I use it myself regularly as well, and we've also built in a network connectivity check but it never fires this frequently or aggressively.

I assume OGS is using sockets / socket.IO for its connectivity? From my experience with it, that does occasionally disconnect, but it has quite a robust automatic reconnect logic.

Is it possible to delay the logic that is triggered when a disconnect is detected by say 5000ms, and if the connection is back before that time has passed, just keep the app as is without showing the warning and resetting the board position?

**Comment by GreenAsJade** [comment]
Yeah, it's using sockets.  I have seen some mysterious disconnect/reconnects in logs from time to time.

The "disconnect" warning is in response to a _positive_ indication from the socket that it's definitely disconnected.

Whether it's going to robustly reconnect is not especially helpful if you are playing live and want to submit a move right at that moment.

I wonder if your owns SaaS app has this kind of "somewhat real time" or "must be connected at the moment we need it" kind of requirement?

The fix just recently deployed is to not distract you with a banner about it if you're not playing live.

**Comment by GreenAsJade** [comment]
Let's close this, on the grounds that theoretically it's fixed :)

If it's not fixed, please raise a new one with new details and a screenshot.

Thanks!

**Comment by adamreisnz** [comment]
> I wonder if your owns SaaS app has this kind of "somewhat real time" or "must be connected at the moment we need it" kind of requirement?

Yes, as a matter of fact it does. There is an access control system hardware component, and it receives various commands and sends info through sockets as well. There is a central socket IO server and it handles connections between all access control systems and clients.

While there are some occasional disconnects, they are nowhere near as prevalent/frequent as I've observed with OGS, event at sites with extremely fragile internet connections (e.g. remote rural areas with 4g internet).

> Let's close this, on the grounds that theoretically it's fixed :)

Sounds good, I'll keep an eye out for it, but today I don't recall seeing a red banner!
