### ISSUE TITLE
Stones and lines do not render on the board.

### ISSUE THREAD

**Issue by edre** [online-go/online-go.com#2403]
**To Reproduce**
View any game view on OGS, see only the board background.

**Expected behavior**
Visible background, lines, and stones.

**Screenshots**
![Screenshot 2023-10-24 10 33 52](https://github.com/online-go/online-go.com/assets/1291499/286f8dab-b28b-4cfd-a72e-769313a865f2)

**Desktop (please complete the following information):**
Google Chrome | 118.0.5993.88 (Official Build) lacros (64-bit)
Revision | 1d05652f52a55dcf9a7905af94949f2bc3a66306-refs/branch-heads/5993@{#1298}
OS | ChromeOS 117.0.5938.157

Cannot reproduce on Firefox 102.13.0

**Smartphone (please complete the following information):**
Cannot reproduce on Android Chrome.

**Comment by anoek** [comment]
If you open up the javascript console (ctrl+shift+i), are there any errors there?

Is this behavior the same when viewing a single game?

**Comment by edre** [comment]
The only error in the console is `The AudioContext was not allowed to start`.

The behavior is the same when viewing a single game.

**Comment by edre** [comment]
On a different machine on literally the same version of Chrome the issue does not reproduce.

Google Chrome | 118.0.5993.88 (Official Build) (64-bit)
-- | --
Revision | 1d05652f52a55dcf9a7905af94949f2bc3a66306-refs/branch-heads/5993@{#1298}
OS | Linux

I looked through about:flags, and they have all the same settings for every flag with `gpu` or `graphics` in it. I suspect the issue is with the firmware, or ChromeOS's new "lacros" setup.

**Comment by anoek** [comment]
Much appreciated for the extra details there. This isn't the first time canvas rendering has broken on newer versions of browsers, hopefully it resolves itself, or baring that hopefully I can reproduce it on a non ChromeOS device since I don't have one handy.

**Comment by edre** [comment]
I filed a bug against Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1495883

**Comment by edre** [comment]
Fixed itself after the latest Chrome update.

**Comment by anoek** [comment]
Great to hear, thanks for following up and letting us know!
