### ISSUE TITLE
Can't change the profile image (TypeError: Failed to fetch)

### ISSUE THREAD

**Issue by igorfv** [online-go/online-go.com#2406]
**Describe the bug**
I get this error when I try to upload a new profile picture.

**To Reproduce**
1. Go to your profile
2. Click on edit
3. Click on image and select a file
5. Click on saving does not save the new image

**Expected behavior**
No errors, been able to replace my profile image

**Screenshots**
<img width="462" alt="image" src="https://github.com/online-go/online-go.com/assets/191252/b215c514-54ec-46c5-91a7-f58dbc5296dd">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 
 - Version 118.0.5993.120

**Additional context**
I changed my profile picture multiple times and it always worked (sometimes I had top try 2 or more times, but it worked).
My profile in case it's exclusive to my account: https://online-go.com/user/view/1404134

**Comment by anoek** [comment]
Yikes, thanks for the report!

**Comment by anoek** [comment]
I was able to reproduce this with larger files on Chrome. Chrome seems fine with smaller files, and the larger test files worked fine in Firefox. Not sure what's going on yet.

**Comment by anoek** [comment]
It looks like smaller files <~100KB work fine regardless of original resolution, anything past that size seems to cause the error. The temporary workaround is to resize your images before you upload, or use a different browser (Firefox seems fine).

**Comment by anoek** [comment]
Alrighty, in theory a workaround for this issue is in place. I'd be curious to know if everything is working on your end too @igorfv
