### ISSUE TITLE
When the opponent chats or shares a variation while I am in another tab in the browser, I should hear a sound or be notified.

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#241]
This has been a problem during slow-paced live games.
I tend to read while playing slow paced games, waiting for the sound of the stone to be placed, but sometimes the opponent might have a question, and I might be minutes late in answering.
Currently, this can be solved with split screen, but a sound or a desktop notification would be much nicer.
Preferably a sound.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
