### ISSUE TITLE
Game list entries use twice the necessary vertical space

### ISSUE THREAD

**Issue by dexonsmith** [online-go/online-go.com#2418]
**Describe the bug**
Every game in the game list that has a clock and is NOT paused is followed by a blank line. This results in using twice the necessary vertical space.

**To Reproduce**
1. Start a few correspondence games that use some (any) time control.
2. Pause one of them.
3. Start a few games that don't use time control (no clock).
4. Start enough other games that the game list is a textual table, rather than pictures of boards (I think 12 or more does it?).
5. Observe the vertical space for game entries.

Note that every game with a clock takes two vertical rows, whether paused or not. The games that are not paused have a blank line. The paused games have a line that's mostly blank, but says "paused" (or "vacation", etc.).

**Expected behaviour**
Most games should take one row of vertical space. Only the paused game(s) should take two rows.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 17.1

**Additional context**
This used to do the expected thing, until cae93c52519786af0ebeaab9a31f54a1b5d2373e. That commit added a `<span class=transmitting>` to the relevant `<div>` for something to do with blitz games, and changed the `<div>` to always be emitted (whether or not the game was paused).

I have a patch that seems to fix the visuals for the case I'm bothered by (the display of a long list of correspondence games) by again suppressing the emission of the `<div>` when it's empty. But I'm not sure whether there's a reason it won't work correctly for the new `<span>` (I'm not sure how to trigger or test its behaviour).

The patch is commit f2ebda37ecbe88076c2116977ef834fb15e0c160, currently on a branch in my fork at https://github.com/dexonsmith/online-go.com/tree/hide-pause-and-transmit-when-empty. I can submit a pull request if it's the right general direction.

(Also, let me know if I should have started with a PR, rather than creating this issue... this is my first patch for the project.)

**Comment by dexonsmith** [comment]
@anoek, cae93c5 was your commit... is there a reason the `transmitting` span needs to be emitted all the time? If so, maybe only for blitz/live games?

(Or, if there's agreement this is an issue worth fixing, I'll submit the above patch as a pull request and we can discuss the right fix and/or how to test it there.)

**Comment by anoek** [comment]
Nope, it was an oversight and never the intent that that would ever show up in the game list (or anywhere but the main game page for that matter). Thanks for hunting that down @dexonsmith !

**Comment by dexonsmith** [comment]
Great! Created #2420 to fix.
