### ISSUE TITLE
When a move is played in a game that is not open, I should hear a sound or be notified.

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#242]
This was a problem for me today. On Discord, I told someone that I wanted to continue our game, but then noticed they were offline. I thought they didn't get the message, so I left my OGS tab on a different game, and was reading something in a different tab.
He waited about 7 minutes after making his move before he messaged me that he had been waiting. (he moved about 1.5 minutes after I messaged him)
I would like a sound to be played when an opponent moves no matter where I am on the OGS website. A desktop notification also works.

**Comment by anoek** [comment]
What browser and OS are you using? The stone sounds should play in the background already

**Comment by Nazgand** [comment]
Really? I double checked before reporting this. Is it not as loud?
Google Chrome Version 58.0.3029.81 (64-bit), Windows 10.

**Comment by anoek** [comment]
Nope should be the same volume.. seems to be working fine over here under chrome 58, though I am under Linux. I know they've been adding a lot of tab throttling and various things to prevent sites from playing audio ads in the background, so there might be something going on that isn't reproducible with just a quick refresh, change the tab, place a stone in a different browser, and hear the stone placement sound.

**Comment by Nazgand** [comment]
Are you willing to start a game with me now so I could attempt to recreate the situation? It was an unranked 6x6, I was white, komi was 0, chinese rules, no clock.

**Comment by anoek** [comment]
Sorry I misread, if the game is open in a background tab it'll play the sound, if the game isn't open and you're elsewhere on the site, you wont hear a sound

**Comment by anoek** [comment]
If someone else implements this, this feature needs to be optional with a setting you can control under `Settings` to turn on or off the audio and/or desktop notifications

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
