### ISSUE TITLE
Game cannot be ended

### ISSUE THREAD

**Issue by HumbleSolipsist** [online-go/online-go.com#2421]
**Describe the bug**
Game cannot be ended. Will not allow me to resign, ie I can click the "resign" button, and confirm that I want to resign in the popup menu by clicking "yes", but nothing happens when I click these buttons. My opponent and I tried both passing, but the scoring refuses to finalize. I have clicked "accept removed stones", but it does nothing. The scoring timer has run out, but it does nothing. I have clicked "auto-score", but it does nothing. In addition, the auto-scoring seems to have failed to properly assess the 2 players' respective territory. I do not yet know if the game would end ordinarily from timeout, I have not tried clicking "Cancel and resume game".

**To Reproduce**
Unsure how to reproduce, or if it is reproducible. If you want to attempt to reproduce, simply play a game and try to end it in any way that one would ordinarily be able to end a game (other than timeout, which I have not tried).

**Expected behavior**
When clicking "resign" and then "yes", the game should end immediately, resulting in a loss for the player who resigned. After both players have passed and the clicked "accept removed stones", the game should end immediately, and assign the appropriate score to each player, resulting in a higher score for the player with more points.

**Screenshots**
![image](https://github.com/online-go/online-go.com/assets/16962618/996cc77d-fce7-4851-b752-eb51eb90ae48)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS (64-bit)
 - Browser: Firefox 116.0.3 (64-bit)

**Additional context**
the game in question (at time of posting, it still hasn't ended):
https://online-go.com/game/58911468

**Comment by HumbleSolipsist** [comment]
now the game has ended, but due to a scoring error it has said that white won (see above), when it seems to me like black should've won

**Comment by anoek** [comment]
There was a scoring server outage during this time that cause this issue. Handling of this scenario needs to be improved, but that's a bit out of the scope of front end issues so I'm going to close this one.
