### ISSUE TITLE
List entries for paused games take extra vertical space on mobile

### ISSUE THREAD

**Issue by dexonsmith** [online-go/online-go.com#2426]
**Describe the bug**
A follow-up issue for #2418 -- turns out that paused games were using extra vertical space for a related reason, and #2420 didn't fix this.

**To reproduce:**

1. Create enough active games to require a game list
2. Pause one
3. Make your screen small (e.g., use mobile)
4. Observe the blank line between the time on the actual clock time and the word "Pause" in "Clock" column.

**Comment by dexonsmith** [comment]
PR is #2427. Let me know if I should have just sent that (i.e., was it worth me writing up this issue?).

**Comment by benjaminpjones** [comment]
> Let me know if I should have just sent that (i.e., was it worth me writing up this issue?)

I think issues can be valuable for tracking, but they aren't strictly necessary - there are plenty of PRs that do not have issues attached.

One thing I do think would be helpful for these cosmetic fixes would be before and after screenshots - would save quite a few clicks to understand the end result :)

**Comment by dexonsmith** [comment]
> One thing I do think would be helpful for these cosmetic fixes would be before and after screenshots - would save quite a few clicks to understand the end result :)

Makes sense, of course, and happy to do it!

... Any chance you could point me at how/where I might host the screenshots? (My reflexes are twenty years out-of-date for web stuff... I feel like the answer should be obvious these days, but I don't know what it is.)

**Comment by benjaminpjones** [comment]
No need to worry about hosting, GitHub takes care of it :) you should be able to click and drag photos into the text box or click the Attach Files button.

![Screenshot showing the Attach File button](https://docs.github.com/assets/cb-26464/mw-1440/images/help/issues/attach-file-icon.webp)

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by dexonsmith** [comment]
(Added the before/after to the PR.)

**Comment by dexonsmith** [comment]
> No need to worry about hosting, GitHub takes care of it :) you should be able to click and drag photos into the text box or click the Attach Files button.

And I was right... the answer was obvious :). (Thanks!)
