### ISSUE TITLE
Opening the friends list should close the notification list and vice versa

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#243]
I do realize it only would save 1 click, so this is lower priority than all other bugs/feature requests, but when I open the notification list, then open the friend list, I can't see the friend list because the notification list is in front of it.
For the same reason of saving 1 click, the friend list should close when the notification list opens.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
