### ISSUE TITLE
Feature request: indications of interactions on completed games

### ISSUE THREAD

**Issue by windo** [online-go/online-go.com#245]
### Summary

Sometimes there is interaction on a game I've played after it has completed. It could either be comments in game chat or a review that is started. In both of these cases, it would be great to receive a notification because currently there is no way to notice except manually going and checking the game chat log.

Relatedly, it would be great to see the number of chat messages (Malkovich or normal ones) exchanged on the game somewhere in completed game list and maybe spectation UI. The idea would be to make games that have discussion going easier to find.

**Comment by jsonn** [comment]
One basic improvement here would be to send a notification / message when a new review is started for a game you are involved in. That's a higher level of interaction than just a message, which is often just a "thanks for the game" or so.

**Comment by benjaminpjones** [comment]
Linking https://github.com/online-go/online-go.com/pull/1540 as that addresses late chats.
