### ISSUE TITLE
Minimize game data used as part of /players/${id}/full

### ISSUE THREAD

**Issue by dexonsmith** [online-go/online-go.com#2455]
Spinning off from #2451, it looks like `/players/${id}/full` sends a ton of data about active games in a `.json` field that can/should be accessed more lazily.
- 2ced2a92912318fe2df16ee158942bed0e7951a4 (#2451) stopped using the clock data.
- Still using the full list of moves, but just need the number of moves.

If we can get reduce that down, the follow-up would be to stop sending the data.

EDIT: more details in https://github.com/online-go/online-go.com/issues/2451#issuecomment-1859183556 and following conversation

**Comment by benjaminpjones** [comment]
Most likely any fix to this will help resolve https://github.com/online-go/online-go.com/issues/1875 as well :)

**Comment by dexonsmith** [comment]
> Most likely any fix to this will help resolve https://github.com/online-go/online-go.com/issues/1875 as well :)

Sadly, the use-less-data part of #2451 was effectively reverted in #2458 (turns out the initial sort does matter), but nevertheless there's a lot of data that's being entirely ignored. 

Maybe this issue could/should be closed as a duplicate of #1875?

**Comment by dexonsmith** [comment]
I'm closing this as an effective duplicate of #1875. There's a chance I'll steal that one from @anoek at some point ;).
