### ISSUE TITLE
Switching among different rounds of a tournament leads to wrong display of players

### ISSUE THREAD

**Issue by SuperIRabbit** [online-go/online-go.com#246]
### Summary

*Briefly describe the issue you are reporting*

See [Steps To Reproduce]

https://forums.online-go.com/t/new-round-glitch/11764
https://forums.online-go.com/t/the-tournament-pages-are-bugged/12349

### Environment

 * Operating system: Any
 * Browser: any
 * Browser Version:

### Steps To Reproduce:

1. Go to any of the multi-round correspondence tournament (e.g. https://online-go.com/tournament/22397 )
2. Randomly click on any other round
3. The players displayed are from the round before the last click

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
This appears to have been fixed, likely thanks to @BarneyStratford 's work
