### ISSUE TITLE
Spelling error in swedish version 

### ISSUE THREAD

**Issue by sousys** [online-go/online-go.com#249]
### Summary

aedanvalu: On the scoring page, the text instructing that players should agree on which stones are alive or not contains the word "överänns", which should be spelled "överens"

**Comment by roy7** [comment]
You might be able to make this correction directly in https://translate.online-go.com/ . I'm not sure.

**Comment by sousys** [comment]
aha thanks. You are correct. I fixed it there.

**Comment by sousys** [comment]
Corrected in https://translate.online-go.com/
