### ISSUE TITLE
Ranking chart zoom and pan is broken

### ISSUE THREAD

**Issue by peterjoel** [online-go/online-go.com#2497]
**Describe the bug**
When you drag the zoom pane to zoom or pan the chart, it flickers and eventually just draws the full un-zoomed chart

**To Reproduce**
See video

**Expected behavior**
It should pan and zoom, and not revert to the un-zoomed chart.

**Screenshots**

https://github.com/online-go/online-go.com/assets/150875/8b8982c9-95c1-430e-9312-db9972ad2e35

**Desktop (please complete the following information):**
 - OS:  Mac Ventura 13
 - Chrome 
 - Version 120.0.6099.71 (Official Build) (arm64)

**Comment by anoek** [comment]
Fixed in https://github.com/online-go/online-go.com/commit/758d503c4169d5915360aa493c0c56e99435f96d - thanks for the report!
