### ISSUE TITLE
Bot games default to Japanese

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#25]
Bots generally seem to support Chinese moreso than Japanese scoring. Leela only knows Chinese, GnoGo can do either with a command line switch. Feugo has weak Japanese scoring support.

Could we either toggle the default over to Chinese for all "Vs The Computer" matches for now, or add a way in the API a bot can tell the server what game rule(s) it wants to allow when people queue Vs Computer? Maybe some part of the connect to server set, or a new API call for "I allow these rules" and send an array in.

Whatever you do, remember to tweak the settings on Fuego and GnuGo to Chinese scoring if this change gets made.

**Comment by anoek** [comment]
Fixed on the backend, will be pushed out tomorrow
