### ISSUE TITLE
Opponent's undo request should make a sound when in a different tab.

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#250]
It just as important as hearing a sound when the opponent makes a move.
Probably not a bad idea for the undo request to make a sound when the tab has focus too.

**Comment by Saxmaam** [comment]
A sound for current and open tabs is great idea.  A visual indicator (something changes color?) would be fantastic.  On small screens, the undo indicator is not always visible, either during a game or when game is just loaded.

**Comment by Nazgand** [comment]
I had another undo request go unnoticed while playing simultaneous games today.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
