### ISSUE TITLE
F1 sets "Place white" instead of "Alternating stones"

### ISSUE THREAD

**Issue by siasio** [online-go/online-go.com#2506]
**Describe the bug**
When using keyboard shortcuts in the Analyze Mode, F1 behaves not as described in [wiki](https://github.com/online-go/online-go.com/wiki/Advanced-Tips-&-Tricks#on-game-screen). It sets "Place white" tool instead of "Alternating stones". I tried also other F-keys but none of them sets "Alternating stones".

**To Reproduce**
1. Go to Settings -> Game Preferences and toggle "Enable function keys for game analysis shortcuts"
2. Open any game on OGS and go to Analyze Mode
3. Press F4 and see that "Place triangle marks" tool is selected
4. Press F1
5. See that "Place white" tool is selected

**Expected behavior**
Instead of selecting "Place white", "Alternating stones" should be selected.

**Screenshots**
![image](https://github.com/online-go/online-go.com/assets/39811817/f7590576-2ff3-4d72-9081-25fa39e813e9)

**Desktop**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 120.0.6099.224

**Additional context**
Right after I go to Analyze Mode, pressing F1 or F2 does not select any tool. Hence, in the steps to reproduce I include step 3 - press F4 - after which F1 and F2 do select tools.

**Comment by anoek** [comment]
Thanks for the detailed report! Got it fixed up, it'll be deployed soon.

**Comment by siasio** [comment]
I confirm that it's fixed. Thank you for your quick action!
