### ISSUE TITLE
API, provide game score during stone removal

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#255]
It'd be nice if the API had a way to tell what score was on the board currently during stone removal. So basically for bots, if score means I win, just accept the score. (As a quick and simple failsafe in gtp2ogs if the server auto score accept fails. This way humans don't need to wait if they aren't going to change the score in their own favor.)

**Comment by anoek** [comment]
Cleaning up, I think this is obsolete because we (for better or worse) just autoscore
