### ISSUE TITLE
A toggle to hide bots on watch screen

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#256]
Someone said they wish they could hide bot matches on the watch screen. That doesn't seem unreasonable. So I'd like to request that as a new feature, someplace on the watch screen have a little checkbox to hide bot games.

**Comment by lemurek** [comment]
That's exactly what I was thinking about yesterday, when I saw first 2 rows being filled with bot games.

**Comment by BHydden** [comment]
This can be closed, now possible to hide bot games on watch screen.
