### ISSUE TITLE
UI Nit: Challenge Dialog "Close" button hard to see when using Dark theme

### ISSUE THREAD

**Issue by ecyrb** [online-go/online-go.com#2566]
The **Close** button is hard to see in the Challenge dialog when using dark mode.

![Sample Challenge Dark Theme](https://github.com/online-go/online-go.com/assets/182420/cead704f-aacf-46a5-a018-1f3fb08c7182)

![Sample Challenge Light Theme](https://github.com/online-go/online-go.com/assets/182420/37b22705-d2bb-4ffa-be15-2faf6149a631)

See the **Cancel** button in this dialog for comparison
![Sample "Waiting for Opponent"](https://github.com/online-go/online-go.com/assets/182420/0eb0e3f6-2bee-4225-bde5-1a48f18f4b11)

Possible solutions could be moving the **Close** button next to the **Play** button, or increasing the contrast of the **Close** button.

Side-note, should it be **Cancel** instead of **Close**?

**Comment by BlazarKnight** [comment]
is this still open?

**Comment by benjaminpjones** [comment]
I believe so

**Comment by MartijnGosgens** [comment]
I see that the cancel button has changed to orange (class="danger") in the meantime. Should the close button also be made orange?
![Screenshot from 2024-07-25 15-13-23](https://github.com/user-attachments/assets/8b757060-5164-494b-81d4-ad82e45369dd)

**Comment by anoek** [comment]
Thanks!

**Comment by BHydden** [comment]
This issue was about the close button on the challenge dialog, which does still exist.
