### ISSUE TITLE
How to change nationality of players in demo games?

### ISSUE THREAD

**Issue by mango314** [online-go/online-go.com#258]
### Summary

I cannot change nationality of players in Demo Games.  I would do this myself if I could identify the relevant source code.

### Environment

 * Operating system: Ubuntu
 * Browser: Chrome
 * Browser Version: 58

### Steps To Reproduce:

1. Go to Main Menu ( left )
2. Click Demo Board
3. See that there is no option for nationality (e.g. underneath name and rank)

### Demo Board

![](https://i.imgur.com/CtcmjZq.png)

### No Options for Player Nationality

![](https://i.imgur.com/xKGMkQS.png)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
