### ISSUE TITLE
Feature Request: Please make the contacts list disappear after clicking on one

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#259]
### Summary

Could you please make the contacts list disappear once you clicked on one of them ? It makes me crazy :')
We shouldn't have to close it by ourselves, imho.

### Environment

 * Operating system: any 
 * Browser: any
 * Browser Version: any

### Steps To Reproduce:

1. Open on the friends list
2. Click on one of them
3.The contacts list never closes on its own and stays eternally while you keep on browsing OGS website.

Thanks

Arnaud

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by arnaudgo** [comment]
Hi,

@anoek could you please re-open that issue? I still can open the friends list, click on a name, visit the friend's profile and the list stll doesn't pop out on its own unless I click somewhere on the page.
The behaviour has significantly improved since your commit but there's still this little detail to fix.

Please, tell me if I should rather open a new issue for it :-)

Thanks,

Arnaud

**Comment by anoek** [comment]
Fixed (more) :)

**Comment by arnaudgo** [comment]
hi @anoek 

Broken again (tried on Desktop and on mobile) :/ 

I can't say since when but yes you had fixed it, I confirm.

Arnaud

**Comment by anoek** [comment]
Yeah looks like we regressed in 3eb99c12eb13db151ad6e2e5ce13bf5f42b3147d , easy to miss, similar calls to things that close open stuff on the screen, those should probably be merged I guess..
