### ISSUE TITLE
Bot games don't always smoothly auto-score

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#26]
https://online-go.com/game/7905072

I had to log into that game to accept the scoring for RoyalLeela. I watched the game end and the opponant accepted, but it was waiting on RoyalLeela. So for some reason the "this is a bot game, auto score it" didn't fire.

Random guess, maybe it was a direct challenge? Is the "auto score this" based on a player being flagged as a bot account, or the game made under Create Game -> Vs Computer?

That's a long shot, but I don't have any other ideas why some games don't actually auto-score.

**Comment by anoek** [comment]
This seems to happen when amazon lambda fails to respond, i think we just need to retry a few times.

**Comment by roy7** [comment]
Does lambda do the scoring?

**Comment by anoek** [comment]
For bot games yes

**Comment by roy7** [comment]
Ok, neat. Retry should fix it although if you have a way to look up lambda
logs based on a gameID you could spot the failure reason.

**Comment by anoek** [comment]
Implemented, awaiting deployment
