### ISSUE TITLE
No clue from which ladder the ladder challenge comes from

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#260]
### Summary

The game information gives no clue from which ladder the ladder challenge comes from

### Environment

 * Operating system:  any
 * Browser: any
 * Browser Version: any

### Steps To Reproduce:

1. For a ladder game you play or your played, click on "Game information"
2. You will read it's a ladder challenge game but no indication from which ladder

### Additional Information:

I suggest to insert a link to the ladder too.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
