### ISSUE TITLE
Game chat has no space for typing (seems almost unusable!)

### ISSUE THREAD

**Issue by dexonsmith** [online-go/online-go.com#2602]
**Describe the bug**
I think something landed recently that made it really hard to type in Game Chat. At least in Safari. There's also some new thing you where you can see old things you've typed before, and if you (accidentally) click on them they get immediately sent to the chat.

**To Reproduce**
1. Go to https://online-go.com/game/61480807 (or any game)
2. Notice the box for typing is super small... it's very hard to tell what you're typing or to check it.
3. There's also some new drop-down to send messages.

**Expected behavior**
How it worked yesterday ;).

**Screenshots**
<img width="451" alt="Image 2" src="https://github.com/online-go/online-go.com/assets/1334620/a7a60097-9454-4333-9f39-cec801a8d126">

**Desktop (please complete the following information):**
 - OS:  macOS 14.3.1
 - Browser: Safari 17.3.1

**Comment by dexonsmith** [comment]
@GreenAsJade , any chance this was caused by https://github.com/online-go/online-go.com/pull/2595?

**Comment by dexonsmith** [comment]
> There's also some new thing you where you can see

Actually, probably not new (probably I just didn't notice it when it was flush right instead of taking up space in the chat box)

**Comment by anoek** [comment]
If you checkout the revision right before does it go away? Seems like a pretty likely candidate. I broke something with my mac so it'll be a little bit before I can look into it myself.

**Comment by dexonsmith** [comment]
> If you checkout the revision right before does it go away? Seems like a pretty likely candidate. I broke something with my mac so it'll be a little bit before I can look into it myself.

Confirmed:
- see the problem with dbb0f1982c5997442cda84f889aa7c951fcf2ccb
- don't see the problem with 19ea2dee0b2a454cd3afdbe80ac5468be17c9aaa

I don't have time to try to fix myself right now (hopping on a call).

**Comment by dexonsmith** [comment]
But my guess it's the `<form>` part of it, rather than the "...hint" thing (the latter of which sounded like a sufficient change to fix the bug)

**Comment by GreenAsJade** [comment]
> he latter of which sounded like a sufficient change to fix the bug

I still didn't see anywhere where it was written that this was the case :(

I'm checking it out now.

**Comment by dexonsmith** [comment]
> I still didn't see anywhere where it was written that this was the case :(

Not sure what the ultimate source was, but I saw it here in the thread at <https://forums.online-go.com/t/unable-to-reply-to-group-chat/49861/14>:

> It’s an implementation detail of Chromium/Android but this is what they’ve done:
> 
> 1. If there are multiple text inputs in a form, send a Tab event instead of Enter for all but the last input element
> 2. If enterkeyhint is set, send Enter no matter what. (even if it’s enterkeyhint=“next” :thinking:)

**Comment by dexonsmith** [comment]
> I still didn't see anywhere where it was written that this was the case :(

@GreenAsJade, I looked it up [in the Chromium sources](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/content/public/android/java/src/org/chromium/content/browser/input/ImeAdapterImpl.java#914) to confirm the comment in the forum thread:
```
    public boolean performEditorAction(int actionCode) {
        if (!isValid()) return false;

        // If mTextInputAction has been specified (indicating an enterKeyHint
        // has been specified in the HTML) then we do will send the enter key
        // events. Otherwise we fallback to having the enter key move focus
        // between the elements.
        if (mTextInputAction == TextInputAction.DEFAULT) {
            switch (actionCode) {
                case EditorInfo.IME_ACTION_NEXT:
                    advanceFocusForIME(FocusType.FORWARD);
                    return true;
                case EditorInfo.IME_ACTION_PREVIOUS:
                    advanceFocusForIME(FocusType.BACKWARD);
                    return true;
            }
        }
        sendSyntheticKeyPress(
                KeyEvent.KEYCODE_ENTER,
                KeyEvent.FLAG_SOFT_KEYBOARD
                        | KeyEvent.FLAG_KEEP_TOUCH_MODE
                        | KeyEvent.FLAG_EDITOR_ACTION);
        return true;
    }
```

**Comment by GreenAsJade** [comment]
I've closed this because the change that caused this bug has been backed out
