### ISSUE TITLE
No clue from which group the tournament game originates from

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#261]
### Summary

Between groups, I guess it may have name collisions for tournaments and the game information doesn't identify exactly what tournament the game is from.

### Environment

 * Operating system: any
 * Browser: any
 * Browser Version: any

### Steps To Reproduce:

1. Go to a tournament game.
2. Click on Game information
3. You see the tournament name but can't know from wich group (if not website-wide) the tournament MySuperTournament is form.

### Additional Information:

It should be useful to have from the game information "frame" the link to the tournament page the game is originated.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
