### ISSUE TITLE
Game thumbnails list threshold should be settable directly from the games page

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#262]
### Summary

Sometimes we want to see thumbnails but maybe not everytime you load the games page. 
It could be nice to have a drop-down list on the games page that allow to dynamically change it without going to our settings.

### Environment

 * Operating system: any
 * Browser: any
 * Browser Version: any

### Steps To Reproduce:
N/A
### Additional Information:
N/A

**Comment by anoek** [comment]
As per the discussion in #290, I think I'd like to change the scope of this request to decouple the list limit functionality on this page, and instead just have a toggle that switches the view from list to thumbnails.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
