### ISSUE TITLE
Game-control-dock pop-out delay broken.

### ISSUE THREAD

**Issue by bradwood** [online-go/online-go.com#2669]
**Describe the bug**
This  no longer works.

![image](https://github.com/online-go/online-go.com/assets/3472045/93625c94-afe7-4583-9d67-c0055d603b42)

**To Reproduce**
1. Set the slider to anything you like (e.g., "off")
2. Go to a game
3. Hover over the game control dock
4. The setting is ignored 

**Expected behavior**

It works as it used to. 

**Desktop (please complete the following information):**

```
Brave	1.65.123 Chromium: 124.0.6367.91 (Official Build) (64-bit) 
Revision	dd88871b12997b018e3acb2f589713a3ea10338b
OS	Linux
JavaScript	V8 12.4.254.14
User agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

```

**Additional context**

The bug probably got introduced a couple days ago, as this is recent. It's doing my head in -- hopefully a fast and easy fix?!

Thanks

**Comment by anoek** [comment]
Should be better now. I think there might have been a change in the way Chrome handles setting transitions, I don't think it was anything we changed recently.

**Comment by bradwood** [comment]
> Should be better now. I think there might have been a change in the way Chrome handles setting transitions, I don't think it was anything we changed recently.

Nope -- it's still broken for me. :-/

**Comment by bradwood** [comment]
wait, hold on -- I had to refresh a few times, seems okay now - -thanks!

**Comment by bradwood** [comment]
Sorry for the flip-flop on this, but it's still broken @anoek -- it seems a little inconsistent and sometimes comes out and sometimes not. But it's definitely not right.

**Comment by anoek** [comment]
Hmm, do you notice a pattern, more specifically, a way to reproduce it? Seems to be working over here

**Comment by bradwood** [comment]
if I move the mouse cursor slowly up and down the dock, waiting for each tooltip to load it seems to be okay, but when I move the mouse cursor left and right over the dock repeatedly, say on the "call moderator" icon, after 3 or 4 right-left-right mouse movements it happens.

**Comment by bradwood** [comment]
I have the slider set to "off" btw

**Comment by anoek** [comment]
Ok, I had some debounce code in there that might have been causing that if you were doing it pretty quick - I modified it, I think that'll fix it for you now?

**Comment by bradwood** [comment]
how do I know if I'm no the newest browser bundle?

**Comment by anoek** [comment]
If you head to https://online-go.com/docs/about you should see `UI: 5.1-6775-g6df773e5`

**Comment by bradwood** [comment]
ok -- that's the build I've loaded -- problem is still happening occasionally.
