### ISSUE TITLE
Typo on spectator waiting room page

### ISSUE THREAD

**Issue by davehcdn** [online-go/online-go.com#2670]
**Describe the bug**
There is a typo on the waiting room page it says "You will be taken to the game it starts...
"

https://github.com/online-go/online-go.com/blob/47d16179f13ecc981cbff07bfe613b20bffa8b93/src/views/OnlineLeagueSpectatorLanding/OnlineLeagueSpectatorLanding.tsx#L102

**Comment by GreenAsJade** [comment]
Whoa.  Doh!  😅
