### ISSUE TITLE
Turn off autocomplete for chat

### ISSUE THREAD

**Issue by robert-sjoblom** [online-go/online-go.com#2677]
**Is your feature request related to a problem? Please describe.**
Sometimes, chat shows earlier messages sent as an autocomplete option.

**Describe the solution you'd like**
Add an `autocomplete=off` to chat input field.

**Additional context**

**Comment by anoek** [comment]
Huh, could have sworn that used to be in there..

**Comment by anoek** [comment]
Fixed in @2678
