### ISSUE TITLE
Please make settings from settings page globally persistent

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#268]
### Summary

The settings are bound to session, not to profile and it's, imho, a boredom: you have to fix your settings from any browser you use.

https://forums.online-go.com/t/settings-bound-to-session-not-to-profile/10666

### Environment

 * Operating system: n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:
 
Please ask if needed

### Additional Information:

N/A

Arnaud

**edit**: I just fixed the link to the forum thread

**Comment by Capt-Brunch** [comment]
For posterity, I'm going to add this comment to state my disagreement with that change by-and-large. That being said, I think color profile could (and maybe should) safely be stored server-side.

**Comment by arnaudgo** [comment]
Hello @Capt-Brunch 

I've just give more details about my wish in the forums, so you might want to read my post and this is the link:

https://forums.online-go.com/t/settings-bound-to-session-not-to-profile/10666/5

Tell me if we share the same point of view.

And, to all: there's already one reaction on this issue there, so keep an eye there :)

Arnaud

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
