### ISSUE TITLE
Automatic live 9x9 double-elimination tournaments have McMahon bars (!?)

### ISSUE THREAD

**Issue by dexonsmith** [online-go/online-go.com#2686]
Automatic live 9x9 double-elimination tournaments have McMahon bars (!?), and assign initial points based on those bars. This means that 2nd and 3rd place may be awarded incorrectly.

Example tournament via API: <https://online-go.com/api/v1/tournaments/105862>
- Notice `tournament_type` is `double_elimination`
- Notice `settings` has `upper_bar` and `lower_bar` (!?)
- Notice some players' `points` are negative (due to bars), affecting how 2nd and 3rd place are awarded
- Notice the player who should have come 2nd didn't even place, due to the points: <https://online-go.com/tournament/105862>

It's not entirely clear whether this is a recent regression.
- It's possible the configurations have incorrectly had bars for a long time, but they were ignored until a recent change.
- Or maybe it's always been like this and no one was able to diagnose the problem.

In any case, the simplest fix is to update the automatic 9x9 live double-elimination configuration not to have bars. I think only @anoek can fix that.

EDIT: forum link is <https://forums.online-go.com/t/tournament-results-bug/51725>

**Comment by pdg137** [comment]
Note that you can see the negative points at this other API endpoint: https://online-go.com/termination-api/tournament/105862/players

In case it helps here's an ancient one where there don't seem to have been negative points awarded (e.g. to user stargrazerfairy who would have probably been DDK): https://online-go.com/tournament/3565 https://online-go.com/termination-api/tournament/3565/players

But it does have the bars in the settings: https://online-go.com/api/v1/tournaments/3524

**Comment by anoek** [comment]
Huh, nothing has changed with those configurations in many many years, odd we're seeing stuff now..

**Comment by dexonsmith** [comment]
If there are old ones without negative points, then maybe some refactor related to the backend changes a few months ago triggered this.

**Comment by dexonsmith** [comment]
Doing a bisection through 1991 archive pages at 25 tournaments per page:
- 1000: https://online-go.com/tournament/61206 good (no negative points, despite presence of DDKs)
- 500: https://online-go.com/tournament/87805 bad (negative points)
- 750: https://online-go.com/tournament/74347 good
- 612: skip (not seeing negative points, but not confident tournament had DDKs)
- 611: https://online-go.com/tournament/81966 good
- 550: https://online-go.com/tournament/85204 good
- 525: https://online-go.com/tournament/86478 bad
- 537: https://online-go.com/tournament/85824 bad
- 543: https://online-go.com/tournament/85557 bad
- 547: https://online-go.com/tournament/85377 bad
- 548: https://online-go.com/tournament/85338 bad
- 548: https://online-go.com/tournament/85327 bad
- 548: https://online-go.com/tournament/85308 bad
- 548: https://online-go.com/tournament/85303 bad
- 548: https://online-go.com/tournament/85279 good
- 548: https://online-go.com/tournament/85299 bad
- 548: https://online-go.com/tournament/85295 skip

That means the first "bad" one I can find was "Live 9x9 Double Elimination Tournament 2022-01-25 14:30", <https://online-go.com/tournament/85299>.

That's pretty close to when two backend changes were committed related to setting initial points in McMahon bars:
- f9b40a50841de263e8120c40e0a0c19a32dcc9d4 (committed January 21st)
- 07b0d6eaf16d619d175852d63393b876d156c797 (committed January 26th)

After staring for a while, I can't see how they triggered the bug. I actually found those changes *before* doing the bisection, since they were obviously touching related code, but decided they couldn't be the problem. It looks to me like the bug was always there: if a double elimination tournament somehow had McMahon bars set, they'd be used.

**Comment by dexonsmith** [comment]
> After staring for a while, I can't see how they triggered the bug. I actually found those changes _before_ doing the bisection, since they were obviously touching related code, but decided they couldn't be the problem. It looks to me like the bug was always there: if a double elimination tournament somehow had McMahon bars set, they'd be used.

Just to clarify: it looks to me like the bug was always there, from looking at the code. But the bisection has convincing evidence that somehow those two commits changed the behaviour; before those commits, McMahon bars in D.E. tournaments were ignored; after those commits, they caused negative points.

**Comment by dexonsmith** [comment]
@anoek, looking at other automatic tournaments (not just "live 9x9"), I'm also seeing McMahon bars also in:
- https://online-go.com/tournament/116084 (Blitz 19x19 Elimination)
- https://online-go.com/tournament/116030 (Live 19x19 Swiss)
- https://online-go.com/tournament/115877 (Blitz 13x13 Swiss)

Combined with "Live 9x9", that's the full set of live/blitz.

For automatic correspondence (I didn't find any in the first two pages of archive, but...):
- The simultaneous round robins won't hit the issue since they don't share a code path, but it might be nice to remove bogus McMahon bars from them too if they're there.
- The simultaneous McMahons *should* have bars, presumably.

**Comment by dexonsmith** [comment]
> Just to clarify: it looks to me like the bug was always there, from looking at the code.

Update: I figured out how f9b40a50841de263e8120c40e0a0c19a32dcc9d4 (January 21, 2022) triggered the bug. I still think it's worth cleaning up configurations to remove bars where they don't make sense, but maybe a backend change is also in order.

**Comment by anoek** [comment]
Interesting, thanks for finding and (presumably) fixing, i'll do some testing with it and get it deployed tomorrow if it all looks good.

**Comment by anoek** [comment]
ogs #1959 has been merged and deployed, new tournaments going forward should be good to go
