### ISSUE TITLE
Autoplay delay should be settable directly from a game page

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#269]
### Summary

Autoplay delay is currently a sitewide setting but it would be nice to be able to change it from the game page.

### Environment

 * Operating system: n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:

Feel free to ask if needed

### Additional Information:

n/a

Arnaud

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
