### ISSUE TITLE
If you have activated (and expired) a trial AI subscription, you still get prompts for a free AI trial

### ISSUE THREAD

**Issue by robert-sjoblom** [online-go/online-go.com#2697]
See title.

Clicking on "Activate Now" doesn't work, though:
![image](https://github.com/online-go/online-go.com/assets/31652489/96431c6f-48c0-4121-8a38-3012987e1359)

**Comment by anoek** [comment]
Huh, and I presume you refreshed and it's still there? Sorry about that, I'll look into why that's happening.
