### ISSUE TITLE
Remove volume setting from Settings page

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#270]
### Summary

The volume bar is present twice: once in Settings page, once in any in-progress page.

There's no need for that setting to cross the devices and clients and I think it's better to link it to a session.

So, I suggest to remove it from that page.

### Environment

 * Operating system: n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:
n/a
### Additional Information:
n/a

**Comment by anoek** [comment]
It's pretty much standard to find volume controls under "Settings" these days so I think it's probably a good idea to keep it there, redundant as it may be.
