### ISSUE TITLE
Unify game links

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/online-go.com#2700]
There are 2 routes for the game page:

- /game/view/:game_id
- /game/:game_id

Similarly, demos and reviews also have a `/view/` route.

https://github.com/online-go/online-go.com/blob/devel/src/routes.tsx#L238-L246

Currently, Tournaments, Automatch and Incident reports link to the `/game/view/` route ([codesearch](https://github.com/search?q=repo%3Aonline-go%2Fonline-go.com+%2Fgame%2Fview%2F&type=code)), while the rest of the site links to the `/game/` route ([codesearch](https://github.com/search?q=repo%3Aonline-go%2Fonline-go.com+%2F%5C%2Fgame%5C%2F%5C%24%5C%7B%2F&type=code)).

While we should keep these routes for backwards compatibility, OGS should be consistent about how it links internally.

## Additional Context

https://forums.online-go.com/t/linking-to-a-specific-move/51913/6

**Comment by anoek** [comment]
Yep, it should just be `game/:game_id` I'd think
