### ISSUE TITLE
Produce a sound every time we change the volume from a game page

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#271]
### Summary

From a game page:

The game page should play a sound everytime we click on the volume button. It helps us gauging it.

### Environment

 * Operating system: n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:

Feel free to ask if needed

### Additional Information:

n/a

Arnaud

**Comment by Nazgand** [comment]
Preferably the stone placement sound.
