### ISSUE TITLE
Submit mode should be settable directly from a game page 

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#272]
### Summary

Could you please remove submit mode from the Settings page and make it appear on any game page ?
The reason that would make it accurate is that it should be a session-scoped setting rather than a global-scope setting. 
The option should be aware of the in-progress game type so that only one drop-down list appears. Let me explain:

if it's a live game, only the submit mode setting for live games should appear.
If it's a correspondance game, only the submit mode settng for correspondance games should appear.

### Environment

 * Operating system:  n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:

n/a

### Additional Information:

n/a

Arnaud

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
