### ISSUE TITLE
Offers the possibility to make OGS remember of one's game preferences

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#273]
### Summary

From an in-progress game page, it would be nice to have a button where to click to make OGS remember one'session-scoped game preferences.
Somehow, it permits to set our default preferences when OGS website doesn't find any custom settings within a session. And when there are both, settings defined in a session should have precedence over the default values.

### Environment

 * Operating system: n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:
n/a

### Additional Information:

n/a

Arnaud

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
