### ISSUE TITLE
Stone removal matrix from the end of game is incorrectly used during analysis and score estimation of old moves

### ISSUE THREAD

**Issue by dany52** [online-go/online-go.com#2735]
https://online-go.com/game/65529837

After 260 white move one prisoner add to black

before 260 white move black have 4 prisoners
![image](https://github.com/online-go/online-go.com/assets/436366/2ebaded3-af4e-4b0a-9daa-99d05332f326)

after 260 white move black have 5 prisoners
![image](https://github.com/online-go/online-go.com/assets/436366/300855b3-f56a-48bb-88e8-f39c1433a52c)

**Comment by BHydden** [comment]
Huh... very weird...

**Comment by anoek** [comment]
Nothing game breaking, just a post game analysis bug, the fix will be live shortly. Thanks for the report!

**Comment by anoek** [comment]
Except the fix broke other stuff so back to working on a fix

**Comment by anoek** [comment]
Related: https://forums.online-go.com/t/stone-removal-and-scoring-updates/52055/257
