### ISSUE TITLE
end game details are all broken

### ISSUE THREAD

**Issue by nsklaus** [online-go/online-go.com#2736]
**Describe the bug**
after game ended, the game details shows broken values

**To Reproduce**
1. play and finish a game
2. Click on 'captures' under player name
3. check details given on popup
4. confirm values given are all wrong

**Expected behavior**
I expected value given would display correctly details about the game that just ended.

**Screenshots**
<img width="720" alt="Screenshot 2024-06-29 at 15 37 47" src="https://github.com/online-go/online-go.com/assets/6810861/a75f2035-a1fd-42f0-af98-6f81d5afa4d2">

**Desktop (please complete the following information):**
 - OS: macos (but tested and confirmed similar problem on linux too)
 - Browser brave (but seen the same problem with other browsers)
 - Version ..version of what? OS, browser, ogs ?

**Additional context**
in the game shown in the screenshot, black won by 54 point.
the details tells black have 27 territory points.. that is nonsense.
same for white, it tells white have 39 territory point.. that is not correct.
same for prisonners.
basicaly all the details given are false.

**Comment by anoek** [comment]
Can you provide a link to the game in question? If you don't want to share it publicly please send it to anoek@online-go.com or send me a message on OGS.

**Comment by nsklaus** [comment]
sure: https://online-go.com/game/65562595
but, it's the same for every game you can find, as far as i can tell.

**Comment by anoek** [comment]
What you're seeing is the score of the game as computed without going through the stone removal process, here's what the game actually looks like

![image](https://github.com/online-go/online-go.com/assets/168460/b9f89ece-341a-47a4-b944-6a402b8aee8d)

the image you posted was of a score estimate, which is not the same thing.

**Comment by nsklaus** [comment]
even without clicking on 'estimate' button, after game ended, when i click on 'captures' i get the broken values. so that is misleading.

side question:
how do one get game score breakdown, if not using AI functions ?
i do not use AI.

**Comment by anoek** [comment]
You're going to be more specific about what you consider is wrong. The game ended by resignation. The resulting scores are computed exactly as the board is, which does not include removing stones so what would otherwise be considered territory is not territory yet.

I'm not sure what you mean by score breakdowns, but try enabling AI reviews to see if that achieves what you were looking for.

**Comment by nsklaus** [comment]
alright, i'll try to be more specific: 
when game ends, in real life i would be able to count how many territory i made, and how many territory my opponent made. i would also be able to count how many stones were captured for myself, and how many stones my opponent captured too. so i would be able to figure out game outcome details as it ended. both the same for games with resignation or with fully finished game.

now the problem: 
with OGS the values given after game ends (by resignation and even with fully finished games) are always broken, false value. and i cannot find a place where these values are properly listed. the only place i know is clicking on 'captures' to game a breakdown of the game when game has ended. maybe a suggestion would be to add correct game breakdown on 'game info' popup (after game ended). it's just a suggestion. i would be happy if i could find the correct values (game breakdown details) just anywhere else as well.

**Comment by nsklaus** [comment]
i mean, if opponent resign early, then it would be understandable to have inaccurate values. but here, the game is as good as finished. there should be  more accurate values displayed.
i would also be happy if given value were correct only for fully finished games. i mean:
breakdown values would be innacurate for games with resignation: ok
but, for fully finished games at least, i would expect to see correct breakdown values. which is not the case as far as i can tell, all breakdown values are currently broken. both with fully finished games and games with resignation toward the end of the game. there is simply no place to find correct values, anywhere, in anycases, unless i'm mistaken ?
