### ISSUE TITLE
Group incorrectly shown on group list

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#2744]
**Describe the bug**
The top group on the group list on my home page is a group I have never joined and am not a member of. 

**To Reproduce**
I don't know how to reproduce the bug but I attach two screenshots as evidence and illustration.  

**Expected behavior**
I expect the group list on my home page to show only the groups I am a member of. 

**Screenshots**

See top group on list: 
![Screenshot_20240705-234442.png](https://github.com/online-go/online-go.com/assets/27974470/9b4b2c3e-202b-4ad8-898c-cb2b52eee347)

See that I am not a member of this group:  
![Screenshot_20240705-234456.png](https://github.com/online-go/online-go.com/assets/27974470/50e9a4a8-b3ca-4bb2-90a5-7f23052e77dc)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Motorola moto g24 power
Android 14
Firefox and Chrome. It isn't browser-specific. 

**Additional context**
This is quite recent, I first noticed it maybe a month ago, it has not gone away so I'm reporting it. 
The bug seems to affect only the list of groups on my home page, not my profile page, where the list of groups seems correct.

**Comment by anoek** [comment]
That's a group invitation, click the X if you don't want to join it and it'll go away

**Comment by alexmitrani** [comment]
OK, thanks for explaining that.
