### ISSUE TITLE
New X for captured stones - yuck!

### ISSUE THREAD

**Issue by andymarden** [online-go/online-go.com#2750]
Can't remember what it used to be but the great big X on a captured stone at the end of the game in scoring - it scares me! Can we have an option to go back to a nice transparent looking stone or something less grossly offensive!

**Comment by changcheng967** [comment]
I have the same thought

**Comment by havryliuk** [comment]
yeah, it's very offputting!

**Comment by anoek** [comment]
https://github.com/online-go/online-go.com/pull/2770 will make this configurable

**Comment by benjaminpjones** [comment]
Closing as it's now configurable via https://online-go.com/settings/theme

<img width="766" alt="Screenshot 2024-09-17 at 10 17 55 AM" src="https://github.com/user-attachments/assets/a2a64af9-d78a-4ee2-a96e-c69ccbb2ba6f">
