### ISSUE TITLE
Ability to filter in game history by result

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#276]
### Summary

Hello,

For those who don't review every game they play, it may be enjoyable to filter one's game history to only see losses (it could be sorting without hidding wins though) so one can pick up one unreviewed game from one's lost games.

### Environment

 * Operating system: n/a 
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:

n/a

### Additional Information:

n/a

Thanks a lot

Arnaud

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
