### ISSUE TITLE
Old unnamed games inaccessible

### ISSUE THREAD

**Issue by LysConflate** [online-go/online-go.com#277]
### Summary

Old games (likely those that were not given a specific name) bear none in the list of games of a player and thus have no link to the game, making them inaccessible for review 

### Environment

 * Operating system: Windows 10
 * Browser: Mozilla Firefox
 * Browser Version: Firefox 53.0 (32 bits)

### Steps To Reproduce:

1. Go to any player's profile 
2. Click their list of games until you get to quite old ones
3. See that some have a blank space for a name and can't be viewed

### Additional Information:

null

**Comment by BarneyStratford** [comment]
I’ve had a look at this and can’t see any sign of a problem. Can you give a specific user for whom this occurs?

Cheers,
Barney

**Comment by LysConflate** [comment]
Of course, here are pictures of this happening on my account (demosha, user 59173), Satomi's (who is 52592) and anoek's (number 1), in this order.

These are all screens taken using the same device and browser (version is now 53.0.2 but I doubt it will matter much?)

![ogs possible bug 1 myself player 59173 demosha](https://cloud.githubusercontent.com/assets/28611284/25948333/4688e998-3653-11e7-993c-a5a410a424a0.png)
![ogs possible bug 2 player 52592 satomi](https://cloud.githubusercontent.com/assets/28611284/25948332/46844438-3653-11e7-884f-16afe806359e.png)
![ogs possible bug 3 anoek too](https://cloud.githubusercontent.com/assets/28611284/25948334/468e35f6-3653-11e7-974d-220d021d2d1e.png)

The same phenomenon seems to happen when viewing from at least my mobile phone (Galaxy S4, Android version 5.0.1, basic Internet application, version 4.0.10-53)
Chrome application (version 58.0.3029.84) gave the same results, with the same games.

![galaxy screenshot satomi 2](https://cloud.githubusercontent.com/assets/28611284/25948551/4805760a-3654-11e7-88e1-1f193170ae48.png)

So a thought, although I am by no means sure of what I am writing:
All those "invisible" games appear to be from before the "mass ranking system adjustment" update, when their lack of name was not a bother since clicking anywhere on the whole line they were described in the list linked to the game. Now that the name only can be clicked, it seems they cannot be accessed.

**Comment by BarneyStratford** [comment]
Yup, I’m seeing it now. For example, https://online-go.com/game/524439 appears to have no name. If you visit the game page and click “Game information” you’ll see it has no name there either. I wonder if this is a DB issue. Could be fixed on the client side by giving a default name to all unnamed matches.

Barney.

**Comment by roy7** [comment]
I don't normally try working on the client much, but that's the easiest solution I imagine. If the name is empty, display "(none)" or "(No Name)" or anything along those lines. Maybe it should be tied to the translation suite and not just English, I don't know. Could instead display the game ID # in the name field.
