### ISSUE TITLE
Board is sometimes rendered tiny

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#278]
### Summary

Bug reported by eidolonia. He says:

"I have been noticing an odd bug where sometimes the board renders super-tiny on my phone. Usually (possibly always?) it's when there's no new move waiting for me, so I'll open the browser on my phone and it will already be pointing at the URL for the game in question. Attached is a screenshot exhibiting the problem - you can see the board just overlapping the '0 captures' under my name. 

Browser is latest Safari on iPhone. "

### Environment

 * Operating system: iOS
 * Browser: Safari
 * Browser Version: Latest (10.1?)

### Steps To Reproduce:

Not entirely sure - will ask for more details.

### Additional Information:

![image1](https://cloud.githubusercontent.com/assets/5913995/25947415/4058386e-3647-11e7-804d-5ea6a5370c1a.PNG)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
