### ISSUE TITLE
Real time update for ranks on play page

### ISSUE THREAD

**Issue by RevarIsave** [online-go/online-go.com#280]
When changing the rank of a user it doesn't update on open challenges they have.  Updating them would cause less confusion/frustration when, e.g., someone accepts a supposedly 20k game while the rank of the player has been fixed upwards.

**Comment by roSievers** [comment]
I had a game just now where my opponent was shown as 19k in the clock/profile card and as 18k in the chat. I believe this is likely another manifestation of the same problem. 

Issue #160 seems related to this. I suspect that is some kind of caching problem?

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
