### ISSUE TITLE
Chat items are sometimes misattributed

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#282]
### Summary

During a game, the spectators can chat to each other. When the game ends, the spectators' chats become visible to the players. Unfortunately, the spectators' chats are attributed to the players, not to the spectators who actually wrote them.

### Environment

 * Operating system: Win 10
 * Browser: Edge
 * Browser Version: Unknown

### Steps To Reproduce:

Not entirely sure. I'm attempting to reproduce this on the dev server. Will update as soon as I have further info.

### Additional Information:

The following chat comes from https://online-go.com/game/8742006 . The screen grab was made by Wolf Guard and e-mailed to me. You can see that spectators' comments are correctly coloured blue, but incorrectly attributed to the players, not to the spectators that wrote them. The black-coloured comments are attributed correctly. I was a spectator in this game and saw the chats attributed correctly.
![chat](https://cloud.githubusercontent.com/assets/5913995/26104368/7a647ce2-3a35-11e7-8e9c-12cac5b3abb9.png)

**Comment by anoek** [comment]
I've been able to reproduce this with the following steps:

```
Make a chat as a player
Make a chat as a spectator
Make a chat as a player
Make a chat as a spectator
cancel the game
```

On the player's screen, the second chat line seems to always be attributed to the player instead of the spectator.
