### ISSUE TITLE
Last mark style from analysis persists to moves

### ISSUE THREAD

**Issue by Capt-Brunch** [online-go/online-go.com#283]
### Summary

If you enter analysis mode and pick one of the symbols (square, X, O, triangle) during your move and then return to game, the translucent stone that follows your cursor retains the last symbol you had selected.

### Environment

 * Operating system: Windows 7
 * Browser: Google Chrome
 * Browser Version: 58.0.3029.110 (64-bit)

### Steps To Reproduce:

1. On your move in a game, enter analysis mode
2. Select one of the four symbols X, O, triangle, square
3. Return to the game by clicking "Back to game"
4. Note that the stone following your cursor for your next move now has the last symbol you used superimposed on it.

### Additional Information:

Screenshot attached
![ogs symbol](https://cloud.githubusercontent.com/assets/1940202/26220623/560c6e7e-3be1-11e7-91b5-4358261c4fd3.PNG)

**Comment by alex-mac** [comment]
In development mode, is there a way to create a game against an opponent? I'm having a bit of difficulty recreating this in my dev environment.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
