### ISSUE TITLE
Add user name based routing

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#285]
### Summary

Re: https://forums.online-go.com/t/username-based-route-to-user-profile-page/12085

It's been requested to be able to link to profiles like `https://online-go.com/user/anoek`, which I think shouldn't practically conflict with anything and would be a nicer way to share links to profiles. 

The existing id based link system should remain intact and used by default internally though since usernames can be changed, so especially as it relates to linking from games and chat messages, the id based system should be used.

**Comment by apetresc** [comment]
If it's any extra motivation, Nate Eagle says he'd be happy to add OGS linking to GoKibitz.com once this is implemented: neagle/gokibitz#160 :smile:

**Comment by anoek** [comment]
This will be live next update (early this week with the release of automatch)
