### ISSUE TITLE
Confirm pass if using two step move settings

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#286]
If you have your settings configured to require a Submit button when moving (two clicks or touched on mobile), then it should also ask you to confirm if you want to pass your turn. Otherwise you can accidentally hit a pass too easily on mobile with no setting to protect yourself from that happening.

**Comment by anoek** [comment]
This is already the case, what are you seeing that's different?

**Comment by anoek** [comment]
Ah, this is not the case when playing *live* games, only when playing correspondence. I agree, pass should ask for a confirmation on live games *iff* double click or submit button is being used.
