### ISSUE TITLE
Play with bot: Unknown speed rapid

### ISSUE THREAD

**Issue by havryliuk** [online-go/online-go.com#2873]
**Describe the bug**
In the new UI, when I am trying to start a game with a bot, I get this error message: **Unknown speed rapid, cannot check challenge, please try again.**

**To Reproduce**
1. Go to **'Play'**
2. Select **Board Size: 19x19**, **Opponent: Computer**, select bot from the list, e.g. **noob_bot_2 (6k)**, select any **Game Clock** and **Handicap** and click **Play**.
3. Popup window with the error appears: **Unknown speed rapid, cannot check challenge, please try again.**

**Expected behavior**
A game with a bot is started as before.

**Screenshots**
![image](https://github.com/user-attachments/assets/52f9a258-17b5-42f5-9b09-e6d434a36928)

**Desktop:**
 - OS: Windows 11 Enterprise, version 23H2, build 22631.4317
 - Browser: Microsoft Edge for Business
 - Version 131.0.2903.63

**Additional context**
Has the API for starting a game changed? And bot developers need to update their bots? Just a guess.

**Comment by GreenAsJade** [comment]
I believe this is fixed now.
