### ISSUE TITLE
Matchmaking results in 20 mins main time even if I chose 5 mins.

### ISSUE THREAD

**Issue by peterjoel** [online-go/online-go.com#2875]
**Describe the bug**
A few times I've chosen a `5m + 5s` game in matchmaking, but the actual game is `20m + 5x30s`.

**To Reproduce**
I didn't happen every time. But 2 out of 3 of the last games I played.

**Expected behavior**
When I choose `5m + 5s` with "flexible" option, I expect to start a game with either `5m + 5s` clock or `5m + 5x30s` clock.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anoek** [comment]
This should be fixed now, thanks for the report!
