### ISSUE TITLE
New create game screens

### ISSUE THREAD

**Issue by andymarden** [online-go/online-go.com#2887]
Ok - maybe not a bug but it feels like it. 

The changes to creating a game have made it like partial to create the game I want - with a long scrolling screen. 

I get that you want some quick settings but imho it's worse than it so l was now.

**Comment by anoek** [comment]
Feedback should be in the forums, but constructive feedback would be even better.

**Comment by andymarden** [comment]
Ok - just to close this off - I would suggest two buttons - standard game vs custom game as a start. And then the next screen is much more targeted. Will post on discussion

**Comment by andymarden** [comment]
You know Ilove you guys!
