### ISSUE TITLE
More control over Reviews. Private reviews of private SGF files

### ISSUE THREAD

**Issue by pondturtle** [online-go/online-go.com#289]
I think it would be great if we could change public/private status of our reviews or even delete them. 

But what I think borders on a bug is that reviews of **private** files from personal SGF library are public. If nothing else, I think that should be changes so they are private just as reviews of private games are.

**Comment by anoek** [comment]
Fixed the accessibility part of this issue on the backend. In the future, open two issues if there are two things being reported :)

**Comment by SAMFYB** [comment]
Is deleting review going to be implemented anytime soon? What's necessary to support this?

**Comment by flovo** [comment]
You should be able to delete your reviews already. 

1) Go to the review you want to delete. 
2) On the pane on the right click Game Information
3) In the pop-up click on Delete.
