### ISSUE TITLE
Ranked games created via Leago.gg do not actually affect rating.

### ISSUE THREAD

**Issue by peterjoel** [online-go/online-go.com#2892]
**Describe the bug**
I have played 2 games from a Leago league, which were created from their platform. The games are shown as "ranked" but neither one actually affected my rating or my opponents'.

**To Reproduce**
1. Participate in a leago league (leago.gg)
2. Arrange a game with an opponent
3. When the game time comes, choose the option to start the game within the Leago platform
4. Play the game
5. Note that it says "ranked: yes" in the game information.
6. Wait several days just in case

The rating graphs for both players do not get an extra data point added. The rankings for both players remain the same.

**Expected behavior**
The winning player's ranking should increase and the losing player's ranking should decrease. The ranking chart should show an extra data point for the game.

**Additional context**
Example games:

* https://online-go.com/game/70385906
* https://online-go.com/game/69494470

**Comment by GreenAsJade** [comment]
This is the intended behaviour.

The game is "ranked" - it did count for a rank.

However, because it was a Leago game, it counted towards the Leago rank and _not_ the OGS rank.

This was a request from the relevant Go associations: they wanted their members to be able to play Leago games without having their OGS rank affected.

**Comment by peterjoel** [comment]
It makes sense that they'd want that. But it's still confusing to say that
it's ranked when it isn't OGS ranked.

Is it possible to configure a competition in Leago to create games that
affect an association ranking as well as OGS ranking?

**Comment by GreenAsJade** [comment]
It's not currently supported by the API, although it readily could be.

It's rather more difficult to make it clear about what "kind" of ranking a game has, in all the places where you might care about that.

Ranked is currently a binary thing - it either is or it isn't.   You have to do lots more digging around to determine what ranks were affected.

**Comment by peterjoel** [comment]
To me, "ranked" should just reflect that they contribute towards the OGS
rank in that case.

Generally the Leago games are identifiable by the text in the game's name
and I don't think it would be confusing to display them as unranked even if
they are being counted towards an external ranking.

**Comment by GreenAsJade** [comment]
Ideally, yes.

It's just not deemed "worth the effort" at this point.
