### ISSUE TITLE
Remove Tracking

### ISSUE THREAD

**Issue by hloeffler** [online-go/online-go.com#29]
### Summary

*Remove Tracking*
https://github.com/online-go/online-go.com/blob/0b599cc055faa4871f91e61c9a7cd669e8d27770/src/index.html#L223-L270

### Environment

 * Operating system:  All
 * Browser: All
 * Browser Version: All

### Steps To Reproduce:

1. Go to https://online-go.com
2. get tracked
3. See that this is wrong 

### Additional Information:

i know you use ads, but there must be a better way

**Comment by anoek** [comment]
Unfortunately we're contractually obligated to have this
