### ISSUE TITLE
Should a chat ban include a person's friends?

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#291]
### Summary

A friend of mine has recently been banned from chatting. Because she is my friend I would like to continue to be able to exchange messages with her. 

### Steps To Reproduce:

1. Get a friend chat-banned.
2. Try to contact her.
3. Find that you can't.

### Additional Information:

This issue is intended to stimulate debate. What is the correct balance to strike? I propose that chat bans should apply to all public forums and to private messages outside your circle of friends, but not to people who have chosen to accept you as a friend.

**Comment by anoek** [comment]
This has been implemented on the backend and will be available next update.
