### ISSUE TITLE
Spectator chat visible during stone removal phase

### ISSUE THREAD

**Issue by RevarIsave** [online-go/online-go.com#293]
There was an issue with this game https://online-go.com/game/8852665
I got there during counting and Ninja-Go could see the chat of PiaVindex. I asked Ninja-Go to confirm it and he said yes, he could see it.

Tested it with some people from German chat in this game https://online-go.com/game/8852906
During the game their chatting was not visible to me or mkei but when we went to the stone removal phase it was.

**Comment by anoek** [comment]
Fixed this on the backend
