### ISSUE TITLE
Untrimmed usernames

### ISSUE THREAD

**Issue by mlopezviedma** [online-go/online-go.com#295]
### Summary

Users having whitespaces at the end and/or at the beginning of their usernames cannot login.

Although that behaviour looks correct to me, the problem is that users *can* set their usernames untrimmed. In my opinion, whether the *Change Username* UI or the Server should trim them.

**Comment by anoek** [comment]
Yeah the server should be doing this, and it totally was at one point at least.. I must have messed that up recently. Thanks!
