### ISSUE TITLE
Implement basic flood counter-measures

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#296]
### Summary

In my opinion, we need basic flood protection implemented in OGS, at least in game and private chats, maybe in tournament and group chats as well.
I think we don't need something very accurate that would cover all possible cases, but just loose limits, enough to prevent some too weak web clients from freezing or enough to prevent data excessive usage.
If it's a bothersome, OGS would let the user the choice whether to block the flooder or not.
In case, such thresholds as the ones I'm suggesting hereafter are already implemented, could you please lower them ?

1st threshold: (browser side) number of occurrences of the same character in the same line.
eg.: 50 ? 100 ?
2nd threshold: (server side) number of lines per user per minute
eg.: 50 ? 100 ?
3rd threshold: (browser side) maximum character limit per line
eg.: 100 ?

As a bonus, everytime one threshold is reached, it could increase a score specific to the user and above a certain score soft limit, it should trigger an alert to the moderation team.
Why ? Because everyone may block a flooder but might not think of reporting his behaviour to the moderation team. With such a feaure, the moderation team could spot recidivists ...  

### Environment
any
### Steps To Reproduce:
ask if needed
### Additional Information:

this thread in the forums: https://forums.online-go.com/t/opponent-flooded-the-chat-to-win-by-timeout/12178

**Comment by anoek** [comment]
This has been implemented on the backend and will be going live today.

**Comment by yewang** [comment]
The game that started the forum thread still seems to cause the browser to freeze up

https://online-go.com/game/8885641
