### ISSUE TITLE
Identity Crisis

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#298]
### Summary

A friend (user id 179886) has recently changed her username from "wolf guard 🐺" to "Uconn Huskies". She seems to be having an identity crisis as a result, with her username flipping back and forth between the two. I've confirmed that it's not an elaborate practical joke this time...

### Environment

 Many users have reported seeing this across several platforms.

### Steps To Reproduce:

1. English chat.
2. Whenever Uconn Huskies comments, her name becomes correct. It stays like that for a while, then the chat screen flickers as it reverts to her old username.

There's also something weird going on with her private chat.

### Additional Information:

![chat1](https://cloud.githubusercontent.com/assets/5913995/26531868/c8a0bb82-43ea-11e7-8ba1-ede8956390c8.png)
![chat2](https://cloud.githubusercontent.com/assets/5913995/26531870/c9faf3f8-43ea-11e7-9596-06a4bbc6da03.png)
![chat3](https://cloud.githubusercontent.com/assets/5913995/26531871/cc6e62a0-43ea-11e7-9454-f8f29f542391.png)

**Comment by roy7** [comment]
Assuming she didn't change it back I actually see the Uconn name right now on

https://online-go.com/player/179886/
