### ISSUE TITLE
Comment box is not visible on library games

### ISSUE THREAD

**Issue by mlopezviedma** [online-go/online-go.com#299]
### Summary

Comments on uploaded SGF files were visible before, but now they aren't.

### Environment

 * Operating system: Linux 4.10
 * Browser: Opera
 * Browser Version: 45.0

### Steps To Reproduce:

1. Go to this uploaded game: https://online-go.com/game/5411500
2. On the move tree you'll see lots of blue circles, indicating the presence of comments on those moves, but there isn't a comment box to show them.

**Comment by pondturtle** [comment]
I confirm this. It is same for me. They show if you start review of them though...

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
