### ISSUE TITLE
Add setting to use an alert box to focus a window and tab when a game begins

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#300]
### Summary

While waiting for a match to be made, some users find it desirable to leave the tab in the background and miss the effect that the old alert box had, which was to bring the window and tab into the foreground when a game began. We should add a setting to use a browser alert box with `alert` as opposed to the "sweetalert" `swal` system we switched to for this particular case.

**Comment by GreenAsJade** [comment]
I was going to do this just now, but I read up on it and it seems strongly deprecated to do this.

Unless I'm mistaken, Chrome doesn't even do this trick any more: I literally could not find documentation for a reliable way to implement it.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
