### ISSUE TITLE
Variations and game tree can be messed up by undos

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#304]
In a game, I planned a variation, got an undo, and played a different move, but the variation from the old move was still branched off from the current move, even though the variation can't be played from the current move.
Also, when my opponent shared a variation branching off of the new move, when I clicked it, it just showed the current board position, resulting me not noticing the variation branching off of the current position.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
