### ISSUE TITLE
"Add friend" action available in cases where no need to

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#306]
### Summary

Even if the user is an artificial intelligence, even if you are logged out, you still have the button "Add friend" displayed.

It's a minor bug but in case you need to free some space in that area, you can hide it :)

### Environment
n/a

### Steps To Reproduce:
ask if needed
### Additional Information:
ask if needed

**Comment by BarneyStratford** [comment]
I can't see this bug at the moment. Can you give a precise sequence of steps that cause it? Or has it evaporated?

**Comment by arnaudgo** [comment]
Hello @BarneyStratford 

I couldn't reproduce it neither :)

Arnaud
