### ISSUE TITLE
Too much scrolling involved in pagination

### ISSUE THREAD

**Issue by viridium** [online-go/online-go.com#308]
There should be a pagination control at the bottom of the "Watch" page, so that we don't have to scroll back up to change page.

**Comment by anoek** [comment]
I think I'd rather see us move towards either auto-fitting the appropriate number of games on a page so there's no scrolling and thus no need for redundant controls, or just switch to infinite scrolling.

**Comment by viridium** [comment]
Sounds like the better option, I agree. Until that happens, is it easy to add a copy of the pagination control to the bottom of the page to "stop the bleeding"?

**Comment by anoek** [comment]
If you can get a couple more people that want this I'd consider it, i'm not sure there's much "bleeding" going on though? Doesn't seem like that big of a deal, the easy solution would be to manually set the page size to fit a full pages' worth of games, and then there's no need for scrolling, no?

**Comment by viridium** [comment]
On a mobile phone, the page size might end up being 1. Also on mobile, scrolling has been choppy, and it occasionally caused a game to be opened. On hitting "back", I don't get to the same place on the page (nor even to the same page, actually). The down–up scrolling makes things cumbersome.
