### ISSUE TITLE
On mobile, review controls are too small

### ISSUE THREAD

**Issue by viridium** [online-go/online-go.com#311]
The review controls end up being too small and close together on my mobile phone, which makes it hard to click the right button when reviewing a game step by step.

**Comment by xanderchin** [comment]
Adding to this, the move comments are way too far down on the interface. It's very annoying to finally click the right button, then have to scroll down to read the comment and back up to see the goban.

**Comment by anoek** [comment]
@xanderchin feel free to open another issue with some suggestions, as is it's a bit hard for me to imagine a way to display both comments and the board in a compact mobile format.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
