### ISSUE TITLE
a couple of things  i miss from kgs...

### ISSUE THREAD

**Issue by brw31415** [online-go/online-go.com#319]
there are a few things i miss from kgs:
1. comments in chat box are numbered by move number
 2. an easy way to store game reviews in the game players' directory, as opposed to the reviewer (who probably doesnt care anyways)

**Comment by crodgers** [comment]
Comments in the chat box are marked with the move number on OGS as well, above the chat line and centered.

**Comment by brw31415** [comment]
but are comments coordinated when stepping through?

**Comment by anoek** [comment]
Please break out issues separately. For enhancements, please articulate what you believe needs to be done to implement the enhancement.
