### ISSUE TITLE
Private games should be filtered out when no granted access

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#320]
### Summary

When you visit a user profile with all on-going games overview, that overview should not include private games if you're not allowed to see them.
By the way, it triggers "Not allowed to access this game" even if you don't attempt "on your own" to access to a private game.
Likely, private games in history should not be listed if you're not allowed or should be marked private.

### Environment

 * Operating system: n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:

ask if needed

### Additional Information:

ask if needed.

Arnaud

**Comment by arnaudgo** [comment]
Mmmm, the first point (private games from the profile overview) can't be always reproduced.
As regards the second point (... from games history), it seems I can always reproduce it :)

**Comment by arnaudgo** [comment]
Hello,

It should not be a big deal in the history to display a [P] TAG in the game history for privates games  in a left-most column. With a caption "Private" ... 

But, maybe it's not worth the effort to display a flag for a game that should not be accessible anyway. But well ... It would be nice to have a more informative row (in the games history).

Arnaud

**Comment by jmdingess** [comment]
This is still an issue; just came here to post the same thing. Going to the profile of a player in private games you don't have access to hits you with several "Not Allowed To Access this Game" notifications.

**Comment by anoek** [comment]
Fixed on the server side (record time on fixing this one!)
