### ISSUE TITLE
19x19 Ladder has two players with rank 86 and two with rank 58, listing opens on wrong page

### ISSUE THREAD

**Issue by cliffordwolf** [online-go/online-go.com#323]
I'm number 259 on the Site 19x19 Ladder. If I open https://online-go.com/ladder/313 it opens on page 13, which lists ranks 239 to 258, i.e. not the page that I am on (which is page 14).

But wait... why does it list ranks 239 to 258 on page 13? Shouldn't it be something like 231 to 260 instead?

I investigated a bit and it turns out there are two players with rank 86:

![image](https://user-images.githubusercontent.com/619764/26895873-4acf3338-4bc3-11e7-985e-b55dc64777fc.png)

And also two players with rank 58:

![image](https://user-images.githubusercontent.com/619764/26896039-d459cfa0-4bc3-11e7-8af9-4b857dc8c7a3.png)

**Comment by anoek** [comment]
"Fixed"

**Comment by anoek** [comment]
(And thanks :) )

**Comment by cliffordwolf** [comment]
Hi @anoek! Thanks for all the great work!

I don't think this issue is fixed. When I go to https://online-go.com/ladder/315 I see the following screen (I'm in position 59 right now in this ladder, which is on the next page, not the page it opens up on):

![image](https://user-images.githubusercontent.com/619764/28754312-26b8c01e-7543-11e7-96e5-aeb9cf50772e.png)

There are two people with rank 40 (as can be seen in the above screenshot) and there are also two people with rank 34 and two people with rank 18:

![image](https://user-images.githubusercontent.com/619764/28754335-66a3b9ea-7543-11e7-988a-17e9d02bde57.png)

![image](https://user-images.githubusercontent.com/619764/28754363-db8b6514-7543-11e7-83ac-fab6127773e2.png)

This causes the 3rd page to cover ranks 39-57 instead of 41-60.

**Comment by anoek** [comment]
bleh.. yeah so I know what's causing this, but it's going to be rather involved to fix it properly. For now I've added a cron to repair the ranks on a nightly basis to help mask the problem. The issue with the site 9x9 should be "fixed" now.
