### ISSUE TITLE
Custom Komi reseting to 6.5

### ISSUE THREAD

**Issue by PrincessBubblegum** [online-go/online-go.com#324]
### Summary
Challenge sent to player rinfifth with custom komi as a ranked game. The komi should be 0.5, but when the challenge was accepted it was 6.5.  The user rinfifth said the same problem occured when he tried to make a custom board at another time.

### Environment

 * Operating system: Windows 10
 * Browser: Chrome
 * Browser Version: 58.0.3029.110 (64-bit)

### Steps To Reproduce:

Not sure about those. Just sent a custom challenge with custom komi. Used the player private message window challene button.

### Additional Information:

Game: https://online-go.com/game/9012747
*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
I think ranked games will ignore any custom komi, that is intentional.

The UI should have prevented a custom komi from being selected for a ranked game, we'll get that fixed up :)

**Comment by anoek** [comment]
This seems to have been resolved at somepoint
