### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by debroos** [online-go/online-go.com#326]
### Summary
Stock Android Browser presents blank scrren on opening OGS
*Briefly describe the issue you are reporting*

### Environment

 * Operating system:Android 4.1.1 
 * Browser:Stock - on Huawei Ascend Y300
 * Browser Version:4.1.1

### Steps To Reproduce:

1. Go to ...https://online-go.com
2. Click ...
3. See - blank page apart from OGS icon in the 
[online-go.com.txt](https://github.com/online-go/online-go.com/files/1060864/online-go.com.txt)
top left corner
![screenshot_2017-06-08-12-34-58](https://user-images.githubusercontent.com/29274773/26926941-9a79f466-4c47-11e7-9716-207152f4fc46.png)

### Additional Information:  Sorry about the aborted first attempt reporting this issue.  My phone didn't offer input of operating system etc, so this latest is via PC

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
Unfortunately we can't support the built in 4.1.1 browser, you might try to see if your device can run Chrome or Firefox mobile though.

**Comment by debroos** [comment]
Thanks for getting back to me.  I suspected that was probably the case.
OGS works fine on Firefox, although very much slower than the stock browser
used to.  Maybe I'll buy a better phone.  Thanks for a great site.  Cheers,
Keith
