### ISSUE TITLE
Tournament bracket (mcmahon) display/links broken

### ISSUE THREAD

**Issue by netnazgul** [online-go/online-go.com#327]
Something is broken in tournament bracket display (specifically McMahon tournaments) and game linking. 

### Environment

 * Operating system: Windows 10 x64
 * Browser: Firefox
 * Browser Version: ESR 52.1.2

### Steps To Reproduce:

1. This [tournament](https://online-go.com/tournament/19323) shows me playing against HongAhnKoa, BiQ, Graphie and JohnnieDarko. All the game links lead to correct games. 
2. If display is switched to another round, McMahon groups are messed up and game links in them do not lead to wrong games of the same tournament. 
3. Even if we are to switch back to current round, group shows me playing against neutralneutralmonk, Samurai T, regina25, TheKreligerMan; game links lead to completely different games.

**Comment by anoek** [comment]
Related to https://github.com/online-go/online-go.com/issues/246

**Comment by anoek** [comment]
This appears to have been fixed at some point
