### ISSUE TITLE
notifications div stays large even if there's no notification

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#332]
### Summary

When there's no notification to read, you can read "No notifications" in a div which stays large ( no-notifications div class ).
On desktop, it's okay we can stand it but on smartphones or tablets with small displays, it matters :)

Could you please fit the div size to that text ?

### Environment

 * Operating system: n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:

Open Notifiications when there's no notifications. See the large area it occupies.

### Additional Information:

ask if needed

Arnaud

**Comment by anoek** [comment]
I think leaving some blank space there reserved for the notifications is important, however I would be happy with some improvement that squished it on mobile / small desktops so that the entire menu would fit.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
