### ISSUE TITLE
Could you please move theme setting to Settings panel ?

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#333]
### Summary

To save space , especially on small displays, but also for more coherency, could you please move theme from the current location to the Settings page ?

### Environment

 * Operating system: any
 * Browser: any
 * Browser Version: any

### Steps To Reproduce:

n/a

### Additional Information:

n/a

Arnaud

**Comment by anoek** [comment]
I've had a lot of positive feedback about having that be available to quickly change, but I'm open to having a poll created to get some more conclusive feedback about that. It probably should be on the settings page as well though.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
