### ISSUE TITLE
Adapt the goban coordinates to the selected WUI language, at least for Asiatic lang.

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#335]
### Summary

As a courtesy, when one user chooses an Asiatic language for the web user interface, he could see coordinates without latin alphabet A,  B, C,..
For example, for Chinese people, they should see 1,2,3... for the vertical lines and 一，二，三，... for the horizontal lines.

### Environment

 * Operating system:  n/a
 * Browser: n/a
 * Browser Version: n/a

### Steps To Reproduce:

n/a

### Additional Information:

Ask if needed

Arnaud

**Comment by anoek** [comment]
I could have sworn i had this working once upon a time..
