### ISSUE TITLE
Overall rank determines eligibility for rank-restricted challenges.

### ISSUE THREAD

**Issue by farraway** [online-go/online-go.com#338]
### Summary

When issuing a challenge with a rank restriction, an opponent's eligibility is determined according to their overall rank rather than the game-type rank specific to the challenge's game-type. This is important because automatic colours and handicaps are determined by the game-type rank, which is a separate rating pool to the overall rank. Separate rating pools should not be used indeterminably.

### Example scenarios

* A player with a 10 kyu blitz rank issues a blitz challenge. The challenge has a rank restriction between 12 and 8 kyu and an automatic handicap. The challenger should expect at most a handicap of 2 stones. Instead the handicap may be any number of stones because the rating-restriction does not apply to the opponent's blitz rank.
* A player with a 10 kyu daily rank, their rating being precisely half-way towards 9 kyu, issues 100 daily challenges. Each challenge has a rank restriction to 10 kyu and automatic colour selection. The challenger should expect an approximate 50/50 split of games with white and black. Instead, there is no way to predict the split in colours because the rating-restriction does not apply to any opponent's daily rank.

### Possible solutions

1. Overall rank should determine eligibility, colours and handicap.
2. Game-type rank should determine eligibility, colours and handicap.

**Comment by farraway** [comment]
A preliminary investigation was done on [this thread on the OGS forums](https://forums.online-go.com/t/a-question-about-rank-and-challenges/12124). I'll reproduce the findings here:


[This line determines the eligibility in the SeekGraph](https://github.com/online-go/online-go.com/blob/8a26913233ee363a41f0ed593cc297dbaaa5837b/src/components/SeekGraph/SeekGraph.tsx#L179) and that appears to check a generic `data.get("user").ranking` value.

At least something like a User with a ranking property is [declared here](https://github.com/online-go/online-go.com/blob/212dd9736004f9c66e7d027d59ece19bac388afa/src/views/User/User.tsx#L318):

```
            "ranking": parseInt($("#user-su-ranking-overall").val()),
            "ranking_blitz": parseInt($("#user-su-ranking-blitz").val()),
            "ranking_live": parseInt($("#user-su-ranking-live").val()),
            "ranking_correspondence": parseInt($("#user-su-ranking-correspondence").val()),
```

This corroborates the idea that properties named `ranking` tend to correspond to a players overall rank, rather than the relevant game-type.

The flow appears to correspond to the following:

1. What is probably some sort of event called `onSeekgraphGlobal` is [triggered with a list of things](https://github.com/online-go/online-go.com/blob/8a26913233ee363a41f0ed593cc297dbaaa5837b/src/components/SeekGraph/SeekGraph.tsx#L154).
2. Whatever these things are, they have a `challenge_id` which we can use to [look up specific challenges](https://github.com/online-go/online-go.com/blob/8a26913233ee363a41f0ed593cc297dbaaa5837b/src/components/SeekGraph/SeekGraph.tsx#L161).
2. We go through each thing in our list, name it `e` for element, and if it is not started or deleted, [we determine the element's `eligible` property](https://github.com/online-go/online-go.com/blob/8a26913233ee363a41f0ed593cc297dbaaa5837b/src/components/SeekGraph/SeekGraph.tsx#L167).
3. Each element has a `min_rank` and a `max_rank` property [we compare to `data.get("user").ranking`](https://github.com/online-go/online-go.com/blob/8a26913233ee363a41f0ed593cc297dbaaa5837b/src/components/SeekGraph/SeekGraph.tsx#L179) in order to determine the value of the `eligible` property.
4. In a clue that says `e` has everything we need, we [then over-write our supposed challenge lookup](https://github.com/online-go/online-go.com/blob/8a26913233ee363a41f0ed593cc297dbaaa5837b/src/components/SeekGraph/SeekGraph.tsx#L192) with a `this.challenges[e.challenge_id] = e;`
5. One final clue, we set a value called `move_time` using another property that `e` has called [`time_control_parameters`](https://github.com/online-go/online-go.com/blob/8a26913233ee363a41f0ed593cc297dbaaa5837b/src/components/SeekGraph/SeekGraph.tsx#L195).

The following seems probable:

* Whatever `e` is, it has `time_control_parameters` which we can probably use to determine the game type.
* We have access to `data.get("user").ranking` which means we probably have access to `data.get("user").ranking_blitz` etc.
* We can therefore calculate the relevant ranking before going into our eligible block and implement the feature properly.

**Comment by anoek** [comment]
I'm closing this as I am very actively working on a replacement for our rating and ranking system that nullifies this issue, should be much better soon :)
