### ISSUE TITLE
Tables and game list views need to be mobile friendly

### ISSUE THREAD

**Issue by kabootle** [online-go/online-go.com#34]
### Summary

On the profile page and "home" page, the tables for game results are wider than the header resulting in really tiny buttons and icons.
Much better is the solution on the "play" page. The tables here are scrollable horizontally.

### Environment

 * Operating system: Android 7.1
 * Browser: chrome
 * Browser Version: newest

### Steps To Reproduce:

1. Go to ... Profile page or home page on OGS with an Android smartphone in portrait mode. 
2. Header is shorter and much smaller than usually

### Additional Information:
Screenshots on forum topic: https://forums.online-go.com/t/header-doesnt-always-cover-the-whole-page-mobile-android/10636?u=kabootle

**Comment by anoek** [comment]
Eg: 

https://github.com/online-go/online-go.com/issues/28#issuecomment-282567228


![](https://cloud.githubusercontent.com/assets/13010650/23341422/4c9612f2-fbfc-11e6-90b6-a559c827cd86.PNG)
