### ISSUE TITLE
Add option to not auto-advance when conditional moves are present

### ISSUE THREAD

**Issue by pwxn** [online-go/online-go.com#340]
### Summary

When using the auto-advance feature, it would be nice if it did not advance if the opponent has submitted conditional moves. This way, you can make all available moves for a specific game while you are still in the mindset for that game. 

### Environment

 * Operating system: Mac
 * Browser: Chrome 

### Steps To Reproduce:

0. auto-advance feature is enabled.
1. It is your turn in multiple correspondence games.
2. You are entering a move for which your opponent has submitted a conditional move.
3. Game advances to the next board, the board you were just looking at is now at the end of the queue.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
