### ISSUE TITLE
Games with no handicap force the strongest player to take white

### ISSUE THREAD

**Issue by juanchodepisa** [online-go/online-go.com#341]
### Summary

I recently started a [tournament](https://online-go.com/tournament/27845) to be played with no handicap. This means one would expect nigiri for all games, that is, random assignment of black and white. Instead, for all games, the stronger player always gets white, which is incorrect and unfair. I'd further argue that it is probably more difficult for a weaker player to deal with the komi against her.

If I remember correctly, this used to be an issue long ago, which I had thought fixed. I wonder if there was a discussion about it that I'm missing.

**Comment by juanchodepisa** [comment]
Never mind, I rechecked and there are some games where it's reversed.

There are 10 out of 28 games the stronger player is black. Expected value is 14, so I'm guessing 10 is still on the fat part of the bell curve.

As a student of mathematics, I should look twice before jumping to confirmation bias.

**Comment by anoek** [comment]
Phew, my favorite kinds of bug reports! :) Thanks for following up!
