### ISSUE TITLE
Can't select ranks for rank restriction

### ISSUE THREAD

**Issue by RevarIsave** [online-go/online-go.com#344]
Reporting for RedAce69

Can't select ranks when enabling rank restriction in custom challenges.
https://prnt.sc/fnyj5n
Issue appeared on Windows 8.1 Pro using Google Chrome 59.0.3071.109 (Official Build) (64-bit)

I checked on Win 7, Chrome Version 58.0.3029.110 and didn't encounter the issue.

**Comment by anoek** [comment]
My hunch is that this is related to having previously had the minimum rank selected, then advancing in rank so the old value was invalid, thus causing some error to be thrown or something.

**Comment by anoek** [comment]
This doesn't seem to be an issue anymore, or at least I can't reproduce it.
