### ISSUE TITLE
Integer values in drop-down list for custom komi

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#345]
### Summary

When setting a custom komi while creating a challenge, there are integer values in the drop-down list.
There should be only decimal candidates.

### Environment

any

### Steps To Reproduce:

ask if needed

### Additional Information:

ask if needed

Arnaud

**Comment by anoek** [comment]
Yeah, I think it's Ing rules that use integral numbers specifically.. and the other rulesets work with integral values too so ¯\_(ツ)_/¯
