### ISSUE TITLE
chat system exposes user ip addresses

### ISSUE THREAD

**Issue by j4g3r** [online-go/online-go.com#348]
### Summary
chat users can stalk and dos each other, various shenanigans are possible once ips are known

### Environment

 * Operating system:  all
 * Browser:  any
 * Browser Version: all

### Steps To Reproduce:

1. Go to ...ogs chat
2. run traffic analyzer
3 profit!

### Additional Information:

http://prntscr.com/folxli

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by arnaudgo** [comment]
Hello,

I haven't done any verification on my side but since it looks quite critical, have you warned the dev team separately so they can double-check and priorize it ? cc @mlopezviedma @anoek

Arnaud

**Comment by anoek** [comment]
erm, this is quite impossible given how the chat system works - all chat goes through our servers, it's not peer to peer.
