### ISSUE TITLE
Making information clearer on Supporter page

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#353]
### Summary

It's possible to see both sentences at the same moment:

You are currently supporting us with $XX per month from your XXX card ending in XXX and expiring on 07/2017, thanks!

And,

"There was a problem processing your support on Jun 29, 2017"

I'm not sure I know what the ideal logic would be but maybe an improvement can be:

if the last charging trial is successful, we should see the first sentence.
If the last charging trial is unsuccessful, we should see the second sentence.

Maybe the second sentence could be in red and maybe the text could be modified. 
I'm thinking of something like "You're not supporting us anymore" (or why not something like "WARNING, after 2 other failures, your support will be automatically canceled, please update your card details if you're willing to keep on supporting us") "[...] due to a failure of charging you the dd/mm/yyyy (or mm/dd/yyyy whatever...) with your card ending with wxyz expring at mm/yyyy".

I'm sorry it's a bit confusing, I hope you understand the main idea of my request.
 
Currently, all supporter privileges seem to go away after the first failure but the page still thank you for the support.
Also, the text "Thank you for your support" is in a bigger font than the little sentence warning there was a problem. Actually that text should become "you're not a supporter yet" or "you're not a supporter anymore" or "there was a problem".

## Environment
any
### Steps To Reproduce:

ask if needed

### Additional Information:

ask if needed

Arnaud

**Comment by anoek** [comment]
Indeed, valid points

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
