### ISSUE TITLE
Game results are not translated

### ISSUE THREAD

**Issue by mlopezviedma** [online-go/online-go.com#355]
### Summary

Game results are not translated, neither in game pages nor in game lists (profiles, libraries, etc).

### Additional Information:

![screenshot-2017-06-30-16h01m34s](https://user-images.githubusercontent.com/10748063/27750047-7e3dfcf4-5dac-11e7-9976-6dbfe150cc8c.jpg)
![screenshot-2017-06-30-16h01m54s](https://user-images.githubusercontent.com/10748063/27750049-813b6fb8-5dac-11e7-9948-d3ef150cee9b.jpg)

**Comment by anoek** [comment]
@mlopezviedma reports points is still untranslated
