### ISSUE TITLE
Feature request: Filtering open tounaments based on if my rank is accepted

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#356]
### Summary

When I visit the page of the open tournaments[1], I would be pleased if I could also see only the tournaments my rank is included in the range allowed by the tournament. So, I can see only the tournaments I can really participate in.

1: https://online-go.com/tournaments

### Environment

any

### Steps To Reproduce:

Ask if needed

### Additional Information:

Ask if needed

Arnaud

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
