### ISSUE TITLE
Strange game : it's my turn but it's not my turn

### ISSUE THREAD

**Issue by hdci** [online-go/online-go.com#357]
### Summary

This concerns game #9252621 (link https://online-go.com/game/9252621). This game is named "sunjang practice"
I'm black, this is white's turn. However, this game appears as if I have to play (the number in black disk at screen's top right shows "1", and when I click on it it leads me to this game).
Also, My opponent doesn't have a clock, though I have one, it shows I have 2 days 20 hours let to make a move, and one hour ago it showed 2 days 21 hours.

Finally, I don't even remember having started this game, for the moves aren't classical (on a 19x19 board the first move which is supposed to be mine is K10 at the center of the board, but when I seldom open like this I create a vertical wall with K16 for instance, but the second move of mine is Q16 which is not a move I would have made).

### Environment

 * Operating system: Mac OS 11
 * Browser: Safari 10.11 or Chrome 59.0.3071.115
 * Browser Version:

Comment : I've got the same result on my android or on Windows 10 and Chrome

### Steps To Reproduce

(None in particular)

### Additional Information:

Screen shot :

![capture d ecran 2017-07-01 a 14 16 15](https://user-images.githubusercontent.com/29815131/27761957-e91b5f6a-5e67-11e7-9fb1-f369adb4683d.png)

**Comment by anoek** [comment]
Hmm, game object says it's white's move, not sure what you were seeing. Hard to do anything about this without some reproduction steps or being able to see the bug in action.

**Comment by hdci** [comment]
Yes that's exactly what I wrote above : it's my turn and it's not my turn.
When I click on the black disk with "1" inside, meaning that I've got a move to perform, I come to this board where it's written "white to move". But at the same time, this is my (black) clock to count down as if it was waiting for me to move.
I cancelled this game to avoid a time out.

**Comment by juanchodepisa** [comment]
There's no error in that game. This game was forked.

The position you are seeing is the starting position for sunjang baduk, a popular variant during the classical period in Korea.

Should I suggest that there should be an obvious way to tell whether a game has been forked from a certain initial position?

**Comment by hdci** [comment]
My opponent challenged me on another game and explained me that he did a forked game (although I don't exactly know what it is precisely). We've begun yesterday a new one and played manually the initial moves. The fact that puzzled me was that the (cancelled) game looked as if it was my (black) turn (the dark disk showing the number of games I have a move to make in, the fact that my clock was counting down), but the text indicated "white to move". Maybe some kind of manipulation error during the forked init.

**Comment by anoek** [comment]
Oh interesting, that's certainly something to look into. Leaving the 'needs more info' tag until we can determine if it's possible to reproduce the bug forking that (or similar) games.

**Comment by juanchodepisa** [comment]
It's worth noting that for sunjang games it is indeed white to move (formally, black plays the first move at tengen, but there's just no difference).

What hdci describes seems to indicate that the timer thinks that it's black's turn even though it's actually white's turn.

I'm willing to bet that the source of this bug is that somewhere in the code there's an assumption that black always plays first in games without handicap (or demo games for that matter). In fact I'm willing to bet that reproducing this bug is actually pretty simple: fork [this game](http://online-go.com/demo/3586).

I could be wrong though.

**Comment by juanchodepisa** [comment]
Point in case: https://online-go.com/game/9302152

I just forked the aforementioned demo game. I'm encountering exactly the same problem as hdci was describing.

It is a correspondence game, so there's plenty of time before it times out.
