### ISSUE TITLE
Overlapping regexes in PrivateChat

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#358]
### Summary

Some URLS can contain an @-sign. For example:
https://www.google.co.uk/maps/place/Platform+9%C2%BE/@51.5321578,-0.1261661

### Environment

 * Operating system: macOS
 * Browser: Safari
 * Browser Version: 10.1

### Steps To Reproduce:

1. Go to Platform 9 3/4
2. Tell someone about the experience in PM
3. See that they can't follow in your magical footsteps.

### Additional Information:

The regexes mangle 

https://www.google.co.uk/maps/place/Platform+9%C2%BE/@51.5321578,-0.1261661

to

<a target='_blank' <a target='_blank' href='mailto:href='https://www.google.co.uk/maps/place/Platform+9%C2%BE/@51.5321578,-0.1261661''>href='https://www.google.co.uk/maps/place/Platform+9%C2%BE/@51.5321578,-0.1261661'</a>>https://www.google.co.uk/maps/place/Platform+9%C2%BE/@51.5321578,-0.1261661</a>

and the other person finds themselves sending an e-mail into hyperspace.

**Comment by anoek** [comment]
Thanks @BarneyStratford  for the quick fix! https://github.com/online-go/online-go.com/pull/359
