### ISSUE TITLE
Correspondence games Submit should not advance to next game but allow planning of conditional moves

### ISSUE THREAD

**Issue by MacNala** [online-go/online-go.com#36]
### Summary

When playing correspondence games the Submit button should not automatically go to the next game but allow the planning of conditional moves

### Environment

 * Operating system: 
Windows 10
 * Browser:
Edge
 * Browser Version:
The latest

### Steps To Reproduce:

1. Go to first correspondence game, play a move
2. Click submit
3. See that entering a conditional move is not possible if there are other games which require a reply. 

### Additional Information:

If there are no further games requiring a move the Submit works correctly.
It is NOT acceptable to say that you can go back to the game and enter conditional moves when you have spent considerable time with the game in front of you to work out what you are planning.

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by roy7** [comment]
If you go to your Settings, you can un-check "Auto-advance to next game after making a move".
