### ISSUE TITLE
Making the private chat minimized window title blink if new incoming message

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#361]
### Summary

Hello,

if not too overkill, it would be nice to have the private chat window title blinking if there's any new incoming message since the user minimized it.

### Environment

 any

### Steps To Reproduce:

Ask if needed

### Additional Information:

ask if needed.

Arnaud

**Comment by anoek** [comment]
Indeed, the private chat system needs an overhaul.. there was some discussion going on in https://github.com/online-go/online-go.com/issues/166 about it as well

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
