### ISSUE TITLE
Ratings don't appear in PlayerDetails

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#362]
### Summary

A user's rating doesn't always appear.

### Environment

Any - it's a backend issue.

### Steps To Reproduce:

1. Go to https://online-go.com/play
2. Click on the name of a user that's not in your player_cache.
3. The user's rating is rendered as "...".

### Additional Information:

![no rating](https://user-images.githubusercontent.com/5913995/27835814-85218eb6-60d4-11e7-95f6-278b202c5170.png)

**Comment by anoek** [comment]
I have this fixed up, it should be up today

**Comment by BarneyStratford** [comment]
Is the fix up? I’m still seeing the problem. I think it needs to be fixed in the termination api.

See you,
Barney.

**Comment by anoek** [comment]
Sorry it is not up yet no, eta Monday
