### ISSUE TITLE
Finished games should show the ranking players were when the game concluded

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#364]
### Summary

As a followup to #363 , the ratings/rankings shown for the players should be what the players were right before the game concluded (prior to the rating adjustment applied for the game). Furthermore, we should update the display of the ranks to be something along the lines of "<player> was <rank>" to indicate that the rank being displayed is historical and not necessarily the current rank.

**Comment by arnaudgo** [comment]
Unfortunately, I miss time right now for entering into details of what I think but imho, it's a topic that would benefit of a discussion with the users...

**Comment by mathkr** [comment]
Can the same be done for the game history on the profile page? I think that would be just as important. 
https://ogs.uservoice.com/forums/277766-online-go-com-suggestions-and-feature-requests/suggestions/6911696-game-history-should-reflect-the-ranks-of-the-playe

**Comment by lrperlmu** [comment]
Here's another discussion thread about this issue: 
https://forums.online-go.com/t/why-in-past-games-the-username-appears-with-the-present-rank/11921

**Comment by BHydden** [comment]
I believe this has been implemented now.
