### ISSUE TITLE
Play a sound to indicate that your opponent has resigned in a live game

### ISSUE THREAD

**Issue by autarch** [online-go/online-go.com#365]
This would a nice UX enhancement. As it stands now, it's easy to miss a resignation when playing a non-blitz live game. My opponent might have 10 minutes of main time left, so I expect moves could take a while. The message indicating a resignation is not particularly eye-catching, and I'm looking at the board, not the upper right corner with the time.

**Comment by anoek** [comment]
This should be happening, if it's not it's a bug.

**Comment by autarch** [comment]
Ah, ok, I'm not hearing anything, though it's possible I'm just not noticing the resignation sound if it's subtle. The click sound for moves _does_ work.

I'm on Chrome 59.0.3071.115 on Ubuntu 16.04.

**Comment by autarch** [comment]
Ok, I just head it. It's _really_ subtle. To my hearing, it's quieter than the click sound. It's also just too short to attract attention some of the time, especially if I'm also listening to music while I play. Maybe this should be retitled to "resignation sound is not attention-grabbing enough"

To make it more work you could offer multiple sound options. Maybe some folks like the current sound.

**Comment by BHydden** [comment]
This issue can be closed, resolved with big audio update.
