### ISSUE TITLE
For AI, "Administrator" text overlaps with the field value

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#367]
### Summary

For AI accounts, the administrator username overlaps with the field name "Administrator".
Displays well with Chrome under Android and also with Firefox on the desktop.

### Environment

 * Operating system: Android
 * Browser: Firefox 
 * Browser Version: 54.0.1

### Steps To Reproduce:

Ask if needed

### Additional Information:

![unreadable_ai_admin](https://user-images.githubusercontent.com/26174230/27984771-0d4aeaa4-63d6-11e7-899e-f5a8e267a87a.png)

**Comment by anoek** [comment]
This is fixed on the glicko2 branch
