### ISSUE TITLE
Cannot disable profanity filter

### ISSUE THREAD

**Issue by mlopezviedma** [online-go/online-go.com#371]
### Summary

Although I have the profanity filter disabled on settings, the filter is still being applied.

### Environment

 * Operating system: Linux x86_64
 * Browser: Opera
 * Browser Version: 45

### Additional Information:

I already cleared cookies and browser cache.

**Comment by pondturtle** [comment]
Same for me
OS: Win 7 AND Lubuntu Linux x64
Browser: Latest Firefox on both and chrome v59 on win
