### ISSUE TITLE
Simple clock display doesn't work properly

### ISSUE THREAD

**Issue by mlopezviedma** [online-go/online-go.com#375]
### Summary

Simple clock always shows `0.0` for the player who has the turn to play.

### Environment

 * Operating system: Linux
 * Browser: Opera
 * Browser Version: 45

**Comment by anoek** [comment]
Are you still seeing this? I pushed up some changes that might have been related to this, and I'm not able to reproduce this bug currently.

**Comment by mlopezviedma** [comment]
I'm still seeing this.
![screenshot-2017-08-02-16h35m12s](https://user-images.githubusercontent.com/10748063/28891109-bfd155f0-779f-11e7-8aee-7b029e24af54.jpg)
![screenshot-2017-08-02-16h35m18s](https://user-images.githubusercontent.com/10748063/28891110-bfd77688-779f-11e7-86c4-eaa47ddba42f.jpg)
![screenshot-2017-08-02-16h35m43s](https://user-images.githubusercontent.com/10748063/28891112-bfdd3d98-779f-11e7-9050-89bffc0710e0.jpg)

**Comment by mlopezviedma** [comment]
I should clarify. Now it shows 0.0 for the player who played last and a blue 5minutes clock for the player who has the turn, like if it was the first move of the game.

**Comment by anoek** [comment]
I'm still unable to reproduce this.. Can you check once more, and if you still see it, can you look to see if your clock is out of sync by chance? (Which is a valid use case, it's just hard for me to test)

**Comment by mlopezviedma** [comment]
If you mean the system clock, then no. Now I always see 5:00 blue countdown for Black and 0.0 for White, no matter who's turn it is.

**Comment by anoek** [comment]
That is really strange.. works great for me on chrome, firefox, and opera on linux :(

**Comment by mlopezviedma** [comment]
It sure is... I tested with Opera on linux by playing against a testing account on an incognito window. Didn't test it with another user.

**Comment by mlopezviedma** [comment]
I'd say we close this one for now, given that noone else reported anything similar?
