### ISSUE TITLE
Rank incoherencies

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#379]
### Summary

Complements closed issue #363 which was mixing two things:

- the display at the same time of the former and current ranks
- kind of cache issue what I had created the issue for.

So, in this issue, I want to talk about two problems that may be linked.

1°/ During a time range without new results,  
it happens frequently that I see a rank, let's say 15 kyu in that area above the goban where the left time appears but where the rating doesn't appear (as the date of today).
So, while I'm switching from a game to another through the black circle mentioning how many games it's my turn in.... sometimes it becomes 14 kyu. In that testing time, 14 kyu is my current rank while 15 kyu is my former rank. 
But sometimes that same value turns back to 15 kyu, following no obvious logic.

2°/ In the same area, my rank appears with a trailing 'T' even if I haven't timed out recenly. And, same behaviour as in the first case explained previously, from times to times it turns back to my rank without that suffix (while I'm switching from a game to another...) 

In both cases, refreshing the page solves the problem for the game page I'm on but few seconds later, it's still possible, for that same game, to see the T again.

I'll enclose to the issue 3 screenshots made during the same 5-minutes period when no new results have occured at the mean time.

I haven't tried to empty my browser cache.

### Environment

 * Operating system: Android 7
 * Browser: Chrome but also Firefox 
 * Browser Version: Chrome 59.0.3071.125 /  FF 54.0.1

It doesn't seem to occur on my dekstop.

### Steps To Reproduce:

Ask if needed
### Additional Information:
![rank-witht](https://user-images.githubusercontent.com/26174230/28208613-7e01e702-6886-11e7-85ab-f6e454445e12.png)
![rank-withoutt](https://user-images.githubusercontent.com/26174230/28208611-7dfe075e-6886-11e7-8451-734717c9401a.png)
![games-history](https://user-images.githubusercontent.com/26174230/28208612-7e00960e-6886-11e7-9f59-5dc26a045bc9.png)

Arnaud

**Comment by anoek** [comment]
So point one I *think* is covered by https://github.com/online-go/online-go.com/issues/364 which is just a distilled #363 essentially

I'm pretty sure what you're seeing with point 2 is actually a side effect of the glicko2 migration going on in the background - https://forums.online-go.com/t/system-thinks-i-have-timed-out-of-a-recent-game/12770/3?u=anoek
