### ISSUE TITLE
Puzzles no longer work in OSX Safari

### ISSUE THREAD

**Issue by pelevesque** [online-go/online-go.com#38]
### Summary

When I click a puzzle set in OS X Safari I am presented with a small graphic instead of a puzzle. 

### Environment

 * Operating system: OSX Sierra 10.12.3 
 * Browser: Safari
 * Browser Version: 10.0.3

### Steps To Reproduce:

1. Try to do a puzzle.

### Additional Information:

I get 5 errors in the console.
I attached a screenshot.

![screen shot 2017-02-27 at 12 39 50 am](https://cloud.githubusercontent.com/assets/4752429/23349999/56b41bba-fc85-11e6-9dc7-57262a470196.png)

![screen shot 2017-02-27 at 12 28 07 am](https://cloud.githubusercontent.com/assets/4752429/23349832/189a1eca-fc84-11e6-9145-8a9ea8a08269.png)

**Comment by pelevesque** [comment]
https://forums.online-go.com/t/puzzles-wont-display-in-safari-correctly/10919

**Comment by blamarche** [comment]
I don't have a mac, but I believe this would be fixed by the pull request here when it goes live. I did not specifically test puzzles however, I will report back: https://github.com/online-go/online-go.com/pull/37#issuecomment-282718082

**Comment by blamarche** [comment]
Looks like it was in two stylesheets, should be fixed via: https://github.com/online-go/online-go.com/pull/40

**Comment by BarneyStratford** [comment]
I saw this same issue, and it looks like it has been fixed now.
