### ISSUE TITLE
Providing a reference on how rank/rating works

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#384]
### Summary

Rank/Rating is one of the things that raise questions the most and today the information is disseminated in several forums threads, some users keep asking already answered questions because sometimes it's a burden to search through the forums or sometimes because we're just lazy.
If we are determined enough, we may have found some interesting content but since they are forums, anyone can provide clues. Will I trust the message ? Will I understand it ? If i need to ask for precisions, sometimes it's already too late for using the same thread. And anyway, a lot of key information I may receive will again get buried with the time and won't necessarily be found by someone else.

Sorry for that long introduction. I wish I could find on OGS website a reference about rank/rating, linked from the pages where's it's meaningful to link to... Through a simple '?' question mark, or some other little symbol.

This could be a pinned forum thread but it could have another form and I'd imagined more something within ogs pages and versioned in git.

It could be a FAQ which is a practical form for checking the information we want. And, it could provide a comprehensive of examples and use cases illustrating the theoric point.

Amongst the questions I'm thinking of:

Are all games affecting my rank ?
How long will my status stay provisional ?
How is rank/rating calculated ? (obviously) which implies:
Does the win/loss margin matter ?
Does the board size matter ?
Do time settings matter ?
Does cancelation affect my rating ?
Does the rating decrease/increase for one game has a maximum/minimum ?
Does the number of wins/losses in a row affect how fast/slow my rating evolves ?
If I stop playing ranked games for a while, can my rating change on its own  ? (based on my previous opponent's performance, for example)
Does resignation affect the same my rating that any other game result ?
Does handicap affect the effect of loss/win on rating ?
Does the result of my other games have an effect on how the result of the current game will affect my rating?
I think I'm under/over rated, is there something I can do ?

### Environment
n/a
### Steps To Reproduce:
n/a
### Additional Information:

n/a

Arnaud

**Comment by GreenAsJade** [comment]
Is the source code for the ranking engine available to inspect?

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
