### ISSUE TITLE
All emails sent from beta misleadingly link to production environment

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#386]
### Summary

I used password recovery on the beta server and got the email "aka" "[OGS] Password Reset Instructions"
Which actually, today, just sends you a password.
It's fine if you use it right away but when you search for it in your mail archives, it may be not easy to know if it's from beta or from production. **Especially when it links to production**

edit: Also true for email types like "Game has started" that link to a game page ... on the production !

### Environment

any

### Steps To Reproduce:

ask if needed

### Additional Information:

Someone (hopefully you!) has requested a password reset for your online-go.com
account. To proceed, simply login with the following credentials:

Username: blabla
Password: blabla

Arnaud

**Comment by arnaudgo** [comment]
Actually, it's worth. It contains a link to the production site even if it's for beta. I haven't noticed that :-)

**Comment by arnaudgo** [comment]
Hi @anoek, I edited both title and content since the issue is broader than I thought :-)

Arnaud

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
