### ISSUE TITLE
Ability to publish the maintenance status of a bot

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#390]
### Summary

As a bot administrator, I would like to be able to set a flag "under maintenance" to the bot when it's under maintenance.

I don't need any logic implemented behind, I just would like to warn OGS users that even if challenges are accepted, my bot is not able to play right now. And it's not because it has just crashed, so there's no need to try again right away since it's under maintenance.

On the bot profile page, this could show as "Under maintenance" or "Functional" with ":-(" or ":-)' according the bit status.

### Environment

n/a

### Steps To Reproduce:

n/a

### Additional Information:

n/a

Arnaud

**Comment by arnaudgo** [comment]
Hello,

I'm afraid there's a little logic to implement: exclude it from the AI account drop-down list when the user chooses to play against the computer.

Arnaud

**Comment by arnaudgo** [comment]
Well, I don't see the last point as required ;) it's enough to stop the bot. I had left it running ...

Arnaud

**Comment by anoek** [comment]
I think the last point is the most important, the need to have an option to exclude a bot from the global list. That has come up a lot recently.

**Comment by arnaudgo** [comment]
Hello,

Well @anoek it seems that when gtp2ogs is not running, the bot is removed from that list. I had imagined it was all the accounts with AI flag but it's not the case. So, maybe not as important as I had originally thought.

:) 

Arnaud

**Comment by anoek** [comment]
Yep that is true, though there's been a lot of interest in running bots in a pseudo development mode where they can be online and play other bots or other players, but aren't constantly getting new games shoved upon them.

**Comment by roy7** [comment]
Just linking this issue to another in the other repo. https://github.com/online-go/gtp2ogs/issues/29

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
