### ISSUE TITLE
Unable to input decimals in autoplay delay (browser specific)

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#391]
### Summary

When you set autodelay in seconds, on desktop browser, you can pick up a float value with one decimal.
There's no need to offer such a precision and the user loses the benefit of the arrows since it's quicker to use the keyboard for inserting a custom value.

**edit: Firefox under Android 7.0 doesn't allow to input decimal separator (.).**

### Environment

Firefox 54.0.1 on Android 7.0:

### Steps To Reproduce:

Ask if needed

### Additional Information:

Ask if needed

Arnaud

**Comment by mlopezviedma** [comment]
What step do you suggest? Maybe 0.5s?

**Comment by arnaudgo** [comment]
Hello @mlopezviedma ,

I'm more worried about offering the same precision whatever the user agent is.
And that was what I meant by this issue (I was not very clear) till I realized the problem I'm facing is that on Firefox under Android, it doesn't let me to insert a float number... Whereas Chrome does.
So, the problem is specific to an environment !

But indeed, it's the opportunity to question about the appropriate step, I think we don't need ms at all, it's not a such critical parameter, right ? However, it's not such a burden to stand a 1/2 precision neither.

Thus,  I suggest 1 second step but I can stand 0.5 second step, which would be better than 0.1s step anyway :)

Arnaud
