### ISSUE TITLE
When disabling analysis, the link for downloading sgf file should be removed

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#392]
### Summary

When you disable analysis, you still have the link for downloading the SGF file and you get the error message saying the file is invalid.

### Environment
any

### Steps To Reproduce:

Create a game disabling analysis.
See there's still the link for downloading the SGF file.
Try downloading it and see there's an error message. 

### Additional Information:

Ask if needed

Arnaud

**Comment by anoek** [comment]
Yeah that shouldn't work. The intended behavior is for the icon to still be there but to inform the user that they can't download the game until after it has concluded.
