### ISSUE TITLE
It is not possible to identify which correspondence games need a reply.

### ISSUE THREAD

**Issue by MacNala** [online-go/online-go.com#4]
### Summary

When first opened the website displays correspondence games in an unordered list.
There is no indication of which games are waiting a reply.
The list is not ordered 
- it should be in the order of games requiring a reply
   and then by lowest time remaining to make a reply.
### Environment

* Operating system: 
Windows 10

  * Browser:
Internet Explorer or Edge

 * Browser Version:
IE11 

### Steps To Reproduce:

1. Go to online-go.com.

**Comment by roy7** [comment]
@anoek If it saves you any effort, here was that grease monkey script as a work around:

https://forums.online-go.com/t/broken-sorting-of-correspondence-games-list-view/10708
