### ISSUE TITLE
Shouldn't this be a draw?

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#402]
### Summary

https://online-go.com/game/9612060
"Black wins by 0 points."
I'd call that a draw, not a win for Black.

**Comment by anoek** [comment]
Perhaps.. it's an artifact of some of the rulesets stating black wins in the event of equal points, and all of the other rulesets sidestepping the issue by using fractional Komi for rated games, so in the interest of simplicity we kept it uniform. I think it'd be fine to mark them as draws for the rule sets that don't explicitly state that black wins when the points are equal. All moot points for rated games though, so not really a high priority.

**Comment by BarneyStratford** [comment]
OK. It's perhaps a UI issue rather than a correctness problem. There are bigger fish to fry at the moment.
