### ISSUE TITLE
Time running out notification

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#407]
### Summary

I play correspondence games, and at the appropriate times I get a notification saying that I am running out of time to make my move. However, the problem I am experiencing is that the time mentioned in the notification doesn't match the game time remaining.

For example, say one of my games has triggered the "12 hours left" warning; recently the warning message has said 6 hours and just now I had two games drop under 12 hours and the message for both of them was 1hr 50 min.

### Environment

 * Operating system: Windows 10
 * Browser: Chrome
 * Browser Version: 60.0.3112.90 (Official Build) (64-bit)

### Steps To Reproduce:

1. Let a correspondence game drop below 12 hours
2. Observe the notification in the top right-hand corner of the web page
3. See that the time remaining in the notification does not say 12 hours  

### Additional Information:

To clarify, the notifications are coming reliably at the correct time, it is simply the content of the notification that is incorrect.
Forgot to take a screen shot, sorry.

**Comment by arnaudgo** [comment]
Hello,

@BHydden says right !! 

It also happens on Android for me, with Firefox 57.0.1

See the screenshots hereafter :) 

Arnaud

---
![non-matching-times-2](https://user-images.githubusercontent.com/26174230/34447001-23dd5fc0-ece0-11e7-8642-827df31449d8.png)
![non-matching-times-1](https://user-images.githubusercontent.com/26174230/34447002-23f70fd8-ece0-11e7-8c1b-37687b210fde.png)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
