### ISSUE TITLE
Bad resizing of window

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#409]
When the window is thin (e.g. 435 pixels wide), OGS looks fine normally, but as soon as Analyze Mode is entered, things are cut off of the right side: komi, board numbers, chat scroll, number of spectators, 'Toggle coordinates'.
Nice looking regular game mode:
https://www.dropbox.com/s/0usonasm80p6zxs/Screenshot%202017-08-10%2021.56.52.png?dl=0
Bad looking Analyze Mode:
https://www.dropbox.com/s/bsfpm0mvv3et8cw/Screenshot%202017-08-10%2021.56.32.png?dl=0
The problems with the chat scroll and spectator count persist as the window is widened to 1120 pixels:
https://www.dropbox.com/s/3c1tccdoohr4gfa/Screenshot%202017-08-10%2022.07.44.png?dl=0

Not specific to Analyze Mode:
The worst resizing problems (but a bit more difficult to replicate) can be obtained from combinations of e.g. making the window horizontally thin, then vertically short, horizontally wide, normal size, horizontally thin resulting in stuff like this:
https://www.dropbox.com/s/40aqol3kve1nx75/Screenshot%202017-08-10%2022.22.08.png?dl=0
I was able to replicate this sort of resizing problem by trying a few times.
Duplicated without Analyze Mode:
https://www.dropbox.com/s/nx8nt0b17ihcbcw/Screenshot%202017-08-10%2022.33.08.png?dl=0

**Comment by alex-mac** [comment]
If it's okay, I'd like to work on this issue! I was able to replicate the issue using Chrome on a Windows machine.
