### ISSUE TITLE
When reviewing a game, cursor no longer follows the cursor of the user in control

### ISSUE THREAD

**Issue by FlyingPumba** [online-go/online-go.com#41]
### Summary

When reviewing a game, cursor no longer follows the cursor of the user in control.
For example, if the user in control jumps to move 90, the other users will remain in the previous move.
This might as well be a visual glitch, and not a server problem.

### Environment

 * Operating system: Ubuntu 16.04
 * Browser: Chrome
 * Browser Version: 54.0.2840.90

### Steps To Reproduce:

1. Open a game
2. Start a revision with user A (the one in control)
3. Join the revision with user B
4. Move around in the moves tree of user A.
5. Cursor and board of user B doesn't update.

### Additional Information:

Not related to a specific game, it has happened in several reviews.

**Comment by anoek** [comment]
This appears to happen when navigating with the forward and back buttons (either keyboard or the below-board controls), though making a placement or "doing anything" syncs the review back up.
