### ISSUE TITLE
Backend refuses to return any players if a single one doesn't exist

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#410]
### Summary

/termination-api/players gives a 404 if any of the players are nonexistent.

### Environment

Backend

### Steps To Reproduce:

1. Make a small mistake while working on OGS code that results in a non-existent player id being player_cache.fetched from the backend.
2. See that a whole bunch of other players that you *know* to exist suddenly fail to show up as well.
3. Spend a while debugging it. :-)

I think it might be better to return as many players as make sense in this situation rather than barfing completely. The front end can handle it and it might save our bacon in future. The new player_cache that's coming up in a future PR has code to explicitly detect this situation.

Low priority, but nice to have.

**Comment by anoek** [comment]
I don't think this is a good idea, I think it would mask programming mistakes and make it harder to track down "sometimes working" bugs on the client side.

The current behavior seems appropriate, if you ask the server for something and it's not there, it should return a 404 and indicate that it couldn't fulfill your request. In this case, if you ask the server for 10 things and it can only find 9, it still couldn't fulfill your request, so it should still return an error explaining that it couldn't fulfill your request and tell you what it couldn't find, which it does. It's an error to not full complete a request.

The other option would be to return a 200 and provide per-item errors, but that complicates client implementations unnecessarily I believe. Returning a hard error for the entire request makes it harder for clients to make mistakes and get away with it.
