### ISSUE TITLE
graphic interface - stones + board

### ISSUE THREAD

**Issue by seunin** [online-go/online-go.com#411]
continuing the discussion we had on message and pull request.
Last talk:

These look really nice :)Currently we don't use images for any of the stones, we procedurally generate them on the fly. That doesn't mean we can't use these, but it does mean some code will need to be written in order to incorporate these.Because of this, can you open up an issue with these attachments (instead of a pull request), that way we can track the implementation details? Once that code is written, then we can make a pull request of that.Also, do you have the originals for these? It could be interesting to use the images prior to the application of the light and shadow layers so that we can rotate those, then apply the light and shadow dynamically, giving more variation to the placed stones.

--

I do have the originals, but unfortunately they are made in Photoshop, and the layers use blends, etc. But I did 5 versions for the white stones, that use different textures. I think the black ones do not need that. Maybe you could program a random selection. 
what do you think?

![black](https://user-images.githubusercontent.com/26085847/29202421-c2907e88-7e70-11e7-88b5-92c40b75f828.png)
![board texture seamless](https://user-images.githubusercontent.com/26085847/29202423-c291f006-7e70-11e7-8158-464bd217c32c.jpg)
![white-1](https://user-images.githubusercontent.com/26085847/29202425-c29311fc-7e70-11e7-93d0-7f05d0bae42c.png)
![white-2](https://user-images.githubusercontent.com/26085847/29202422-c2912a86-7e70-11e7-8ff9-9db8dc9ba12d.png)
![white-3](https://user-images.githubusercontent.com/26085847/29202426-c2959af8-7e70-11e7-9e60-dc4823a72630.png)
![white-4](https://user-images.githubusercontent.com/26085847/29202424-c2928ec6-7e70-11e7-84f2-d26c9851d5ad.png)
![white-5](https://user-images.githubusercontent.com/26085847/29202427-c2a992ce-7e70-11e7-9be9-7b5963a5a561.png)

**Comment by anoek** [comment]
The photoshop files are fine, it's easy enough to extract what's needed.

We'd certainly use a random selection, but it'd also be a nice touch to be able to rotate them randomly as as well.

**Comment by seunin** [comment]
Photoshop files will not work. I may not have expressed myself too clearly. Sorry about that. You will just have to trust me :)

I have made more iterations on the white stone. They are now 15 stones - rings are rotated and custom adjusted in density for each one.
I'm reattaching the whole thing.

Hope this will be fine.

![black](https://user-images.githubusercontent.com/26085847/29217758-5f890008-7ebb-11e7-9f53-f9f463ff3b17.png)
![board texture seamless](https://user-images.githubusercontent.com/26085847/29217757-5f8775ee-7ebb-11e7-8f73-ad494ab1fe3b.jpg)
![white-1](https://user-images.githubusercontent.com/26085847/29217762-5f8d9014-7ebb-11e7-8cb4-2374a3fad0f1.png)
![white-2](https://user-images.githubusercontent.com/26085847/29217760-5f8ad46e-7ebb-11e7-90e6-ed9ceed053fb.png)
![white-3](https://user-images.githubusercontent.com/26085847/29217761-5f8cd728-7ebb-11e7-8c1e-77e7057a5a32.png)
![white-4](https://user-images.githubusercontent.com/26085847/29217759-5f8a9062-7ebb-11e7-86c2-81b62e07263d.png)
![white-5](https://user-images.githubusercontent.com/26085847/29217765-5faa6c8e-7ebb-11e7-8ea0-789042b44863.png)
![white-6](https://user-images.githubusercontent.com/26085847/29217763-5fa6640e-7ebb-11e7-85a5-4aad6530f7c7.png)
![white-7](https://user-images.githubusercontent.com/26085847/29217764-5faa7c88-7ebb-11e7-89a5-6af39de45b2e.png)
![white-8](https://user-images.githubusercontent.com/26085847/29217767-5faeb6a4-7ebb-11e7-9016-a362d693db0f.png)
![white-9](https://user-images.githubusercontent.com/26085847/29217768-5fb10a30-7ebb-11e7-8582-7f2fbdbad0b7.png)
![white-10](https://user-images.githubusercontent.com/26085847/29217766-5fae54de-7ebb-11e7-95cd-a95b98633b08.png)
![white-11](https://user-images.githubusercontent.com/26085847/29217771-5fc81e00-7ebb-11e7-864c-b27b9853e5d5.png)
![white-12](https://user-images.githubusercontent.com/26085847/29217769-5fc56638-7ebb-11e7-9a40-c9cfec74ff23.png)
![white-13](https://user-images.githubusercontent.com/26085847/29217770-5fc7ce32-7ebb-11e7-9759-23bb34a65ab5.png)
![white-14](https://user-images.githubusercontent.com/26085847/29217772-5fcfdc58-7ebb-11e7-840f-1bc206b61da5.png)
![white-15](https://user-images.githubusercontent.com/26085847/29217773-5fd2d1ce-7ebb-11e7-84e0-9e8e79f22273.png)

**Comment by seunin** [comment]
Hi @anoek ,
How are things? 
I was wondering if you advanced in programming the graphics. 
All the best,
