### ISSUE TITLE
Unable to Edit Group posts

### ISSUE THREAD

**Issue by agentneigh** [online-go/online-go.com#412]
### Summary

Unable to edit the words in Group Posts

### Environment
Windows 10 
Chrome

### Steps To Reproduce:
Click Edit, try to edit text, nothing changes.
### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
Fixed in 

2573c61afa1a27ad5c35960f438c030a5d65e9ec 
014fb966a88abfed6766828fada6dbf0a46b6cbe
