### ISSUE TITLE
Game information missing from notification / in game

### ISSUE THREAD

**Issue by agentneigh** [online-go/online-go.com#415]
### Summary
Their is no Game name when receiving a notification,
When in game, Game name or if game is ranked is missing
### Suggestion

On start of a new game have chat show:
Game name
Rules
Time Settings
Handicap / Komi

### Steps To Reproduce:

On all game challenges, notification simply do not show game name.
In new game, unable to easily tell some game settings, rank / time setting / game name / game rules

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
