### ISSUE TITLE
Error when using The TOR Browser

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#416]
"You do not have permission to perform this action." No explanation of what the action is or how to get permission.
![screenshot at 2017-08-15 21-12-11](https://user-images.githubusercontent.com/499794/29344635-d9d5f370-81fe-11e7-8408-d978ff70321d.png)

I am in a game which is not shown.
The friends list is not available.
I was unable to view my profile.

The problem went away after pressing "New Tor Circuit for this Site", but I think the problem shouldn't have happened in the first place.

**Comment by anoek** [comment]
The fact that the site is loading at all is the bug here, not that there are partial failures. Unfortunately Tor has been a major vector for abuse in the past so we have been blocking it.
