### ISSUE TITLE
SGF loading can result in excess marks

### ISSUE THREAD

**Issue by agentneigh** [online-go/online-go.com#417]
### Summary

SFG loaded into the SGF library tend to have errors, more so those with complexity for example lectures
### Environment

Windows Explorer 11 / chrome
SGF's found here : http://senseis.xmp.net/?SteveFawthrop%2FCounting

### Steps To Reproduce:

rename .txt link to SGF link
save in SGF library
run SGF, see example pictures 

### Additional Information:

![image](https://user-images.githubusercontent.com/17864308/29371311-a2317384-8282-11e7-9f90-618114f9fdb6.png)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
