### ISSUE TITLE
Downloaded SGFs still show old rankings

### ISSUE THREAD

**Issue by sousys** [online-go/online-go.com#418]
### Summary

Downloaded SGFs still show old Rankings, even tho game was started under new system

**Comment by climu** [comment]
Hi,

Just a note to say this bugs affect people who upload their games to [gokibitz](https://gokibitz.com/) as well as the [Open Study Room](https://openstudyroom.org/) system.

**Comment by alexmitrani** [comment]
It is not clear what they are, sometimes the rankings stored in the SGFs are way out.  It is only clear that they are not the actual ranks displayed in OGS.

**Comment by alexmitrani** [comment]
SGFs are probably one of the few areas where KGS is clearly better than OGS.  Every day OGS users who upload their kifus to gokibitz.com are editing their SGFs to correct the ranks or leaving comments such as "actual ranks are..." on gokibitz.  While this is not a massive amount of work it is irksome and strange given how good OGS is in other respects.

**Comment by Ainue** [comment]
This is a huge issue that makes OGS incompatible with major review sites like https://gokibitz.com

I've had several dan friends abandon OGS and return to KGS where exported SGFs do not have this issue.

**Comment by Jajunk** [comment]
Please fix this!

**Comment by anoek** [comment]
Finally fixed this on the back end, should be deployed later today.

**Comment by climu** [comment]
Sorry to raise that again but I think there is still an issue with players who doesn't have a rank on OGS.

This [game](https://online-go.com/game/12203137) for instance show odnhis as 13 kyu while he has a ? on his profile.

Thanks for all!

**Comment by anoek** [comment]
Would it be preferable to display a `?`? 13k is the actual rank underneath the hood, the deviation is so high that it's not really a good estimate, hence why we mask that on the interface by putting a `?`.. but math wise, 13k is correct.

**Comment by SharpKing** [comment]
IMO it would make sense to follow the same logic as display on OGS. So if the deviation is high enough, show ‘?’. It’s more accurate than 13K because that happens to be the default rank for the glicko2 or w/e system. (not an expert on that!)

**Comment by BHydden** [comment]
Yeah I agree if the uncertainty is too high rank should just be '?'

**Comment by anoek** [comment]
Alrighty, deploying the change in a few minutes
