### ISSUE TITLE
Don't invert/rotate/flip shared puzzles so people talk about the same position

### ISSUE THREAD

**Issue by ajcsimons** [online-go/online-go.com#425]
### Summary

When someone shares a puzzle (e.g. https://online-go.com/puzzle/3433) from OGS to another place on the internet it is common for confusion to follow as different users view the puzzle with different colours/orientations. So the original poster might ask "Why can't black play at c3 on move 5?" to which another replies "It's white's turn at move 5, and c3 is off the board".

It would be better if the puzzle appeared the same for all users to facilitate discussion (I am aware the reason for varying it when someone is doing tsumego training). This shouldn't require the viewer to use the OGS controls (not everyone will and they may not be familiar with them).

To achieve this I suggest either make a new sharing url such as https://online-go.com/puzzle/3433/share which displays an invariant version of the problem (problem is user might just copy normal url from address bar), or even better use the http referer to detect if the viewer is coming from outside OGS, and if so automatically show them the invariant version of the problem. A "don't vary puzzles" profile option won't work as this needs to work for people who don't have an OGS account.

### Environment

 * Any browser

### Steps To Reproduce:

1. Go to any puzzle url such as https://online-go.com/puzzle/3433/
2. Do it again in another tab/browser
3. Observe the problem doesn't always look the same

### Additional Information:

* Example confusion: https://www.reddit.com/r/baduk/comments/51jizg/question_about_this_life_and_death_problem/d7cng7g/

**Comment by anoek** [comment]
Dup of https://github.com/online-go/online-go.com/issues/123
