### ISSUE TITLE
OGS needs some kind of anti game abandonment system

### ISSUE THREAD

**Issue by pondturtle** [online-go/online-go.com#427]
### Summary

Lately, at least in my own games, game abandonment and havign to wait for timeout has become a real and frequent issue. Waiting 40 minutes for game to end or take rank hit is just not fun and it spoils experience A LOT.  

I don't have exact idea on how this could work. But I believe there should be some system in place to allow to end these games (by annulment at very least) and penalise those, who abandon games repeatedly.

**Comment by BHydden** [comment]
We already monitor whether a player is in the game or not. I like tygem's system of starting a 5m resignation timer on disconnection. This way If it's just a drop out they have a chance to return but players of longer live games don't have to wait out the full clock.

**Comment by pondturtle** [comment]
I know you will lose game if you go out of it, but are still online. But if you go offline I noticed no system in place.

As for calling mods I was told by one in chat "Don't report if your opponent abandoned game, I don't care" (might not be exact quote word, for word - it is some time, but more or less accurate)

That is why I am raising the issue,

**Comment by anoek** [comment]
This is actually a dup of https://github.com/online-go/online-go.com/issues/352 .. we used to have it, I broke it in v5, and I'm working on a better way of addressing it as we speak :)
