### ISSUE TITLE
A bunch of source maps give a 404.

### ISSUE THREAD

**Issue by BarneyStratford** [online-go/online-go.com#433]
The following files don't exist on the server:
https://cdn.online-go.com/lib/react-datetime/2.8.10/react-datetime.min.js.map
https://cdn.online-go.com/lib/es6-shim/0.35.3/es6-shim.map
https://cdn.online-go.com/lib/eventemitter3/2.0.2/index.min.js.map
https://cdn.online-go.com/lib/blueimp-md5/2.5.0/js/md5.min.js.map
https://cdn.online-go.com/lib/es6-promise/4.0.5/es6-promise.auto.map

It would be good to either put the files up or have the minified JS not say that a source map is available, as this causes spurious errors to be logged in the console. I'd like to get to a state where errors are logged only if an actual error occurs.

**Comment by anoek** [comment]
I see that those are missing and so I'm sure I *should* be seeing errors, yet I am not. Where are you looking that you see the error messages?

**Comment by anoek** [comment]
The files you listed should be up now

**Comment by BarneyStratford** [comment]
> I see that those are missing and so I'm sure I should be seeing errors, yet I am not. Where are you looking that you see the error messages?
The errors show up in the console, not in the UI. I’m using Safari 10 under Mac OS 10.11. Most of the errors have now gone, but I’m still seeing a 404 for https://cdn.online-go.com/lib/es6-promise/4.0.5/es6-promise.auto.map on the dev server.
