### ISSUE TITLE
Increase the height of the navbar on online-go to match the forum

### ISSUE THREAD

**Issue by alex-mac** [online-go/online-go.com#435]
### Summary

Right now, the height of the `header.dheader` on the forum is 60px. On the online-go.com, `#NavBar` has a height of 32px. Increasing the padding of `#NavBar` by 14px on all sides would make the navbar less cramped and increase the height to 60px.

### Environment

 * Operating system: MacOS
 * Browser: Chrome
 * Browser Version: 60.0.3112.113

### Steps To Reproduce:

1. Go to https://online-go.com/ and inspect the navbar at the top
2.Go to https://forums.online-go.com/ and inspect the header element

**Comment by anoek** [comment]
I'd welcome some improvement in this area however if an increase is made it probably wont work generically, it'll probably need to be dynamic so we don't waste too much realestate on smaller screens (which is a large percentage of our user base)

For reference and testing here are the most common screen resolutions that our players use:

```
17.55% - 1920x1080
14.30% - 1366x768
12.83% - 360x640 (mobile)
 6.49% - 1440x900
 4.96% - 1280x800
 4.68% - 375x667 (mobile)
```

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
