### ISSUE TITLE
Bots - no stone removal phase

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#443]
### Summary

I understand and support bot games not having a stone removal phase. As discussed in https://forums.online-go.com/t/no-stone-removal-phase/13635 I believe there should be some method that a game can be continued after the bot has auto-scored if the human wishes to correct a scoring error.

### Environment

Bot games on OGS.

### Steps To Reproduce:

1. Play a bot game and complete to scoring phase.
2. Notice that a group has incorrectly been marked alive/dead.
3. Have some way of continuing play to clarify the position.

**Comment by anoek** [comment]
This used to be the case but led to a lot of cheating
