### ISSUE TITLE
Weekend pause doesn't apply to Simple time settings

### ISSUE THREAD

**Issue by icy31k** [online-go/online-go.com#449]
### Summary

Games with Simple time settings do not pause during the weekend.

### Environment

 * Operating system: any
 * Browser: any
 * Browser Version: any

### Steps To Reproduce:

1. Go to https://online-go.com/tournament/29438
2. Click any game
3. During the weekend, timer shows both pause, and unfrozen countdown

### Additional information ###

![](https://ogs-forums.s3.amazonaws.com/optimized/2X/a/afe38b2a75ab2e557cfd00236a05d1f5119f20a3_1_690x417.jpeg)

The case with vacation pause: eventually counted down to zero (no timeout has occured)
![3813e5a8-6bb1-4c6d-a5ba-b705e815f051](https://user-images.githubusercontent.com/2444687/30856443-0df6050e-a2c1-11e7-8f74-7f0d0d5404e4.jpeg)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
