### ISSUE TITLE
clickable 'games with your move pending' notification orb count wrong after game ends

### ISSUE THREAD

**Issue by zake8** [online-go/online-go.com#45]
Example:
1. Black circle in upper right shows 8 games waiting on you to move
2. Click it and you go to the game with the least time remaining for you to move
3. Make/submit your move - count goes down to 7
4. Click it again to go to the next game
**5. Game is in scoring phase, you select territory, submit, your opponent already did this, you match selections, and the game ends with you winning
6. The count still shows 7...**
7. Click it and you go to the game with the least time remaining for you to move
8. Make/submit your move - count goes down to 6

**Comment by anoek** [comment]
This has been fixed on the backend and will be deployed soon
