### ISSUE TITLE
Board not maximally sized on mobile devices

### ISSUE THREAD

**Issue by mark5000** [online-go/online-go.com#451]
### Summary

Ads on the game page unreasonably shrink the game board on mobile devices. Formerly, the game board occupied the full width of the screen on my mobile device. Since the addition of game page ads, the board now occupies just 60% of the width of the screen when game page ads enabled, and 70% of the space even when they are not.

Separately, I do not see any game page ads under either setting.

### Environment

 * Operating system: iPhone 5s
 * Browser: Safari
 * Browser Version: iOS 10.3.3

### Steps To Reproduce:

1. Go to any game using a mobile device.
2. See that the game board is unreasonably small, regardless of user settings. 

### Additional Information:

Ads enabled:
![mobile game ad](https://user-images.githubusercontent.com/13010650/30888701-d7dbac74-a2d6-11e7-80e0-71bcc0cdb194.jpg)
Ads disabled:
![mobile game no ad](https://user-images.githubusercontent.com/13010650/30888710-de15617a-a2d6-11e7-9c42-8b228ee73bda.jpg)

**Comment by slideclimb** [comment]
I was just about to open an issue stating the same problem. It also occurs on Android 5.0.1 using Chrome v56.0.2924.87.
![image](https://user-images.githubusercontent.com/15685876/30884394-cca86cb4-a30f-11e7-8022-7abec872978d.png)

**Comment by mark5000** [comment]
Commenting that the issue still exists since game page ads were removed. The board still shrinks to about 70% its former size upon entering a game.

**Comment by anoek** [comment]
Would it be possible to get a screenshot from the current behavior @mark5000 ? This issue, while introduced at the same time as the brief existence of the ads, was actually unrelated. I *thought* I fixed it this morning, but your comment was made well after the fix was put in place, so it could be there's some lingering issue(s).

**Comment by mark5000** [comment]
It did fix it to some extent. Now the board is about 80% the width of my screen.

![img_2914](https://user-images.githubusercontent.com/13010650/30979818-b9f2e7d2-a433-11e7-8904-dc5334602adf.PNG)
