### ISSUE TITLE
Time Control options don't reappear when selecting another game speed mode

### ISSUE THREAD

**Issue by Fumon** [online-go/online-go.com#452]
### Summary

In the Send Challenge dialog, selecting "none" for time control makes the options of time control blank when switching back to a game speed mode which does not have "none" as an option.

Switching off of the default time control then makes the options reappear.

### Environment

 * Operating system: Windows
 * Browser: Firefox
 * Browser Version: 55.0.3

### Steps To Reproduce:

1. Select correspondence game speed.
2. Select None for time control.
![image](https://user-images.githubusercontent.com/425547/30992762-7a596290-a479-11e7-8d05-da6d3d995fd8.png)
3. Select Live or Blitz in game speed.
![image](https://user-images.githubusercontent.com/425547/30992772-83bc3f24-a479-11e7-89d1-fc7b93e74ac6.png)
4. Note the lack of control over the default time control.
![image](https://user-images.githubusercontent.com/425547/30992869-ea59b57c-a479-11e7-9ea6-ec52102545c0.png)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
