### ISSUE TITLE
Display "Total games played" somewhere 

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#453]
### Summary

When we removed the old Elo ratings graph from the profile page we also lost an easy "Total games played" count. We should add that information back in somewhere nicely.

### Additional Information:

https://forums.online-go.com/t/counting-n-of-games-played/14130/4

**Comment by GreenAsJade** [comment]
I put an implementation of this onto the win-loss-pie branch.

**Comment by mlopezviedma** [comment]
This one can be closed now due to #467
