### ISSUE TITLE
Disconnection timer stays visible even after win by timeout

### ISSUE THREAD

**Issue by Walther** [online-go/online-go.com#457]
### Summary

Disconnection timer stays visible even after win by timeout

### Environment

 * Operating system: MacOS
 * Browser: Chrome
 * Browser Version: Version 60.0.3112.113 (Official Build) (64-bit)

### Steps To Reproduce:

1. Play a game with short time controls
2. See that the opponent disconnects
3. Win by timeout, but the disconnect timer for the opponent is still visible and counting down

### Additional Information:

<img width="385" alt="screen shot 2017-10-02 at 14 13 26" src="https://user-images.githubusercontent.com/2943750/31075052-45984f48-a77c-11e7-9155-85d0da4f952d.png">

**Comment by anoek** [comment]
This has been fixed on the backend finally, the changes will be live in a day or two.
