### ISSUE TITLE
Some of the links on the site are not links

### ISSUE THREAD

**Issue by Walther** [online-go/online-go.com#458]
### Summary

Some of the links on the website are not links. E.g. on the Games page, you can't right click on the boards and copy the link or open to new tab via context menu - right clicking takes you immediately to the game. Same happens on your own page with the games. Additionally, in the table view (when you have lots of games) on your page, hovering the game names doesn't result in a pointing pointer, again, because they're not links.

I'm aware that in many places around the site the link features have been implemented via JavaScript. It might be a good idea to wrap things into `<a>` tags where possible though, as this limits the amount of special behaviours to implement in JS side of things - no need to specially catch stuff like ctrl-click / cmd-click and mouse middleclick for opening in new tab, etc.

### Environment

 * Operating system: Windows 10
 * Browser: Chrome
 * Browser Version: Version 61.0.3163.100 (Official Build) (64-bit)

### Steps To Reproduce:

1. Go to Games page
2. Right click a board
3. See that the page immediately goes to the game, instead of giving you a context menu with e.g. link information

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
I know I did this for a reason once upon a time, but I don't recall why. It seems perfectly reasonable to me for everything to be a link as you say.
