### ISSUE TITLE
Letter "I" is missing on Goban coordinates

### ISSUE THREAD

**Issue by cryptotsune** [online-go/online-go.com#459]
### Summary

*Briefly describe the issue you are reporting*

### Environment

 * Operating system: Safari or Brave on IOS, Chrome on Windows 10
 * Browser:
 * Browser Version: Latest as of October 2017

### Steps To Reproduce:

1. Go to any correspondance game under your profile
2. Goban coordinates goes directly from H to J without displaying an "I"
![missing i](https://user-images.githubusercontent.com/32480572/31118101-d08fcc4c-a85e-11e7-8740-a67fe3d8fe6a.JPG)

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by BHydden** [comment]
This is intentional because capital I looks like lowercase l

**Comment by cryptotsune** [comment]
oh ok, sorry about this then
