### ISSUE TITLE
Cancel button confirms conditional moves

### ISSUE THREAD

**Issue by kabootle** [online-go/online-go.com#46]
### Summary

When you start planning conditional moves but then decide not to confirm them, you could always click cancel and the conditional moves that were not saved yet were deleted again. 
Lately, cancel does seem to safe conditional moves as well though. The only way to get rid of played moves in conditional move planner is to manually delete every move and then hit confirm

### Environment

 * Operating system: tested on Android, but forum post suggests, it applies to the desktop version as well
 * Browser: chrome
 * Browser Version: newest

### Steps To Reproduce:

1. Go to ... A game
2. Click ... Plan Conditional moves
3. Play a few moves in Conditional move planner
4. Click cancel
5. Open Conditional move planner again
6. The cancelled moves were saved and are still there

### Additional Information:

Link to forum post: 
https://forums.online-go.com/t/i-just-noticed-in-the-conditional-move-planner-that-cancel-is-the-same-as-accept-conditional-moves/10459?u=kabootle

**Comment by anoek** [comment]
The moves aren't confirmed (ie stored to the server), but the tree is not reset to the original state on the user interface. (Refreshing or navigating away/back shows us that the moves revert to the last confirmed state).

**Comment by kabootle** [comment]
Ah, I see. I guess resetting the tree to the last saved state would be less confusing. Not a high priority though if the conditional moves are not actually active.

**Comment by anoek** [comment]
Yep still should be fixed, just clarifying in case someone wants to take a crack at fixing it before I get to it :)
