### ISSUE TITLE
automatch blitz has 5 minute maintime

### ISSUE THREAD

**Issue by typohh** [online-go/online-go.com#460]
5 minute main time is detrimental when attracting dan level players. Yet blitz is almost exclusively for dan players since very few kyu players will feel comfortable playing it. Instead of using the poll as basis for deciding time settings (as was apparently done). A poll where pretty much everyone wrote their opinion on blitz, most of whom don't even play it blitz. Why not just look up what kind of games are requested most with a given byomi. I suspect it will show that very few dan players ever ask for main time when creating a custom game (they might occasionally accept 5 minute main time if nothing else is available). Yet its almost exclusively dan players who play blitz, at least going by other servers statistics. Hence it seems rather wasted that automatch has 5 minute main time, which probably deters many dan players from using it in the first place and might well end up keeping them away from the server too since finding games becomes that much more difficult.

**Comment by GreenAsJade** [comment]
I don't think there's any evidence that blitz is exclusively for dans.

I just took a "random" sample of the top 5 people in my friends list, and every one of them has blitz games.

They are all DDKs.

**Comment by typohh** [comment]
GreenAsJade So in other words, you looked at 5 ddk and one of them plays blitz. Curious, what time settings did he use?

**Comment by anoek** [comment]
Can you point me at the other server statistics you are looking at?

**Comment by GreenAsJade** [comment]
@typohh No, I looked at 5 DDKs, and 4 of them play blitz.

It's unfortunately not that easy to pluck out games of a particular speed from a person's game history, so I'm not sure what settings were being used.
