### ISSUE TITLE
Win-loss bar graph not reliable.

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#466]
### Summary

My test user's graph looks strange.   It doesn't have many results.

### Environment

dev server, head of devel client branch

### Steps To Reproduce:

0. Run the devel client from the head of the branch
1. Go to http://dev.beta.online-go.com:8080/user/view/645
2. See that there is no dark purple in the bar graph, but DevGaJ has one "loss vs weaker"

### Additional Information:

<img width="1440" alt="screenshot 2017-10-05 23 15 37" src="https://user-images.githubusercontent.com/61894/31226869-8c4b3762-aa23-11e7-86fe-b368873a2729.png">

**Comment by GreenAsJade** [comment]
This has been confirmed on the main server, by this report in the forum:

https://forums.online-go.com/t/wins-losses-chart/15419

**Comment by tcarette** [comment]
I'm hitting this bug in dev too while working on the bar chart.
Anybody has any hint as to why it is buggy?

**Comment by GreenAsJade** [comment]
Yeah, I think there's something not right at the moment.

Right now DevGaj has a bunch of ranked games, but the Profile is claiming only 12 ranked games.

I pinged anoek on OGS as well about this.

**Comment by tcarette** [comment]
I think I've found a problem in the first X coordinate of the bar chart - I just have to locate the problematic function.

![image](https://user-images.githubusercontent.com/2481066/59148386-b86c7d80-8a08-11e9-8006-f31020233a2e.png)

**Comment by tcarette** [comment]
I am wondering if the scale `this.ratings_x: d3.scaleTime()` is not set to be daily and used as monthly in the bar chart, causing troubles.

I'm a noob in javascript though so idk.

**Comment by tcarette** [comment]
A naive change of the date_range seems to create very weird behaviour. I guess there is a problem with the range selection: it interferes with the bar chart. I think I will be able to deal with that.
However I'm not sure about the impact of the rounding of the date_range on the line chart. Opinion?

`       
        let date_range:any = d3.extent(this.game_entries.map((d:RatingEntry) => { return d.ended; }));
        date_range[0] = new Date(date_range[0].getUTCFullYear(), date_range[0].getUTCMonth());                                      
        date_range[1] = new Date(date_range[1].getUTCFullYear(), date_range[1].getUTCMonth());                                      
        date_range[1].setMonth(date_range[1].getMonth() + 1);

`

![Screen Recording 2019-06-08 at 17 38 16](https://user-images.githubusercontent.com/2481066/59149354-a98bc800-8a14-11e9-9af4-55893427c318.gif)

**Comment by tcarette** [comment]
the bug cannot be reproduced for a user with games spanning multiple months though so not sure I understand.

**Comment by tcarette** [comment]
Ok, I have a version which is not totally glitchy, but is maybe less ambitious.

I get rid of particular logic for when the selection is the same month as today. Also, as explained above, I define the date range as monthly, i.e. first of the first game month, and first day of the month following the last game. So the line plot is incomplete, but the bar chart has a fixed range spanning the full month that it reports on.
![image](https://user-images.githubusercontent.com/2481066/59158513-72bcbd00-8abb-11e9-8af0-c5db12ee9b4f.png)

In particular, it means that selecting a fraction of a month displays a bar char that doesn't really makes sense. Note that this is the same behaviour as the chart for selection of past months.
![image](https://user-images.githubusercontent.com/2481066/59158518-76e8da80-8abb-11e9-9e31-9592da194084.png)

Here is the branch if you want to check it out. I'm waiting for feedback before making a pull request.
https://github.com/tcarette/online-go.com/tree/issue_466

**Comment by anoek** [comment]
Thanks for your work on this!

I'm happy with this solution, it's certainly better than what we currently have.
