### ISSUE TITLE
Feature request: hint for the date in the chat backlog

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#468]
### Summary

Hello, in chatrooms, we have time hh:mm for every entry of the backlog but there's no hint for the day.
It would be nice to have that.

### Environment

 * Operating system: any
 * Browser:any
 * Browser Version: any

### Steps To Reproduce:

Ask if needed

### Additional Information:

Ask if needed

**Comment by arnaudgo** [comment]
Hello @anoek and @MartijnTheunissen !

Does it also work for private chatlogs ?

If not, it would be nice to have it working for both.

If it is already working for both private and public chat logs, or for any other reason, this issue can be closed.

Arnaud

**Comment by BHydden** [comment]
bump @anoek this can be closed

**Comment by anoek** [comment]
Thanks :)
