### ISSUE TITLE
PR listed as integrated but I'm still not seeing the icon

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#478]
### Summary

PR listed as integrated but I'm still not seeing the icon
https://github.com/online-go/online-go.com/pull/476

### Environment

 * Operating system: Windows 10
 * Browser: Google Chrome
 * Browser Version: 61.0.3163.100 (Official Build) (64-bit)

### Steps To Reproduce:

1. Go to Profile Page
2. Scroll down to user history
3. See that there is still no icon under Game History
4. F5 and shift+F5 multiple times, no change.

### Additional Information:

![image](https://user-images.githubusercontent.com/28991649/31422458-758d4342-ae99-11e7-99fe-aae0b6135d5c.png)

**Comment by GreenAsJade** [comment]
I reckon that's because there's still the final step of "released" after "integrated".

I too am curious about what the release cycle is :)

**Comment by anoek** [comment]
It's usually fairly quick but I merged this right before driving across country, so chose not to push up any changes right before I went offline for multiple days :) I'll get it pushed up soon

**Comment by GreenAsJade** [comment]
I think this can be closed now :D ;)

**Comment by BHydden** [comment]
Quite :-)
