### ISSUE TITLE
Zen mode should display clocks, undo, pass & resign buttons

### ISSUE THREAD

**Issue by farraway** [online-go/online-go.com#484]
### Summary

To effectively play live & blitz games players need to see the clocks. They may also need to access `pass` and `resign` buttons. Further, an `undo` button should be visible so that players can request an undo or see that their opponent has requested one.

Without this information, especially the clocks, Zen mode is unusable for live & blitz games.

### Environment

 * N/A

### Steps To Reproduce:

1. Start a live or blitz game.
2. Enable Zen mode

### Additional Information:

* This has been discussed (briefly) in [this forum post & poll](https://forums.online-go.com/t/poll-clocks-prisoners-in-zen-mode/14257).

**Comment by Adam314159** [comment]
Another user suggestion is to move all control panels to the side so the goban can scale to the maximum size.

https://forums.online-go.com/t/change-the-zen-mode/17019/5

**Comment by sousys** [comment]
This seems like an important issue. I think this should be bumped up
