### ISSUE TITLE
Scrolling through group posts glitches

### ISSUE THREAD

**Issue by Adam314159** [online-go/online-go.com#485]
### Summary

When trying to scroll quickly through multiple posts in groups it results into wrong post being displayed

### Environment

 * Operating system: Win 8.1
 * Browser: Moz Firefox
 * Browser Version: Moz Firefox 56.0.1

### Steps To Reproduce:

1. Go to any group with multiple posts
2. Quickly click the navigational arrow in posts several times
3. The post now displayed does not match the actuall number of the post next to the arrows

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
