### ISSUE TITLE
index by stone suggestion

### ISSUE THREAD

**Issue by brw31415** [online-go/online-go.com#488]
### Summary

clicking on a stone to show board position when the stone was placed there

*Briefly describe the issue you are reporting*

### Environment

 * Operating system: 
 * Browser:
 * Browser Version:

### Steps To Reproduce:

1. Go to ...
2. Click ...
3. See that X wrong 

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
When in analysis mode, hold down 'shift' and click a stone to do this :)
