### ISSUE TITLE
Game not registered in my OGS profile Line graph

### ISSUE THREAD

**Issue by Mogadeet2** [online-go/online-go.com#490]
The game I played October 15 did not register on the bar graph on my profile page. The games on the 14th and 16th register, but not the one on the 15th. 

The game is: 2017-10-15 19x19 cmairena vs. Mogadeet cmairena Mogadeet W+Resignation, ranked

The missing game is listed in my game history (which is why I knew it was missing).

When moving the mouse over the line graph (where it highlights the game day with a red dot and notes the date in a pop-up balloon), it registers October 14 and October 16, but no October 15.

Please note that I am in the U.S. and the dates are listed as they would be here.

Mogadeet

Screen Captures. It registers the 14th and 16th, but not 15th:
![new picture](https://user-images.githubusercontent.com/32945536/31800832-a75b7f00-b511-11e7-8ba8-54600e48ac85.png)

![new picture 1](https://user-images.githubusercontent.com/32945536/31800840-ba700be2-b511-11e7-9632-b7d4b85037ec.png)

Here’s the games in my game history, including the October 15th game that is not showing up.
![new picture 2](https://user-images.githubusercontent.com/32945536/31800846-ca44e0e2-b511-11e7-83e0-e76382c12133.png)

Here is a link to the forum discussion site.
https://forums.online-go.com/t/game-not-registered-on-my-profile/14320

I am using Windows 7, and Firefox 56.0 browser.

The people in the Support Forum believe it is a bug and suggested I post the issue here.

Mogadeet

**Comment by anoek** [comment]
Well, it is a bug, but it looks like it's only a display bug. Here's the raw data for that graph:

https://online-go.com/termination-api/player/464253/rating-history?speed=overall&size=0

You can see the game (10295952) was recorded in there just fine, so your rating is intact at least. However, it should certainly show up in that graph as well, and why that's not happening as expected, I'm not sure yet.

**Comment by Mogadeet2** [comment]
Thank You!

Mogadeet
