### ISSUE TITLE
Zen mode: allow to switch games by swiping left or right

### ISSUE THREAD

**Issue by d180cf** [online-go/online-go.com#491]
Plus an indication that there are other games that need attention (maybe the Zen icon could change color in such cases).

**Comment by GreenAsJade** [comment]
"Swipe" is a very phone-centric concept.   But I can envisage left and right arrows appearing when you move your mouse next to the side of the screen, to click to the next active game, and yes the Zen icon changing color.

However, I feel like this isn't in the spirit of Zen mode.  Surely in Zen mode you are supposed to be totally focussed on the game at hand?  

So the counter argument is "If you want to 'come out of that focus', then click the Zen icon then click the outstanding games counter to go to the next".

**Comment by anoek** [comment]
We can differentiate between a touch event and a mouse event, so this feature can be added such that it's only applicable to devices with touch input. 

I've actually thought about and wanted this myself as well, though I think it should work in zen and non zen modes as well.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
