### ISSUE TITLE
Feature request: Detailed tournament list

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#497]
Copied from https://forums.online-go.com/t/tournament-list-on-home-page/14343

Hi,

Currently, there is a list of tournaments on the user’s home and profile pages.
It lists the tournaments open for registration, and the tournaments the user is participating in.

It would be nice to have some visual clue to see if it is open for registration or already started (apart from having to read all the dates and times and do timezone conversion)

Also, I would love to see the round each tournament is currently in, and the number of ongoing games and total games in that round in the list, something like:
Monthly Simultaneous McMahon 2017-09-16 17:00 (20 ongoing/100 total games in R1)

This would make it easier to see if the tournament is close to going to the next round. And thus make it easier to decide between enlisting for a new tournament and waiting for an older one to advance to the next round.

Kind regards, Mirjam

**Comment by BHydden** [comment]
andysif: I think they should be 2 separate lists: the tournaments that you are “in” and that are “available”.

sppedchase: chronological order, not alphabetical order

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
