### ISSUE TITLE
On mobile, chat switches out of Malkovich mode, but variation input is still green

### ISSUE THREAD

**Issue by airjp73** [online-go/online-go.com#498]
### Summary

On mobile, switching between landscape and portrait mode causes chat to switch from Malkovich back to chat. But the variation box remains green as though it's in Malkovich mode.

### Environment

Brand new Galaxy Tab A 10.1

 * Operating system: Android 7.0
 * Browser: Chrome
 * Browser Version: 61.0.3163.98

### Steps To Reproduce:

Starting with device in portrait mode.
1. Open up a game.
2. Go into analysis mode
3. Switch to Malkovich mode.

Both the chat input and the variation input are now green (Malkovich mode)

4. Rotate device to switch to landscape mode.

Chat input has switched back to chat mode, but the variation input is still green. Clicking record puts the variation into normal chat.

**Comment by GreenAsJade** [comment]
There's another ticket along these lines, suggesting (rightly, I think, because I raised it :) ) that the Malkovitch status of game chat should be preserved between sessions.  I presume that would solve this.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
