### ISSUE TITLE
Byo-yomi extra periods presentation is confusing

### ISSUE THREAD

**Issue by lemurek** [online-go/online-go.com#5]
### Summary

*Byo-yomi presentation is confusing*

Consider a game with time settings of 2 mins base time and 1 extra byo yomi period of 30s, how much time left in game does this player have?
0:05+1x30s

It can mean that either:

1. There are 5 more seconds of base time and extra byo-yomi period
2. Player has entered overtime and his last byo yomi ends in 5 seconds

Even both situations are presented in the same way, breaching that 5 seconds limit in the second option means losing a game on time. 

### Environment

 * Operating system: any
 * Browser: any
 * Browser Version: any

### Steps To Reproduce:

1. Start a game with time settings 2 mins base time + 1 x 30s byo-yomi
2. Observe time presentation in base-time and in over-time

### Additional Information:

![screen shot 2017-02-25 at 12 17 40](https://cloud.githubusercontent.com/assets/12175058/23330980/79e9ad16-fb54-11e6-96bd-750e01bb8689.png)

**Comment by anoek** [comment]
Changes to the clock display are a bit of a sensitive topic amongst players, I'd like some additional weigh in from folks about this proposed change before merging any code.

**Comment by matburt** [comment]
I'm pretty sure, for better or worse, this is how the code has worked since the Nova days. We've had lots of folks comment on it over the years... I'm not sure we can change it without major backlash at this point.

**Comment by mark5000** [comment]
I do think OGS has a troublesome clock. In the current implementation, using the above image as an example, it's impossible to know if the user is on their first overtime period or on the last seconds of main time. There's absolutely no difference. Let's consider other servers:

![tygem timing](https://cloud.githubusercontent.com/assets/13010650/23332660/38fe2bbe-fb32-11e6-9206-29c96f2a1690.png)

On tygem, the main time converts into a visual countdown. There is also a voice cue for "overtime countdown has begun" and "the last overtime" period. It is fundamentally clear what the situation is at all times.

![foxgo timing](https://cloud.githubusercontent.com/assets/13010650/23332887/2f80509a-fb36-11e6-9f4c-d6b9069c68af.png)

On Fox Go, the main time is displayed in minute:second format while overtime is displayed as seconds only (and in bigger numbers). There is also a voice cue for "byo yomi now starts" and "last byo yomi."

![kgs timing](https://cloud.githubusercontent.com/assets/13010650/23332668/56b6226a-fb32-11e6-88e7-d0ef90da7e0d.png)

On KGS, overtime periods aren't displayed at all until the player enters overtime, then the remaining overtime periods are displayed in parentheses next to the timer. This has the disadvantage of hiding information during the game, but the advantage of making clear when the player enters overtime.

![wbaduk timing](https://cloud.githubusercontent.com/assets/13010650/23332662/42dd8a44-fb32-11e6-83ea-a2c2a2e44947.png)

World Baduk has a similar implementation to OGS. There is nothing visual to notify the player they have entered overtime. However, there is a voice cue for entering overtime and for the last overtime period.

![igs timing](https://cloud.githubusercontent.com/assets/13010650/23332672/6790f8b2-fb32-11e6-811d-2cc1ce1e86cd.png)

On IGS/PandaNet, the words "Main time" are written beneath the timer. This switches to overtime periods when the player enters overtime.

![netmarble timing](https://cloud.githubusercontent.com/assets/13010650/23332664/49c364fa-fb32-11e6-9a8d-3ec2f8eb2368.png)

Netmarble is identical to OGS implementation. When the main time expires, overtime starts without fanfare, although like OGS there is a countdown for last seconds, but only on the overtime periods and not for main time.

![cyberoro timing](https://cloud.githubusercontent.com/assets/13010650/23332666/4e11a03a-fb32-11e6-82b2-79bb205470c1.png)

Cyberoro is also OGS implementation. Main time switches to overtime periods without notice and nothing changes on the screen.

My takeaway from this exercise is there's nothing inconsistent about OGS's implementation compared to other servers, especially Netmarble and Cyberoro. However, I feel some notice (whether auditory or visual) that the player has entered overtime would be an improvement on the current implementation.

**Comment by bluepie88** [comment]
> I'd like some additional weigh in from folks about this proposed change before merging any code.

I have a very strong preference for the clock display to observe the conventions of mathematics! In my mind, "0:05+1x30s" unambiguously evaluates to a total of 35 seconds. So I expect to be able to wait up to 35 seconds before making my move before losing due to timeout.

**Comment by anoek** [comment]
I put this question into a poll here: https://docs.google.com/forms/d/1PIrbxvs5e8-S7ui6tEnyOkT67XOpji0Sipkz2Hvf2Qc/edit#responses

**Comment by BHydden** [comment]
resolved with new sudden death feature, 
this issue can be closed

**Comment by BHydden** [comment]
bump @anoek close me

**Comment by anoek** [comment]
Thanks @BHydden :)
