### ISSUE TITLE
Loading games with missing or corrupted data should display a useful error message

### ISSUE THREAD

**Issue by juanchodepisa** [online-go/online-go.com#50]
### Summary

[This (old) game](https://online-go.com/game/437044), appears to be eternally loading

### Environment

 * Operating system: Ubuntu 16.04.1
 * Browser: Chrome
 * Browser Version: Version 54.0.2840.100 (64-bit)

### Steps To Reproduce:

1. Go to game linked above
2. Do nothing
3. The board appears superimposed with the message "Loading..."

### Additional Information:

The game chat doesn't work either, Zen mode is buggy and so are most of the right panel options.

**Comment by juanchodepisa** [comment]
Forgot to mention, I took that game from RaikB's profile

**Comment by anoek** [comment]
Unfortunately that's a casualty of a very old bug :( nothing to be done about it at this point.

**Comment by roy7** [comment]
If the old game is corrupted is it possible to fail gracefully instead of the hung/endless loading?

**Comment by anoek** [comment]
fair enough

**Comment by juanchodepisa** [comment]
I might add that this game continues to appear as 'ongoing' on RaikB's profile. If there are other instances of corrupted game data, they probably appear as ongoing to the users involved.

If I was any of them, I'd find that annoying. Is there a way to  prevent this? (maybe put the game as no-result due to an error, and take them away from active games for good)

**Comment by benjaminpjones** [comment]
## Good First Issue

### Code points:

- [Game.initialize()](https://github.com/online-go/online-go.com/blob/2728256945409f5856cef80d77ced58c61cbec27/src/views/Game/Game.tsx#L802): Here, the `games/` API is hit, but there is no handler in case there is an issue fetching data.  In case of error, we want to detect a server error in the `catch` clause, and display a message to the user accordingly.

### Prerequisites:

- Some familiarity with [asynchronous JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous), specifically using `.catch` clauses.

### Additional info:

There are multiple ways one can display a message to the user.  In this case, [`this.goban.message`](https://github.com/online-go/goban/blob/840a03f7385497270179f3544ec8b23fd227e31b/src/GobanCanvas.ts#L2284) can be used to override the erroneous "Loading..." message.

If you would like to tackle this issue and have questions, feel free to leave a comment here!

**Comment by GreenAsJade** [comment]
Games.tsx has been refactored since @benjaminpjones 's comments.

The relevant line is now https://github.com/online-go/online-go.com/blob/09ab0e4ef5095ab59440f01769745ec10170aa1c/src/views/Game/Game.tsx#L1202

**Comment by PabloLION** [comment]
Can I take this issue and just replace the
> erroneous "Loading..." message 
to something like
> Error: corrupted game file
?

If so, please assign me 😃

**Comment by BHydden** [comment]
No assignment needed. Just submit a PR :)

**Comment by PabloLION** [comment]
I think I need some help...

How can I reuse this modal?

![image](https://user-images.githubusercontent.com/36828324/200111956-1f715520-562c-4a25-a66d-2b5c2433ae0b.png)

## background
I've set up the server and uncommented the [BACKEND = 'PRODUCTION';](https://github.com/online-go/online-go.com/blob/d4ea23c1548ef1519728c8e8ae1b564d7aa3f09b/Gulpfile.js#L5) to use the production server data.
I see all the errors are ignored. The errors are: when game not exist API returns code 404; and when for the corrupted game it was 500. 
Yet on 404 (when I visit a not existed game like http://dev.beta.online-go.com:8080/game/4370448924576), this modal was shown (pic below). I see the was from "https://sweetalert2.github.io/" but I cannot find it's implementation in this repo.
So I tried searching "internal error: unable to load game data, please try again later" by part in this repo and in [goban](https://github.com/online-go/goban) but got nothing. And the Chrome React Developer Tools cannot find this modal either.

**Comment by GreenAsJade** [comment]
So - we are using the sweetalert2 library for doing those popups.

We have them set up the way we like them to be using our module `swal_config`

If you want to make a popup like that you do:

`import { alert } from "swal_config";`

and this sort of stuff:

```
        void alert.fire({
            text: pgettext(
                "Appears in a dialog while the server is responding",
                "Accepting game...",
            ),
            icon: "info",
            showCancelButton: false,
            showConfirmButton: false,
            allowEscapeKey: false,
        });
```

**Comment by GreenAsJade** [comment]
I've realised your real question may be different: you're hunting for where is that modal alert actually fired?

The trick is that the text in it is coming from the server.    This makes it a bit hard to search for in the client codebase!

The _type of_ code you are looking for is something like this:

```            put("challenges/%%/join", challenge.challenge_id, {})
                .then(() => {
                    alert.close();
                    if (challenge.invite_only) {
                        navigate("/", { replace: true });
                    } else {
                        navigate(`/play#rengo:${challenge.challenge_id}`, {
                            replace: true,
                        });
                    }
                })
                .catch((err: any) => {
                    alert.close();
                    errorAlerter(err);
                });
```

See how it does `errorAlerter(err)`  ... the `err` is the message from the server that will be displayed./

So you need to find the particular call to the server that failed and caused this error.

The way to do that is to look in the network tab of the debugger tools and find red entries - failed network calls.

That will tell you what the kind of call is (for example, `put` above) and the route.  With those you can search for the call that is causing it.

Good luck 🤪

**Comment by benjaminpjones** [comment]
>That will tell you what the kind of call is (for example, put above) and the route. With those you can search for the call that is causing it.

Leaving a hint since I think websocket calls are a little harder to track down:

<img width="1675" alt="Screen Shot 2022-11-05 at 5 00 19 AM" src="https://user-images.githubusercontent.com/25233703/200118964-2c879e16-5f77-4649-9512-d8256ad82954.png">

And the code that listens to/alerts on that message:

https://github.com/online-go/online-go.com/blob/89b6c6687a27161ea24b66232b7708c25a5332dd/src/main.tsx#L282

But yeah, if OP is just looking to copy the style of the alert, `errorAlerter()` is the right function to do so!

**Comment by GreenAsJade** [comment]
Pff there's another wrinkle: the server can send an error message that's a hard kind of ailer.

I was able to deduce that the message you captured is in fact one of those.

It's coming from here:

https://github.com/online-go/online-go.com/blob/a0cb2908be96f79d1f0b30f8934cb7623f3c90e2/src/main.tsx#L281-L282

What this means is that it's a result of the server really failing hard.  The server sends a message saying "ERROR", "internal error: unable to load game data, please try again later", and the client catches it in `main` there and displays it.

**Comment by GreenAsJade** [comment]
Hah snap!

**Comment by PabloLION** [comment]
@GreenAsJade @benjaminpjones Huge thanks! I think it costs even more replying me than finish this function 😂😂 I fell so welcomed! Thanks again.

So if the 404 can be fired by alert (I of course saw the `swal_config`) Should I add a handler for 500 status? Or just an 
```ts
alert.fire({
            title: "game data deprecated",
            icon: "error",
        });
```

I didn't send the error message because it's `undefined`. maybe showing an `"internal error: unknown"` is better?

**Comment by benjaminpjones** [comment]
Happy to help!  Even if it "costs" something, having another contributor on board is probably even more valuable :)

> So if the 404 can be fired by alert (I of course saw the swal_config) Should I add a handler for 500 status?

I actually didn't understand what was being asked until I read the PR, but it looks like you're handling the errors in a good way.
