### ISSUE TITLE
Sorting games by time should put "on hold" games last.

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#500]
### Summary

Right now, games that are under vacation, and possibly pause, come first in the sort list when appearing on the home page.

Since these are least time-critical, they should come last.

This ticket follows on from #487, where it was noted.   But #487 was a different transient bug which seems to have disappeared.

**Comment by BHydden** [comment]
I can't remember whether this was already fixed or not, but I believe it is the same issue as #424
