### ISSUE TITLE
Percentage of fund raising objective not visible anymore

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#502]
### Summary

Hello,

I'm a supporter and I like the new layout of the Supporter page but I missa lot the progression gauge to the goal OGS aims at, before the next milestone.

### Environment

 * Operating system: any
 * Browser: any
 * Browser Version: any

### Steps To Reproduce:

Ask if needed

### Additional Information:

Ask if needed

**Comment by BHydden** [comment]
+1, I changed my bookmark url for ogs to the supporter page so I could keep an eye on the fund raising. Sad to see it's gone.

**Comment by anoek** [comment]
Good to know I wasn't the only one doing this :)
