### ISSUE TITLE
Forking games resets all captures

### ISSUE THREAD

**Issue by jmdingess** [online-go/online-go.com#508]
### Summary

When you fork a game, none of the captures thus far carry over, independent of if you change the ruleset or not. 

### Steps To Reproduce:

An easy way to test:
1. Go to a finished game with some amount of captures
2. Fork the game, putting on any ruleset you choose (Note, as there are no captures in some rulesets anyway, like chinese, you may want to choose wisely)
3. See that all the captures are gone in the new game.
4. If you pass twice, the score will probably be off.

### Additional Information:

I took the same steps I noted above. The rulesets in both were japanese.
https://online-go.com/game/10265799 original game.
https://online-go.com/game/10454128 forked game, same ruleset. Note that all captures are gone in analysis mode.

**Comment by Adam314159** [comment]
It also seems that ko rule is ignored for several first moves of a forked game.
see https://online-go.com/game/16313157 for an example.
