### ISSUE TITLE
Feature request: upload Tygem .gib files

### ISSUE THREAD

**Issue by brw31415** [online-go/online-go.com#512]
to upload BID files

**Comment by anoek** [comment]
Can you include some details about this? Links to specifications, that sort of thing?

**Comment by brw31415** [comment]
sorry i meant gib file , which is format used on tygem website


from Sensei:

https://senseis.xmp.net/?Utilities

   - [image: [ext]] gib2sgf <https://github.com/wzhliang/gib2sgf> Converts
   between GIB <https://senseis.xmp.net/?GIB> and SGF
   <https://senseis.xmp.net/?SGF>


2017-11-05 21:45 GMT-05:00 Akita Noek <notifications@github.com>:

**Comment by BHydden** [comment]
Cleanup:
Propose changing issue name to "Feature request: upload Tygem .gib files"

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
