### ISSUE TITLE
the cup icon linking to ladder/tournament has disappeared

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#517]
### Summary

For ladder and tournament games, there was a cup icon linking to the ladder or the tournament.
It's not visible anymore.

### Environment
any
### Steps To Reproduce:
ask if needed
### Additional Information:
https://forums.online-go.com/t/the-cup-icon-for-ladders-seems-to-have-disappeared/11540

**Comment by mlopezviedma** [comment]
The ladder/tournament icon is now shown on the right side menu. This issue can be closed now.

**Comment by arnaudgo** [comment]
It also works (again?) for ladders. I agree it can be closed :)
