### ISSUE TITLE
No link to the group from a ladder page

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#518]
### Summary

When you're one a ladder page (after a link on a profile page has led you to), you  can't see any link to the group the ladder originates from.

### Environment
n/a
### Steps To Reproduce:

Ask if needed

### Additional Information:

Ask if needed

**Comment by alex-mac** [comment]
Is this ticket asking for "back button" functionality from a ladder page (https://online-go.com/ladder/313) to the profile? I'm not sure what the group refers to in this issue

**Comment by mlopezviedma** [comment]
@alex-mac Read "ladder" as "group ladder" :)

**Comment by arnaudgo** [comment]
Hello @alex-mac , I was indeed not referring to the site ladders :) Thanks @mlopezviedma for giving the precision :) 

Arnaud
