### ISSUE TITLE
Challenge button doesn't appear at first time after joining a ladder

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#519]
### Summary

After having joined a ladder, your username appears on the ladder. No challenge action is available, for that, you need to reload the page.

A light enhancement would be to make it available just after having joined the ladder :)

### Environment
any
### Steps To Reproduce:
ask if needed

### Additional Information:
ask if needed

**Comment by anoek** [comment]
This has been fixed as of the recent-ish ladder ui updates
