### ISSUE TITLE
Can't select text in PM boxes

### ISSUE THREAD

**Issue by VincentCB** [online-go/online-go.com#52]
### Summary

When you select text in a PM box, as soon as you let go of the mouse button, the focus goes back to the chat box and you lose your selection. It makes it difficult to copy text from PMs.

### Environment

Tested on Chrome/Windows, Chrome/Android and Safari/macOS, all latest versions.

### Steps To Reproduce:

Open a PM box and select some text in it.

**Comment by Spoekenkieker** [comment]
Confirmed for Chrome/macOS (both latest)

**Comment by roy7** [comment]
The only trick I've found when I want to copy/paste some PMs is to go to the home page, it tends to work better there.
