### ISSUE TITLE
Offering the choice not to show offline friends in the drop-down list

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#520]
### Summary

I'm worried about those who have too many friends, and too many inactive friends!
Today, connected friends are on the top of the list, which is fine. Maybe could OGS offer the ability not to show in that list offline friends?

### Environment

 any

### Steps To Reproduce:

Ask if needed 

### Additional Information:

Ask if needed.

**Comment by anoek** [comment]
I too want this

**Comment by mlopezviedma** [comment]
This issue can be closed now.

**Comment by arnaudgo** [comment]
Yes it can ! Thank you very much :) This fix made my day :+1:

**Comment by arnaudgo** [comment]
Hello !

I'm so sorry, I really prefer closing issues than re-opening them. Would it be a big deal to make the list not closing when checking/unchecking the implemented checkbox?

cc @mlopezviedma 

Arnaud

**Comment by mlopezviedma** [comment]
I tried, but I didn't find a way to acomplish that. @anoek any hint?

**Comment by anoek** [comment]
To clarify, @arnaudgo do you mean not make the size of the friend list shrink when checking/unchecking the box? If so that should just be a matter of setting the height of the box @mlopezviedma

**Comment by mlopezviedma** [comment]
Nope. When you click the checkbox, the **drop** list closes. Is there a way to avoid that, but keeping the current behaviour? (it's good that the drop list closes when you click a player and then a button on the player details)

**Comment by anoek** [comment]
Ooh oh, probably just `event.stopPropagation()` in your checkbox action so it doesn't bubble up to process the click on that friend list backdrop

**Comment by arnaudgo** [comment]
I don't understand you @anoek, is there a "not" you didn't want to write ?

But well, I would prefer not getting the list close when checking or unchecking so I think shrinking/extending is the behaviour I would like to see. In other words, checking or unchecking don't make the friends list disappear but it filters it out.

Arnaud

**Comment by mlopezviedma** [comment]
Oh, I see what happened now. I tried with `ev.stopPropagation()`, but I was managing the `changed` event instead of `onClicked`. I'll send another PR soonish. :)
