### ISSUE TITLE
Opponent's conditional moves visible in the api

### ISSUE THREAD

**Issue by nathanj** [online-go/online-go.com#522]
### Summary

I'm not sure if this is by design, but it feels like a bug. The conditonal moves that your opponent have submitted are visible in the api.

### Steps To Reproduce:

1. Create a correspondence game.
2. Have your opponent add some conditional moves.
3. View https://online-go.com/api/v1/ui/overview

**Comment by anoek** [comment]
Whoops.

**Comment by anoek** [comment]
Fixed. Thanks for the report!

**Comment by BHydden** [comment]
That was speedy ;-)
