### ISSUE TITLE
Game constantly reported as "it's my turn" although it is not 

### ISSUE THREAD

**Issue by basti1302** [online-go/online-go.com#523]
### Summary

This correspondence game https://online-go.com/game/10522129 is always considered in the TurnIndicator component, even when it is my opponents move. So, even when I have made all my moves, the turn indicator shows a "1" and when I click on it, it switches to this game. 

It has been like this since the beginning of this game.

I did a bit of debugging/troubleshooting myself, see below.

### Environment

 * Operating system: MacOS High Sierra
 * Browser: Google Chrome
 * Browser Version: Version 62.0.3202.94 (Offizieller Build) (64-Bit) 

### Steps To Reproduce:

You would probably need to log in as me to see the symptoms I described, so you probably can not reproduce it. I also do not know how to reproducibly get a game into a state where it has this issue.

### Additional Information:

I believe this is not a front end issue. I checked the web socket "active_game" event for this game:
```
42["active_game", {
    "id": 10522129,
    "phase": "play",
    "name": "Ladder Challenge: basti1302(#160) vs Misawa(#153)",
    "player_to_move": 323219,
    "width": 19,
    "height": 19,
    "move_number": 23,
    "paused": 0,
    "private": false,
    "black": {
        "username": "Misawa",
        "id": 12573,
        "rank": 18,
        "professional": false,
        "accepted": false,
        "ratings": {
            "overall": {
                "deviation": 74.61047604647892,
                "rating": 1535.6891190444296,
                "volatility": 0.05886608878148762,
                "games_played": 1980
            }
        }
    },
    "white": {
        "username": "basti1302",
        "id": 323219,
        "rank": 19,
        "professional": false,
        "accepted": false,
        "ratings": {
            "overall": {
                "deviation": 76.89201358083707,
                "rating": 1532.3270481148688,
                "volatility": 0.05902020466205859,
                "games_played": 281
            }
        }
    },
    "time_per_move": 89280
}]
```

It shows 323219 as the player_to_move. This is my id. It is not my move though. So for some reason the back end thinks it is my move in this game although it is not.

The front end just works as designed on this faulty data.

**Comment by basti1302** [comment]
For the record, I found another issue that describes similar behaviour, it might be related:
https://github.com/online-go/online-go.com/issues/357

But since this issue talked a lot about forked games, I decided to create a new issue for this. The game in question is not forked.

**Comment by basti1302** [comment]
I asked the opponent in this game if he/she has the same problem. Here is the response:

> [18:34] Misawa: Yes, my whole turn notification system is broken. It constantly says its my turn in the same three games, and then won't autoload any of the games where it is my turn. I have to keep going back to the home page to see where it is my turn. It's super annoying. I'm complaining about it in the Support Forum, but after a week, no response or change.
> Move 49
> [20:04] basti1302: Hm, so maybe there is a problem with your account and it also affects other players in the games they play against you. Very weird.

**Comment by basti1302** [comment]
Oh, I didn't notice there is already a thread over the OGS forum about this: https://forums.online-go.com/t/game-notification-bug/14563/16 

Sorry about the crossposting.

**Comment by Adam314159** [comment]
After the update now happenning to a large number of players:
https://forums.online-go.com/t/game-shows-its-my-move-while-its-not/15398
https://forums.online-go.com/t/apparently-not-fixed-notifications-broken/15355/15

**Comment by GreenAsJade** [comment]
Was this fixed by the recent fix?

**Comment by basti1302** [comment]
I believe the original issue has been fixed, but lateley there seems to have been a regression with similar Symptoms? I did not keep track of it lately, though.

Feel free to close or keep it open, whatever works best for you from the maintainer perspective.
