### ISSUE TITLE
Need context aware documentation / help

### ISSUE THREAD

**Issue by cgay** [online-go/online-go.com#524]
### Summary

I think OGS would really benefit from improved documentation. For example, when looking at my profile page it would be great to have a "?" (help) widget on the Statistic section that explains the graph, the numbers on the axes, etc. Also one on the rank section explaining the different ranks and how they work. On the game page there could be one on the clocks explaining exactly how the chosen clock works. For example, what exactly is "39h + 2wk / 0 / 14" ?

Another way to go would be to have per-page documentation and just put the help widget in a standard place on each page. It's a little less flexible that way I guess.

To me this seems like much higher priority than new features like auto-match.

Thanks for listening.
-Carl

### Environment

 * Operating system: Debian Linux and Windows 10
 * Browser: Chrome
 * Browser Version: 62.0.3202.94 (Official Build) (64-bit)

**Comment by cgay** [comment]
By the way, I originally suggested this on the dev forum: https://forums.online-go.com/t/need-context-aware-help-documentation/11631  There are a couple of responses there.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
