### ISSUE TITLE
Timed out correspondence game not ranked

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#525]
### Summary

It appears that some timed out correspondence games are not getting ranked

### Additional Information:

As described [here](https://forums.online-go.com/t/timed-out-game-was-not-rated/14666), there is a clear case where a game ended and did not generate a ranking point on the graph.

**Comment by GreenAsJade** [comment]
... and it looks suspiciously like an 'escape' - the timed out higher ranked person appears behind in this game.

**Comment by BHydden** [comment]
Not a bug it is currently a feature. The first timeout loss counts, all following are annulled.
