### ISSUE TITLE
Duplicate accounts resulting in lost access to supporter account

### ISSUE THREAD

**Issue by wmayner** [online-go/online-go.com#531]
### Summary

I created an account with Google OAuth. Then, I created an account without Google OAuth but using my Google account email as the username. I donated and became a supporter using that second account.

Now, I can't seem to avoid logging in to the first account I created with OAuth, and therefore I can't access my supporter-status account.

How can I delete the OAuth account and recover access to my supporter account?

### Environment

 * Operating system: Mac
 * Browser: Chrome
 * Browser Version: Version 62.0.3202.94 (Official Build) (64-bit)

### Additional Information

- Supporter account username: `w_m`
- OAuth account username (to be deleted): `wmayner929db69c728b4dd0`
- Email address initially used for both accounts: <my GitHub username>@gmail.com

**Comment by anoek** [comment]
I shot you an email to get that fixed up for you.
