### ISSUE TITLE
HTML 5 validity for attribute href on element link: Illegal character in query: | is not allowed.

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#532]
### Summary

When using fonts google api, the | character is preserved in the returned link.

HTML 5 validity for attribute href on element link: Illegal character in query: | is not allowed.

### Environment

any

### Steps To Reproduce:

n/a

### Additional Information:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fonline-go.com

**Comment by anoek** [comment]
Huh, copy paste from google led me astray.

**Comment by anoek** [comment]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fbeta.online-go.com
