### ISSUE TITLE
1-1 labels need to be handled properly in game chat

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#533]
### Summary

@arnaudgo noted:

> Whatever I use Chinese or English version of the site, X labels go from A to T (e.g. for 19x19).
>
> But, for Y labels go ascending from the top to down regarding the Chinese version and from the bottom to up in the English version.
>
> When in the game chat, I want to share a position while using the Chinese version, I mentally translate 一 to 1, 二 to 2, and so on. But my conversion leads to a wrong position since the Y gets indexed the English way.

I think we need to do two things: 
   1) Add proper support for 1-1 labels in chat
   2) Automatically convert detected a1 and 1-1 labels to the user's display preference

**Comment by arnaudgo** [comment]
Ahhh, thank you very much @anoek ! I hadn't taken the time to open the issue for that ... My apologies.
Busy...

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
