### ISSUE TITLE
Date display in forum comments

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#537]
### Summary

Currently, old posts are displayed Mmm 'YY
and recent posts are displayed Mmm DD

Sometimes it’s hard to see the apostrophe that distinguishes a year from a day making it unclear when a comment was posted (was it the 15th of September this year? Or was it September 2015?)

### Additional Information:

I don’t have a specific preference on how one or both of the dates are changed but I think it would help if it was immediately obvious whether a comment was from a previous year or the current year.

Discussion available at 
https://forums.online-go.com/t/date-display-in-forum-comments/14797

@driph says: 
Discourse settings can be simply changed as per https://meta.discourse.org/t/change-to-dd-mmm-mmm-yy-for-post-dates/13625/34

**Comment by anoek** [comment]
The forum software we use is [Discourse](https://www.discourse.org/), you'll want to bring it up over there for any changes like that.

**Comment by driph** [comment]
It just requires someone with admin permissions to go in and make the change.

**Comment by anoek** [comment]
Sweet, ok cool, I updated to do YYYY instead of 'YY, thanks for pointing me to where I needed to go to make the change!
