### ISSUE TITLE
Emergency button for the mods

### ISSUE THREAD

**Issue by sousys** [online-go/online-go.com#539]
A function for the mods that will generate email/sms or other form of signal to devs that the site is experiencing problems. Some sort of signal that generate notifications to devs whereever they are, just so that they know that problems are happening.

**Comment by BHydden** [comment]
Already in existence, just not available to the general public. Admin are asleep in America currently, problem will be resolved asap

**Comment by sousys** [comment]
Where is it then?

**Comment by BHydden** [comment]
I come under public, but I know forum mods have special ways of contacting the devs that I don't. However, it seems anoek agrees that more could be available and is interested in developing something more along these lines.

**Comment by anoek** [comment]
This has been implemented, details of usage are on the internal forum thread.
