### ISSUE TITLE
Download SGF option does not always name file correctly in Chrome

### ISSUE THREAD

**Issue by Nabeshin3D** [online-go/online-go.com#540]
### Summary

Downloading the SGF from https://online-go.com/game/10412395 in Chrome results in a download with a file name of "sgf" instead of the normal file name.

### Environment

 * Operating system: Win 7/10
 * Browser: Chrome 
 * Browser Version: 62.0.3202.94

### Steps To Reproduce:

1. Go to https://online-go.com/game/10412395
2. Click "Download SGF" in side-menu
3. Receive file called "sgf"

### Additional Information:

"sgf" file appears to be an otherwise valid sgf.  Just the filename is missing.

**Comment by arnaudgo** [comment]
Hello,

For the given game, it doesn't work for me neither using Chrome under Android but works for Firefox.
I might be not a random error but linked to the players names: it worked well for another game I tried using Chrome.

As a side note, I consider OGS should be less permissive in the choice of an username, group name or tournament name but not necessarily with the same rules enforced.

Arnaud

**Comment by Nabeshin3D** [comment]
My first guess was it had to do with my username beginning with an emoji.  However downloading the sgf from https://online-go.com/game/9791709 works fine.  In both cases I was black.

**Comment by arnaudgo** [comment]
Nice deduction @Nabeshin3D ;) 
Mind that in the second game you mention, you were not playing against someone whose username contain any apostrophe or whitespace :)

Arnaud

**Comment by Nabeshin3D** [comment]
Indeed, it seems you've found the issue.  While my other games download fine, I get missing filename behavior when downloading any of my opponent's games.  It seems likely that this can be fixed if the filename generator is made to handle ' characters gracefully.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
