### ISSUE TITLE
Game history should show player's rank at the time of the game.

### ISSUE THREAD

**Issue by lrperlmu** [online-go/online-go.com#542]
### Summary

Past games appear with players' present ranks. They should appear with the rank at the time the game was played.

### Environment
N/A

### Steps To Reproduce:

1. View Game History in each player's profile.

### Additional Information:
Link to forum post:
https://forums.online-go.com/t/why-in-past-games-the-username-appears-with-the-present-rank/11921

**Comment by arnaudgo** [comment]
Hello !

Looks like a duplicate of #364  :)

Arnaud
