### ISSUE TITLE
For the USA flag the caption text should be changed to "United States of America"

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#543]
### Summary

When you put the mouse over the flag of USA of a player, the caption text appearing is "United States".

It should be "United States of America", don't you think so ?

### Environment

any

### Steps To Reproduce:

Ask if needed

### Additional Information:

Ask if needed

Arnaud

**Comment by anoek** [comment]
Looked into this, this string is actually coming from the unicode cldr: http://cldr.unicode.org/ that provides locale-specific names of countries for country codes, so meh, I'd say good enough. I wouldn't object to someone hacking this in but it'd be more trouble than it's worth. I suspect that if it ever becomes ambiguous they'll clarify it in the CLDR and it'll trickle down to us.

**Comment by srl295** [comment]
@anoek btw, you may be interested in https://github.com/unicode-org/cldr-json/ , in fact you may only need the npm packages `cldr-localenames-full` or `cldr-localenames-modern` for your use.
