### ISSUE TITLE
Making player games history resizable with a handle on the lower right corner

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#544]
### Summary

Hello,

Please, could you make the box containing the games history resizable with the mouse through a handle on the lower right corner ?

Thanks

### Environment

Any

### Steps To Reproduce:

ask if needed

### Additional Information:

Ask if needed

Arnaud

**Comment by arnaudgo** [comment]
Hello,

if it's only horizontally resizable, I will be happy with it to avoid the current scrolling bar.*

Arnaud

**Comment by BHydden** [comment]
+1 especially frustrating when there is both a horizontal scroll bar and 6 inches of unused space either side of the container.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
