### ISSUE TITLE
My go boards turned blue on Firefox @ Android only

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#545]
### Summary

Hello,

Since nearly 2 weeks my go boards all turned blue on Firefox at Android only.
I have the feeling it could be due to having emptied my browser cache at that time and that the problem might have been introduced a longer time ago. 
But, I might have not noticed because of some cache which didn't get invalidated ? 
I haven't spent time checking if the property is cached and when it theorically expires ... 
I haven''t tried emptying caches in other browsers to see if I can reproduce the problem.

I am not overriding any style browser-side.

It might have appeared after a Firefox update but I cannot be sure...

### Environment

 * Operating system: Android 7.0
 * Browser: Firefox
 * Browser Version: 57.0.1

### Steps To Reproduce:

Ask if needed

### Additional Information:

![allboardsblue](https://user-images.githubusercontent.com/26174230/34453956-07ac7dc4-ed60-11e7-9c56-ecee641113e5.png)

Arnaud

**Comment by arnaudgo** [comment]
It happens on all games page as well on one game page.

**Comment by anoek** [comment]
That looks like our HNG theme - might have it gotten clicked by accident? 

Click your profile drop down in the upper right, you'll see a number of board themes available - you should be able to revert it to the standard one by selecting the left most second from the top board icon (that's the default wood grain look)

**Comment by arnaudgo** [comment]
Thanks @anoek :-) I had probably done that ... Fixed now!
