### ISSUE TITLE
Running out of vacation time or having run of it should bring a notification

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#547]
### Summary

Hello, your vacation time can end without notifying you but it would be nice :)

### Environment
n/a
### Steps To Reproduce:
ask if needed
### Additional Information:
ask if needed

Arnaud

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
