### ISSUE TITLE
Links aren't highlighted on PM and group pages

### ISSUE THREAD

**Issue by mlopezviedma** [online-go/online-go.com#55]
### Summary

Links are highlighted on main and games/reviews chats, but neither on PM boxes nor on group pages.

### Environment

 * Operating system: Linux
 * Browser: Opera
 * Browser Version: 43.0.2442.806

### Steps To Reproduce:

1. Go to a group page that has links on its page (e.g. https://online-go.com/group/25 ) or open a private message and send a message with a link on it
2. See that it's not highlighted

**Comment by juanchodepisa** [comment]
I don't think they are highlighted anywhere across the entire site. For some of those places is reasonable not to highlight (like in the main menu) but in many other places it looks just awkward.

I wanted to post an issue for the particular case of editable fields where markdown is used, but then I realized there was already this one.

**Comment by windo** [comment]
It doesn't just look awkward but on groups pages important links are effectively invisible. For example, learning ladder group uses an external google doc to track review requests. Unfortunately all the "Notice Board" links in the group rules appear just as regular text so unless you hover over them, you might have trouble figuring out how to get to this mysterious "Notice Board":

https://online-go.com/group/865

**Comment by windo** [comment]
It looks like global.styl uses "themed text-color" and "text-color-active" for links globally. It sounds a bit annoying to manually twiddle with the styles of a bunch of elements so presumably there should be something high-level to designate some elements to have blue links and for some elements to not. A class? A react element type (or something)? Per-view defaults?

**Comment by anoek** [comment]
Ehh.. seemed like a good idea at the time. But it was not. All links are now colored, unless specifically overridden (which is pretty much only on the NavBar and some links on the Overview page)
