### ISSUE TITLE
Ladder UI Problems When Switching Pages

### ISSUE THREAD

**Issue by hyperpape** [online-go/online-go.com#550]
### Summary

When navigating to a different page of the ladder, the numeric page you're on (page 1,2,3, etc...) may get out of sync with the data displayed. 

### Environment

 * OS: Linux (but have seen elsewhere)
 * Browser: Firefox (ditto)
 * Browser Version: 57.0.1

### Steps To Reproduce:

1. Go to the ladder page
2. Quickly click the arrow to switch pages several times
3. See that the resulting page is (sometimes) out of sync with the number

That is, if you are on page 4, then click left three times, you may end up on page 2 or 3 instead of 1. 

This issue is exacerbated by the lack of any UI feedback that the ladder is loading data, so you can't distinguish between "you're seeing an out of date page, but the next one is loading" and "you're done loading pages, and have ended up on an unexpected one". (This is more of a problem for users on a slow/flaky connection).

**Comment by anoek** [comment]
"fixed" with the recent-ish ui updates of the ladder ui
