### ISSUE TITLE
show the number of running games out of the maximum when games thumbnail threshold is set

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#552]
### Summary

This is a very minor enhancement I request. I didn't know how to express it clear.

When one sets a games thumbnail list theshold (to something different that always show in list), it might be useful to read on one's games page some counter like: N running games out of M where M is the defined threshold before games get displayed in list rather than in miniatures.

It's very low priority and maybe totally useless but you think it might be useful ... :) 

### Environment

n/a

### Steps To Reproduce:

ask if needed

### Additional Information:

ask if needed

Arnaud

**Comment by anoek** [comment]
Are you saying the first N games get displayed as thumbnails, the rest in a list?

**Comment by arnaudgo** [comment]
Hi @anoek ! You haven't understood at all ! And after having read myself again, I could clearly understand the issue title neither :-D 

Well, I changed the title, slightly and here's an example, I hope it makes the point clearer.

User Paul wants to display running games in list when their number is over 25 (what I call his thumbnails threshold) 
He has 23 running games, so he still sees them in thumbnails. 
It would be nice to see 23/25, in other words: 3 running games are left before displaying them in list.
Or maybe 2 if I'm off by one !
I think my example makes it clearer, I hope so !

Arnaud

**Comment by anoek** [comment]
Ah yes got it :)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
