### ISSUE TITLE
Game history sometimes slow to load, or fails to load

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#553]
### Summary

Went to https://online-go.com/player/419331/ and the History area never populated. 

### Environment

 Chrome

### Steps To Reproduce:

Load someone with a lot of history and it may be slow to populate. I've never seen it fully fail before like this though.

It appears from my console that the API call to get the games returned an error code 520. 
http://puu.sh/yXo5n/c961f44d93.png

I tried loading that URL a few times directly:

https://online-go.com/api/v1/players/419331/games/?page_size=50&page=1&source=play&ended__isnull=false&ordering=-ended

And the first ones worked, but then I did get:

Error 520 Ray ID: 3da4f9fe898050aa • 2018-01-09 05:26:02 UTC
Web server is returning an unknown error

**Comment by anoek** [comment]
This should be "fixed" with the new hardware (linked player seems to load reasonably quickly now)
