### ISSUE TITLE
Payment card and CVV numbers input masks are error-prone

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#554]
### Summary

In support page,

The card number is probably always a 16-digit number and the CVV a 3-digit number.
But the input fields let the user input longer numbers. 
If the input masks were forcing a correct length, the user could easily spot some of his typo mistakes.
Probably the impact is low and is just a waste of time user side. But, then it's an optimization, still.

### Environment

any

### Steps To Reproduce:

Ask if needed

### Additional Information:

Ask if needed

**Comment by anoek** [comment]
This has been addressed by #580 implicitly (we now use Stripe, which has a very nice credit card input system)
