### ISSUE TITLE
Games missing gamedata / active_game messages to bot

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#555]
https://online-go.com/game/11310878

I noticed RoyalZero had never moved in this game. When I start up my RoyalZero bot, there's no active_game message for this game ID # in any of my logs. All I can find is when the challenge came in and bot accepted, but no message with this ID # has ever been received since.

In fact, similar situation:

https://online-go.com/game/11310878
https://online-go.com/game/11306221
https://online-go.com/game/11306255
https://online-go.com/game/11306579
https://online-go.com/game/11306642
https://online-go.com/game/11307290
https://online-go.com/game/11299602

Other games do work fine and games are being played/finished normally.

**Comment by roy7** [comment]
I tried a quick game vs Fuego but they never made first move. Perhaps because of this same issue, would be my guess.

https://online-go.com/game/11313697

**Comment by roy7** [comment]
RoyalLeela seems to have one too. https://online-go.com/game/11311959

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
