### ISSUE TITLE
Auto Advance to next game not working

### ISSUE THREAD

**Issue by WheelbarrowPete** [online-go/online-go.com#556]
### Summary
After the site came back online (1/15/18) the system no longer advances me to the next game.
Also, the small black circle with the number of games I need to make moves in is no longer visible.
I checked my “Settings” a few times and that box is still checked.

This happens on a few different devices (computer, tablet, phone, etc.)

*Briefly describe the issue you are reporting*

### Environment
Windows 10, Chrome browser, Version 63.0.3239.132 (Official Build) (64-bit)
Also iPhone8, iOS 11.2.2, Safari browser.
Also iPad mini 4, iOS 11.2.2, Safari browser.

 * Operating system: 
 * Browser:
 * Browser Version:

### Steps To Reproduce:

Every time I'm on the site in the last few days the problem persists.

1. Go to ...
2. Click ...
3. See that X wrong 

### Additional Information:

I can find the games where it's my turn to move by going to the home page, and those games are highlighted in green.  This has always been the case.  It's just that the "Auto Advance to Next Game after Making a Move" button (in Settings) isn't working.  By the way, I have this button checked.  I also tried unchecking it, logging out, then rechecking it, but same problem.

Thanks.
rgesh22@gmail.com

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
Is this still an issue for you? I haven't heard any other comlaints about this. Were there any other changes to your home network when this happened, the introduction of a new router or anything like that?

**Comment by anoek** [comment]
never mind i see a whole thread about it here: https://forums.online-go.com/t/notifications-and-outstanding-game-count-not-working/15355/29

**Comment by Bloodyaugust** [comment]
@anoek This seems to have been resolved.
