### ISSUE TITLE
Sorting in the active game list is confusing

### ISSUE THREAD

**Issue by pyrocumulus** [online-go/online-go.com#558]
### Summary

The active game list, isn't sorted by time remaining anymore. The indication is there, but it just doesn't work. This is a small problem, however other processes that use the same list also use the same broken sorting. 

For example when you use the 'advance to next game on move' feature for correspondence games, it does this as well. In the past you could do a couple of moves/games and you'd see the time remaining increase, so when it would say 48 hours for example, you know that all the other moves would have at minimum 48 hours remaining.

I've been getting a lot of 'almost out of time' notifications because of this.

### Environment

 * Operating system: Android/Windows
 * Browser: Chrome, Chrome Android
 * Browser Version: 63.0.3239.132 for Windows

### Steps To Reproduce:

1. Go to https://online-go.com/overview
2. See that the ordering is wrong
3. Try to fix it by clicking on Clock column
4. See that it's still not correct

### Additional Information:

Here is a screenshot of [my game list](https://online-go.com/player/248861/), for optimal clarity:
![image](https://user-images.githubusercontent.com/1721382/35088160-12a84924-fc33-11e7-843d-a2c2b421c169.png)

**Comment by bitlux** [comment]
When I sort by "Clock", it actually sorts by the time on the opponent's clock:
![screenshot from 2018-01-25 23 06 11](https://user-images.githubusercontent.com/12686590/35428553-924c0eda-0224-11e8-8119-01f7cc603d25.png)
This persists across reversing the sorting order.

**Comment by BHydden** [comment]
It sorts games where it is your move by your clock and games where it is your opponents move by their clock.

**Comment by pyrocumulus** [comment]
@bitlux 
I thought so as well, but that's not what's happening for me. When I sort on my own clock, most of the games are sorted by the opponents clock but not all of them. Reversed or regular both have the same issue and the same weirdness arises from sorting by my own clock.

@BHydden 
I'm trying to understand what you are saying, but I see no logic in the sorting by Clock or Opponents clock at all. Even when I look at the other clock than the one I'm sorting by, there is no obvious logic to what the order is.

**Comment by BHydden** [comment]
Grey game = vacation, for some unusual reason they are sorted to the little time remaining end rather than the more time remaining end

Green game = games where it is your move, these will be sorted by how much time you have remaining (the clock that is ticking down) 

Unhighlighted game = games where it is your opponents move, these will be sorted by how much time your opponent has remaining (again, the clock that is ticking down)

**Comment by pyrocumulus** [comment]
@BHydden 
Thanks. With your information I think I get now, how the games are sorted when I sort on my own clock. But I still think it's really confusing that if you click to sort by a certain column, it doesn't sort all the things in that column but only part of it. Together with the vacation games it makes it really hard to intuitively understand what is happening.
When I sort by the opponent's clock I think it's even more confusing. When I sort ascending, the applied sort appears descending and vise versa. But apart from that, the reverse logic seems to apply indeed. Games where it's the opponent's move are sorted by their timer and games where I have the move are sorted by mine.

While I get it now, thanks to your explanation, I still think the base idea for this sorting method this is really counter intuitive. Even apart from the weirdness with vacation games and sorting by the opponents clock.

_Continuing_
The next problem is the order that the 'moves' indicator uses. When I navigate to the Home page I see I have a game in which I have with 24h remaining and a lot with more remaining. When I click on the upper right moves indicator, it does not take me to the game with the least time remaining. Instead it takes me to the game with the oldest ID. While there is logic to that, it's just isn't practical. You want to execute moves with the least time remaining.

**Comment by Bloodyaugust** [comment]
Perhaps this issue should be closed, and a player discussion about the optimal sorting of this list held elsewhere, with a separate issue being created to handle this:

> The next problem is the order that the 'moves' indicator uses. When I navigate to the Home page I see I have a game in which I have with 24h remaining and a lot with more remaining. When I click on the upper right moves indicator, it does not take me to the game with the least time remaining. Instead it takes me to the game with the oldest ID. While there is logic to that, it's just isn't practical. You want to execute moves with the least time remaining.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
