### ISSUE TITLE
Number of games on top right isn't updating.

### ISSUE THREAD

**Issue by MCSH** [online-go/online-go.com#559]
### Summary

The black number on the top right corner has been stuck for me for some time - at least a week. It shows 5 but I am playing more games and it's not my turn in any of them.

### Environment

 * Operating system: Linux (two different machines), android
 * Browser: google chrome
 * Browser Version: 63.0.3239.132 (Developer Build) (64-bit) (don't have access to the other machines atm)

### Steps To Reproduce:

I don't know what caused it to reproduce it. My account name is MCSH, id 344067 if it helps.

I tried getting help in chat but.... people are annoying there.

> [ 0:30]MCSH: Guys, the black number on the top right corner has been stuck for me for some time. It shows 5 but I am playing more games and it's not my turn in any of them.
> [ 0:32]MCSH needs help
> [ 0:33]Gurxtav: you mean that
> [ 0:33]EricJHan Operator: Thank you for calling the help line, someone will be with you in 10,000,000 minutes, please wait
> [ 0:33]Gurxtav: Triet refreshing the page?
> [ 0:34]Gurxtav: press f5
> [ 0:34]MCSH: Yeah, when I say some time I mean at least a week and on different machines as well.
> [ 0:35]MCSH: on 2 different desktops and a mobile device
> [ 0:39]elx: What is the best way to place handicap?
> [ 0:39]elx: Perhaps komoku?
> [ 0:39]elx: Then you can enclose two corners with next moves
> [ 0:40]Kungfu Panda: star points are really not that bad
> [ 0:40]EricJHan: ^
> [ 0:40]EricJHan: That framework, like my hips don't lie
> [ 0:41]shinygami Thank you for using our interstellar rescue service, due to time dilation, you can expect rescue in 100,000,000,000,000,000,000 hours, 20 minutes, and 3 seconds.
> [ 0:42]EricJHan: Welcome to the jiggle hotline, we will be with you in 50,000 jiggles
> [ 0:42]EricJHan: :^)
> [ 0:42]MCSH: alright this is a waste of time....

**Comment by anoek** [comment]
Dup of #556
