### ISSUE TITLE
rank restriction bug

### ISSUE THREAD

**Issue by TableCarpet** [online-go/online-go.com#560]
I create games with with different rank restriction ranges. 
7k-1k or 14k-8k for example. And sometimes people out of this range accept it. It happens EVERY day.
Usually they are only 1 rank higher or lower than this range. Maybe because rank changed recently.
When I click their name in game it displays not the same rank as in profile. Maybe rank restriction uses this wrong number.

**Comment by anoek** [comment]
Have you seen more than 1 rank difference? I'm wondering if it's a rounding/not rounding issue, or something else

**Comment by TableCarpet** [comment]
I don't remember. I will tell if someone with more than 1 ranks difference accepts.

I just created unranked game 10k-25k and 8.9k accepted. In game he displayed as 9.3k and when game ended his in game rank changed to correct value.

**Comment by Adam314159** [comment]
if users are to be trusted it seems it happens way out of range as well
https://forums.online-go.com/t/rank-restriction-bug/15196

**Comment by TableCarpet** [comment]
0.3 kyu is max difference I seen these days. Doesn't look like rounding issue. More like max rank change after game of 2 not new users.

**Comment by TableCarpet** [comment]
Just created game 9k-13k and 5k accepted it.

**Comment by TableCarpet** [comment]
Created game 11k-13k and 8k accepted it.

**Comment by anoek** [comment]
Finally fixed on the server side, thanks for the persistence in bringing this to my attention.
