### ISSUE TITLE
Zeus strike should happen on demand.

### ISSUE THREAD

**Issue by lemurek** [online-go/online-go.com#561]
### Summary

As discussed under https://forums.online-go.com/t/make-time-out-resigning-opt-in-rather-than-opt-out-for-opponent/15484/9 under certain circumstances the forced loss upon 5 minute disconnect might not be a desired option. Example circumstances are:
* friendly non-ranked games
* quality games interrupted by accident

Given the use of pause button is not very intuitive way of working around a problem, the idea to make opponent decide whether to terminate a game after prolonged disconnect seems reasonable.

### Environment

 * Operating system: any
 * Browser: any
 * Browser Version: any

**Comment by anoek** [comment]
I agree this would be nice

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
