### ISSUE TITLE
Posting to /api/v1/games/<id>/move causes 500 / Server Error

### ISSUE THREAD

**Issue by jladdjr** [online-go/online-go.com#564]
### Summary

Using Postman to try to make a move in an active game results in `<h1>Server Error (500)</h1>`.

### Environment

 * Operating system: OS X
 * Browser: (Postman)

### Steps To Reproduce:

(omitting call to `/oauth2/access_token` to get `access_token`)

```
curl -X POST \
  https://online-go.com/api/v1/games/11707567/move \
  -H 'Accept: application/json' \
  -H 'Authorization: Bearer <OMITTED>' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 9bce50aa-2b99-90f5-afb2-8225b97b59f8' \
  -d '{
  "move": "bc"
}'
```

Using `/api/v1/games/11707567/move` results in:
```
<h1>Server Error (500)</h1>
```

Using `/v1/games/11707567/move` results in:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/games/11707567/move</pre>
</body>
```

### Additional Information:

Related API documentation:
https://ogs.docs.apiary.io/#reference/games/game-movement/make-a-move-in-a-game

Similar issues found on forum:

Server error also reported at:
https://forums.online-go.com/t/sending-move-from-api-causes-500-error/14328 

Reports seeing `{"detail": "Method 'POST' not allowed."}`:
https://forums.online-go.com/t/unable-to-submit-moves/7405

**Comment by jladdjr** [comment]
I'm wondering if folks are encouraged to use the Real Time API instead of the REST API to issue commands in games:
https://ogs.readme.io/v4.2/docs/real-time-api

I know that there's also gtp2ogs:
https://github.com/online-go/gtp2ogs/blob/devel/gtp2ogs.js

**Comment by anoek** [comment]
Aye, real time api would definitely be preferred for doing anything with moves. We did have REST support that kinda worked for a bit, but no one was using it (including us), so I didn't port it over in the last major revision here... docs need updating :(

**Comment by ansible-test-user** [comment]
> Aye, real time api would definitely be preferred for doing anything with moves. We did have REST support that kinda worked for a bit, but no one was using it (including us)

Okay, gotcha. Are there patches of the API (like moves) that didn't get moved over, or is the REST API as a whole more or less inactive / not currently supported?

**Comment by jladdjr** [comment]
> Aye, real time api would definitely be preferred for doing anything with moves. We did have REST support that kinda worked for a bit, but no one was using it (including us)

Okay, gotcha. Are there patches of the API (like moves) that didn't get moved over, or is the REST API as a whole more or less inactive / not currently supported?

**Comment by anoek** [comment]
Pretty much anything that involves interacting with a game wasn't ported over, and I have no plans to. The real time API is where it's at :)
