### ISSUE TITLE
Add push to server for PWA notifications

### ISSUE THREAD

**Issue by kevincoleman** [online-go/online-go.com#568]
### Summary

Adding a push service for notifications to open up service worker notifications for progressive web apps.

### Environment

 * Operating system: any
 * Browser: All but Opera

### Additional Information:

Since the site functions nicely as a PWA, adding a push functionality on the server side would allow for development of a service worker that keeps users notified of moves.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
