### ISSUE TITLE
Facebook authentication required even after password is set

### ISSUE THREAD

**Issue by lemurek** [online-go/online-go.com#574]
### Summary

For accounts originally authenticated with Facebook, configuring password doesn't enable independent authentication mechanism. Instead app still uses facebook id for login.

### Environment

 * Operating system: Any(?)
 * Browser: Any(?)
 * Browser Version: Any(?)

### Steps To Reproduce:

1. Set-up password in facebook authenticated account.
2. Open incognito window and try to login with your password
3. Instead of getting into the service you end up with facebook login widget

### Additional Information:

<img width="710" alt="screen shot 2018-03-03 at 14 02 39" src="https://user-images.githubusercontent.com/12175058/36935146-a97a1208-1eeb-11e8-9899-4f126181e479.png">

**Comment by anoek** [comment]
Hmm... seemed to work for me in both chrome and firefox?

**Comment by lemurek** [comment]
For me the issue is 100% reproducible. Both under incognito mode of chrome or under a clean session in new browser, i.e. Safari. Did you make sure all the prerequisites where met?

1. Account originally authenticated with facebook.
2. Password account setup as a secondary auth.
3. Clean session without the facebook authentication active.

**Comment by lemurek** [comment]
I discovered the problem when I was trying to login to the mobile app: https://forums.online-go.com/t/are-you-a-developer-want-ogs-on-a-mobile-device/1419/209 

That app supports password authentication only and fails to authenticate me, most likely due to the facebook auth requirement.

**Comment by Mabsss83** [comment]
Same issue with my google account.
To reproduce
1. disconnect
2. try to reconnect with username/password
3. the google account sign-in pops

I think I created a simple account that I linked with google sometime after.

I couldn't connect to the android app cause the google sign in is broken there.

**Comment by simonseyock** [comment]
I have a similar problem, but not on all browsers. It especially happens on chrome on my mobile.

1. I created my account via google sign in
2. I added a password
3. on mobile chrome it always redirects me to the google sign in page

After that I tried to disconnect my google account from the online-go account via my google settings. Even now the login always redirects to the google sign in page.

**Comment by dan-ih** [comment]
Also looking for a way to unlink my google account.
