### ISSUE TITLE
Countdown for end of main time should be changed

### ISSUE THREAD

**Issue by Fyaaa** [online-go/online-go.com#578]
Just a small thing but I've seen a lot of people not like having the same voice count down the final 10 seconds of main time as it would be in overtime.  I think a better alternative, if you want to alert the user that main time is ending would be something similar to other servers, where it might say "Overtime countdown begins" or some other preferred wording.

**Comment by anoek** [comment]
Totally open to this, the main block that I see would be we need someone with a good voice to record that and a new set of numbers (would probably be weird to have a different voice for the two things)

**Comment by xstephenhu98** [comment]
Can just use Google's voice for those recordings?

**Comment by mlopezviedma** [comment]
How about just one beep per second on, say, 3 2 1?

**Comment by lemurek** [comment]
I've created another issue for that looong time ago :) I'm glad that someone else finds it confusing as well. https://github.com/online-go/online-go.com/issues/7

Is there a way to merge issues together ?

**Comment by lemurek** [comment]
> Can just use Google's voice for those recordings?

There is also Amazon Polly service that provides a multilingual speech synthesizer (the same that's behind Alexa's voice). It could be used to provide a multilingual messages easily customisable by users from different countries!

**Comment by anoek** [comment]
I would assume it's against the google and polly ToS's to use samples like that, but maybe not? I haven't looked into it.

**Comment by lemurek** [comment]
Looks like Polly does not have any restrictions on the numbers of playouts. So you can record once and then use the prerecorded samples as much as you wish: https://aws.amazon.com/polly/faqs/

**Comment by lemurek** [comment]
And I'm happy to use my personal AWS account to generate the samples if that will be helpful. Free tier is up to few million characters, so I won't ask for reimbursement ;)

**Comment by BHydden** [comment]
Think this can be closed as of the (not so) recent audio update.
