### ISSUE TITLE
Making Malkovich log entries editable (at least till the game ends)

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#581]
### Summary

We can consider Malkovich logs are usually not for spontaneous chat since only observers can read them.
I'm not 100% confident with that assertion though.
We can consider Malkovich log entries are usually dedicated for being used as a reference for the game they are linked to e.g. move commentaries, etc ..

It may be very useful to be able to correct any mistakes one can make e.g. typos on move numbers, coordinates, etc ...without overloading the Malkovich log since it can grow fast if players are very talkative.

Malkovich log aims to be easy to be read and easy to be understood.

A possibility would be to make them always editable, even after the game has ended but I'm not very fond of even if I don't see any big drawback though. However, I think we need a final version so the requested ability to edit one entry must end.

Making all entries, Malkovich or not, editable, don't seem to me to have big drawback neither but still I would prefer not making them editable because it may break the flow of the conversation somehow.

### Environment

n/a

### Steps To Reproduce:

n/a

### Additional Information:
Ask if needed

Arnaud

**Comment by anoek** [comment]
I could see this as being pretty cool, deserves some thought.. not sure the best way to present that ability to the user, seems like maybe an alternative interface might be worth exploring (like a more traditional sgf editing interface where you can edit notes / malk log entries per move), but then that's kind of a bigish change too.. will have to ponder that a bit.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
