### ISSUE TITLE
Option for "your move" notifications to be sent only once for all games

### ISSUE THREAD

**Issue by netnazgul** [online-go/online-go.com#59]
Add an option for "your move" notifications to be sent only once there is a game to play and do not send subsequent emails on EVERY game that becomes available; supposedly until a visit to online-go. Same as with forums where you do not get a mail for every post in every topic you've subscribed to, but a single notification "there are new posts in your bookmarks, go visit".

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
