### ISSUE TITLE
Scoring issues in bot games

### ISSUE THREAD

**Issue by lemonsqueeze** [online-go/online-go.com#590]
Hi,

I'm looking at [online-go.com/game/12128522](https://online-go.com/game/12128522)

![screenshot](https://user-images.githubusercontent.com/2463904/37676674-db1a6f52-2c78-11e8-9a92-9c057534e65a.png)

and a few others pachipachi played recently which got scored incorrectly (white wins this actually).
For unranked games i guess it doesn't matter but for ranked games that looks like an issue...

How do we deal with this ?
Flagging the games manually for moderator attention doesn't sound great, and i'm sure the moderators have better things to do too. Shouldn't bots have a way to disagree at least ?

No silver bullet, but some ideas maybe:
1) In case bot and server disagree could fall back to something like `kgs-genmove_cleanup` protocol which is fairly foolproof, if unfriendly...
2) Or let player know: "Bot and server don't agree on scoring, please resume play and try scoring again later". Situation may never get clarified so after a number of times would need to fall back to 1. or call a moderator, or something ...

**Comment by lemonsqueeze** [comment]
Btw, i did some work on fixing scoring issues in Pachi. The situation was pretty similar to ogs's score estimator: there were situations where mc evaluations were unclear and it would get dead stones wrong, which would lead to kgs-genmove_cleanup phases on kgs ...

Nowadays it can score about 99% games correctly: playouts handle most sekis so that's not an issue, and it won't agree to pass unless all uncertainties have been cleared out. It's fairly lightweight, i'm wondering maybe it could be hacked into a scoring module for ogs ...

**Comment by anoek** [comment]
FWIW this is our score estimator code here: https://github.com/online-go/score-estimator  it's the same code we use for automatic end game dead stone removal, only with more iterations

**Comment by roy7** [comment]
If someone wants to experiment with it, I made a more seki-aware version here:

https://github.com/roy7/score-estimator/tree/seki

**Comment by lemonsqueeze** [comment]
[Pachi ogs score estimator experiment](https://github.com/online-go/score-estimator/issues/5)

**Comment by roy7** [comment]
Bummer. I only had a few seki positions to test on when I worked on it originally and it worked for those at the time. :(

**Comment by lemonsqueeze** [comment]
[Game 14829464](https://online-go.com/game/14829464)
6 months down the road and nothing has changed, ogs development dead ?
This is not an enhancement btw, it's a bug.

**Comment by BHydden** [comment]
Ogs development isn't dead, it's just a small team who does an exceptional job, but can still only do one thing at a time.
Given that earlier in this thread anoek said the score estimator code is used for end game stone removal, and the score estimator is the current project getting worked on right now, I'd guess this is getting fixed as well, even if it doesn't have comments on this specific ticket.

**Comment by lemonsqueeze** [comment]
Cool, good to know.
