### ISSUE TITLE
Ability to filter out unwanted notifications

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#591]
### Summary

Sometimes you get five or more notifications for the same event when you are not interested in even a single one.

I would like to be able to mute all notifications minus some of certain types (server maintenance,..) forever, for hours or I don't know.
Of course, I would love to be able to unmute them before the deadline and I would like to be able to access to the notifications history including the missed/ignored ones.

Obviously, it would be super if muting were not session-bound.

### Environment

 Any

### Steps To Reproduce:

Any

### Additional Information:

Ask if needed

**Comment by anoek** [comment]
To be clear, you're talking about the announcements that pop up in the upper right that have links to games or twitch channels or whatever? As opposed to the "game started!" notifications in the drop down?

**Comment by arnaudgo** [comment]
Thank you for asking, indeed ”event" can refer to many things and your assumption is correct: I was excluding "Game started!" or "Game has ended"...

I was referring to the kind of events you mentioned.

Arnaud
