### ISSUE TITLE
Chat rooms not appearing under refresh

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#592]
### Summary

When I log into OGS and click Chat, I don't see my group chats on left (even if I'm already in the room) until I refresh the browser.

### Environment

Windows, MSIE or Chrome I think behave the same?

### Steps To Reproduce:

Log in, click Chat, I only see: http://puu.sh/zMvgN/77bea9a274.png

I click refresh, then I see: http://puu.sh/zMviP/b51195ad02.png

**Comment by anoek** [comment]
Yeah this one bugs me a lot

**Comment by Bloodyaugust** [comment]
While trying to repro, it is worth noting that this only occurs if going to the chat page from another page. If you sign in/out while still on the chat page, this bug does not occur.
