### ISSUE TITLE
Implementing github content integration in some pages

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#593]
### Summary

It's a feature responding to a very specific need which may be not only mine.
It would not be the great feature but well, I file an issue just in case.

I would like to manage my profile content in a github markdown file which one could be dynamic based on rules which would be my own.
It would be nice to authorize non-cascaded iframes through <github> tags or alike.
I'm aware the use case is marginal but well, it's fun to make something less "plain" in the only page an user is master on. We could imagine an user put his personal statistics of his choice or to display dynamically the ranks (s)he has on another go server, or the last posts (s)he made on some GO forums, or the last bought go books, or some extract from the EGD (for European players :) ), etc..

Of course, this could be extended to some other areas like for example the description of a group.
One admin (of the group) could make the description change by the means of OGS API calls retrieving for example the last tournament top players or statistics on the group members. We can imagine anything to make the group more attractive and the description more "lively".

### Environment

any

### Steps To Reproduce:

any

### Additional Information:

Ask if needed

**Comment by arnaudgo** [comment]
it got stripped off but I suggested github tags that in certain contexts would be converted into iframes with the github url ( maybe given only in a form user:repository:file ) within .

Arnaud

**Comment by anoek** [comment]
Could have totally done this two months ago, but *somebody* went ahead and pointed out https://github.com/online-go/online-go.com/issues/551 was a problem ;P

I'm certainly open to having more lively and interesting profile pages, I guess it's not clear to me a way to generically / safely proceed, so more discussion needed I guess?

**Comment by arnaudgo** [comment]
Haha !! That's mean !! 

My suggestion is to implement one (but why not more) custom OGS tag (e.g. "github" with angle operators around &lt; &gt; ) that would be interpreted in certain pages and translated into an iframe.

Which is a bit different of permitting an user to directly use html iframe tag :) 

i assume we cannot insert iframes within a github markdown file but I haven't checked it and anyway it could be the case in the future. So maybe restricting the use of inner iframes at the top-level i.e. OGS content.

Eventuallyj it could have more than "github" tag but well this is a first idea that came to my mind.

Arnaud

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
