### ISSUE TITLE
[BUG] Player win/loss data wrong when filtered in the top table

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#597]
### Summary

On the profile page, when you filter the results by the game-type, the data is not correct.

### Steps To Reproduce:

1. Go to the profile of Kosh. [5k]
2. Click on the 9x9 correspondence rating in the ratings breakdown table
3. See that there are no wins vs stronger opponents appearing in the bar graph or pie chart.
4. Mouse over the 20 March point
5. See that 2 wins vs weaker opponents are report.

Actually, there were two games vs stronger opponents on that day.

This is correctly returned with no game-type filter applied

**Comment by anoek** [comment]
Realized what we were seeing, while Sdaharu's overall rank is 5d, the 9x9 corr. rating at the time of that match was less than Kosh's 9x9 corr. rating, hence the result.

**Comment by GreenAsJade** [comment]
Awesome detective work, sorry I didn't pick that up!
