### ISSUE TITLE
3D boards, stones and bowls theme

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#598]
### Summary

It would ne nice to have a theme with 3D boards, srones and bowls :-)

Using WebGL or whatever technology.

### Environment

 any

### Steps To Reproduce:

n/a

### Additional Information:

Ask if needed.

Arnaud

**Comment by anoek** [comment]
I think we'll probably stick to 2d on this site

**Comment by apetresc** [comment]
Worth noting that if you really want to play on OGS with a 3D interface, [Ancient Go](https://store.steampowered.com/app/468160/Ancient_Go/) is a client for OGS that does exactly that.
