### ISSUE TITLE
Floating arrow to go to the top of the page

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#599]
### Summary

It would be nice to have a floating object (could be an arrow) that would lead to an internal anchor set on the top of the page.
So, there's no need to scroll up even if Home or PageUp would already do the job.
If that link can work on mobile or tablet, it would be great.

### Environment

 any

### Steps To Reproduce:

n/a

### Additional Information:

ask if needed.

Arnaud

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
