### ISSUE TITLE
If you leave a group, you should drop out from its ladders automatically

### ISSUE THREAD

**Issue by mlopezviedma** [online-go/online-go.com#61]
### Summary

If you are not a member of a group anymore, whether because you chose so or because an admin kicked you, the server should automatically drop you out from all the group ladders you are in.

### Environment

 * Operating system: any
 * Browser: any

### Steps To Reproduce:

1. Join some group
2. Join some ladder from that group
3. Leave the group
4. See that you are still in the ladder you joined

**Comment by anoek** [comment]
I'm going to close this as a "wont fix", it doesn't seem to be a problem very often practically speaking, and the current behavior is nice in the sense that if people get booted or leave, then rejoin a group, it doesn't trash their current position in the ladder. If someone leaves for good, and it's a problem that they have chosen to remain in a group ladder, we can always boot them.
