### ISSUE TITLE
editing quick chat entries sometimes adds <br>

### ISSUE THREAD

**Issue by Adam314159** [online-go/online-go.com#613]
### Summary

Pressing enter after a space when editing quick chat entries adds <br> tag

### Environment

 * Operating system: win 8 pro
 * Browser: mozzila FF
 * Browser Version: 59.0.2 (64 bit)

### Steps To Reproduce:

1. Go to ...any game page
2. Click ... the arrow of quick chat entries, press edit, edit something, then press space and enter
3. See that <br> tag is added, but the editing is ended, so the tag can surve no purpose

### Additional Information:

Really minor, but it was brought up on forums. 
https://forums.online-go.com/t/edited-quick-chat-options-have-br-when-saved/16337

**Comment by stephancurran** [comment]
I've created a PR to fix this. It was using _innerHTML_ rather than _innerText_ to get the message, so spaces were converted to `&nbsp;`.
