### ISSUE TITLE
# of viewers on the popup button not always accurate

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#62]
http://puu.sh/uqh6v/c419da25ff.jpg

Consider that screen shot, there's 2 in the lobby but the icon shows 1.

**Comment by anoek** [comment]
I've seen this happen though I'm unsure how to reproduce it, any assistance in figuring that out would be appreciated.

**Comment by BarneyStratford** [comment]
That sounds like an interesting bug. I’ll take it if you like.

Barney.

**Comment by anoek** [comment]
Go for it :)

**Comment by roy7** [comment]
Made a fork game, went into it. someone joined me to test something. Shows it as 1 person there.

http://puu.sh/uJntR/92a87ef357.jpg

He leaves and rejoins, number says 1 the whole time. I press F5, and then it says 2.

**Comment by BarneyStratford** [comment]
I’m seeing the bug too, all too frequently, but never on my dev server. I’m still working on it. I’ll post a fix as soon as I have one, but this is proving tricky. It is definitely not an exception from within the asynchronous code, but looks instead like componentDidMount isn’t even being called. As soon as I call it myself everything’s fine.

Barney.

**Comment by anoek** [comment]
Should be now fixed with https://github.com/online-go/online-go.com/pull/181 thanks to @BarneyStratford :)
