### ISSUE TITLE
Variation viewing can get corrupted

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#630]
### Summary

Sometimes when you are looking at multiple variations in the chat history, the displayed plays on the board can change based on what other variations you have highlighted over.

### Environment

 * Operating system:  Windows 10
 * Browser: Chrome
 * Browser Version:

### Steps To Reproduce:

Go to game https://online-go.com/game/12385967

Point at the variation for move #12. You'll see this:

http://puu.sh/zYQJL/3400fd5b09.jpg

Look where moves 1 2 and 3 are at. Now move mouse away so board is clear, then point at the variation for move #10. Then move mouse away, and point at move #12 again. Now you'll see this:

http://puu.sh/zYQKp/3c10b48694.jpg

Notice there are two move #1 and two move #2 both on the board at the same time now for this variation.

**Comment by GreenAsJade** [comment]
Unfortunately the game you've pointed at is Private, so we can't see what you're describing.

**Comment by roy7** [comment]
Doh. Try this one.

https://online-go.com/game/12393047

Mouseover variation for move 87, then move 85, then back to move 87.

**Comment by GreenAsJade** [comment]
I see it.

**Comment by roy7** [comment]
Just a note this is still lingering around. ;)

**Comment by anoek** [comment]
Bleh, indeed..

**Comment by anoek** [comment]
OK @roy7 I think this is fixed up. I don't think I broke anything along the way.. let me know if you notice anything strange :)

**Comment by roy7** [comment]
Oooo thanks!! I'll be sure to report if I can make it break again. ;)
