### ISSUE TITLE
Review mode has extra buttons

### ISSUE THREAD

**Issue by Alpha3031** [online-go/online-go.com#632]
### Summary

Review mode has extra buttons (Pass, Back to Game) that behave unexpectedly.

### Environment

 * Operating system: OpenSUSE Tumbleweed, Android
 * Browser: Chromium, Firefox, Konqueror
 * Browser Version: 65.0.3325.181-1.2, 59.0.2-2.3, 17.12.3-1.1

### Steps To Reproduce:

1. Go to any review page.
2. You should see three buttons, two green (Back to Game) and one blue (Pass).
3. Clicking on either pass button works normally, however:
4. Clicking on back to game removes the two green buttons, and the blue button will no longer work.
5. After a while, the page will refresh and the two green buttons will return.

### Additional Information:
![screenshot_20180409_204744](https://user-images.githubusercontent.com/6917205/38498565-711786a2-3c37-11e8-845e-d4fa7f583869.png)

**Comment by GreenAsJade** [comment]
Yeah, I see it.  I get it too.

It's a result of the recent change in placement of the buttons in the other modes - overlooked this aspect of things.

I'll try to fix ASAP.

**Comment by GreenAsJade** [comment]
@Alpha3031 Thanks for reporting, should be fixed now.
