### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by ShAlexanderGo** [online-go/online-go.com#634]
### Summary

In review move comment in "Move comments..." field doesn't change if you jump to different move by clicking on chat message. It may confuse people.

### Environment

Windows 10, Opera 52.0.2871.40, but it shouldn't matter.

### Steps To Reproduce:

1. Go to review (that you cannot edit) here: https://online-go.com/review/310224 (the game is on 0th move and there's "0th move" comment on it)
2. In the chat click "move 0+120".
3. Now comment still says "0th move" even though the game jumped to a different state.

### Additional Information:

https://imgur.com/miIy54J

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
