### ISSUE TITLE
Add Sign-Out Button to Signed-In Dropdown

### ISSUE THREAD

**Issue by Bloodyaugust** [online-go/online-go.com#638]
### Summary

The design language around signing out is confusing: Sign in is in the top-right, but sign-out is nowhere to be found in the user drop-down that replaces it. Instead, you must open the left-hand menu. This is un-intuitive.

**Comment by Bloodyaugust** [comment]
Should have an `enhancement` label.

**Comment by GreenAsJade** [comment]
Totally agree!  Have often thought the same!

**Comment by anoek** [comment]
Subtle in line is probably good. I had originally tried to have the logout button there, but I could never make it look good with everything else that was there. I was attempting to put the logout, settings, and profile links in there together as those are all pretty common things to have under that style of profile image drop down list, but with the notifications and quick theme settings, I couldn't figure it out. FTR I'm open to modifying how the theme settings stuff looks and works, perhaps even by moving the board/stone settings out to the settings page (I have heard some good feedback about having the light/dark theme stuff right there, but I'm not so sure people twiddle the board/stone settings all that often after they are happy with one). Notification list tweaks are fine too, though I think that functionality should probably stay there.

Anyways, if I knew the right answer I'd have done it :) good luck!

**Comment by anoek** [comment]
Closing since there's been no momentum on this for awhile.
