### ISSUE TITLE
tab title indicates of new messages of blocked users

### ISSUE THREAD

**Issue by Fuseques** [online-go/online-go.com#647]
### Summary

when a chat tab is open in the browser but not currently focused, whenever there's a new message, the tab title turns into "(1) Chat", or "(n) Chat" in general, signaling you that there is new content in chat. problem is - it appears to be true even when someone you've blocked posts a message. this creates a very annoying situation in which you click the tab seeking the new content, but there is none.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
