### ISSUE TITLE
Play tab shows games I can't play even when filter is turned on.

### ISSUE THREAD

**Issue by neoliminal** [online-go/online-go.com#648]
### Summary

The Play tab should show games I can actually play. However it is shows me games I can't play and when I click on that it gives an error message.

### Environment

 * Operating system: MacOS
 * Browser: Chrome
 * Browser Version: Current

### Steps To Reproduce:

1. Go to https://online-go.com/play
2. Check that filter "show all challenges" is not set. Click game that is not accessible because of level limits?
3. See that you can't play the game. 

### Additional Information:

I don't a screen shoot, but the error said I couldn't play the challenge because I was too high level... even though the I was actually lower level than the player offering the game.

**Comment by neoliminal** [comment]
![screen shot 2018-04-30 at 10 13 20 am](https://user-images.githubusercontent.com/30296951/39437584-88feabe2-4c5e-11e8-9748-6325344a6e9d.png)
Here is the error message, it's for a game I can easily be with range for.

**Comment by neoliminal** [comment]
![screen shot 2018-04-30 at 10 15 06 am](https://user-images.githubusercontent.com/30296951/39437641-ac90bfe6-4c5e-11e8-83be-8764b19e6bf2.png)

This is the listing, I click on the bottom one.

**Comment by GreenAsJade** [comment]
Fixed by #649

**Comment by anoek** [comment]
Closing to track #649
