### ISSUE TITLE
Back-end rejects game acceptance when player rank is equal to max

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#649]
### Summary

If the player's rank is equal (exactly equal) to the max specified for a custom game, the back-end rejects it after the player hits "Accept"

### Steps To Reproduce:

https://forums.online-go.com/t/very-annoying-bug-where-i-cant-play-listed-games/16747?u=greenasjade

### Other information:

The acceptance gets all the way to here, in GameAcceptModal:

        post("challenges/%%/accept", this.props.challenge.challenge_id, {})
        .then(() => {
            swal.close();
            this.close();
            this.props.onAccept(this.props.challenge);
        })
        .catch((err) => {
            swal.close();
            errorAlerter(err);
        });
    }}}

The error reported to the user comes from the catch().

(Which explained the mystery of why I couldn't grep the error message to find where it was coming from!)

**Comment by GreenAsJade** [comment]
Hah - I didn't realise the OP had posted this as #648 :)

This report is more specific though :)

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
