### ISSUE TITLE
Compensation stone error in Chinese rules?

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#651]
While toying around with how handicap works with custom komi, I realized when black gets 1 handicap stone white is getting 2 compensation instead of 1. My test game was:

https://online-go.com/game/12761515

Per the rules from https://online-go.com/docs/go-rules-comparison-matrix "White receives an additional point of compensation for each black Handicap stone."

**Comment by Adam314159** [comment]
As it is now, white recieves an extra point for HC under Chinese rules, even without actually recieving a HC stone (only diminished komi). I think this is not correct as it creates needless differences between Area and Territory counting while also being super confusing by reducing komi and immediately giving extra point back.

example game:
https://online-go.com/game/18284287

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
