### ISSUE TITLE
Add score estimator to game review

### ISSUE THREAD

**Issue by autarch** [online-go/online-go.com#653]
Adding the score estimator to the game review tool would be really useful. I often will play out a variation of a game through the endgame and I'd like to be able to use the score estimator to give me a count. As it stands I have to manually count, which is a pain.

**Comment by IFOV37** [comment]
I second this.  On more than one occasion I tried using score estimator in reviews, only to find out that you can't.  Seems like something that should already be a feature.

**Comment by DaWinicko** [comment]
This is definitely something I would agree with. I don't think anyone is against counting themselves since that is an integral part of the game but with slight variations of force moves or path changes it would be beneficial to have the ability to have a constant score editor to update that.
