### ISSUE TITLE
Uploading sgfs with missing PB, PW

### ISSUE THREAD

**Issue by ShAlexanderGo** [online-go/online-go.com#658]
### Summary

Can't view sgf in library if players' names are missing (PB,PW)

### Environment

 * Operating system: Windows 10
 * Browser: Opera
 * Browser Version: 52.0.2871.99
But it shouldn't matter

### Steps To Reproduce:

1. Go to the library
2. Upload sgf without players' names, for example attached "this is one sgf.sgf"
3. Try to view this sgf from library
4. Get an error

### Additional Information:

Example SGF: https://drive.google.com/file/d/1_YINhc8U0WIalEvRF_vwJOEDkJiM3h0n/view?usp=sharing
Link to my upload: https://online-go.com/game/13048324
Picture: ![bug](https://user-images.githubusercontent.com/2367259/40621434-5efd5cc8-62a5-11e8-88f9-a70ae2012b6f.png)

Update: looks like players names are filled automatically in general data, but not in "gamedata": https://online-go.com/api/v1/games/13048324

**Comment by anoek** [comment]
This seems to have been fixed at some point, it's working for me now at any rate!
