### ISSUE TITLE
Bug: rank not showing

### ISSUE THREAD

**Issue by BastiaanBekooij** [online-go/online-go.com#659]
### Summary

Rank does not display in rank graph. This is only an issue for me. I asked another player and they didn't have this problem.
The issue occurs on any players page for me.
![image](https://user-images.githubusercontent.com/31536320/40627217-fa94f782-62bd-11e8-985d-a447877fbd83.png)

### Environment

 * Operating system: windows
 * Browser: chrome
 * Browser Version: ?

### Steps To Reproduce:

1. go to a random user
2. look at their rank graph
3. instead of a rank see "{[rank}}" and "{[rank deviation}}"

### Additional Information:

Personally I think it's because of the [ instead of { . Might be a translation issue (I'm Dutch)
![image](https://user-images.githubusercontent.com/31536320/40627293-735c610a-62be-11e8-908f-b6c3baa9f294.png)

**Comment by anoek** [comment]
This looks like it was fixed at some point. And yeah, that's a translation bug.
