### ISSUE TITLE
Correspondence game missing from game stats and possibly omitted from rating calculation 

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#660]
### Summary

My OGS username is alemitrani.  I noticed that in the "correspondence" category on my game stats page it says "0 wins against stronger opponents", and this is incorrect. My rank is about 10k and I won a ranked correspondence game against an opponent who was 4k quite recently - Tatesin92.  It called my attention at the time that this win didn't seem to affect my rating at all.  Was it disregarded, and if so, why?  

### Environment

 * Operating system: Android 6.01
 * Browser: Chrome
 * Browser Version: 66.0.3359.158

### Steps To Reproduce:

1. Go to https://online-go.com/player/322830/
2. Click correspondence 19 x 19 cell on rating table
3. See that it says "0 wins against stronger opponents", which is incorrect (see below).

### Additional Information:

alemitrani vs. Tatesin92: https://online-go.com/game/12692522

Please let me know if you need any further information.

**Comment by anoek** [comment]
So the stonger/weaker per category  uses the category score, not your overall rank. Her 19x19 correspondence rating was stronger than yours when that game was played, which is why it's recorded as you see it. Hope that clears things up, cheers!
