### ISSUE TITLE
Not receiving pm email notifications ?

### ISSUE THREAD

**Issue by lemonsqueeze** [online-go/online-go.com#661]
Hi,
Got pm'ed a few days ago but didn't receive email notification although i have
"Email me a notification when ... A user sends you a mail message" checked in settings.

Just tried pm'ing from another account but didn't get the email either.
Anyway to find what's going on ? The account is 'minipachi'.
Thanks.

**Comment by anoek** [comment]
PM's have never sent out an email, the "Notifications" that we email are those little indicator notifications you get in the upper right side, they tell you when games have started / ended, tournaments start/end, that sort of thing
