### ISSUE TITLE
(non-simultaneous) McMahon pairing broken

### ISSUE THREAD

**Issue by bergedorfcacher** [online-go/online-go.com#662]
The normal (non-simultaneous) McMahon tournaments use the chosen pairing method across all players instead of within the group of players with the same amount of points. Only if you use strength as pairing method you will get something similar to a McMahon tournament, with the others it's just chaotic. Note that simultaneous McMahon tournaments behave entirely differently in this respect - and entirely reasonable. For them player are put into groups according to the points they have and the pairing method chosen is only used as a secondary criterion (as it should be).

For an example look at this tournament: https://online-go.com/tournament/31547

Here the first pairing is: hammer123 (9+d, 0 points) - mr.kowal (17k, -25 points)

There are many players available with -1 to -24 points between them.

This should not be possible in a McMahon format.

**Comment by anoek** [comment]
The pairing method in that tournament was set to random, so chaos is somewhat expected ;) Try other pairing methods for less chaotic behavior.

**Comment by bergedorfcacher** [comment]
If this is intended behaviour (which makes no sense imo), then why does simultaneos McMahon behave differently? In simultaneos McMahon the randoness is applied WITHIN the group of players with the same amount of points, as it  should be in  McMahon tournament. But if the pairing method should really be applies across all players, then it should be 'fixed' in simultaneous McMahon too.

Also: If I want a real McMahon tournament, which pairing method should be used? As far as I know you can pick between stride, strength, slaughter and random. None of these methods pair according to points.

**Comment by anoek** [comment]
Hmm, matburt might be the one to better answer those questions, he's the tournament mastermind :)
