### ISSUE TITLE
iOS safari board taps cause whole board to blink

### ISSUE THREAD

**Issue by blamarche** [online-go/online-go.com#664]
### Summary

Using an iOS device, open a game or enter analysis mode and play a move. The whole board should briefly flash. Other links and interactive items on OGS do not flash when tapped, so it seems they have the proper style set, but not the board.

### Environment

 * Operating system: iOS 9, 10, 11
 * Browser: Safari
 * Browser Version: ?

### Steps To Reproduce:

Using an iOS device, open a game or enter analysis mode and play a move. The whole board should briefly flash.

### Additional Information:

It seems these two css properties may be useful:

```
-webkit-backface-visibility:  hidden;
-webkit-tap-highlight-color:  transparent;
```

**Comment by blamarche** [comment]
Will this be addressed?

**Comment by anoek** [comment]
Thanks for the reminder and the fix. Done, I'll push it up live later today.

**Comment by blamarche** [comment]
Awesome, its minor in isolation but a big QoL improvement for iOS users!
