### ISSUE TITLE
Board details are missing in Chrome for many window sizes

### ISSUE THREAD

**Issue by jonzingale** [online-go/online-go.com#667]
### Summary

Board  lines and stones disappear for all but small screen size
in Chrome.

### Environment

 * Operating system: Mac OS
 * Browser: Chrome
 * Browser Version: Version 67.0.3396.87 (Official Build) (64-bit)

### Steps To Reproduce:

1. Go to ... Game
3. See that board may be blank
 

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*
![screen shot 2018-06-21 at 12 12 11 pm](https://user-images.githubusercontent.com/5322278/41737469-a1cb5ed8-754c-11e8-9d0c-c036e1eecdc3.png)

**Comment by apetresc** [comment]
I'm curious if this is related to a similar issue I've seen in Chromium. Can you try disabling GPU hardware acceleration, restarting Chrome, and see if you can reproduce this? (I know it's not a permanent fix, it's just helpful for diagnosis)

**Comment by jonzingale** [comment]
Adrian,

I am sorry to report that turning off the GPU hardware acceleration
and restarting Chrome did not reproduce the error. I will let you know
if I see it again.

Jon

**Comment by jonzingale** [comment]
thanks for getting back. again, i will let you know if i witness this in
any other browser.
