### ISSUE TITLE
Game fork, custom komi

### ISSUE THREAD

**Issue by ShAlexanderGo** [online-go/online-go.com#668]
### Summary

Custom komi resets to 6.5 when forking a game from demo board.

### Environment

 * Operating system: Windows 10
 * Browser: Opera
 * Browser Version: 53.0.2907.99

### Steps To Reproduce:

1. Make demo board.
2. Fork it and challenge a player with custom komi different from 6.5 (Japanese rules).
3. When the game starts komi is set to 6.5.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
