### ISSUE TITLE
Scoring status in reviews

### ISSUE THREAD

**Issue by mlopezviedma** [online-go/online-go.com#67]
### Summary

In some cases reviews get stuck with blue squares on the board (like dame points) and the reviewer **cannot** add branches at all.

### Environment

 * Operating system: Any
 * Browser: Any

### Steps To Reproduce:

Unknown

### Additional Information:

Example: https://online-go.com/review/229516

**Comment by anoek** [comment]
Is this an isolated case? If so we need browser info at the least to try to reproduce.

**Comment by mlopezviedma** [comment]
I suspect it happens whenever you start a review at scoring phase. I'll confirm this on beta.

**Comment by mlopezviedma** [comment]
Been able to reproduce it on both Opera and Chromium (Linux x86_64). It doesn't depend on the browser, it seems. Looks like if you start a review on scoring phase and the board had dame intersections at any moment, reviews are stuck.

See this game's reviews: https://beta.online-go.com/game/2512
