### ISSUE TITLE
Facilitation of score-disputes

### ISSUE THREAD

**Issue by sousys** [online-go/online-go.com#673]
### Summary

A simple and efficient way for players to play out any unresolved situations without affecting final score. 

When two players dont agree on a seki or the state of a group (live or dead), it should be possible for them to continue to play it out until both players agree, but it should then revert to the boardposition at which point the dispute started (end of game). 

From what i hear, this is how disputes are handled IRL tournament games. 

This "mode" would probably be initiated thru some sort of handshake; "Your opponent wants to enter dispute-analysis mode. Do you accept?" or some such.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
