### ISSUE TITLE
Problem with monthly payment via paypal

### ISSUE THREAD

**Issue by simonseyock** [online-go/online-go.com#675]
### Summary

I can't make a monthly payment with paypal. I don't know if this problem is really on the side of ogs, but normally I am able to make paypal payments on any other site (also monthly ones).

### Environment

I tried it about 6 times on 2 consecutive days with firefox and chrome.

### Steps To Reproduce:

Choose support ogs, EUR as currency and paypal as payment.

Paypal asks for password, let's me confirm the payment and then redirects to a page saying: 

> Die letzte Aktion konnte leider nicht abgeschlossen werden.
>
> Wenn Sie einen Einkauf tätigen oder eine Zahlung senden wollten, prüfen Sie in ca. 30 Minuten Ihr PayPal-Konto und Ihren E-Mail-Posteingang auf Erhalt einer Transaktionsbestätigung.
>
> Wenn Sie von einer anderen Website auf diese Seite gelangt sind, kehren Sie bitte zu dieser Website zurück (verwenden Sie dazu nicht die Browser-Schaltfläche "Zurück"), und starten Sie die Aktion erneut.
>
> Wenn Sie von der PayPal-Website auf diese Seite gelangt sind, klicken Sie oben links auf das PayPal-Logo, um zur Startseite zurückzukehren und die Aktion erneut zu starten. Ggf. müssen Sie sich erneut einloggen.

Rough translation: The last action could not be completed. Please check your email account in 30 minutes for an transaction confirmation.

I never received an email, and the transaction does not show up in my paypal overview nor in my bank account.

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
Hmm, this unfortunately isn't the first time we've had issues with the German Paypal system, not sure what it is. Unfortunately I don't think there's a whole lot we can do on our side about this... on the up side, they seem to resolve their problems after a little bit :)
