### ISSUE TITLE
Handicap sometimes get set to None in Tournaments with Handicap Auto

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#676]
### Summary

I'm participating in a **double elimination tournament** where Handicap is set to Auto.
In 1 of 5 game the Handicap is None despite a rank difference of 10k. The other games got created with handicap. 

The weaker player 14k got white, the stronger 4k got black.

### Additional Information:

Forum Post (for reference): [There is no handicap stones](https://forums.online-go.com/t/there-is-no-handicap-stones/17687)
Tournament: [Great Dragon Of Fire 2018](https://online-go.com/tournament/39104)
![screenshot: tournament settings](https://user-images.githubusercontent.com/4864182/43449005-ece78736-949e-11e8-9a53-fe71b4ffda4f.png)
Game: [Tournament Game: Great Dragon Of Fire 2018 (39104) R:1 (flovo vs 🌀🍁oopsImStoned🍁🌀)](https://online-go.com/game/view/13811989)
![screenshot: game settings](https://user-images.githubusercontent.com/4864182/43449225-6b3044f2-949f-11e8-995b-5b8743932533.png)

I searched the Forum for similar problems (only the last year). This is maybe related (I cannot check since it is a private Tournament): 

- Forum Post: [Wrong Round Robin handicap](https://forums.online-go.com/t/wrong-round-robin-handicap/15476), Tournament [Winter 2018 Lviv Tournament - Middle](https://online-go.co/tournament/33902)

I omitted the posts about McMahon tournaments, since those handle Handicap in another way.

**Comment by anoek** [comment]
Found the root of the issue, long story short we were using some old rating information in the tournament code. Should be all better now for future games, sorry about that!
