### ISSUE TITLE
Account creation form should implement double-check input for password

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#677]
### Summary

I don't know what is the correct way to express my idea in English which is not my mother tongue..

The current form for account creation is error-prone for the password selection. There is no safety guard ensuring what the user types is what he wants to set as a password.

A double input plus a check if input passwords match would help.

### Environment
any
 * Operating system:  any
 * Browser: any

Arnaud
 * Browser Version:

### Steps To Reproduce:

1. Go to ...
2. Click ...
3. See that X wrong 

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by kevincoleman** [comment]
I think the “Forgot password” feature should be enough to cover this edge case. If anything, we should require users to either type their email address twice or verify their email before first login—but since a mistyping of your email address just creates an account you won’t use, you can still create the account you will use.

I see the intent of your request, @arnaudgo, but I think we’re currently at the optimal solution.

**Comment by benjaminpjones** [comment]
"Confirm password" can reduce conversion rates: https://uxmovement.com/forms/why-the-confirm-password-field-must-die/

One thing the article suggests is unmasking passwords is key (i.e. that little eye you can click on to "show password").  @arnaudgo would that feature answer your issues with the current login process?

**Comment by BHydden** [comment]
> unmasking passwords is key (i.e. that little eye you can click on to "show password")

As I understand it, this poses a rather substantial security floor, as it changes the text field from a secured form to a normal one, and this can render it vulnerable to any scrapers that may or may not intercepting.

**Comment by benjaminpjones** [comment]
Yes, implementation would need to be handled with care.  However, the ubiquity of the "show password" option indicates to me, at least instinctively, that there is a way to do this without substantially impacting security.

Consensus (based on briefly browsing stackexchange, links below) seems to be that anything that can get your password when unmasked can probably get your password masked. Also, it's opt in, so still shouldn't be a problem for the security conscious.

https://webmasters.stackexchange.com/questions/100103/is-a-show-password-option-on-login-form-safe
https://security.stackexchange.com/questions/47557/why-is-there-a-show-password-functionality-in-some-login-forms
https://security.stackexchange.com/questions/40327/security-behind-the-windows-8-eye
