### ISSUE TITLE
Empty boards under Konqueror

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#678]
### Summary

Boards are empty

### Environment

 * Operating system:  GNU/Linux
 lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (buster)
Release:	testing
Codename:	buster
 * Browser: Konqueror 
 * Browser Version: 5.0.97
KDE Frameworks 5.45.0
Qt 5.10.1 (built against 5.10.1)

### Steps To Reproduce:
Ask if needed

### Additional Information:
![konqueror_empty_board](https://user-images.githubusercontent.com/26174230/43679495-3723e846-9826-11e8-816e-c3329a9e6aea.png)

Arnaud

**Comment by apetresc** [comment]
This is almost certainly caused by this: https://bugreports.qt.io/browse/QTBUG-65314

Try the workaround described at the end of that thread.
