### ISSUE TITLE
Critical issue: no commit in branch devel since the last 4 weeks

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#680]
### Summary

No commit has been made in the branch devel of th repository online-go/online-go.com since the last 4 weeks.

### Environment

any

### Steps To Reproduce:

$ git remote -v
origin	https://github.com/online-go/online-go.com.git (fetch)
origin	https://github.com/online-go/online-go.com.git (push)
$ git status
On branch devel
Your branch is up to date with 'origin/devel'.

nothing to commit, working tree clean
$ git log --since="4.weeks"|wc -l
0

### Additional Information:

Ask if needed

Arnaud :-) 

cc @anoek

**Comment by GreenAsJade** [comment]
@arnaudgo  Note that this doesn't _necessarily_ mean that nothing is happening, since you are only looking at the client side code.

**Comment by arnaudgo** [comment]
Hello,

Haha @GreenAsJade your remark is smart and I didn't assume nothing was happening. I only meant to make a joke ^^ :-) 
But, I am aware of what you pointed out :) 

Arnud

**Comment by anoek** [comment]
Yep yep :) I'll cycle back to the UI in good time!
