### ISSUE TITLE
Games that are annulled due to mass timeout should be marked as annulled

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#682]
### Summary

It's inconsistent and frustrating that we can't see which of our games were annulled due to mass timeout.

https://forums.online-go.com/t/pump-up-the-rank-the-wrong-way-win-by-timeout/17790/7?u=greenasjade

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
