### ISSUE TITLE
“Email address has been used too many times“

### ISSUE THREAD

**Issue by wmayner** [online-go/online-go.com#683]
### Summary

I can't change my email address on the settings page, because a dialog box appears that says “Email address has been used too many times”. What does this mean?

**Comment by Adam314159** [comment]
There is a limit on how many accounts can be linked to one e-mail address. The message means that that particular address you are trying to use is linked to too many accounts. 

For future questions it would be better to use the forums (https://forums.online-go.com/) This page is pretty much reserved for reporting technical bugs, not asking questions :)

**Comment by wmayner** [comment]
This might be a technical bug, because the account that was linked to the email address should have been deleted. It seems that even though it was deleted, the email address that it was associated with is still in the database. So it seems that now that email address is permanently unusable, which doesn't seem like the intended behavior.

**Comment by anoek** [comment]
It looks like there were a couple of accounts with that email address that were unused. I've cleared the email from those accounts, so you should be able to use your email again.

**Comment by wmayner** [comment]
Thank you!
