### ISSUE TITLE
Rank restriction can be set to nonsensical values under some circumstances (min/max reversed)

### ISSUE THREAD

**Issue by Adam314159** [online-go/online-go.com#684]
### Summary

Min/Max restriction can on occasion be set to values where the maximum rank is actually lower than the minimal one. Not sure how it affects the game selection.

### Environment

 * Operating system: Win10
 * Browser: Chrome 
 * Browser Version: 68.0.3440.106 (64bit)

### Steps To Reproduce:

Not perfectly sure about all the circumstances but the values sometimes seem to default to an impossible selection, or can be set so, without triggering the check.

### Additional Information:

See the gif and the thread at:
https://forums.online-go.com/t/beginners-min-max-ranking-confusion/17953/6

**Comment by anoek** [comment]
I think this has been fixed somewhere along the way? I am unable to reproduce it at anyrate.
