### ISSUE TITLE
ranked game not annulled after 1 move played

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#686]
### Summary

If you cancel a game after black placed the 1st stone, the game is not annulled.

### Steps To Reproduce:

1. Create a correspondence game. (Fisher 1d12h + 8h up to 2d, no handicap, chines rules)
2. Black places 1 stone
3. Black resign/cancels the game (within a few minutes)

=> Observe that the game is not annulled.

### Additional Information:

This happened to me in at least 3 games:
https://online-go.com/game/14341483
https://online-go.com/game/14178041 (annulled later by moderator)
https://online-go.com/game/14177940 (annulled later by moderator)

Edit: Without handicap, after black played 1 stone, black can resign but not cancel
With handicap (2), black gets the cancel button even after playing both handicap stones.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
