### ISSUE TITLE
Game lost by timeout with 3 seconds left on the timer.

### ISSUE THREAD

**Issue by ladimolnar** [online-go/online-go.com#687]
### Summary

I had one instance when I lost by timeout when the clock (and the audible countdown) indicated that I had 3 seconds left.

### Environment

 * Operating system: Ms Win 10 Pro
 * Browser: Google Chrome
 * Browser Version: 68.0.3440.106 (Official Build) (64-bit)

### Steps To Reproduce:

1. Go to play
2. Start a game against a computer. See the screenshot attached for the configuration I choose.
![gamesettings](https://user-images.githubusercontent.com/12121068/45465526-75c08380-b6ca-11e8-9cb7-4d1b6e5f798f.png)

2. Start playing
3. At some point wait until the count goes to 3 or 2 seconds. 
4. Play your move.

Expected: the game will consider your last move as valid and continue. 
Actual: The game is lost by timeout. 

### Additional Information:

Game: https://online-go.com/game/14379986

**Comment by kobakitty** [comment]
Simple timing has been broken since i started playing on OGS 2014. It has always had a few seconds lag, i think this is pretty widely known bug.

**Comment by anoek** [comment]
Tracking under https://github.com/online-go/online-go.com/issues/669
