### ISSUE TITLE
Undo against bots?

### ISSUE THREAD

**Issue by Wizek** [online-go/online-go.com#688]
Could we undo against (some?) bots?

I think it would help me and many others learn by actually trying out many variations of a game. As in, the bot actually responding to our variations instead of just us imagining what it might respond in an analysis session. I've played some games like this in the Android Go game called "Crazy Stone" and I would like to be able to do the same in OGS as well.

I've tried with Master Mantis (9k), but it usually responds so quickly that I don't get the chance to even click undo.

I've also tried with a higher level bot, RoyalZero (6d), which sometimes takes its time, but even when I click undo it seems that it isn't ever inclined to accept the request.

If there is any problem with this potentially messing up rankings -- I'm not sure if it has that potential or not, but just in case I mention; as in, players winning many games against bots to climb ranks -- I would be perfectly okay with bots only ever accepting undo requests in non-ranked games. This is only for practicing after all.

And as for the bot potentially being too quick, I imagine that the related issue #328 being fixed would solve that problem neatly as well.

Anyone wishing for the same? Is this a realistic feature request? Could it perhaps be as simple as changing Master Mantis' implementation with something like the following pseudo code?

```js
events.listenFor("undoRequest", function (request) {
  if (game.isRanked) {
    // ignore
  } else {
    request.grant();
  }
});
```

I have no idea about the actual architecture yet so please do tell me if it is more involved than that.

I also imagine that it is not only me who would have the benefit of learning from such a feature, but many other players as well, as this has the potential to tighten the feedback loop of learning. As in, being able to see the consequences of actions much more quickly and in a much more controlled environment than having to start new games from scratch each time. So the effect is increased efficiency. I know that this way of learning has helped me immensely with Crazy Stone when I was very new to Go, and I miss it in OGS.

***

And in the meantime, do you think I might have any ways of working around this limitation? I've had a few ideas:

- Fork the game each time I want to undo. This works, and I can re-challenge the bot every time, but it is much more cumbersome than being able to click a single undo button.
- Try downloading the SGF file and load it up with Crazy Stone. I don't know if this would work but maybe it could. It could be a nicer learning experience as undoing is only ever one tap away, but it is even more involved than the above idea to go from one game platform to the other.

Any other ideas?

**Comment by JikkuJose** [comment]
I am quite surprised this isn't there in OGS. Its a pretty great feature to learn and understand our mistakes

**Comment by anoek** [comment]
Yeah it's true, it needs to be added.

**Comment by ncdlek** [comment]
but the game should be unranked
