### ISSUE TITLE
Better label for Score Estimator

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#690]
### Summary

Better label for Score Estimator, to correctly convey what it does and what it should be used for

 

### Additional Information:

As suggested in the forum:

https://forums.online-go.com/t/score-estimator-fix-it-please/18288/9?u=greenasjade

**Comment by GreenAsJade** [comment]
Implemented by #691

**Comment by anoek** [comment]
Closing because I want the score estimator to be better and for the label to be accurate. This is becoming more of a priority I think
