### ISSUE TITLE
Display User Profile Bug On OSX Sierra + Safari

### ISSUE THREAD

**Issue by pelevesque** [online-go/online-go.com#693]
### Summary

When I click on a player's name to see his or her or zer's profile, I guess an error message saying congratulations you have found a bug...

### Environment

 * Operating system: Mac OS Sierra 10.12.1
 * Browser: Safari
 * Browser Version: 10.0.1

### Steps To Reproduce:

1. Try going to see a player's profile.

### Error Message:

Can't find variable: fetch

    in t
    in div
    in div
    in div
    in t
    in t
    in t
    in t
    in div
    in Unknown
    in t

**Comment by forever-maximus** [comment]
Fetch isn't supported in older versions of Safari:

https://caniuse.com/#search=fetch

The easiest way to fix this is to just update your version of Safari. It looks like versions 10.1 and up support Fetch.

**Comment by anoek** [comment]
I added a polyfill for this, so it should be fixed.
