### ISSUE TITLE
Sgf download is missing CA[UTF-8]. Cannot be correctly opened in a different sgf editor

### ISSUE THREAD

**Issue by elsantodel90** [online-go/online-go.com#695]
### Summary

The downloaded sgf files are missing CA[UTF-8]. Encoding seem to be UTF8 in fact, but it is not specified within the sgf file itself as it should be (the "default" according to the spec would be "latin1", which is obviously not appropriate for international user generated texts).

### Environment

 * Operating system: Ubuntu 16.04
 * Browser: Either Chrome, or directly using "curl" passing it the sgf download url

### Steps To Reproduce:

1. Download an sgf file, like https://online-go.com/api/v1/reviews/344433/sgf
2. Open with another editor like cgoban. Unicode characters like Spanish "á é í ó ú ñ" are messed up.
3. Open the sgf with a text editor. It can be manually verified that CA[UTF-8] is not there.

### Additional Information:

For example when downloading
https://online-go.com/api/v1/reviews/344433/sgf

The file actually is UTF-8 encoded, but the encoding is not specified on the file with the CA property as it should. That causes troubles when loading it with some other software. Adding the CA[UTF-8] property fixes this. I imagine that fixing this should be very easy, although it might be a backend change (I do not know if backend directly works with games sgf or only with an internal representation, so that sgf are generated dinamically on request).

OGS forum post: https://forums.online-go.com/t/sgf-download-is-missing-ca-utf-8-cannot-be-correctly-opened-in-a-different-sgf-editor/18539

**Comment by anoek** [comment]
This has been fixed on the backend, it should be live later today.
