### ISSUE TITLE
Tournament Pairing Method Strength doesn't work as expected

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#696]
### Summary

The pairings in a [tournament](https://online-go.com/tournament/41154) with pairing method strength are not between players of equal strength (rank).

The pairings are:
4k-4k, 11k-7k, 13k-10k, 12k-9k, …
instead of 4k-4k, 7k-9k, 10k-11k, 12k-13k, …

Pairing methods Slide and Slaughter might be affected as well. They felt sometimes off as well. 

### Additional Information:

![Full match up](https://user-images.githubusercontent.com/4864182/46789109-446bbf80-cd2b-11e8-86fd-d7b2cb28be73.png)
Screenshot of the pairings. I took it 30 minutes after tournament started (the ranks shouldn't change that much in this short time frame)

https://forums.online-go.com/t/tournament-pairing-method-strength-doesnt-work-as-expected/18553

PS: I'm not sure if you read every bug report on the forum, therefor I repost it here.

**Comment by anoek** [comment]
The strength pairing method considers maximum weight for the whole pairing graph, it uses the blossom algorithm here: https://en.wikipedia.org/wiki/Blossom_algorithm

**Comment by flovo** [comment]
I'm trying to get my head around this.

If I understand it correctly, the Blossom algorithm always finds a matching with as many games as possible. And the weighted version is guaranteed to find the maximum possible matching for which some metric is minimal/maximal as a secondary goal.

For the Strength pairing method I would expect the weights to be the rating difference of the matched players, and the metric we try to minimize the sum over all rating differences for the selected matches.

Using that metric, the matchings in the tournament above could be optimized further, by selecting the pairings 11k-13k and 7k-10k instead of 11k-7k and 13k-10k (rank difference 2+3=5 instead of 4+3=7, using rating this should be better as well). Since this change doesn't affect the other pairings and is locally better, I would expect that the overall result would be better as well.
(It's the first round of the tournament, so all pairings should be possible)
