### ISSUE TITLE
Initial McMahon points assignment looks wrong

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#697]
### Summary

In a tournament with McMahon bars 9k-3k, the initial scores looked wrong. 
A 7k player started with -2 points while another started with -6 points.
There was also a 2k player which started with -4 points although 2k is above the McMahon bars. 

This happened not only in this tournament, but in this case it was rather obvious. 

### Additional Information:

![image](https://user-images.githubusercontent.com/4864182/46792478-fc509b00-cd32-11e8-8903-474b2c7dfaba.png)
![image](https://user-images.githubusercontent.com/4864182/46792440-e511ad80-cd32-11e8-9bfd-cddeef776db3.png)
![image](https://user-images.githubusercontent.com/4864182/46792522-18ecd300-cd33-11e8-9c7b-bc4e7a031963.png)
(Screenshots taken within some hours after tournament started)

https://forums.online-go.com/t/how-are-initial-mcmahon-scores-calculated-probably-a-bug/18131

**Comment by pdg137** [comment]
Happy 2022! Here are some more examples of this issue from the [Fast Correspondence Title Tournament 2022](https://online-go.com/tournament/82076) that started yesterday.  It's a 15k-5k tournament so I expect 6k to be at -1, 7k -2, etc.

![image](https://user-images.githubusercontent.com/466760/147854599-b7b0e98c-bfa7-4009-aaff-3fcc82088c8a.png)

Look at [the 11k player](https://online-go.com/player/1051695/Narbalek) getting a 0. They have an unusual rank history, with the last 100+ games being timeouts or annulled.

![image](https://user-images.githubusercontent.com/466760/147854605-cf41d879-1370-4b2b-be9a-28f09021a93e.png)

There's Feijoa at (~6.4k) and Russjass at (~8.7k) both starting with -3.  I'm not sure how these are rounded, but I would have expected -2 and -4 based on displayed rank.

**Comment by lggruspe** [comment]
I suspect the initial McMahon points are computed during registration rather than when the tournament starts. Narbalek used to be higher ranked.

**Comment by pdg137** [comment]
Interesting idea! I don't think it's possible for that to be the explanation, though, since the tournament was created in November. Also, that would be strange since you can change the settings after people have registered!

**Comment by pdg137** [comment]
Some examples from [a tournament](https://online-go.com/tournament/83357)  that started a few minutes ago:

![Screenshot_20220115-110621](https://user-images.githubusercontent.com/466760/149634745-04ab0491-089d-4f8e-a37b-9c5c100c2a1a.png)

![Screenshot_20220115-110936](https://user-images.githubusercontent.com/466760/149634816-cf4201f8-4584-4232-af50-f48d75c1ec92.png)

It's supposed to have 3k and 7k bars.

**Comment by anoek** [comment]
> I suspect the initial McMahon points are computed during registration rather than when the tournament starts. Narbalek used to be higher ranked.

Yep this is exactly what's going on

> Interesting idea! I don't think it's possible for that to be the explanation, though, since the tournament was created in November

Narbalek in specific had a ton of games annulled on Dec 2 for AI use, so it's very likely that their rank was higher than 5k when they signed up for the tournament.


I'm going to look into recomputing those points as the tournament starts, seems like that'd be a lot better.

**Comment by anoek** [comment]
Alrighty this has been fixed, the points will now be computed at tournament start (well, when deployed, which should be later today.. It's on beta if anyone cares)
