### ISSUE TITLE
Go Variant : Hidden Move Go

### ISSUE THREAD

**Issue by sousys** [online-go/online-go.com#701]
### Summary

I think go variants would be a really fun addition to, and draw for, ogs. Besides Rengo, which obviously has been a standing community-request for a while, i would like to pitch Hidden Move Go. 

Pre-game move selection:
- Before the game starts, each player choose 3 points on the board where they want to place hidden stones. 
- if players choose the same spot in selection-phase, both players get to replace those stones 

Gameplay:
- The hidden stones remain hidden until they are revealed during the game, either by blocking a placement on the same spot, or being activated by a capture.

Other than that, the game is played as usual. 

### Additional Information:

- No ranked games allowed
- boardsizes allowed 19x19, 15x15, 13x13?  No 9x9 (3 stones would be to much for that)
- Your own hidden stones should be visible during play, or placement should be marked somehow.
- both players hidden stones should be visible for spectators. thats half the fun, i feel. ( alt. make it a setting in the game creation dialog to allow or disallow spectators to see hidden stones)

Example of gameplay:
https://www.youtube.com/watch?v=Tm6wBpBPQdU

**Comment by ShAlexanderGo** [comment]
Number of hidden stones doesn't have to be 3 and agreed upon before the game.

If players choose the same spot, I suspect it's handled differently, depending on how it was agreed. In games I saw these stones cancel each other out, but players don't know about it. I saw also variants where whoever claimed the spot first during the game, gets that spot. So definitely there's a discussion to be had about specifics of the rules.

And stones can be "revealed" manually (like if you want to know whether your hidden stones was canceled or not).
