### ISSUE TITLE
Filtering options in Games window. 

### ISSUE THREAD

**Issue by sousys** [online-go/online-go.com#702]
### Summary
Expand the ability to filter games in the observe games window
- rank limit, 
- collumn-sorting
- game type
- filter out bot-games

**Comment by kobakitty** [comment]
[_] hide/show bot games
Because so many of us dislike watching games against bots

**Comment by sousys** [comment]
> [_] hide/show bot games
> Because so many of us dislike watching games against bots

thanks. updated text

**Comment by flovo** [comment]
Make it sortable by number of viewers, so we can meet to kibitz.

**Comment by BHydden** [comment]
I brought this up again https://forums.online-go.com/t/observe-games-page-overhaul/24083?u=bhydden

I also added prioritise friends to the top of search option as a project goal.

**Comment by benjaminpjones** [comment]
I think you fixed this one @anoek. Github parser just isn't smart enough for the multi-bug PRs!

**Comment by benjaminpjones** [comment]
[BUMP] This one can be closed (along with #309)

**Comment by BHydden** [comment]
Already added.
