### ISSUE TITLE
Add a link to github somewhere in the main site

### ISSUE THREAD

**Issue by kobakitty** [online-go/online-go.com#705]
### Summary

Currently OGS doesn't have a direct link to github anywhere on the main site, and only way for users to know that this place exists is by either asking it on chat or at the forum.
I suggest to have a direct link to https://github.com/online-go/online-go.com/issues on left side panel under the name "development ideas" 

### Environment

 * Operating system: 
 * Browser:
 * Browser Version:

### Steps To Reproduce:

1. Go to ...
2. Click ...
3. See that X wrong 

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
It's here: https://online-go.com/docs/about :)
