### ISSUE TITLE
Pause game in stone-removal if one side calls for a mod 

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#707]
### Summary

It would help everyone if the action of "calling a moderator" during "stone removal phase" put the game forcibly in "pause".

Note that the moderator would then need a button (which doesn't currently exist) to unpause, obviously.

**Comment by sousys** [comment]
This is a good idea.

**Comment by koshogs** [comment]
You might need to tweak the idea.  There isn't always a Mod online so this proposal might cause problems with live tournaments.

**Comment by GreenAsJade** [comment]
A couple of things here:

- We now have more mods, and from the "mod" side of the fence, it feels like we have 24 hour coverage now.
 - Would you rather have a tourney held up so the correct result can be ensured, or proceed with a bad result due to a stone-removal-phase troll?

The new mods are unanimous that this will be a great improvement: we are already tired of arriving at live games where the victim has given in or been timed out of the stone removal phase and all we can do is annul.

**Comment by GreenAsJade** [comment]
That being said, actually I can see that _live_ tournaments (as you said), might actually be totally problematic if the next round is held up like this .

Do live tournaments have multiple rounds that might get blocked this way?

Maybe the pause-due-to-report-called should itself have a timeout.  Or not apply to live tournament games.   

Or we could just put it in and see if it works or not :)

**Comment by violaineT** [comment]
It's more a problem to have a corrupted tournament result as to have it being hold on the time a moderator solve the issue.

**Comment by GreenAsJade** [comment]
[This topic has come up again](https://forums.online-go.com/t/what-to-do-in-case-of-a-scoring-dispute-title-changed/20019/37).

For the record I think we should put this in and see how it goes.

**Comment by GreenAsJade** [comment]
Conrad raised the point that mods might want to freeze a game at any time, not just scoring phase.

And maybe even not if a report is raised.    

Adding this note for the record: my feeling is that the primary use case is in scoring phase after a report.

During the game, there is no harm if the game proceeds.    In contrast to scoring phase, where a wrong result can get locked in, or the game can be forced back to play inappropriately.

**Comment by sousys** [comment]
this issue becomes more pressing each day i feel. just exclude turneygames?
