### ISSUE TITLE
Glitch when placing stone in Chrome and Firefox

### ISSUE THREAD

**Issue by siulkilulki** [online-go/online-go.com#709]
### Summary
When placing stones really annoying graphical glitch occurs (video attached).

### Environment
I tested on: 
#### 1
* Operating system: Arch Linux
* Browser: Firefox
* Browser Version: 63.0 (64-bit) 
#### 2
* Operating system: Arch Linux
* Browser: Chromium
* Browser Version: Chromium 70.0.3538.77 Arch Linux

I had this also on laptop with GalliumOS on Chrome and with Chrome on Windows.

### Steps To Reproduce:

1. Start new game
2. Place stone

### Additional Information:
Video: https://0x0.st/sIwP.mkv

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
