### ISSUE TITLE
Fischer time settings bug

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#713]
### Summary

At openstudyroom.org we are running a 9x9 tournament, which has been publicised on the OGS forums.  The time settings are Fischer with 3 mins main time + 2 seconds per move with a maximum of 3 mins. The bug is that when a challenge is issued with these settings, the person receiving the challenge receives 3 mins main time + 5 seconds per move and this is what is implemented in the game.  We have tested this with 2 different pairs of players and 4 games and the bug is consistent.  

The other settings are: chinese scoring, komi of 7 for white.   

### Environment

 * Operating system: various.  including Android.
 * Browser: various. including Chrome 
 * Browser Version:

### Steps To Reproduce:

1. Go to game request
2. Issue challenge with settings defined above
3. See that the challenge received is as described above and not what was specified.  

### Additional Information:

I will include in additional comments.

**Comment by alexmitrani** [comment]
browser version
![screenshot_20181119-144729](https://user-images.githubusercontent.com/27974470/48725203-2fc3f680-ec0a-11e8-94a0-451585bece45.png)

**Comment by alexmitrani** [comment]
example of settings
![screenshot_20181119-140834](https://user-images.githubusercontent.com/27974470/48725262-61d55880-ec0a-11e8-9897-00b83f04f5b3.png)

**Comment by alexmitrani** [comment]
links to games with the above settings
https://online-go.com/game/15355167
https://online-go.com/game/15355092
https://online-go.com/game/15351778

**Comment by alexmitrani** [comment]
screenshots of received challenges with the tournament-valid time settings
![screenshot_20181119-145304](https://user-images.githubusercontent.com/27974470/48725426-ecb65300-ec0a-11e8-9a39-39003a0b97ad.png)

**Comment by anoek** [comment]
This has been fixed on the backend
