### ISSUE TITLE
Simple time + weekend pause causes infinite game

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#714]
### Summary

This game had simple time of 5 days per move plus weekend pause.

https://online-go.com/game/view/13625156

It appears that each time the weekend pause hit, the players got their time back, so they never timed out.

At least, that's what one of them said was happening

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
