### ISSUE TITLE
Uploaded SGFs enter "play mode", not "review mode"

### ISSUE THREAD

**Issue by reinerp** [online-go/online-go.com#731]
### Summary

When I upload an SGF to the "SGF library", it uploads in "play mode", but should upload in "review mode". To put it in "review mode", I need to start a review of the same game.

### Steps

1. Do a Review on online-go.com
2. Download the SGF.
3. Upload the SGF to online-go.com's SGF library. Produces this result: https://pasteboard.co/HTJTePb.png, https://online-go.com/game/13754644. Note that the text box that normally holds review comments is missing. As a consequence, the review comments are missing.

What I would like to happen: in step 3, the game should already be in review mode, so that the text box with move comments is visible.

The workaround is to start a review from the newly uploaded game. That produces this result: https://online-go.com/review/363461, https://pasteboard.co/HTJUjmr.png. This result is in "review mode", and so the textbox and the comments are now visible.

**Comment by anoek** [comment]
I can see the logic to this, and i'm not sure why it wasn't like that to begin with.. however at this point I don't think I want to change it as doing so would remove the ability to do ai reviews on the uploaded sgf, which has been of interest to a lot of people.
