### ISSUE TITLE
Add Lord Howe Island flag

### ISSUE THREAD

**Issue by schambers** [online-go/online-go.com#734]
### Summary

Per discussion in forums.online-go.com discussion, this covers adding a flag for Lord Howe Island:

To add a flag: Fork https://github.com/thouis/world-flags-sprite Add you flag, commit to your repository Submit a pull request to thouis Let me know so i can pull it all down and get it into the build smile
and this:

I’d be certainly happy to merge pull requests in for this. To make this happen, add the flag(s) to https://github.com/online-go/world-flags-sprite and then add entries to https://github.com/online-go/online-go.com/blob/devel/src/lib/translate.ts#L99

And finally; What’s this all in aid of ?..Lord Howe Island
![lord_howe_island](https://user-images.githubusercontent.com/31563/51067988-3ef96c00-15dd-11e9-976c-7de0dc87c674.png)

**Comment by koshogs** [comment]
Kindly opened by schambers at my request.  I for one am ready to raise the flag, when available.

There are many comparable examples already in use.  Christmas Island, Cocos (Keeling) Islands and more significantly, Norfolk Island.  To include Norfolk Island and not Lord Howe Island or vise-a-versa is anathema.

Self-governing, Lord Howe Island is quite simply the most beautiful place on Earth (World Heritage Listed) and it seems a shame to not have it represented on OGS.  You simply haven't lived until you've played Go on the Malabar or on the top of Mt. Gower.

**Comment by schambers** [comment]
Pull requests in both repos submitted:

- https://github.com/online-go/online-go.com/pull/735

- https://github.com/online-go/world-flags-sprite/pull/1
