### ISSUE TITLE
Switching "Show x" number of games from a small to large

### ISSUE THREAD

**Issue by schambers** [online-go/online-go.com#739]
### Summary

When you change "Show 8" games at a time to "Show 28" and you're on the last page, it says no games being played until you click previous page

### Environment

 * Operating system: OSX
 * Browser: Chrome
 * Browser Version: n/a

### Steps To Reproduce:

1. Go to Games
2. Click "Show 8" in drop down to get a large number of pages
3. Go to last page. for me it was page 9
4. Choose "Show 28" in drop down
5. Number of pages changes to "9 / 3"
6. Text on page says "no games being played"
7. Click back one page and everything resets to normal

### Additional Information:

This seems just a minor bug. If you switch the dropdown selection for number of games per page, it should recalculate the correct number of pages and return to you the first or last page of the appropriate number for that display size

**Comment by flurmbo** [comment]
Anyone mind if I try working on this issue? And I think it would make the most sense to just always return to the first page of results for the newly selected size

**Comment by schambers** [comment]
Go for it. I filed it but haven't had a chance to dig into it.
