### ISSUE TITLE
UI glitch: score estimator status persists through game switch

### ISSUE THREAD

**Issue by windo** [online-go/online-go.com#741]
### Summary

It is a minor UI glitch, but reporting anyway. When you click on the score estimator on one game and then switch to another game through a notification (that is, not navigating away from game view) then the score estimator result will persist on the new game.

### Environment

 * Operating system: Ubuntu
 * Browser: Chrome
 * Browser Version: 66.0.3359.181

### Steps To Reproduce:

1. Go to a game you are playing
2. Click on score estimator
3. For this step, you need to have an active notification about another game you are playing and click on it
4. Observe score estimator from the previous game showing up on the game you just navigated to

**Comment by windo** [comment]
Hmm, does not seem to reproduce now. Maybe there is an extra condition to triggering this.

**Comment by anoek** [comment]
Ok cool closing for now until we can figure out how to reproduce
