### ISSUE TITLE
Can't create puzzles on FireFox

### ISSUE THREAD

**Issue by jmdingess** [online-go/online-go.com#744]
### Summary

Smurph in the chat brought it to my attention that puzzles are currently down for whatever reason. He and I are both experiencing the same problem and both of us use FireFox. KoBa, another user, mentioned that it was working for them on Google Chrome.

The issue happens when you go into the New Puzzle section of the puzzles tab, pick a collection, put some stones out, enter a description and a title - everything you need to go to the next page. The problem is that hitting the 'Moves' tab at the top or the 'Next' tab at the bottom does not take you to the next page, but instead moves mouse focus/keyboard input to the Title field, regardless of it is filled out or not

### Environment

 * Operating system: Windows 10
 * Browser: Firefox
 * Browser Version: 64.0.2
 * Adblock: uBlock Origin, disabled on OGS

### Steps To Reproduce:

1. Go to https://online-go.com/puzzle/new
2. Fill out details
2. Click "Moves" or "Next"
3. See that it moves your keyboard input to the 'title' section, but does not move you to next page

### Additional Information:

* I was able to upload https://online-go.com/puzzle/14088 two days ago (The 28th) in the same environment without issue
* As I was writing this up, Smurph said it started working for them again, though it still does not for me

**Comment by anoek** [comment]
Interesting.. it seems to be working fine for me as well. How long of a title were you providing? I think there's a four or five character minimum if I recall correctly.

**Comment by jmdingess** [comment]
Well, I feel silly. That was probably it - I never realized there was a character minimum.
