### ISSUE TITLE
Total number of ranked games above pie chart behaves oddly on some user profiles when clicking on different rating categories

### ISSUE THREAD

**Issue by flurmbo** [online-go/online-go.com#749]
### Summary

Oddly, this issue seems to only affect some user profiles. If you're having trouble reproducing it I can dm you a user page that it affects.

### Environment

 * Operating system: Ubuntu
 * Browser: Firefox and Chrome

### Steps To Reproduce:

1) In the gif below, I load an affected user page.
2) Notice above the pie chart it says there are a total of 1222 ranked games in all categories.
3) Click on the first button in the 19x19 row
4) It still says 1222
5) Click on first button in 9x9 and 13x13 rows, shows normal looking totals
6) Click on 19x19 button again, now it says 272.

### Additional Information:

![peek 2019-02-16 21-00](https://user-images.githubusercontent.com/35127144/52907871-31648100-3230-11e9-9f53-ee4bf4be9da9.gif)

**Comment by BHydden** [comment]
I'm not currently able to replicate this, perhaps it was fixed? Does @GreenAsJade know anything about this?

**Comment by flurmbo** [comment]
Hi @BHydden, unfortunately I don't think I wrote down which users' profiles were affected by it (I had only noticed it happening on a couple pages I believe). However I checked all the profiles of players I played in February and was unable to replicated it, so it looks like this might have been fixed.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
