### ISSUE TITLE
Warning message on bot profile for NOT logged in users

### ISSUE THREAD

**Issue by Adam314159** [online-go/online-go.com#750]
### Summary

When accessing a bot profile on NOT logged in account a confusing warning message is displayed.

### Environment

 * Operating system: Win 8 pro
 * Browser: tested on FF  (but probably irrelevant)
 * Browser Version: 65.0.1

### Steps To Reproduce:

1. Log out of OGS or enter private browsing
2. Go to any bot profile (for example: https://online-go.com/player/419331/)
3. A warning message is displayed: “Not allowed to access this game”
4. Otherwise all functions normally as far as I can tell

### Additional Information:

I assummed it is somehow connected with private games, but it seemed to happen regardless of whether there is an ACTIVE private game (but I am not 100% sure). 
raised here: https://forums.online-go.com/t/not-allowed-to-access-this-game-when-viewing-user-page/20370

**Comment by anoek** [comment]
Ah shoot, yeah that's because of private games, not bot specific I don't think. Thanks for the report

**Comment by Adam314159** [comment]
Yeah, sorry :( probably a duplicate, I searched badly
https://github.com/online-go/online-go.com/issues/320
<---

**Comment by anoek** [comment]
Fixed on the server side
