### ISSUE TITLE
An idea about modular UI.

### ISSUE THREAD

**Issue by comntr** [online-go/online-go.com#751]
The OGS UI consists of a few rectangular blocks: user icons, the board, the header, the comments section and so on. These blocks are arranged in a certain way by the devs. The user can't rearrange them later. I'd personally prefer a different layout: the board at the top, the header hidden, comments at the bottom, the user icons hidden or collapsed into small icons that I could click on to expand them. This layout would work better for phones. But others may not like it and want something different. So, the idea is to let the user enter into the "layout changing mode", rearrange the blocks and return to the regular UI mode. Blocks would follow something like the case flex model which to make it intuitive. How does that sound?

**Comment by anoek** [comment]
I'm open to this, are you volunteering or is this a feature request?

**Comment by comntr** [comment]
Let's make this a feature request so I and others can volunteer in spare time. It can be something like a little design doc outlining what and how needs to be done. We can use this issue as this "doc" unless there is a better place for it.

**Comment by anoek** [comment]
I'm ok with leaving it open for a little bit to see if there's anyone willing to take it on, but It's a big feature so if there are no takers then I'll probably just end up closing it.

**Comment by AdamT213** [comment]
I would be willing to work on this, but i would need a better sense of exactly how you propose to change the UI. I also have another request if this does end up going through. I think it would be cool if a user could scale the size of the board, particularly in desktop view. I am used to playing on mobile, and when I do play on desktop, the board is overwhelmingly large and has a non trivial effect on my play.
