### ISSUE TITLE
Some Players Cannot Drop Out of Ladder

### ISSUE THREAD

**Issue by yewang** [online-go/online-go.com#755]
### Summary

Some players have reported being unable to drop out from a ladder. This might be related specifically to the sitewide 19x19 ladder.

### Environment

Problem persists across all platforms, OSes, browsers.

### Steps To Reproduce:

For an affected account:
1. Attempt to drop out from ladder via the "Drop out from ladder" button, and confirm by clicking "Yes" on the pop-up dialog.
2. No observable change appears. Player remains on ladder.

Note: it is unclear what causes a particular account to be affected, while others seem not to be.

### Additional Information:

Related discussion on the forums
https://forums.online-go.com/t/cant-drop-out-from-ladder-19x19/18962
It seems to have affected at least four different users. One case is active, which may give an opportunity to investigate the root cause.

**Comment by anoek** [comment]
This should now be fixed
