### ISSUE TITLE
Security hole. Players may add unfiltered HTML into their profiles.

### ISSUE THREAD

**Issue by neoliminal** [online-go/online-go.com#761]
### Summary

Players may create links to audio, video and other autoplay content using HTML in the description on their profile pages.

example:

&lt;audio controls autoplay&gt;
&lt;source src=&quot;https://www.dropbox.com/s/kkkk22x3kddgl0g/02Track2_64kb.mp3?dl=1&quot; type=&quot;audio/mpeg&quot;&gt;
&lt;/audio&gt;

### Environment

 * Operating system: All
 * Browser: All
 * Browser Version: All

### Steps To Reproduce:

1. Go to description and add a video or audio tag.
2. Click submit
3. See that it plays.

### Additional Information:

https://online-go.com/player/561104/ is currently using this, but I've included the source from their page in case he changes it before you see this.

[OGS.htm.zip](https://github.com/online-go/online-go.com/files/3069217/OGS.htm.zip)

**Comment by anoek** [comment]
We do actually filter: https://github.com/online-go/online-go.com/blob/devel/src/components/Markdown/Markdown.tsx#L36 

We only block script, iframe, and style tags. I think we discussed it awhile ago and were ok with audio / video tags, though at this point i'm wondering why we let the `autoplay` attribute through.

**Comment by neoliminal** [comment]
Yes, perhaps just blocking **autoplay** would be enough. I don't need anyone around me suddenly hearing a random song/video content because I am looking at a player's profile.

Plus the possibility of people posting obscene or advertising exists, both of which are unlikely, but I've seen stranger things. (Just see what gets posted in chat as an example of how some players skirt this.)
