### ISSUE TITLE
Disable in-game chat for both players if one does not have chat permissions

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#762]
### Summary

I think it would be helpful to disable in game chat if one of the players does not have chat permissions.

There are a number of benefits to this.

It started from this thread:

https://forums.online-go.com/t/disable-chat-function-option/20964?u=greenasjade

where a person is requesting the ability to have students participate in OGS without being exposed to "internet chat": this would substantially solve that problem.

If implemented, it would also help solve the longstanding chestnut of people being offended by chat-banned people not replying, and would remove the possibility of trolls attacking chat-banned people in chat, knowing that they can't reply.

It would need consideration of whether chat-banned people also cannot _receive_ chats.   I think this would be a natural thing to add.

This feature might also see people _requesting_ a chat ban, so that they can be left in peace.

**Comment by anoek** [comment]
I think disabling chat for both would not be desirable as after the game the player can kibitz with spectators and that sort of thing. Also it would be a clear indication that the other player was chat banned. If we are ok with that, we should just say it (like a system note or something, "the player you are playing against is banned from chatting").. but then that would be a little weird at times and might add more of a stigma than we intend.

**Comment by GreenAsJade** [comment]
> I think disabling chat for both would not be desirable as after the game the player can kibitz with spectators and that sort of thing. 

I was meaning that the in game chat would be disabled _during_ the game - that being the time when some people like to be left in peace (the "please don't say hi to me" brigade).

> Also it would be a clear indication that the other player was chat banned. If we are ok with that, we should just say it (like a system note or something, "the player you are playing against is banned from chatting").. but then that would be a little weird at times and might add more of a stigma than we intend.

As per discussion in the forum, I think that "just marking that the other player is chat banned" is rather inferior because of the stigma risk you mention, and also the invitation to then bait the person knowing that they can't reply.

If this were implemented, I think that the term would change from "chat banned" to "chat disabled".   This is a condition that a person could have electively (the "please don't say hi to me" brigade), or involuntarily by moderators.   No-one would know which it was for any given opponent.

**Comment by anoek** [comment]
I think have a "Disable my chat" would be a neat feature, and maybe just remove that whole chat box, chat page, and PM's (except for Mod PMs I reckon), and allow a mod to set this flag as well.

I'm not convinced this shouldn't be a separate feature from our shadowban though, as some of those folk we chat ban really want to be heard, so if they know they are blocked they'll be more enticed to work around around the ban causing more headache for the mods. I don't think that cost is worth paying for the few users who take it way too personally when they say hi and their opponent doesn't / can't respond - most users just brush it off and play the game, as there are lots of possible reasons for that.

**Comment by GreenAsJade** [comment]
True - maybe combining is a false economy.
