### ISSUE TITLE
create custom game in Firefox Android broken

### ISSUE THREAD

**Issue by simonseyock** [online-go/online-go.com#765]
### Summary

Creating custom games in Firefox on Android does not work. Creating games with standard settings work.
This error started to appear some weeks ago. Before it worked fine.

### Environment

 * Operating system: Android 7.1.2
 * Browser: Firefox mobile
 * Browser Version: 66.0.2

### Steps To Reproduce:

1. Create custom game. Settings:
19x19
Ranked
Analysis disabled
Restrict rank: 1k - 12k
Rules: Japanese
Handicap: auto
Color: auto
Komi: auto
Time settings: Correspondence Fisher 2d + 1d up to 5d
Pause on weekends
2. Click "create game"
3. Popup "an error has occurred" appears.

### Additional Information:

**Comment by anoek** [comment]
Hmm, I was unable to reproduce this, is it still happening ?

**Comment by simonseyock** [comment]
yes I am still not able to create games on my phone ...
I tried to log in to my account in chrome but this does not work as it always redirects me to the sign via google page ... this might be related to #574 but i am not sure if I initially signed in via google.
If it helps you I can try to remotely debug my phone and get any debug information you might need.

**Comment by simonseyock** [comment]
Today I tried again and it worked
