### ISSUE TITLE
CSRF Failed popup message when attempting to challenge opponent

### ISSUE THREAD

**Issue by ksafford** [online-go/online-go.com#767]
<img width="453" alt="Screen Shot 2019-05-07 at 11 33 55 AM" src="https://user-images.githubusercontent.com/1257916/57316876-6b6d5280-70bc-11e9-9cf8-468794271a08.png">

### Summary

When attempting to challenge a player on the site 19x19 ladder, I get an error: CSRF Failed. Referrer checking failed: No referrer

### Environment

 * Operating system: OpenSuse Tumbleweed
 * Browser: Brave 
 * Browser Version: 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)

### Steps To Reproduce:

1. Go to the site 19x19 Ladder. 
2.Click on a player's name. 
3.Click the challenge button
4. See an error message pop up

### Additional Information:

*Include any screen shots, links to games/reviews, wonky SGFs, or other information that is useful*

**Comment by anoek** [comment]
Sounds more like a Brave browser bug, some quick googling seems to indicate they have been messing a lot with referrer stuff.
