### ISSUE TITLE
Feature problem: Ai butting in on game anylysis, can't turn off

### ISSUE THREAD

**Issue by pondturtle** [online-go/online-go.com#772]
Trying to analyse my game after it is played. AI keeps butting in on it and suggesting moves.
![buttin](https://user-images.githubusercontent.com/28937761/57770672-16ab8680-7711-11e9-964e-606f677efbd5.jpg)

I think that simple option to turn off/hide any AI features is needed or if it is already there it really needs to be more visible

**Comment by anoek** [comment]
A fair request, I'll ponder on how to fit some toggle somewhere for that

**Comment by anoek** [comment]
You can now do this in settings or on the right side of the page
