### ISSUE TITLE
unable to support OGS via paypal

### ISSUE THREAD

**Issue by popz73** [online-go/online-go.com#773]
Hello,
The "checkout with paypal" button doesn't seem to work - this screen shows up

![image](https://user-images.githubusercontent.com/12851952/57799037-6ceaea80-774e-11e9-8b36-92c3825574dc.png)

I've tried with Firefox and Chrome without add-ons, same result.
It doesn't seem to be a general paypal issue - I tried other 'donate' buttons around the web and it goes up to the payment screen just fine

could you check or otherwise let me know of an alternative way to support via Paypal? (preferably one that is still registered in OGS so that I can have the perks :))

**Comment by anoek** [comment]
Yikes, thanks for bringing this to my attention, I'll look into it and get it fixed up ASAP

**Comment by anoek** [comment]
Just as a followup I've contacted support and they are looking into it. I don't see anything that changed on our side, but I could be wrong. There's very little debugging information to go on right now, which is quite frustrating.. but we're working on it.

**Comment by dawran6** [comment]
FYI only the recurrent donation has this issue to me. I can still make a one-time donation.

**Comment by anoek** [comment]
This should be fixed now FYI.
