### ISSUE TITLE
unable to create custom game

### ISSUE THREAD

**Issue by TableCarpet** [online-go/online-go.com#774]
I tried it with Opera and Chrome on 2 accounts.

1) create ranked 19x19 game with rank restriction
2) cancel
3) create unranked 19x19 game with rank restriction
4) cancel
5) create ranked 19x19 game with rank restriction

"An error has occurred" message appears. Its impossible to create any custom game after that until I delete cookies. But then error happens again soon, because there are other ways to replicate error. Some other users writed about it.

**Comment by anoek** [comment]
Thanks for the report, I'm surprised I wasn't getting screamed at for this one. You should be all set now.
