### ISSUE TITLE
Outdated contributor list on site

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#775]
### Summary

The contributor list found at https://online-go.com/docs/team is missing 8 accounts.

### Environment

Front end webpage

### Steps To Reproduce:

1. Go to https://online-go.com/docs/team
2. See that 8 names are missing when compared to [the official GitHub list](https://github.com/online-go/online-go.com/graphs/contributors). 

### Additional Information:

Missing contributors include:
https://github.com/sinking-point
https://github.com/konaraddi
https://github.com/drichard
https://github.com/Bloodyaugust
https://github.com/simonecarriero
https://github.com/GreenAsJade
https://github.com/briank621
https://github.com/hloeffler

**Comment by GreenAsJade** [comment]
Curiously, this list, which OGS uses to populate the page:

https://api.github.com/repos/online-go/online-go.com/contributors

Is different to this list:

https://github.com/online-go/online-go.com/graphs/contributors

... the latter appearing to have more contributors in it (but not being presented in JSON :) ).

**Comment by BHydden** [comment]
They're also in a different order, for whatever that's worth.

**Comment by anoek** [comment]
https://api.github.com/repos/online-go/online-go.com/contributors?anon=1 returns more results for accounts that don't have the email address used in commits associated with their github user correctly, however as BHydden noted that even this list is still missing 8 people. Haven't looked into who those are yet or what's different about them.

**Comment by BHydden** [comment]
As you can see from the below list, the new API-anon is much worse. The only missing person from the original API that appears on the anon list is GreenAsJade. Furthermore, the anon list has several extra missing people, two people with their name listed twice!, and includes 2 entries to which I couldn't find a match in the master list...

Full   List (A-Z) | API | API-anon |  
-- | -- | -- | --
1forh |   |   |  
AdamT213 |   | missing |  
Alderi-Tokori |   |   |  
alex-mac |   | missing |  
anoek |   |   |  
balpha |   | missing |  
BarneyStratford |   |   |  
basti1302 |   |   |  
bitlux |   |   |  
Bloodyaugust | missing | missing |  
briank621 | missing | missing |  
cassidoo |   |   |  
crodgers |   | double entry |  
DmitriyKirakosyan |   |   |  
dragon96 |   | missing |  
drichard | missing | missing |  
evoluteur |   |   |  
felixthelucas |   |   |  
flurmbo |   |   |  
gemedet |   |   |  
GreenAsJade | missing |   |  
hloeffler | missing | missing |  
Idex |   |   |  
IFOV37 |   | double entry |  
ihoover |   |   |  
kevincoleman |   |   |  
konaraddi | missing | missing |  
lemurek |   |   |  
MartijnTheunissen |   |   |  
mlopezviedma |   |   |  
msayson |   |   |  
nclavaud |   |   |  
roy7 |   |   |  
schambers |   |   |  
simonecarriero | missing | missing |  
sinking-point | missing | missing |  
stephancurran |   |   |  
timuzhti |   | missing |  
---->??? |   | greyson | greyson@l4digital.com
---->??? |   | Brendan L | drac@dracsoft.com

**Comment by anoek** [comment]
OK I feel their documentation could be a little better here.. there's a default page size of 30, and there are more pages. https://api.github.com/repos/online-go/online-go.com/contributors?per_page=100 returns a lot better results. We should probably deal with pagination eventually, but I got some other stuff taking priority at the moment, and I reckon we have 72 more contributors to go before that's an issue :)

I think without anon is what we want since it matches the contributors tab on github I believe, and if someone is missing the fix is for them to add their email address to their github profile correctly and then they should start showing up.

**Comment by anoek** [comment]
Temporarily fixed in ed1bbce983d73fce4b807cc4f1c832d585ffb9e7 (until we need pagination)

**Comment by BHydden** [comment]
Sounds perfect!
![image](https://user-images.githubusercontent.com/28991649/58326960-a2d84f00-7e71-11e9-8e27-9ba533e62005.png)

**Comment by BHydden** [comment]
> Temporarily fixed in [ed1bbce](https://github.com/online-go/online-go.com/commit/ed1bbce983d73fce4b807cc4f1c832d585ffb9e7) (until we need pagination)

![image](https://user-images.githubusercontent.com/28991649/58326998-bb486980-7e71-11e9-8d22-4a9cf3c58415.png)
