### ISSUE TITLE
Estimator All Tied Up

### ISSUE THREAD

**Issue by pelevesque** [online-go/online-go.com#776]
### Summary

The crafty player bw_go finds secret easter egg hack thingy jingy. 

Makes a 1x3 board. White has 3.0 komi. Black plays in the center. Both pass. Score is 3.0 for black and 3.0 for white. Tie game, but OGS doesn't seem to be able to handle a tie.

It says "Black wins by 0 points"

When 'Estimate score' is clicked it says "White by 0"

https://online-go.com/game/17944831

**Comment by anoek** [comment]
Interesting, I suspect this probably happens with any similar situation regardless of board size

**Comment by kobakitty** [comment]
Yes, this happens to every game that's played under integral komi and ends up as draw. OGS does show the gameresult as B+0 instead a tie, and it has always been like this. Another post about the bug https://github.com/online-go/online-go.com/issues/657

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
