### ISSUE TITLE
Add ability to appear offline

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#791]
Mods (and maybe everyone?) should be able to use the site without appearing online. This should apply to the green dot in the private chat window as well as the game user list.

**Comment by BHydden** [comment]
If normal users get this ability, it shouldn't work on mods.

**Comment by GreenAsJade** [comment]
Note that related to this is a problem that the API that the app uses actually allows users to use the site while appearing offline.   It also makes them immune to megaphone.

I wish that could be fixed.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
