### ISSUE TITLE
activites / calendar tab

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#796]
Devin Flake (Facebook): it would be great if OGS had an 'activities' or 'calender' tab that showed active tournaments, reviews, livestreams, etc. Something persistent. Sometimes I'll dismiss an announcement and then not be able to find it again.

BHydden: Attached to this should we implement it should be some way to pin certain activities to the top if there is something more special than all the other special things.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
