### ISSUE TITLE
AI "Top game changing moves" should omit move 0 for handicap games

### ISSUE THREAD

**Issue by tenorslowworm** [online-go/online-go.com#799]
The AI "Top game changing moves" feature always includes move 0 for handicap games -- understandable in a way, since the placing of the handicap stones certainly swings the win percentage a great deal! -- but this is a waste of a slot that could be devoted to a third real move, which would be more helpful to the players.

I'm filing this here in the UI section because I'm hoping that the fix can be pretty superficial, that instead of messing with the engine, you can just detect that it's a handicap game from the UI and then simply ask the engine for its top four rather than top three game changing moves and omit move 0 from what's returned. 

I won't include browser info or screen shots, etc., since I assume this is currently working as intended and everybody is seeing what I'm seeing, but if that turns out not to be the case, then I can provide more info. (One note I'll include is that I'm seeing this when opening past correspondence games that were completed before the AI feature was added, just in case that makes a difference. I haven't played any new games since then.)

**Comment by lightvector** [comment]
In addition to merely including the placement of the handicap stones a swingy move, it also actually seems to have a bug as well.

Take a look at here:
https://online-go.com/game/18106352

Not only is move 7 included as a swingy move, if you look on move 6, it suggests that white is winning 99.5%. Which is silly, white should not be winning just after *black* has placed almost all handicap stones.

**Comment by anoek** [comment]
This has been fixed on the server side
