### ISSUE TITLE
Country column in New Users section of Moderator Center always empty

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#801]
as per title

![image](https://user-images.githubusercontent.com/28991649/58772994-d26c2180-85fe-11e9-8358-68b7042ea056.png)

**Comment by BHydden** [comment]
Humbly suggest it be removed and replaced with a column (preferably functional) listing a user's current ban status :)

**Comment by anoek** [comment]
Fixed missing country, now highlight row in red if they share some aspect with another banned account (ip, bid). cfe515dd999a9bb1c99086a7ceb99b879081d752

**Comment by BHydden** [comment]
Oooh interesting!
