### ISSUE TITLE
Oral byo-yomi counting should have an option to count up

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#802]
In japanese tournaments you count up instead of down, this should be an option, and perhaps default based on a player's location.

From https://senseis.xmp.net/?JapaneseTiming%2FNHKCup

   Bob Myers:
   And for those interested in arcane variations of byo-yomi conventions, and IIRC, the seconds are read off at the 10, 20, 25, and 28 second point of each thirty-second period, and the 30, 40, 50, 55, 58 second point of each extended thinking period. However, after all ten extended thinking periods have been exhausted, the last ten seconds are read off one by one: ichi, ni, san, with the player in question losing when the byo-yomi-gakari pronounces the dreaded "juu".

**Comment by BHydden** [comment]
Issue can be closed. You included this option with the big audio update.

![image](https://user-images.githubusercontent.com/28991649/144713056-af064bac-53e3-45c1-9395-4151ed617303.png)
