### ISSUE TITLE
AI analysis winrate graph does not agree with bar display

### ISSUE THREAD

**Issue by mkmatlock** [online-go/online-go.com#805]
### Summary

The win rate graph sometimes appears to oscillate wildly, but the winrate reported in the bar display does not agree with the graph display. This behavior might only happen when the winrate is extremely lopsided (e.g 99.5%+ for one side to win), but I'm not sure. Here is an example game: https://online-go.com/game/18178142 I've included a screenshot below showing what I see.

### Environment

 * Operating system: Mac OS
 * Browser: Chrome
 * Browser Version: 74.0.3729.169

### Steps To Reproduce:

1. Run an AI analysis (particularly for lopsided wins?)
2. Click a move with apparent winrate oscillations
3. Observe discrepancy

### Additional Information:

<img width="1303" alt="Screen Shot 2019-06-07 at 6 35 24 PM" src="https://user-images.githubusercontent.com/391221/59138460-dd9eb480-8952-11e9-8ea0-01c340137280.png">

**Comment by BHydden** [comment]
This actually got fixed just a little earlier today :-) please recheck the link you sent ;-) all games have been fixed retroactively.
