### ISSUE TITLE
Timer not resetting time between moves

### ISSUE THREAD

**Issue by Lone-Coder** [online-go/online-go.com#81]
### Summary

The timer is occasionally not resetting between moves. 

For instance on https://online-go.com/game/7968787, I played move 287 with 5 seconds left. Black made move 288, then I suddenly only had 5 seconds to make a move and timed out. The problem was happening the entire end game. Time on client wouldn't reset between moves

This has happened in other games as well where I had a single second to make a move.

Not sure if it is lag or a javascript problem of some kind.

### Environment

 * Operating system: Windows 10
 * Browser: Chrome
 * Browser Version: 56.0.2924.87 (64-bit)

### Steps To Reproduce:

Play a bunch of games on my computer. Might be just during busy times. Maybe it's my crappy internet.

### Additional Information:

I had 10 browser tabs open at the same time, including Pandora music and GMail and several other OGS tabs.

I did have one odd Chrome Extension enabled. I'll disable it and see if issue goes away.
https://chrome.google.com/webstore/detail/css-used/cdopjfddjlonogibjahpnmjpoangjfff?utm_source=chrome-app-launcher-info-dialog

Here is a screenshot of the javascript console:
![image](https://cloud.githubusercontent.com/assets/920120/23582818/ad7419a4-00f0-11e7-8356-2a2774d1702d.png)

**Comment by anoek** [comment]
As an update I deployed a potential fix for this on Sunday, and am keeping an ear out for any further or similar reports.

**Comment by anoek** [comment]
Assuming fixed
