### ISSUE TITLE
feature request: score estimator should be disabled when analysis is disabled

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#813]
Good afternoon

The score estimator is an analysis tool so should be disabled when analysis is disabled in the match options.  

I don't know about other countries but in Chile the online tournament regulations (http://www.igochile.cl/igochile2/home/reglamentos/) forbid the use of analysis tools.  For that reason the Federación Chilena de Go presently prefers KGS for online tournaments.  I would like it to be possible for online tournaments in Chile to use OGS in future therefore I am making this feature request.  

This was also discussed in detail here: https://forums.online-go.com/t/score-estimator-should-be-optional-when-defining-a-match/18052

I look forward to your reply.  

Kind regards

Alex Mitrani
Federación Chilena de Go

**Comment by anoek** [comment]
Yep this came up with AGA/EGF tournaments as well. I think the current plan is to add a new option to disable the score estimator.
