### ISSUE TITLE
Stay on game after second pass

### ISSUE THREAD

**Issue by jsonn** [online-go/online-go.com#816]
Currently, if more than one game requires a move, the second pass will still move to the next game. It should stay on the current game as the scoring requiring attention/confirmation from the user anyway. This will indirectly also help #700 by avoiding part of the problem.

**Comment by anoek** [comment]
Yeah that's a good idea

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
