### ISSUE TITLE
AI Review fail

### ISSUE THREAD

**Issue by Ricocotam** [online-go/online-go.com#820]
After [this](https://online-go.com/game/17574496) game the AI report "top changing moves" pretty strange. And actually its estimation are pretty bad imo

Just to report,

Cheers

**Comment by anoek** [comment]
Thanks, it should be notably better now. Now I see it properly identifies the main blunder as it should. The full review still highlights some better top 3 moves, but at least it's not quite as embarrassingly bad now.
