### ISSUE TITLE
game I'm not playing showing as an active game on my profile

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#826]
![Screenshot_20190706-152253](https://user-images.githubusercontent.com/27974470/60760355-37ea6e00-a002-11e9-9383-a2cc86f3872b.png)
### Summary

I accepted a challenge but there was an "error submitting move" on my first move.  
When OGS reloaded someone else was playing my opponent but it was showing as an active game on my profile.  

### Environment

 * Android 9
 * Chrome

### Steps To Reproduce:

This may be tricky to reproduce because it probably depends on there being an error submitting a move.  

### Additional Information:

See attached screenshot. 

Thanks.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
