### ISSUE TITLE
Don't mess with comment input during reviews of life games

### ISSUE THREAD

**Issue by jsonn** [online-go/online-go.com#827]
### Summary

Writing move comments during a review of a running game is annoyingly interrupted by new moves.

### Environment

 * Operating system: 
 * Browser:
 * Browser Version:

### Steps To Reproduce:

1. Start a review of a running (live) game.
2. Focus comment box and start wrting
3. See the board jump to a new move every so often.

### Additional Information:

It would be nice to not change the board position if the comment box is currently focused.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
