### ISSUE TITLE
9x9 automatic handicap incorrect

### ISSUE THREAD

**Issue by chaverly1** [online-go/online-go.com#833]
### Summary

I am able to create automatic handicap games with a rank difference of 4 or 5, yet White's komi is only reduced by 2 points

### Environment

 * Browser: Chrome
 * Browser Version: 75.0.3770.100 

### Steps To Reproduce:

1. Create a new 9x9 challenge between players ~5 ranks apart
2. Set handicap to *automatic*
3. A game will be created with no stones already on the board, and 3.5 komi for White. This is incorrect because a 5 rank difference merits more than a 2 point reduction in standard komi.

### Additional Information:

From my initial results, it appears the 9x9 handicaping system is completely off for closer ranks.

**Games in question:**
[Game 1](https://online-go.com/game/18567046): 4 rank difference, No starting stones, 3.5 komi
[Game 2](https://online-go.com/game/18567079): 5 rank difference, No starting stones, 3.5 komi
[Game 3](https://online-go.com/game/18567116): 10 rank difference, 3 starting stones, -2.5 komi

**Game 3** was actually about right. The chart I always use would have given **3 stones, 0.5 komi**, which is pretty close. I've pasted the chart data at the bottom of my post for reference.

However, Game 1 and Game 2 make no sense at all. Per my chart, I would expect:

**Game 1**: No starting stones, -6.5 komi
**Game 2**: 2 starting stones, 2.5 komi

Even some approximation of those would be acceptable.

I've also been part of AGA 9x9 fun tournaments, and they employed a simpler system of **reducing komi by 2 points per rank** difference (e.g. 3 ranks = -.5 komi , 7 ranks = -8.5 komi). I could live with that too. 

**Rank/Handicap Chart** 
(Can't remember where I got this list, but I'd expect a mapping similar on OGS)

|Rank difference|19x19 Stones|19x19 Komi|13x13 Stones|13x13 Komi|9x9 Stones|9x9 Komi|
|---|---|---|---|---|---|---|
|0|0|6.5|0|5.5|0|5.5|
|0.5|0|0|0|3.5|0|3.5|
|1|0|-5.5|0|0|0|2.5|
|1.5|2|0|0|-3.5|0|1.5|
|2|2|-5.5|0|-5.5|0|0|
|2.5|3|0|2|3.5|0|-1.5|
|3|3|-5.5|2|0|0|-3.5|
|3.5|4|0|2|-3.5|0|-4.5|
|4|4|-5.5|2|-5.5|0|-6.5|
|4.5|5|0|3|3.5|2|3.5|
|5|5|-5.5|3|0|2|2.5|
|5.5|6|0|3|-3.5|2|1.5|
|6|6|-5.5|3|-5.5|2|0|
|6.5|7|0|4|3.5|2|-1.5|
|7|7|-5.5|4|0|2|-3.5|
|7.5|8|0|4|-3.5|2|-4.5|
|8|8|-5.5|4|-5.5|2|-6.5|
|8.5|9|0|5|3.5|3|3.5|
|9|9|-5.5|5|0|3|2.5|
|9.5|10|0|5|-3.5|3|1.5|
|10|10|-5.5|5|-5.5|3|0|
|10.5|11|0|6|3.5|3|-1.5|
|11|11|-5.5|6|0|3|-3.5|

**Comment by chaverly1** [comment]
After giving the issue more thought, I believe the root cause is the use of handicap = 1.

This designation has no meaning. Handicap = 0 is the same thing as handicap = 1. Either way, Black plays first.

![image](https://user-images.githubusercontent.com/13876919/61189941-803d0800-a662-11e9-8bf9-e782af75fb35.png)

**Comment by anoek** [comment]
:+1:

**Comment by anoek** [comment]
Sorry I misunderstood and thought you thought the issue was resolved, I see it now.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
