### ISSUE TITLE
sound turns on every time site is loaded

### ISSUE THREAD

**Issue by simonseyock** [online-go/online-go.com#834]
### Summary

Every time I load the page in Firefox mobile the sound turns on. The reload happens every time I select the tab.

### Environment

 * Operating system: Android 7.1.2
 * Browser: Firefox mobile
 * Browser Version: 68.0

### Additional Information:

I can do remote debugging if desired.

**Comment by anoek** [comment]
Is the browser clearing cookies frequently by chance? That's usually the cause of this, as the volume information is stored in local storage (which is cleared along with cookies).

**Comment by simonseyock** [comment]
The cookies are not disabled. I tried to debug it and was not able to see localstorage and cookies with the remote debugger of firefox. It seemed kind of broken.
And then at some point I reloaded the page and it stayed turned off.
Now when I enable the sound it gets reset to silent every time the page is loaded in my mobile firefox.

I encountered the same problem in firefox on my linux laptop. There I was able to debug the localstorage.
I loaded the page. Sound was on (even though i disabled it before). I could not find the `ogs.preferences.sound-enabled` or `ogs.preferences.sound-volume` keys that I have If I use firefox on my windows desktop. Other stuff appears in local storage.

I turned the sound off and the preference does not appear. I reloaded the page and sound was on again. The preference of course does still not appear.

I also tried to delete all values in local storage, but it still does not save my sound settings

**Comment by simonseyock** [comment]
So I looked at the code a little.
Could it be that this problem is the problem:
https://github.com/online-go/online-go.com/blob/c04b661d226e06ff7027cd9580b65379082473dd/src/views/Game/Game.tsx#L1703
toggleVolume calls the private _setVolume which does not call saveVolume

**Comment by simonseyock** [comment]
I can indeed confirm that as soon as I use the slider instead of the toggle button that the sound volume gets saved.

**Comment by simonseyock** [comment]
In the Settings component which has the same slider and a similar structure, the preferences are indeed stored inside the `_setVolume` method.
I can do a PR if you like.

**Comment by anoek** [comment]
Interesting, cool thanks for the PR :)
