### ISSUE TITLE
post-game mobile anomaly #1

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#836]
### Summary

When I tap on my opponent's name to see their info I get a blank page.

### Environment

 * Operating system: 
Android 9
 * Browser: Chrome
 * Browser Version: 75.0.3770.101

### Steps To Reproduce:

1. play a 9x9 game
2. tap on opponent's name
3. lo and behold, a blank page

### Additional Information:

* see attached screenshot showing this page: https://online-go.com/player/659539/

![Screenshot_20190716-225823](https://user-images.githubusercontent.com/27974470/61333146-02bdf700-a81e-11e9-8bbb-ef2030ffa006.png)

See additional comments on #837.

Thanks

**Comment by alexmitrani** [comment]
Resolved by removing content filters.

**Comment by anoek** [comment]
Oh interesting, thanks for the followup!
