### ISSUE TITLE
post-game mobile anomaly #2

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#837]
### Summary

When I play a game, then go home and create a new challenge, nothing happens.

### Environment

 * Operating system: Android 9 
 * Browser: Chrome
 * Browser Version: 75.0.3770.101

### Steps To Reproduce:

1. Play a 9x9 game
2. Go home, play, create challenge, confirm.  
3. See that no challenge has been created and nothing happens.  

### Additional Information:

Related to post-game mobile anomaly #1 (issue #836), both started occuring after the server problems a few days ago.  Both are transient and solved by closing the browser and re-opening.  Still, they are irksome and never happened previously - hopefully they will be easy to resolve.  

Thanks.

**Comment by anoek** [comment]
Hm, I am unable to reproduce either of these issues. Do you have any more details you can provide on reproduction? Are you creating custom challenges, computer, automatch?

**Comment by alexmitrani** [comment]
hi, yes, custom challenges.  9x9, live speed, 0 mins + 3*15s byo-yomi, analysis disabled, rank unrestricted.

**Comment by anoek** [comment]
Hm, I'm still not able to reproduce it, using those identical settings with that nearly identical browser (75.0.3770.143 over here - but I highly doubt that is the issue).

Could you try logging in in an incognito tab and trying it there? I'm wondering if something is in a "funky state" with stored settings, doing that test should answer the question.

**Comment by alexmitrani** [comment]
hi, I tried again using an incognito tab, and both issues #836 and #837 persisted.

**Comment by alexmitrani** [comment]
Resolved by removing content filters.
