### ISSUE TITLE
Add some explanation for AI review feature

### ISSUE THREAD

**Issue by okainov** [online-go/online-go.com#840]
I really miss explanation what all those colors and numbers in AI review mean. Ok, I understood that number is somehow win percentage for each player,  But I still do not understand colors, highlight.

And also it would be great if some manual playout-moves were analyzed as well

**Comment by flovo** [comment]
https://forums.online-go.com/t/help-understanding-the-computer-analysis-output/21910/2?u=flovo

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
