### ISSUE TITLE
Server Time / Weekend indicator

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#849]
### Summary

"Can we please add a server date/time indicator somewhere? That way I could know when weekend pauses start and end. Even niftier would be a “weekend starts/ends in _ hours” indicator that only shows on friday/sunday." 
 - smurph

Found this and wanted to throw it up... might be something I'll look into coding up soonish. Thinking it could just be a simple server clock somewhere on the home page and profile page.
I only feel confident coding up the first suggestion so if anyone else feels like implementing the "weekend starts / ends" stuff feel free to chime in.

### Additional Information:

https://forums.online-go.com/t/server-time-weekend-indicator/18731

**Comment by BHydden** [comment]
I got this project up to "ready to submit to anoek for checking over" today... but silly me did it in the same branch as the other project I'm working on... so, if I can split the branches successfully tomorrow... there should be a new PR going up then... :P

**Comment by anoek** [comment]
git cherrypick is your friend :)

**Comment by BHydden** [comment]
Thanks! I was going to attempt some convoluted copy backup - > git revert deal but I'll look into your suggestion first ❤️

**Comment by BHydden** [comment]
#878 merged.

Closing.
