### ISSUE TITLE
AI marks are visible after "disable AI review"

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#856]
### Summary

When the user disables AI review in Game view, the AI marks are only deleted for the current move. For other moves the marks are still visible.

### Steps To Reproduce:

1. View a game with (full) AI review
2. View multiple moves while AI review enabled.
3. Disable AI review (right panel)
4. The marks for all visited moves (but the last visited move) are still visible.

### Additional Information:

This was reported on the forum at least once https://forums.online-go.com/t/disable-ai-review-does-not-hide-the-winrate-changes/22510?u=flovo

**Comment by anoek** [comment]
Thanks for the fix!
