### ISSUE TITLE
"disable AI review" also jumps to the last official move

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#858]
### Summary

When the user disables AI review (right panel), the current move changes to the last official move. 

### Steps To Reproduce:

1. Go to Game View
2. Go to any but the last move
3. Click on "Disable AI review" in the right panel
4. We are now on the last official move.

### Additional Information:

https://forums.online-go.com/t/disable-ai-review-does-not-hide-the-winrate-changes/22510

**Comment by flovo** [comment]
This is probably caused by https://github.com/online-go/online-go.com/blob/93c70b6db82c66c446db7600014043207834e6be/src/views/Game/Game.tsx#L973

**Comment by anoek** [comment]
Thanks for the fix!
