### ISSUE TITLE
"Disable AI review" removes marks placed by the user

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#860]
### Summary

"Disable AI review" removes marks placed by a user as well.

### Steps To Reproduce:

1. Go to a game
2. Switch to Analyze Mode
3. place some marks (e.g. circles)
4. Click on "Disable AI review"
5. Not only the pp markings are gone, but the marks (circles) as well.

### Additional Information:

Marks from shared variations are removed temporarily, but can be restored by clicking on the share in chat again. Unshared marks are lost.

This happens since we remove *all* marks when disabling AI review.
https://github.com/online-go/online-go.com/blob/93c70b6db82c66c446db7600014043207834e6be/src/views/Game/Game.tsx#L972

**Comment by anoek** [comment]
Yeah this is unfortunate. The two solutions that come to mind are to either have a special "ai-mark" that we set and clear, or to duplicate the marks code all together and have one for generated marks (ie from ai), and one for user generated marks.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
