### ISSUE TITLE
AI review: shift+click doesn't update AI review

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#862]
### Summary

When AI review is enables, Shift+Click on a move jumps to selected move, but the AI review still shows the review for the last seleced move (heatmap and blue circle). 

### Steps To Reproduce:

1. Go to a finished game with AI review
2. Ensure AI review is enabled
3. Shift+Click on any move
4. See that heatmap and blue circle are still on the same position as in step 2). There are no pp marks as well.

### Additional Information:

A game with full AI review for testing: https://online-go.com/game/18734180

**Comment by anoek** [comment]
Fixed, thanks for the report!
