### ISSUE TITLE
Clock packets are being sent after move packets

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#863]
I noticed my bot in a 5 min per move Simple clock game wasn't thinking for each move. In gtp2ogs we use the black_time and white_time to calculate time left for your move, and set other player's clock to 1 second (vs just not setting it at all).

Turns out since the clock update is after the move command, we start processing the move before the clock has updated. So black_time and white_time are always wrong in that situation (player to move is 0 instead of showing time left), and this also impacts other parts of loadClock() since last_move will be the time stamp of prior player's last move, not our last move.

I'm thinking we should send new clock info over the API before we send the new move info? Or should the full clock data be loaded into the move packet so you get it all at once?

**Comment by anoek** [comment]
I am trying to remember if I had a particularly good reason to do this. I want to say I had a reason, but I'm not sure if it was a good one that would prohibit swapping the order of those.

I will ponder on it more. If I had to do it again I would probably send them both as one packet, but then again we do handle clock messages outside of handling moves (most notably when the clock is paused or resumed.)

Given that we handle them sporadically I am inclined to believe that changing the order *should* be fine. Let me ponder on it a bit and see if it would be problematic to swap these on the server.

**Comment by anoek** [comment]
OK I looked into it and I believe it is safe for me to do, so it is now done. Starting immediately you should be receiving the clock message right before the move message. Hopefully nothing breaks :D

**Comment by roy7** [comment]
Thanks! So far things look good and Simple time is working as expected with my bots!
