### ISSUE TITLE
Up and down arrow keys don't work in conditional move planner

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#864]
When using the conditional move planner, the up and down arrow keys should function instead of just the left and right arrow keys.

It's been reported that the lack of up and down arrow keys can cause the analysis branch to be navigated instead of the conditional move planner as well, though I haven't reproduced this. Regardless, properly supporting up/down in the conditional move planner should resolve this.

**Comment by BHydden** [comment]
FWIW, the report mentioned above is #237

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
