### ISSUE TITLE
[AI review] Blunder count not available for full review

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#866]
### Summary

The "10+%moves" is only available for the free "hunch", not for the better full run.

We should calculate it as well for the full runs.

### Additional Information:

![10+%moves](https://user-images.githubusercontent.com/4864182/63009334-94a03a80-be84-11e9-949f-c4074f409984.png)

https://forums.online-go.com/t/ai-review-updates-2019-06-19/21792/96?u=flovo

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
