### ISSUE TITLE
AGA white pass last not working

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#870]
### Summary

According to AGA rules white has to pass last https://www.usgo.org/sites/default/files/pdf/completerules.pdf
> 11) The Last Move:White must make the last move--if necessary, an additionalpass, with a stone passed to the opponent as usual. The total number of stonesplayed or passed by the two players during the entire game must be equal.

It's not cleat to me how to handle it since
> 9) Ending the Game:Two consecutive passes signal the end of the game. Aftertwo passes, the players must attempt to agree on the status of all groups ofstones remaining on the board. [...]

This is only an issue if we use Territory Scoring. For Area scoring an additional pass should be worth 0 points anyway.

### Additional Information:

In one of my games the game ended after black passed. 

https://online-go.com/game/19016726

The API entry is set correctly
```json
         "white_must_pass_last": true,
```

**Comment by flovo** [comment]
It seems we use Area Scoring, so this is only irritating, but not score changing.
```json
        "score_territory": true,
        "score_territory_in_seki": true,
        "score_stones": true,
        "score_handicap": true,
        "score_prisoners": false,
        "score_passes": true,
```

**Comment by anoek** [comment]
Yeah I didn't end up enforcing it because area scoring, and it's just an extra thing to do that is unnecessary with area scoring. I had forgotten I had a setting in there though, that's kinda funny and should probably be removed since it's non functional.. old old code.
