### ISSUE TITLE
[AI review] show only the next move

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#872]
### Summary
As requested on the forum:

I am a bad player and really enjoy the ai variations, but they could be presented in a way that is more educational to me. I would like to have a toggle that either the whole ai variation is shown as is now or alternativly only the next move of the ai variation is shown.

What I want to do is click through the AI variation, think about every move and learn that way. However since from the very first move all 26 or whatever moves of the variation are displayed I can’t really do that because I see a lot of stones that aren’t on the board and they confuse me hard.

I could do without if someone can tell me a good workaround, but so far I haven’t bee successful. Best thing i could think of is second window, but with 1 screen that works only mediocre.

### Additional Information:

https://forums.online-go.com/t/feature-request-only-show-next-move-in-ai-variation/22600?u=flovo
https://forums.online-go.com/t/suggestion-for-display-of-ai-review-play-out/23188?u=flovo

**Comment by b3n** [comment]
+1

My suggestion would be an option to show the numbers without the transparent stones. With the numbers alone one can visualise (or play out) the sequence of moves without getting confused by what's currently on the board and what is a future move in the variation.
