### ISSUE TITLE
Allow both players to place stones in review session?

### ISSUE THREAD

**Issue by brylie** [online-go/online-go.com#875]
A friend and I are studying Go together, and would like to be able to explore moves and patterns via the review tool (we live far apart). However, the review tool, analyze tool, and demo board seem to only let one player add pieces, or are visible to only one player in a game. 

Is there a way that two players can review a game in progress together, allowing both players to place stones and create alternative branches, so the other can see?

**Comment by brylie** [comment]
This would also be helpful when doing online reviews with Go teachers.

**Comment by anoek** [comment]
You can quickly pass control to another person by clicking their name in the username list and clicking the "Give Control"

You can also share variations quickly without control by placing some stones and then clicking "Share Variation", if the reviewer clicks the link then the review will switch over to the branch you provided.

So far those two features have worked pretty well for people, I don't intend on adding a mode to have two people place stones visible to all at the same time at this point as doing so starts to open up some nasty race condition scenarios I'd rather avoid.

**Comment by brylie** [comment]
Jep, those are great. Thanks! ☺

**Comment by brylie** [comment]
I will try those on the Demo Board too, as that would allow us to start from a clean board.
