### ISSUE TITLE
Conditional Move Planner & double-click/submit-move mode.

### ISSUE THREAD

**Issue by mmartin** [online-go/online-go.com#876]
### Summary

When using `Submit-move button` or `Double-click to move` submit modes, `Plan conditional moves` button becomes available right after placing the provisional stone, i.e. before submitting the final move. After that the Conditional Move Planner works really wonky.

### Environment

 * Operating system: Gentoo Linux
 * Browser: Firefox
 * Browser Version: 68.0.2 (64-bit)

### Steps To Reproduce:

1. Set submit mode to `submit-move button` or `double-click to move`;
2. open game where it is your move;
3. place a provisional stone;
4. `Plan conditional moves` button becomes available, click it;
5. the provisional stone is gone;
6. try placing some moves;
7. stones' colors are reversed.
![cond_moves](https://user-images.githubusercontent.com/236237/63699260-23b83580-c829-11e9-8c61-a3840ce4ff1d.png)

### Additional Information:

After accepting conditional moves, they are saved to the server (the ones from the right side of the screenshot).

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.

**Comment by mmartin** [comment]
The bug exists.

**Comment by turtoise0** [comment]
Related: #1030
