### ISSUE TITLE
[Score estimator] individual player scores are useless/wrong in games ended with score

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#882]
### Summary

When using “estimate score” on a finished game (ended by scoring), the individual scores for black and white are just useless/wrong. They are prisoners (+ komi).

This is a cosmetic issue. The estimated score difference is correct.

### Steps To Reproduce:

1. Go to a game won by score (https://online-go.com/game/19350057)
2. Click “estimate score”
3. See that the individual scores don't reflect the state of the board.

### Additional Information:

![Untitled](https://user-images.githubusercontent.com/4864182/64292875-a6e53400-cf6b-11e9-8c39-45c9e168b1bb.png)

**Comment by flovo** [comment]
To prevent any confusion, it would probably be best to hide the captures/points line when SE is on (, or to show the capture count/points of the SE instead).

**Comment by anoek** [comment]
Fair point
