### ISSUE TITLE
[AI review] variations are visible when AI review is disabled

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#883]
### Summary

When we select an AI variation and later “disable AI review” the AI sequence is still visible

### Steps To Reproduce:

1. Go to a game with AI review (https://online-go.com/game/19422644).
2. Click on a AI suggestion.
3. “disable AI review”.
3. See that the AI suggestions are still visible.

### Additional Information:

https://forums.online-go.com/t/ai-bug-variation-displayed-when-ai-disabled/22767?u=flovo

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
