### ISSUE TITLE
Demo game doesn't load

### ISSUE THREAD

**Issue by Harleqin** [online-go/online-go.com#888]
**Description**
The following game is stuck on the loading screen:

https://online-go.com/game/review/190510

**To Reproduce**

1. Open https://online-go.com/game/review/190510
2. The board is shown empty, with a dark bar "Loading..." over it

**Expected behavior**
The demo loads and I can see it.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Icecat 60.7.0esr (64-bit) or Firefox 69.0 (64-bit)

**Comment by anoek** [comment]
The working link for this is: https://online-go.com/review/190510
