### ISSUE TITLE
AGPL license can be problematic

### ISSUE THREAD

**Issue by windo** [online-go/online-go.com#89]
The AGPL license choice is a bit understandable - with just plain GPL one could imagine that a new online go site could open up, use online-go frontend code, change it and not contribute the changes back.

Personally, that scenario does not sound very feasible to me. For example, would it be markedly better if they were forced to open up their changes? Would the current maintainers be willing to go and pull the changes back (there is nothing that would force them to send pull requests if they don't want to). If they wanted to keep on making use of upstream changes, it would get annoying from them fast if they just allowed the codebases to converge.

AGPL is apparently considered to be problematic by corporate copyright lawyers. Since most emplyment contracts with bigger corporations require that employees generally clear open source contributions with the corporation, this makes AGPL problematic for the employees of those corporations as well.

For my personal case, AGPL code contributions require a special process to hand over all copyright to me (presumably because they do not wish hold any AGPL copyrights or something). For most other licenses (for example plain GPL) there is a separate light weight, fast and streamlined process.

To make it clear, I'm asking you to consider changing the license to GPL (or most other mainstream open source licenses) to allow more people to contribute to the project.

**Comment by anoek** [comment]
I'm not opposed to this, though we'd have to have sign off by all current contributors at this point I do believe. Anyone else care to chime in here, would switching to GPL make your life any easier?

**Comment by anoek** [comment]
As no one has commented on this, I suggest that if you're still interested in seeing this happen, the discussion be moved out into the forums or onto uservoice to gauge community interest. I'm going to close this on github as it doesn't seem to be progressing here.
