### ISSUE TITLE
Auto-advance jumps from the your-turn tree into the active-games tree

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#892]
**Describe the bug**
Post-implementation of PR - #852 it was discovered that the "auto-advance" feature would automatically move a player from their last played move to their first active game.

**To Reproduce**
1. Have Auto Advance turned on and multiple correspondence games, in which at least one is your turn
2. Play a move in all the games that it is your turn
3. See that after your last move is played the server still auto advances you into the new all active games tree.

**Expected behavior**
Auto-advance should only move you to a game if it is your turn to move in that game. Progressing into the all-active-games tree should be a purely manual decision.

**Additional context**
For the life of me, I can't find where the auto-advance class lives in order to fix this 🤦‍♂ 
The issue was first reported in [this forum post](https://forums.online-go.com/t/zero-game-waiting/22781/21) and the 3 following comments.

**Comment by flovo** [comment]
Have you found:

https://github.com/online-go/online-go.com/blob/4c8a23ee74e7a990a4e39890f7198c9f7a4f865d/src/views/Game/Game.tsx#L464

https://github.com/online-go/online-go.com/blob/4c8a23ee74e7a990a4e39890f7198c9f7a4f865d/src/lib/goban.ts#L32-L36

https://github.com/online-go/online-go.com/blob/4c8a23ee74e7a990a4e39890f7198c9f7a4f865d/src/lib/goban.ts#L109-L120

**Comment by BHydden** [comment]
Thanks :) found the first one but didn't find the lib files. Looks like I should be able to fix it with an extra condition in online-go.com/src/lib/goban.ts#L115

**Comment by BHydden** [comment]
pending anoek approval, this should be good to go
