### ISSUE TITLE
User on vacation time has games with "0.0" time remaining

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#894]
**Describe the bug**
[User](https://online-go.com/player/560833/nielo) on vacation time has games with "0.0" time remaining

**To Reproduce**
1. Go to https://online-go.com/player/560833/nielo
2. See that several (though not all) games have 0.0 remaining time. Guessing it's a display bug?

**Expected behavior**
Time should display paused remaining time, as some of the same user's games do further down.

**Screenshots**
![image](https://user-images.githubusercontent.com/28991649/64655700-66584f80-d470-11e9-838a-4fe92d571ff3.png)
![image](https://user-images.githubusercontent.com/28991649/64655733-7839f280-d470-11e9-9cb2-af20b645cdd1.png)
![image](https://user-images.githubusercontent.com/28991649/64655754-8425b480-d470-11e9-8d98-6a89068b70dc.png)
![image](https://user-images.githubusercontent.com/28991649/64655761-91db3a00-d470-11e9-95a6-1764b28fe31f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome
 - Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by BHydden** [comment]
The case is not isolated

![image](https://user-images.githubusercontent.com/28991649/64964432-64faad00-d8de-11e9-888d-f637c58e74e2.png)
https://online-go.com/game/view/18806400

**Comment by kobakitty** [comment]
Its one of those bugs related to simple timing, its been like this forever :/

**Comment by anoek** [comment]
I think this has finally been fixed
