### ISSUE TITLE
Analyze Game mode does not render any board details on Chrome for Android

### ISSUE THREAD

**Issue by LaurieLinz** [online-go/online-go.com#898]
When I visit the "Analyze Game" link on my android phone from Chrome version 77.0.3865.73, the board renders but the stones do not for games that have over 100 moves played. I am not sure the exact number of moves where it breaks. I have games that are 45 moves in and it works but my game at 122 moves, it does not. Works on Chrome for Mac Version 76.0.3809.132 (Official Build) (64-bit).

![signal-attachment-2019-09-15-095533](https://user-images.githubusercontent.com/14853507/64924328-8190cb00-d7a0-11e9-8431-65b4d31e0798.jpeg)

**Comment by BHydden** [comment]
Related

https://forums.online-go.com/t/blank-board-in-analyze-mode/22877?u=bhydden

**Comment by BHydden** [comment]
@anoek is it possibly related to latest commit 2f34439

**Comment by LaurieLinz** [comment]
> @anoek is it possibly related to latest commit [2f34439](https://github.com/online-go/online-go.com/commit/2f34439cfbbd6355884ea05bcc39dcddfbc19dbb)

Likely - that was about the time I started noticing it

**Comment by BHydden** [comment]
Comment from @anoek on [a separate forum thread](https://forums.online-go.com/t/alphago-teach-whole-board-joseki/22896/18?u=bhydden) that I believe is referencing this issue

> "There is a separate issue with graphical glitches, I think Chrome is breaking things with their canvas again." - anoek

**Comment by anoek** [comment]
This should be resolved now
