### ISSUE TITLE
The site is missing an Automatch feature

### ISSUE THREAD

**Issue by EyeSeeEm** [online-go/online-go.com#9]
### Summary

The site is missing an Automatch feature.

### Environment

 * Operating system: Any
 * Browser: Any

### Steps To Reproduce:

1. Go to online-go.com
2. Click on "Play" at top of screen.
3. Notice that there is no automatch feature

### Additional Information:

I suggest adding a simple automatch system similar to the one that KGS offers.
It would make finding an opponent much quicker and simpler and require less knowledge and setup for newcomers.

Here is the KGS Automatch as an example, from https://www.gokgs.com/

![automatch_button](https://cloud.githubusercontent.com/assets/588917/23331942/10ee726c-fb70-11e6-9133-9026dae15dcc.png)

![automatch_menu](https://cloud.githubusercontent.com/assets/588917/23331944/1446650a-fb70-11e6-92d0-ddce4cef4389.png)

**Comment by roy7** [comment]
anoek mentioned on chat that this is something he's hoping to work on near term once major server stability issues are resolved.

**Comment by anoek** [comment]
https://github.com/online-go/online-go.com/pull/284
