### ISSUE TITLE
Vacation Day Accrued not displaying properly for 0 Days

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#915]
**Describe the bug**
September 22, 2019
[21:22]💖 KoBa 💖: Vacation Accrued: (Supporter) out of 60 Days
[21:22]💖 KoBa 💖: that thing only says "out of 60 days" if player has less than 1 day of vacation time available

**Expected behavior**
Display "0 Days" not ""

**Screenshots**
![image](https://user-images.githubusercontent.com/28991649/65395084-701b7480-ddd9-11e9-8c40-c52cdc3e1f3d.png)

**Comment by kobakitty** [comment]
>Expected behavior
Display "0 Days" not ""

Or make it show ">1" instead "0" for the sake of clarity?

**Comment by BHydden** [comment]
> Or make it show "<1 days" instead "0 days" for the sake of clarity?

It'll depend on whether I need to hardcode it or just change a setting...

**Comment by BHydden** [comment]
I can't tell exactly what this line does;

https://github.com/online-go/online-go.com/blob/7b8c2903efb8c41c0bde0bb2e695c4c2dc6e1a90/src/lib/translate.ts#L46

...but I suspect this is why the function returns "" instead of "0 Days"

any chance @GreenAsJade or @flovo could take a quick look at this for me? I'd rather not hardcode in a back door if I can avoid it.


<details><summary>Below is the whole function the above snippet came from</summary>
<p>

```typescript
export function ngettext(singular, plural, count) {
    let key = singular + "" + plural;
    if (key in catalog) {
        if (catalog[key].length === 1) {
            count = 1;
        }

        return catalog[key][count === 1 ? 0 : 1];
    }
    return debug_wrap(count === 1 ? singular : plural);
}
```

</p>
</details>

**Comment by GreenAsJade** [comment]
As a first observation, this works for me:

        console.log("NGT DBG", ngettext("a", "b", 1));
        console.log("NGT DBG", ngettext("a", "b", 2));
        console.log("NGT DBG", ngettext("a", "b", 0));

NGT DBG a
NGT DBG b
NGT DBG b

**Comment by BHydden** [comment]
grr... that's how anoek said it should work... so why isn't it then? :/

**Comment by BHydden** [comment]
_() is just a gettext so I guess it must be inside interpolate() somewhere

**Comment by GreenAsJade** [comment]
... which strongly hints that vacation_time_accrued is not '0' but rather an empty string or some other thing by the time it hits ngettext.

IE check your code and assumptions before blaming the libraries ;)

**Comment by BHydden** [comment]
hmm ok good call maybe math.round small/big doesn't = 0 like I assumed... time for some of my own console logs lol

**Comment by BHydden** [comment]
Thanks @GreenAsJade 

It turns out if(0) returns false, who knew 😛
