### ISSUE TITLE
Change the behaviour of `color=automatic`

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#916]
When creating a game, the color setting `Automatic` always results in white being the stronger player when the rank difference is bigger than 1 rank. This is the correct behavior for games with handicap. 

For games without handicap I would expect `color=automatic=random`, since neither color has an advantage through komi. The tradition for the stronger player to take white is rooted in pre komi times, and shouldn't apply to modern komi games.

**Comment by BHydden** [comment]
Since "random" is already a settable option, I don't think "automatic" should be made redundant. For those that want a traditional non-handicap game, this change would make it impossible to set an open challenge in which the potential opponents could be either stronger or weaker but in which the stronger is always white.

**Comment by flovo** [comment]
Call it traditional.

To me automatic means: When playing with handicap the stronger player gets white. 

I played about a year with automatic instead of random, because I thought it would default to random if there is nothing requiring an explicit colour choice.

**Comment by BHydden** [comment]
Hmm, feels like a lot of effort for a cosmetic change... finding every instance of the word automatic and swapping it with traditional... 

Don't get me wrong, I definitely do agree that this would be a more accurate name for it, and I guess you have the skills to rename all of them if you have the motivation to match 😛

**Comment by anoek** [comment]
I *think* we'd get push back on this, but I'm open to doing a poll to see if the community feels like automatic in even games should be random. It makes sense to me for it to be random, but then there's precedence and tradition of the stronger player taking white when ranks are known, and we have the random/nigiri option for when that's not desired, so I *think* the current setup is what people want.

**Comment by flovo** [comment]
I'll create a poll if I find the time.

I don't think we get much pushback if we add a traditional option (which is already implemented as automatic, so it shouldn't be much extra work?). 

Players new to go will probably expect automatic to be random when no handicap is set.
At least 2 users on the forum wrote that automatic should equal to random when no handicap is set.
https://forums.online-go.com/t/sugggestion-for-less-time-control-options/23318/17?u=flovo
https://forums.online-go.com/t/sugggestion-for-less-time-control-options/23318/31?u=flovo

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
