### ISSUE TITLE
User pop-up showing wrong rating

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#919]
**Describe the bug**

At the end of this game: 

https://online-go.com/game/19659846

RedAgent took this screenshot:

https://imgur.com/a/VsoMuKx

which shows that while his opponent is ranked 25k (they were ranked that way at the commencement of the game, and at the end) the rating displayed is out of date/wrong.

It appears to be the person's rating from the previous datapoint on the rating graph.

It is asserted (untested by me) that this is somewhat reproducible - IE able to be seen in other cases where an opponent's rating has changed on the day of the game prior to the game in question.

**Expected behavior**

The User pop-up should display the current rating.

**Comment by BHydden** [comment]
I have suspected (but not tested) that this may have something to do with whether the humble rank or system rank is being displayed.

**Comment by RedAgent14** [comment]
![r](https://user-images.githubusercontent.com/6283350/65469478-396f4980-de2d-11e9-8790-bd9c49604e3d.png)

Image of the same issue occurring in another ranked match

**Comment by flovo** [comment]
If I remember correct, the ratings in the drop down are only updated if you reload the site.

**Comment by GreenAsJade** [comment]
"Humble rank" is the rank that is used for  game matching.  It is a mechanism to avoid the problem that glicko requires the initial rating of all new users on the site to be in the middle of the rating range, but we don't want to match new users on the site with 13k people.

Humble rank says that while your rank uncertainty is high, you get matched with opponents at the bottom of your rank band.  IE if you are 13k +/- 6k (the starting rank, approx) then you will be matched as a 19k untill you have played some ranked games and that uncertainty comes down.

**Comment by BHydden** [comment]
It's both. That's why new accounts look like 1150 19kyu instead of 1500 13kyu

**Comment by GreenAsJade** [comment]
Ah - I didn't know that.    I don't really understand it.

A rating is always associated with an uncertainty.  Where do we read "1150 19kyu " without the uncertainty?

**Comment by BHydden** [comment]
That's a display issue. New accounts say 1150 +- 350 when at that stage they are actually 1150 +700 -0 since in reality they are 1500+-350 but for some reason the humble rank doesn't update their humble uncertainty.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
