### ISSUE TITLE
Joseki view is not cleaned up

### ISSUE THREAD

**Issue by max-spb** [online-go/online-go.com#920]
**Describe the bug**
After exploring some moves in Joseki, if you click "Joseki" menu instead of the "double arrow" button to return to the beginning, the view is not cleaned up correctly. The resulting screenshot is attached

**To Reproduce**
1. Go to 'Joseki'
2. Explore some moves
3. Click 'Joseki'

**Expected behavior**
The view is cleared the same way as if the "double arrow" button is clicked.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version: Version 76.0.3809.132 (Official Build) (64-bit)

![joseki](https://user-images.githubusercontent.com/22071645/65484646-3f564080-dea8-11e9-9f06-9acaf1817a6a.png)

**Comment by GreenAsJade** [comment]
Just confirming that I can reproduce this.  I don't know how it's even possible, since it should be a full page reload 😮
