### ISSUE TITLE
feature request: "Spartan Mode" ranked no-frills game mode

### ISSUE THREAD

**Issue by aloofandpoofed** [online-go/online-go.com#923]
There currently appears to be no option for "no undo", resulting in low level frustration due to differing expectations. If zen mode is updated to block incoming message popups, I think it'll be possible to manually create game offers with the rest of this, but a one-click "just play go" option would be great.

Described in the forum here: https://forums.online-go.com/t/hide-messages-while-being-in-zen-mode/23026/3?u=harveycrichton

Several of us would like 

> a mode in which there’s basically nothing but a board and clock (could call it something awesome like Spartan Mode).
> 
> No undo button, no message window popups, no analysis, no conditional moves… nothing extra.

**Comment by anoek** [comment]
Hidden private chats implemented in #918

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
