### ISSUE TITLE
Enable player name substitution for game names

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#935]
Automatic created games (tournaments, ladder, quick match finder) have the names of both players in the games title. (e.g. Tournament Game: Great Dragon Of Darkness 2018 (40174) R:1 (flovo vs Yuriika))

It would be nice to have the same for custom games. 
Ideally the creator of the game could insert placeholders like ’?white?’ and ’?black?’ in the game's name, which then are replaced by the server when the challenge is accepted.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
