### ISSUE TITLE
PaginatedTable component shows wrong results when typing too quickly

### ISSUE THREAD

**Issue by flurmbo** [online-go/online-go.com#939]
**Describe the bug**
This is a small bug I noticed on a user's game history. When typing a page number into the input of the PaginatedTable component, it will only show the page corresponding to the first digit of the page number. So for example, if you type in "25", it will show page "2" of the results. See the attached gif for an example.

This is because when the PaginatedTable first notices the input has been changed to "2", it sets `this.updating` to true, which blocks the update() function from making an ajax request after the "5" has been typed in (unless you type very slowly!) 

I've made a PR for this but someone more familiar with the code should probably take a look at it.

![paginatedtable](https://user-images.githubusercontent.com/35127144/66011725-d82d2300-e489-11e9-89e2-a7c9c698b468.gif)

**Comment by anoek** [comment]
Implemented in #940
