### ISSUE TITLE
SGF Library - Server Error 500 for Asian characters

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#944]
**Describe the bug**
Attempting to upload an sgf with some Asian characters in fields returns a server error.
See https://forums.online-go.com/t/upload-with-server-error-500/23157

**To Reproduce**
1. Go to https://online-go.com/library/
2. Click on upload
3. Select a game that has Asian characters in some of its fields
4. See Server Error 500

**Expected behavior**
We should have full UTF-8 character support for all fields of Game Information.

**Additional context**
pastebin of console output after attempted upload and subsequent error
https://pastebin.com/91N8xeWj

**Comment by felixthelucas** [comment]
It was just a matter of encoding, @anoek. While I did get the error when uploading the file mentioned in the post as was, converting it to UTF-8 (from Big5) [did the trick](https://online-go.com/game/20878363). Unless the SGF library _is_ supposed to handle different encodings, I think we can scratch this one as a bug.

**Comment by anoek** [comment]
Awesome, thanks!
