### ISSUE TITLE
Add "redo" in joseki

### ISSUE THREAD

**Issue by golopot** [online-go/online-go.com#947]
**Is your feature request related to a problem? Please describe.**
When I am exploring a joseki, I can use left arrow key to "undo" (go back to previous move), in a similar way, I want to use right arrow to redo (go to the move before an "undo" action). I find this feature very useful in josekipedia.com.

**Describe the solution you'd like**
Add a redo button, and it's key binding.

**Describe alternatives you've considered**
Not available.

**Additional context**
Not available.

**Comment by GreenAsJade** [comment]
I agree that this would be good.

Just like "faster go back", it is non-trivial, but it is on my list.

**Comment by GreenAsJade** [comment]
This was implemented by #1028
