### ISSUE TITLE
Improve latency when user send a series of "go back" in joseki

### ISSUE THREAD

**Issue by golopot** [online-go/online-go.com#948]
**Is your feature request related to a problem? Please describe.**
When I send a series of "go back" in joseki, I experience a significant latency, about 500 ms to 1000 ms, for each "go back". For example, when I want to go back 10 moves, I need to wait at least 500 ms in each key stroke. It seems that the app waits for the http request to finish before it can pick up another "go back". That is unnecessary. I expect "go back" to be instant, and not blocked by a http request.

**Describe the solution you'd like**
Make "go back to last move" not blocked by the page loading.

**Describe alternatives you've considered**
Cache the traversed path of moves. This allows the access of the last move to be instant.

**Additional context**
Not available.

**Comment by GreenAsJade** [comment]
I only just saw this, and I totally agree.

It's "on my list".   As you say, it may involve caching the previous results, which is "non-trivial".

**Comment by anoek** [comment]
Done in pr #974
