### ISSUE TITLE
Game starts in analyze mode if previous page is an ended game in analyze mode

### ISSUE THREAD

**Issue by golopot** [online-go/online-go.com#949]
**Describe the bug**
Game starts in analyze mode if I was reviewing an ended game and a challenge that I created is accepted.

**To Reproduce**
1. Create a game challenge
1. Go to an ended game and enter analyze mode
1. Wait for the game challenge (step 1) to be accepted. Notice the app auto-navigates to the started game.
1. Notice the the game starts in analyze mode.

**Expected behavior**
The started game should **not** start in analyze mode. 

**Screenshots**
Not available.

**Desktop (please complete the following information):**
 - OS: Linux
 - Chrome 77

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
