### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by wouwouwou** [online-go/online-go.com#950]
A while ago I asked via one of the communication channels if the account with username wouwouwou can be deleted on online-go.com

Can you please help me with that? I would be very grateful!

**Comment by anoek** [comment]
I can't verify you're identity over github, if you can log in to that account though you can change the username yourself to something else if you'd like. Accounts themselves cannot be deleted as they are bound to games which are jointly owned between players, but usernames can be changed.
