### ISSUE TITLE
Is ai review supposed to consider pass as a move option

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#956]
**Describe the bug**
In game https://online-go.com/game/20000000 at move 262 I was irritated not to see the AI recommended move (blue circle). A quick look at https://online-go.com/termination-api/game/20000000/ai_review/1023478 showed, that the recommended move is a pass.

The second best choice is C12. If on clicks on C12 to see the variation, one cannot find moves 11, 13, 15 of the variation, since they're passes. 

Is the AI supposed to consider pass as a valid play for review purposes? 

**Screenshots**
![image](https://user-images.githubusercontent.com/4864182/67144244-032eb980-f275-11e9-877b-6b70e9ac6554.png)

**Comment by anoek** [comment]
I'm going to say yes? I think it's useful to know that the computer thinks that there is nothing left to be done, and it's appropriate to pass, as opposed to highlighting essentially dame moves. Especially in Japanese scoring, it's detrimental not to pass if everything is done.
