### ISSUE TITLE
ai review suggesting impossible moves

### ISSUE THREAD

**Issue by alexmitrani** [online-go/online-go.com#962]
the ai review suggests a sequence that involves playing a stone on top of another stone

**To Reproduce**
https://online-go.com/game/20081131
sequence starting n16 on move 108

I expected ai sequences to consist of all valid moves

**Smartphone (please complete the following information):**
 - Device: Motorola G6 play
 - OS: Android
 - Browser: Chrome 
 - Version 78.0.3904.62

**Additional context**
The SGF is a bit unusual, created on IGS / Panda, completed from move 69 using GridMaster, imported into SGF library.  The game was played from move 69 on OGS because GoPanda crashed.

**Comment by alexmitrani** [comment]
I can't reproduce the described behaviour, it stops working completely and places x's on the intersections selected :-(

**Comment by alexmitrani** [comment]
![Screenshot_20191025-075752](https://user-images.githubusercontent.com/27974470/67566160-7c0e9500-f6fd-11e9-9457-09bf47bfa276.png)

**Comment by flovo** [comment]
15 (T15) captures the black group (Q16...), so Q16 is again empty after 15. Unless you are playing [Paper and Pencil Go](https://senseis.xmp.net/?PaperAndPencilGo), Q16 is a valid move on an empty point.

**Comment by alexmitrani** [comment]
OK, you're right @flovo, thanks for clarifying that.  It isn't very clear from what is shown on the screen, is it?  It would be much clearer if the black stones to the right of Q16 could be removed or at least made transparent.
