### ISSUE TITLE
Time remaining not shown in correspondence games

### ISSUE THREAD

**Issue by nickcollins** [online-go/online-go.com#965]
**Describe the bug**
In android chrome and desktop firefox, my correspondence games do not show how much time I have left to move, either from the profile or in game. First noticed about an hour ago.

**To Reproduce**
1. Go to https://online-go.com/user/view/169626
2. Time remaining is not visible for any of the displayed games.
3. Go to https://online-go.com/game/18994703
4. Time remaining is not visible in the specific game.

**Expected behavior**
Time remaining should be prominently visible in the usual locations.

**Screenshots**
let me know if you need screenshots and i'll find a way to get them to you.

**Desktop (please complete the following information):**
 - Ubuntu
 - Firefox
 - Version 69.0.1

**Smartphone (please complete the following information):**
 - Android Pixel 3
 - Android
 - Chrome
 - Version ?

**Comment by anoek** [comment]
I'm currently trying to figure out what's going on with this one.

Have any moves been made on any of the games since you've noticed the bug? (If so, does the bug persist?)

**Comment by nickcollins** [comment]
Yea, i've played in most of the games where it was my turn to move, and in at least a couple my opponent played too, and the issue persists in all cases

**Comment by anoek** [comment]
OK thanks for getting back to me, working on it.

**Comment by anoek** [comment]
This should be fixed now :)
