### ISSUE TITLE
Color coding in game history

### ISSUE THREAD

**Issue by mattetress** [online-go/online-go.com#968]
This is my first time contributing to open source, so please bear with me if I do something that's not completely the normal way of doing things. 🙂  

I'm RubyMineshaft, btw.

Issue is in response to this forum post requesting game results to be color coded based on opponent strength.

https://forums.online-go.com/t/suggestion-colorcoding-game-history/23454

**Comment by mattetress** [comment]
Uh oh, looks like something weird happened... failing checks. Let's see if I can't figure it out

**Comment by GreenAsJade** [comment]
Bring it on!
