### ISSUE TITLE
Invitation to game (open challenge) as a URL

### ISSUE THREAD

**Issue by jwilenius** [online-go/online-go.com#971]
As a user of online-go I would like to be able to post a link in our discord chat as an invitation to a game.
I would like to define the game rules etc in the same way as I do when creating a challenge/game; but I would like to make it an “open” challenge and whomever clicks the link first get to play the game as my opponent.

This is the "custom game" popup:
<img width="868" alt="Screenshot 2019-11-01 at 11 26 26" src="https://user-images.githubusercontent.com/22654330/68019065-037a7c00-fc9b-11e9-864b-e52127a9d57c.png">
We could add a "open challenge checkbox" and when one clicks the create challenge instead of being redirected to the waiting screen, just show a url for the challenge with an instruction of what to do with it.

This way, I can create a game, post it in the chat room (Discord) and wait for some other player to engage.
If they have an account, they could be prompted to log in first, and if not, to create an account.

This makes sense since we have players that play on many different servers but share a common discord chat. It would in my opinion make OGS a better candidate for being the server of choice.

**Comment by MrFlork** [comment]
Perhaps **Open Challenge** isn't a good name, but that is a minor detail that can be changed. All games created by the Custom Game button are open challenges. Perhaps **Create game invitation link** or something is better.

**Comment by BHydden** [comment]
This issue was originally requested on the forums in [2014](https://forums.online-go.com/t/invite-new-users/515?u=bhydden)
and more recently discussed [here](https://forums.online-go.com/t/invitation-to-game-or-open-challenge-as-a-url/23366?u=bhydden)

**Comment by BHydden** [comment]
A key idea proposed in the recent forum discussions is the idea that unranked games could be played without necessarily needing an account to be created.

**Comment by BHydden** [comment]
Not stale. Great QoL update. Please 🙏

**Comment by ahiijny** [comment]
Still a good QoL update to have.

**Comment by benjaminpjones** [comment]
Isn't this already addressed by the "Invite only" feature?

![Screenshot_20240217_203558_Firefox](https://github.com/online-go/online-go.com/assets/25233703/3b40fd6e-8b0f-4a7c-8b43-2aaf8678e06d)

cc: @GreenAsJade

**Comment by ahiijny** [comment]
Ah, I believe you're right! (I must've missed that announcement.)
