### ISSUE TITLE
[AI review] Top 3 moves display wrong move number

### ISSUE THREAD

**Issue by flovo** [online-go/online-go.com#972]
In game https://online-go.com/game/20189646 the move numbers of the top 3 moves for the full review have an offset of -2 to the actual move they are referring.

Steps to reproduce:
1) click on any of the suggested 3 moves (e.g. 101)
2) see that the move number in the variation view is 2 moves higher (e.g. 103)

The free 3 moves are showing the correct number

**Comment by flovo** [comment]
It's a game with free handicap placement and 3 stones handicap.

**Comment by mattetress** [comment]
I am unable to reproduce this error in a dev environment.  All of my attempts show the correct move numbers

**Comment by mattetress** [comment]
I see in the linked game that it only happens for the full AI review.  Is there a way I can give myself the ability to kick off full reviews on the dev server?

**Comment by flovo** [comment]
Edit the Gulpfile instead. Edit the second and third occurrence of `beta.online-go.com` to `online-go.com` to point the Dev environment to the main server.

**Comment by mattetress** [comment]
Perfect, thank you!
