### ISSUE TITLE
Add support for PWA service stuff

### ISSUE THREAD

**Issue by anoek** [online-go/online-go.com#976]
There's a lot of neat things we can do with progressive web apps, we should add support for them.

Relates to #568 and PR #720

**Comment by mih4ajlo** [comment]
Hello @anoek, what is the status of this feature? What functionalities are supposed to be covered with PWA?  
I suppose that beside app look and feel, it would be nice to have puzzles, josekies, demo board and maybe correspondence games available offline

**Comment by anoek** [comment]
I haven't done any research into what all we can or should do, or what is required to do so

**Comment by BHydden** [comment]
Nein! No closing!

**Comment by anoek** [comment]
I think I am going to close this, this should be more specific if it's an issue.. this is just a general "hey don't forget about that", but we've got enough to track. If someone wants to do some research and pondering into PWA's and figure what might fit, and open more specific issues, that would be welcome I think. (Or PR's, those would be even more welcome :grin:)

**Comment by teauxfu** [comment]
It looks like maybe this has gotten easier lately. Push notifications for PWA mode would be huge 

https://old.reddit.com/r/webdev/comments/1lqcncr/finally_safari_on_ios_now_supports_web_push_my/?rdt=53744
