### ISSUE TITLE
User mentions no longer displaying properly when passing control in demos

### ISSUE THREAD

**Issue by mattetress** [online-go/online-go.com#979]
**Describe the bug**
When passing control within a demo the text replacement seems to be broken 

![Screen Shot 2019-11-05 at 3 09 30 PM](https://user-images.githubusercontent.com/42720842/68246593-b79f3e00-ffde-11e9-9b15-01d7a3e361bd.png)

**Comment by flovo** [comment]
oh. there is the strange syntax used. Thank you for reporting.
