### ISSUE TITLE
Display Zeus Lightning on all mini-board displays

### ISSUE THREAD

**Issue by BHydden** [online-go/online-go.com#987]
**Is your feature request related to a problem? Please describe.**
When looking at mini boards on game page or profile page, you can't tell if one of the opponents has lost connection.

**Describe the solution you'd like**
It would be nice if you could tell if one of the opponents had lost connection, perhaps with the lightning bolt over the board?

**Describe alternatives you've considered**
Lightning bolt could be next to the board, or next to the name of the player who disconnected.

**Additional context**
As requested 😉

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
