### ISSUE TITLE
Ranks below cutoff show up on MiniGoban

### ISSUE THREAD

**Issue by CarterFendley** [online-go/online-go.com#988]
Players below the provisional cut off usually have their rank rendered as "[?]". However the MiniGoban component will render them with an actual rank estimation. 

Seems to be something up with the "rankString" method. Would fix it but can't parse the math that is going on in that method.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
