### ISSUE TITLE
Guests can access private games

### ISSUE THREAD

**Issue by jmdingess** [online-go/online-go.com#990]
**Describe the bug**
When not logged in, you are allowed to view private games

**To Reproduce**
1. Log out (or open a private/incognito browser)
2. Go to a private game - the one that we discovered this on was [this](https://online-go.com/game/20446956)
3. No warning is displayed, you have access

**Expected behavior**
Guests should not be allowed to access private games

**Desktop (please complete the following information):**
 - Browser Firefox version 70.0.1

**Comment by koshogs** [comment]
Confirmed. After logging out, I was able to open the game in question (Windows8/Opera).

I then tried to open the game from the player's profile page. Failed to open when I was logged in (confirming it's private status) and then again, able to open it when logged out.

Definitely a bug.

**Comment by anoek** [comment]
Yikes, thanks for letting me know!

**Comment by BHydden** [comment]
This game also experiences this issue. https://online-go.com/game/view/20746389

**Comment by jmdingess** [comment]
It's every game, yeah

**Comment by anoek** [comment]
Fixed
