### ISSUE TITLE
Cancellation does not result in exit from ladder

### ISSUE THREAD

**Issue by GreenAsJade** [online-go/online-go.com#998]
**Describe the bug**

If you cancel a game, declining the challenge, on a ladder, you should be kicked from the ladder.

However, this is not happening, which means that people can retain their spot on the ladder indefinitely by cancellation of games

Reference game:  https://online-go.com/game/20508700  

After this game, black remained on the ladder.

**Comment by BHydden** [comment]
Maybe not necessarily kicked, as is the case with timeout... but the winner should at least take their spot as would be the case with a normal resignation.

**Comment by GreenAsJade** [comment]
Ah - I can see that this is true: specifically, the opponent should end up above the cancelling player, so that cancelling does not result in a person "camping" in a spot.

**Comment by GreenAsJade** [comment]
FTR Kosh did a test and found that in his test the cancelling player ended up above the cancelled player.

@BHydden  fixed up the ladder result for the players in the reported reference game above.

@BHydden do you strongly recall that it was as I described: white did not end up above black in the ladder after black cancelled?    I'm not sure how to conclusively prove this was the case based on what we can see now.

**Comment by BHydden** [comment]
I can confirm that your rank did not change AT ALL after your opponent cancelled your ladder game. Expected behaviour would be that you would take their spot and they (and everyone below them) would move down one.

**Comment by GreenAsJade** [comment]
Thanks - that's what I thought... Kosh's result threw me into doubt :)

**Comment by koshogs** [comment]
There have been other reports in forums of the ladder not updating after a win. eg: https://forums.online-go.com/t/ladder-ranking-did-not-update/22461 but it didn't necessarily involve a cancellation. There may be no link between the bug and how the game ended.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.
